### PR TITLE
🚀 Release 0.43

### PR DESCRIPTION
**Pull request by tkoyama010**
PyVista December 2023 release

Release v0.43.0

---
## Highlights

Feel free to suggest highlights you want to add.

- #4855 by @FelipeCybis

https://github.com/pyvista/pyvista/assets/41338087/d6ba752a-b158-4441-83b0-3e638529c6ef

- #4965 by @MatthewFlamm

- #4974 by @tkoyama010 

- #5103 by @banesullivan 

Screenshot 2023-10-18 at 8 24 40 PM

- #5171 by @akaszynski 

- #5176 by @jmargeta

Screenshot 2023-10-18 at 8 24 40 PM

## Waiting on the following Issues or PRs:

- [x] #4688
- [x] #5091
- [x] #5095
- [x] #5158
- [x] #5160
- [x] #5112 
- [x] #5128                                                                     
- [x] #5133
- [x] #5140
- [x] #5143
- [x] #5176
- [x] #5168 
- [x] #5247
- [x] #5240
- [x] #5242
- [x] #5246
- [x] #5271

Potentially:

Next release:

- #4938
- #4942
- #5029
- #5119
- #5188

------

## Steps to release

- [x] Sync this branch with `main`
- [x] Grep for deprecations slated to be removed by `v0.43` and remove
- [x] Bump `main` to `0.44.dev0` (this PR)
- [ ] Keep this branch (`release/0.43`) and update the version to `0.43.0`. And commit the change to this branch.
- [ ] Tag `v0.43.0` and push the tag.
- [ ] Verify [docs](https://docs.pyvista.org/) and [PyPI](https://pypi.org/project/pyvista/) have updated.
- [ ] Update the [conda-forge feedstock](https://github.com/conda-forge/pyvista-feedstock).
- [ ] Generate [release documentation](https://github.com/pyvista/pyvista/releases/tag/v0.43.0)

------

### CODE REVIEW

**Comment by jmargeta** [comment]
Hey @tkoyama010, this release is turning out fantastic!

Thanks for the inclusion of  #5176 for 3D label map visualizations. In medical imaging/machine learning community, we frequently need to quickly visualize image segmentations. What do you think about adding it to the highlights? Here's a better screenshot from the frog tissue labels example: 
image

And I suggest we don't miss the "Add more typehints" (#5171) PR - a huge QoL improvement for PyVista users, along with all the vtk 9.3 support this release brings.

**Comment by tkoyama010** [comment]
@jmargeta
Thank you for your suggestion. And thank you for the nice image!

**Comment by tkoyama010** [comment]
If there are no problems, version 0.43 will be released on 7 December. Thanks to everyone for their excellent contributions.

**Comment by tkoyama010** [comment]
Thank you for your comment. We have a habit of checking for responses from other reviewers by waiting 24 hours after approval. Please wait another half day or so.

**Comment by banesullivan** [comment]
@tkoyama010, greenlight to release tomorrow (December 7th, which it may already be where you are in the world 😄)

**Review by banesullivan — APPROVED** [review]

**Pull request merged**
