### PR TITLE
fix image regression

### LINKED ISSUE #1132: Image cache seems to be broken
On my system the image cache functionality doesn't work. I noticed it when I changed an empty figure to a non-empty one yet the tests ran fine.

The problem seems to be at https://github.com/pyvista/pyvista/blob/master/pyvista/utilities/regression.py#L131-L132:
```py
    im1 = remove_alpha(to_img(im1))
    im2 = remove_alpha(to_img(im2))
```
The return value from `remove_alpha` ends up being an empty mesh:
```
>>> im2.GetDimensions()
(0, 0, 0)
```

Removing the `remove_alpha` call makes the problem go away, and a handful of cache comparisons suddenly break. I don't know if any of these are due to the alpha channel. But changing the above code to
```py
im1 = remove_alpha(to_img(im1))
im2 = remove_alpha(to_img(im2))
if im1.GetDimensions() == (0, 0, 0): 
    # or im2, doesn't matter
    raise RuntimeError('Uh-oh')      
```
breaks every plotting test from the looks of it.

My setup:
```py
>>> import pyvista as pv; pv.Report()

--------------------------------------------------------------------------------
  Date: Mon Feb 01 16:09:10 2021 CET

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.5 GB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics 620 (WHL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 20.3.3

  Python 3.8.7 (default, Jan 27 2021, 23:12:13)  [GCC 10.2.1 20210110]

           pyvista : 0.28.dev0
               vtk : 9.0.1
             numpy : 1.20.0
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.8
        matplotlib : 3.3.3
         pyvistaqt : 0.3.0
             PyQt5 : 5.15.2
           IPython : 7.19.0
          colorcet : 1.0.0
           cmocean : 2.0
     ipyvtk_simple : 0.1.4
             scipy : 1.6.0
        itkwidgets : 0.32.0
              tqdm : 4.56.0
--------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by akaszynski**
### Fix image regression

Image regression has been broken for quite some time, probably since the last minor patch.  This PR patches the regression testing, adds additional tests to ensure the testing works, and fixes `add_background_image`, which was broken due to the `pyvista.Camera` class.

Resolves #1132

### CODE REVIEW

**Comment by adeak** [comment]
I'm curious, what happens with VTK < 9 regarding https://github.com/pyvista/pyvista/pull/1134/files#diff-aa48cb28e019460e0bfbd237faddbe6a824b28a684e0a79352d93c839380ebbfR85?

**Comment by adeak** [comment]
I compared `vtkLight.cxx` between VTK v8.2.0 and master, and I think I can only see whitespace changes in both `ShallowClone` and `DeepCopy`. What am I missing? Or did you mean the problem that was fixed by https://gitlab.kitware.com/vtk/vtk/-/commit/54feb523f77bf4ab9b8645634709367e67327fde? It seems that this just made it into 8.2.0.

**Comment by akaszynski** [comment]
It's 8.1.2, so we'd have to patch that within `pyvista` for that version.  I know that many using Linux don't use 9.0.1 because the render windows refuse to close, so maybe it's a good idea.

**Comment by adeak** [comment]
In that case I'll PR with that, it should be simple. I only let VTK do the work out of a laziness of sorts (and thinking that not keeping a list of existing attributes is more future-proof). But it's not like the current implementation is bug-free either, see https://gitlab.kitware.com/vtk/vtk/-/issues/18093

**Pull request merged**
