### PR TITLE
Deprecate and remove PlotterITK

### PR DESCRIPTION
**Pull request by banesullivan**
I'm pretty sure no one is actually using this, and it wasn't even registered as a `jupyter_backend`. Maintaining this is more of a burden than a benefit, and there are much better alternatives to this API... like using `itkwidgets` directly which supports PyVista data types!

This is in support of #3690

We're going to deprecate and remove this immediately without a transition plan or warning because it is not a core feature and not a proper "jupyter backend"

### CODE REVIEW

**Comment by banesullivan** [comment]
Further justification: `itkwidgets` is broken on import and causing CI failures:

```
tests/jupyter/test_itk_plotting.py:11: in <module>
    import itkwidgets
/usr/share/miniconda/envs/pyvista-vtk/lib/python3.8/site-packages/itkwidgets/__init__.py:13: in <module>
    from .widget_viewer import Viewer, view
/usr/share/miniconda/envs/pyvista-vtk/lib/python3.8/site-packages/itkwidgets/widget_viewer.py:14: in <module>
    import itk
/usr/share/miniconda/envs/pyvista-vtk/lib/python3.8/site-packages/itk/__init__.py:28: in <module>
    from itk.support.extras import *
/usr/share/miniconda/envs/pyvista-vtk/lib/python3.8/site-packages/itk/support/extras.py:35: in <module>
    import itk.support.types as itkt
/usr/share/miniconda/envs/pyvista-vtk/lib/python3.8/site-packages/itk/support/types.py:172: in <module>
    ) = itkCType.initialize_c_types_once()
/usr/share/miniconda/envs/pyvista-vtk/lib/python3.8/site-packages/itk/support/types.py:137: in initialize_c_types_once
    _B: "itkCType" = itkCType("bool", "B", np.bool)
/usr/share/miniconda/envs/pyvista-vtk/lib/python3.8/site-packages/numpy/__init__.py:284: in __getattr__
    raise AttributeError("module {!r} has no attribute "
E   AttributeError: module 'numpy' has no attribute 'bool'
=========================== short test summary info ============================
ERROR tests/jupyter/test_itk_plotting.py - AttributeError: module 'numpy' has no attribute 'bool'
```

Looks like it is incompatoble with numpy 1.24 which gave ample warning about the built-in type aliases going away

With this in mind, I'm treating this as a HOTFIX and will merge expeditiously

**Comment by banesullivan** [comment]
CI failure due to needing #3736

**Comment by adeak** [comment]
I'm surprised by this breakage since in https://github.com/pyvista/pyvista/pull/3659#issuecomment-1331424611 I could get rid of these by upgrading all dependencies...

**Comment by adeak** [comment]
I'm also surprised we don't pin the basic dependencies. If numpy were bumped by dependabot we would've seen this coming.

**Comment by banesullivan** [comment]
> I'm also surprised we don't pin the basic dependencies.

Oh huh. We don't pin numpy, do we. At first, I thought this was just that we don't pin the conda environment but yeah we don't pin the core dependencies. We may want to look into that seperately

**Review by akaszynski — APPROVED** [review]
Agree with removing this. This has been broken ever since [JupyterLab 3.0](https://blog.jupyter.org/jupyterlab-3-0-is-out-4f58385e25bb), and we have way too many `juptyer_backend`s and should start to converge on a consistent backend soon.

Recommending immediate merge to fix the build.

**Pull request merged**
