### PR TITLE
Remove private array appending helpers.

### PR DESCRIPTION
**Pull request by JevinJ**
### Overview

This would remove the helper methods for appending arrays in common.py, they don't really do much as private methods and removing them would remove 100 lines.

### CODE REVIEW

**Comment by banesullivan** [comment]
I want to do some local testing on this... will review soon

**Comment by JevinJ** [comment]
@banesullivan Have you gotten to testing this yet?

**Comment by akaszynski** [comment]
I think this is good to go.  These private functions are rarely used and can be easily replaced by append.  Good work @JevinJ!

**Review by akaszynski — APPROVED** [review]

**Comment by larsoner** [comment]
I get failures on `master` now, I think probably the GC test should have been merged then all PRs rebased/merged:
```
__________________________________________________________________________ ERROR at teardown of test_plot __________________________________________________________________________

    @pytest.fixture(autouse=True)
    def check_gc():
        """Ensure that all VTK objects are garbage-collected by Python."""
        before = set(id(o) for o in gc.get_objects() if _is_vtk(o))
        yield
        pyvista.close_all()
        gc.collect()
        after = [o for o in gc.get_objects() if _is_vtk(o) and id(o) not in before]
>       assert len(after) == 0, \
            'Not all objects GCed:\n' + \
            '\n'.join(sorted(o.__class__.__name__ for o in after))
E       AssertionError: Not all objects GCed:
E         vtkCubeAxesActor
E         vtkLookupTable
E         vtkLookupTable
E         vtkUnsignedCharArray
E         vtkUnsignedCharArray
E       assert 5 == 0
E        +  where 5 = len([(vtkmodules.vtkCommonCore.vtkUnsignedCharArray)0x7fc3bf362820, (vtkmodules.vtkRenderingAnnotation.vtkCubeAxesActor)0x...b880, (vtkmodules.vtkCommonCore.vtkLookupTable)0x7fc3c3377820, (vtkmodules.vtkCommonCore.vtkLookupTable)0x7fc3bf362640])
```

**Comment by akaszynski** [comment]
Crap.  Didn't think of that.  Reverting this branch.

**Comment by GuillaumeFavelier** [comment]
I investigated real quick and this could be added in `deep_clean()`:

```py
        if getattr(self, 'mesh', None) is not None:
            self.mesh.point_arrays = None
            self.mesh.point_arrays = None
```

Anyway, this means that `deep_clean()` needs to be called.

Since the `Plotter` closes when `show()` is called in our tests and since `close()` now removes itself from `_ALL_PLOTTERS`, `close_all()` is noop (the list is empty) in the `check_gc` fixture.

This requires a discussion I think

**Comment by GuillaumeFavelier** [comment]
The following diff makes my tests green locally but reverts @larsoner PR, should I open a PR?

```diff
diff --git a/pyvista/plotting/plotting.py b/pyvista/plotting/plotting.py
index c2b2bc81..fe353896 100644
--- a/pyvista/plotting/plotting.py
+++ b/pyvista/plotting/plotting.py
@@ -2737,8 +2737,6 @@ class BasePlotter(PickingHelper, WidgetHelper):
 
         # this helps managing closed plotters
         self._closed = True
-        if self._id_name in _ALL_PLOTTERS:
-            del _ALL_PLOTTERS[self._id_name]
 
 
     def deep_clean(self):
@@ -2750,6 +2748,9 @@ class BasePlotter(PickingHelper, WidgetHelper):
             if renderer is not None:
                 renderer.deep_clean()
         # Do not remove the renderers on the clean
+        if getattr(self, 'mesh', None) is not None:
+            self.mesh.point_arrays = None
+            self.mesh.cell_arrays = None
         self.mesh = None
         if getattr(self, 'mapper', None) is not None:
             self.mapper.lookup_table = None
```

**Comment by akaszynski** [comment]
> The following diff makes my tests green locally but reverts @larsoner PR, should I open a PR?

About to say that as well.  Simply ran:
```
git revert 87ec4fa66835e385d6e50715c8de173150298962
```

@GuillaumeFavelier, a PR would be appreciated.  If you make it I'll approve and merge it.

**Pull request merged**
