### PR TITLE
Add table CSS override

### PR DESCRIPTION
**Pull request by banesullivan**
I'm hoping this will resolve https://github.com/pyvista/pyvista/issues/3728

I cannot build the docs on my current machine, so I will have to come back to this on another machine to verify/adjust

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]
Awesome fix. Thanks!

**Comment by banesullivan** [comment]
Before merging, I'd like to wait for a response from SG here: https://github.com/sphinx-gallery/sphinx-gallery/issues/1058

**Comment by MatthewFlamm** [comment]
> rather than make a release for this, I think I may go into one of the CSS files in the published docs here: https://github.com/pyvista/pyvista-docs/tree/gh-pages/_static and add this manually for now

I think this strategy is fine.  Could also use a post release, but it may be more work.  https://peps.python.org/pep-0440/#post-releases

**Comment by banesullivan** [comment]
Added a hotfix here: https://github.com/pyvista/pyvista-docs/commit/888201cadf9846e6702c13cd91322fbcb3f88ba1

... not sure if that will actually work

**Comment by akaszynski** [comment]
@banesullivan, do we still need this?

**Comment by banesullivan** [comment]
I'm not sure. I triggered a re-deploy on tag 0.37 to re-publish our main docs: https://github.com/pyvista/pyvista/actions/runs/3744781087

**Comment by akaszynski** [comment]
> I'm not sure. I triggered a re-deploy on tag 0.37 to re-publish our main docs: https://github.com/pyvista/pyvista/actions/runs/3744781087

Turns out the issue is with `requirements_docs.txt`.

Recommending a patch release, working on it...

Thanks @RomanIlchenko1308 for pointing out the issue.

**Comment by RomanIlchenko1308** [comment]
Thank you @banesullivan and @akaszynski
Have a nice day🔥

**Comment by banesullivan** [comment]
I'm going to close this PR and let the patch release handle this

**Pull request closed without merging**
