### PR TITLE
WIP: Fix clip scalars multiple usages

### PR DESCRIPTION
**Pull request by MatthewFlamm**
### Overview

This PR is working towards resolving #1463.

### Details

First I will push failing tests to confirm that it indeed fails as expected with the whole CI suite as there is some subtle crosstalk in `vtk` somehow.  Interestingly, the test I added uncovered another bug in that the returned region is inverted.  When `invert=True`, the default, we should obtain the part of the mesh with the scalars below the value specified, but this is not the case here.  The second, which should be removed later, tests that the multiple calling of `clip_scalar` also fails when using `invert=False`.  This tests that calling it multiple times also causes a bug.

Second, I will push some changes to the `clip_scalar` filter to see if the test passes as expected.

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
This test failed due to the returned region being inverted from the expectation.  We expect that with `invert=True`, we should receive a mesh with values less than `0.0`.

```txt
def test_clip_filter_scalar_multiple():
        mesh = pyvista.Plane()
        mesh['x'] = mesh.points[:, 0].copy()
        mesh['y'] = mesh.points[:, 1].copy()
        mesh['z'] = mesh.points[:, 2].copy()
    
        mesh_clip_x = mesh.clip_scalar(scalars='x', value=0.0)
>       assert np.isclose(mesh_clip_x['x'].max(), 0.0)
E       assert False
E        +  where False = <function isclose at 0x7f167ef45378>(0.5, 0.0)
```


This test failed (after flipping the result) due to calling the clip_scalar filter multiple times, which reproduces #1463 
```txt
def test_clip_filter_scalar_multiple_inverted():
        mesh = pyvista.Plane()
        mesh['x'] = mesh.points[:, 0].copy()
        mesh['y'] = mesh.points[:, 1].copy()
        mesh['z'] = mesh.points[:, 2].copy()
    
        mesh_clip_x = mesh.clip_scalar(scalars='x', value=0.0, invert=False)
        assert np.isclose(mesh_clip_x['x'].max(), 0.0)
        mesh_clip_y = mesh.clip_scalar(scalars='y', value=0.0, invert=False)
>       assert np.isclose(mesh_clip_y['y'].max(), 0.0)
E       assert False
E        +  where False = <function isclose at 0x7f167ef45378>(0.5, 0.0)
```

**Comment by MatthewFlamm** [comment]
Only the tinypages test is now failing, so it seems to be fixed.  The group of clip filters uses a unique way to set the scalars to process compared to the other filters, so I figured this might cause the issue.  This PR now just sets the scalars as the active scalars.  I'm really unsure what causes the bug with the original logic, so it would be good to confirm that this works for other cases as well.

@flutefreak7 are you able to test this PR with however you were trying to use clip_scalar?

**Comment by MatthewFlamm** [comment]
Is there a reason that the clip filters are skipped on windows and/or mac?  Is it to simply save testing time?  Or were these tests actually previously failing on windows and mac?  If the latter, then this could have been a symptom of this bug.

https://github.com/pyvista/pyvista/blob/5a2bb7395ad12254a6e71d5632fee6beabce66d6/tests/test_filters.py#L49-L50
https://github.com/pyvista/pyvista/blob/5a2bb7395ad12254a6e71d5632fee6beabce66d6/tests/test_filters.py#L69-L71

**Comment by MatthewFlamm** [comment]
If this PR is good for `clip_scalars`, I would propose replacing this logic in _all filters_ with the active_scalars methodology.

**Comment by flutefreak7** [comment]
> 
> 
> Only the tinypages test is now failing, so it seems to be fixed. The group of clip filters uses a unique way to set the scalars to process compared to the other filters, so I figured this might cause the issue. This PR now just sets the scalars as the active scalars. I'm really unsure what causes the bug with the original logic, so it would be good to confirm that this works for other cases as well.
> 
> @flutefreak7 are you able to test this PR with however you were trying to use clip_scalar?

I can try later today or at worst tomorrow. I think grabbing this PR's code and trying it out is just barely within my comfort zone / experience level and I have an active interest in the fix to I can spare some work time figuring it out. :)

**Comment by MatthewFlamm** [comment]
> I think grabbing this PR's code and trying it out is just barely within my comfort zone / experience level and I have an active interest in the fix to I can spare some work time figuring it out. :)

Great!  Let me know if you need help with this aspect.

**Comment by adeak** [comment]
At the risk of stating the obvious, I think it's worth making clear that the inversion behaviour you mentioned is a code bug and not a doc bug.

The implementation uses either `vtkClipPolyData` or `vtkTableBasedClipDataSet` based on the type of mesh. These directly get passed the `invert` keyword, and they specify:

> Set/Get the InsideOut flag.
> 
> When off, a vertex is considered inside the implicit function if its value is greater than the Value ivar. When InsideOutside is turned on, a vertex is considered inside the implicit function if its implicit function value is less than or equal to the Value ivar. InsideOut is off by default.

> Set/Get the InsideOut flag.
> 
> With this flag off, a vertex is considered inside (the implicit function or the isosurface) if the (function or scalar) value is greater than IVAR Value. With this flag on, a vertex is considered inside (the implicit function or the isosurface) if the (function or scalar) value is less than or equal to IVAR Value. This flag is off by default.

which suggests that the documentation is correct but the behaviour is wrong.

This also raises a concern: there are several possibilities here: two kinds of VTK filters for two kinds of meshes, and clipping with an implicit function or scalar arrays. The latter should be OK, because we never use an implicit function. But the former suggests that it's even possible that only some kinds of meshes show the bug (which would contribute to its elusiveness).

Finally, perhaps we want to make the scalar-based filtering more explicit? The docs say

>  If a clipping function is not specified, or GenerateClipScalars is off( the default), the input scalar point data array is then employed for clipping.

Perhaps we should also set `GenerateClipScalars(True)` as a show of good will (or paranoia)? I guess it shouldn't _really_ be necessary, since there's no implicit function, _and_ this should be the default...

**Comment by MatthewFlamm** [comment]
> At the risk of stating the obvious, I think it's worth making clear that the inversion behaviour you mentioned is a code bug and not a doc bug.

Correct, my reading is that the documentation in pyvista is consistent with vtk.  It was at first confusing to me that pyvista has the default switched.  It is ingrained in my brain that we are clipping _away_ part of the mesh less than the value (the default in vtk), while in pyvista we retain the part of the mesh less than the value.  I've gotten used to it.

I'm now looking at the existing tests, and this test looks to be fundamentally flawed, so it is unclear whether the current tests should all pass:

https://github.com/pyvista/pyvista/blob/5a2bb7395ad12254a6e71d5632fee6beabce66d6/tests/test_filters.py#L71

In particular, the test asserts that the minimum value in the original dataset was less than the clipping value.  We should be testing whether the maximum value of the clipped dataset is the same as the clipped value, or that all values in the clipped dataset are <= the clipped value.  This paragraph assumes `invert=True`, the default here.

https://github.com/pyvista/pyvista/blob/5a2bb7395ad12254a6e71d5632fee6beabce66d6/tests/test_filters.py#L86

**Comment by MatthewFlamm** [comment]
> This also raises a concern: there are several possibilities here: two kinds of VTK filters for two kinds of meshes, and clipping with an implicit function or scalar arrays.

From a user perspective, I quite like the clarity of usage in pyvista by having the functions be split by usage rather than underlying vtk functionality.  For future consideration, we could consider splitting this filter into subclasses for the particular mesh types that utilize a common helper function.

> Perhaps we should also set GenerateClipScalars(True) as a show of good will (or paranoia)? I guess it shouldn't really be necessary, since there's no implicit function, and this should be the default...

My reading of the vtk source is that `GenerateClipScalars(True)` is only used when you are __not__ clipping by scalars.  That is, when you are using an implicit function, vtk needs to generate _new_ scalars using the implicit function .  It is very confusing, and I had to read it several times for it to sink in.  The last quote in your comment states that the default behavior is to clip by existing scalars, so I think it is clear enough to me.  If we want to be explicit it should be `GenerateClipScalars(False)`

**Comment by adeak** [comment]
> From a user perspective, I quite like the clarity of usage in pyvista by having the functions be split by usage rather than underlying vtk functionality.

Absolutely! I just meant that debugging might be more cumbersome, because there are more paths where VTK might be buggy.

> My reading of the vtk source is that `GenerateClipScalars(True)` is only used when you are not clipping by scalars.

Yes, sorry, I didn't read the whole sentence in the docs. It is indeed confusing of course. 

>  If we want to be explicit it should be `GenerateClipScalars(False)`

That's what I meant to write. But you're probably right that this would be superfluous. After all we're not setting any implicit function, so unless VTK divines one by default for some inexplicable reason, it can't help but use scalars.

**Comment by MatthewFlamm** [comment]
Gently pinging @flutefreak7 to see if you are still interested in testing this PR and, only if so, if you need help setting up your environment to use the code from this PR.

**Comment by MatthewFlamm** [comment]
This was superseded by #1538

**Pull request closed without merging**
