### PR TITLE
Revert "Render window refactor"

### PR DESCRIPTION
**Pull request by akaszynski**
Reverts pyvista/pyvista#2964

Potential regression as our test suite is failing on `main`:
```
tests/test_datasetattributes.py::test_preserve_field_data_after_extract_cells Fatal Python error: Segmentation fault

Thread 0x00007f13b2831700 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/threading.py", line 324 in wait
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/threading.py", line 607 in wait
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/threading.py", line 1376 in run
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/threading.py", line 1016 in _bootstrap_inner
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/threading.py", line 973 in _bootstrap

Current thread 0x00007f1447dde740 (most recent call first):
  Garbage-collecting
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/charts.py", line 4399 in deep_clean
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/renderer.py", line 1906 in clear
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/renderers.py", line 377 in clear
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/plotting.py", line 3591 in clear
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/plotting.py", line 3847 in close
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/plotting.py", line 5125 in __del__
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/hypothesis/internal/conjecture/data.py", line 929 in draw
```

Possibly a fluke, but I'm reverting for now and then running some more serious testing before merging this feature.

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]

**Comment by larsoner** [comment]
Thank you for reverting, this broke 56 of our tests in MNE-Python :)

**Comment by larsoner** [comment]
(I mean that https://github.com/pyvista/pyvista/pull/2964 broke them, so this PR fixed them)

**Comment by akaszynski** [comment]
@larsoner, could you please point out the tests/workflow that I can test against? I'd still like to merge it in #3216 and I'd like to ensure it works with your codebase prior to merge.

**Comment by larsoner** [comment]
It was the commit above this comment:

https://github.com/mne-tools/mne-python/pull/11096#issuecomment-1228641846

But basically if you clone mne you should be able to do
```
python setup.py develop
python -c "import mne; print(mne.datasets.testing.data_path(download=True, verbose=True)"  # downloads ~2GB!
pytest mne/viz/_brain
```

**Pull request merged**
