### PR TITLE
Ignore inherited members and attributes and switch to the full doc build

### PR DESCRIPTION
**Pull request by akaszynski**
Get rid of inherited attributes and method in our doc build autosummary.

### CODE REVIEW

**Comment by akaszynski** [comment]
Style and Docstring Check / docstringcheck (pull_request)  is failing:
https://askubuntu.com/questions/1265388/problem-with-apt-get-update-on-ubuntu-20-04-lts

Going to look the other way for this.

**Review by banesullivan — DISMISSED** [review]
So needed! Some old links may break but it's worth it to clean up the search interface and not re-run the same examples for every DataSet subclass

**Review by banesullivan — COMMENTED** [review]
Looks like attributes are still documented for every subclass:

Screen Shot 2023-01-31 at 3 58 38 PM


But OH MY! Does this make finding relevant filters so much better. For example, trying to find ImageData/UniformGrid-specific filters:
Screen Shot 2023-01-31 at 3 59 54 PM

**Comment by akaszynski** [comment]
Trying to fix the attributes issue.

**Comment by akaszynski** [comment]
Attributes no longer duplicated:
tmp

**Review by banesullivan — APPROVED** [review]
Awesome!!

**Pull request merged**
