### PR TITLE
Add toolbars to Qt plotter

### PR DESCRIPTION
**Pull request by banesullivan**
What other options should be in a toolbar? 

Perhaps we should overhaul the saved camera locations to be managed in a toolbar?

### CODE REVIEW

**Comment by banesullivan** [comment]
I've generalized this so that we could add various toolbars

**Comment by akaszynski** [comment]
Saved locations might look great as a table within a panel, but that’s quite an overhaul. I like the toolbar.

**Comment by banesullivan** [comment]
It was pretty easy to reimplement the saved cameras into a toolbar:

**Comment by banesullivan** [comment]
I'm getting some weird warning when I try to move the toolbar:

```
qt.qpa.cocoa.window: <QNSPanel: 0x7ff69c8ecce0> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
```

**Comment by banesullivan** [comment]
@GuillaumeFavelier, you leverage the `BackgrounPlotter` a lot, are there any other features you'd like to see as a toolbar?

Also, if you have the time, a code review would be much appreciated since you have more experience with Qt than I.

**Pull request merged**
