### PR TITLE
Add `flake8-comprehensions` check using `ruff`

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

See https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4.

### Details

- None

### CODE REVIEW

**Review by bjlittle — APPROVED** [review]

**Comment by bjlittle** [comment]
@tkoyama010 Lovin' your efforts to leverage `ruff` on `pyvista` 🚀

If you want a hand to help divide and conquer, then I'd be glad to help out, but I don't want to step on your toes ... Do you have a plan of attack that I could help chip away at?

**Comment by tkoyama010** [comment]
> @tkoyama010 Lovin' your efforts to leverage `ruff` on `pyvista` 
> 
> If you want a hand to help divide and conquer, then I'd be glad to help out, but I don't want to step on your toes ... Do you have a plan of attack that I could help chip away at?

Yes. Please. I am doing this because I want to study Python best practices. Therefore, I have no specific plans 😏
I would love to see any best practices you discover as well 🥳

**Comment by tkoyama010** [comment]
@bjlittle One thing I noticed. We should be cautious about adding that does not support autofix. Errors without it can be stressful for developers.

**Comment by bjlittle** [comment]
> I would love to see any best practices you discover as well 🥳

@tkoyama010 Since you asked ... recently I've been pretty darn impressed by the best practice offered over on [Learn Scientific Python](https://learn.scientific-python.org/).

They've curated some really invaluable resources for the scientific python developer i.e., written by scientists for scientists.

If you have the spare time, I'd highly recommend grabbing a cuppa and skimming through their material. You'll be sure to learn something 👍 

In particular, they've collated some really great [Topical Guides](https://learn.scientific-python.org/development/guides/) ... probably of which most you will know, but at the very least, checkout their [Repo Review](https://learn.scientific-python.org/development/guides/repo-review/), which allows you to assess the health/quality of your repo against their recommended best practices.

That in itself is pretty awesome. It'll generate a report on your level of compliance, and link off to the sections in their docs that help you to understand what to do and how to do it; they're really lowered the bar on adoption.

They also offer a `pre-commit` hook so that if your committed to adopting their standards, then the hook will enforce it for developers, either via the hook or the [pre-commit.ci](https://[pre-commit.ci](https://pre-commit.ci/)/) CI service.

You can also run their tool in the command line, see [PyPI sp-repo-review](https://pypi.org/project/sp-repo-review/), rather than use their WASM tool in the browser.

**Comment by tkoyama010** [comment]
> > I would love to see any best practices you discover as well 🥳
> 
> @tkoyama010 Since you asked ... recently I've been pretty darn impressed by the best practice offered over on [Learn Scientific Python](https://learn.scientific-python.org/).
> 
> They've curated some really invaluable resources for the scientific python developer i.e., written by scientists for scientists.
> 
> If you have the spare time, I'd highly recommend grabbing a cuppa and skimming through their material. You'll be sure to learn something 
> 
> In particular, they've collated some really great [Topical Guides](https://learn.scientific-python.org/development/guides/) ... probably of which most you will know, but at the very least, checkout their [Repo Review](https://learn.scientific-python.org/development/guides/repo-review/), which allows you to assess the health/quality of your repo against their recommended best practices.
> 
> That in itself is pretty awesome. It'll generate a report on your level of compliance, and link off to the sections in their docs that help you to understand what to do and how to do it; they've really lowered the bar on adoption.
> 
> They also offer a `pre-commit` hook so that if you're committed to adopting their standards, then the hook will enforce it for developers, either via the hook or the [pre-commit.ci](https://%5Bpre-commit.ci%5D(https://pre-commit.ci/)/) CI service.
> 
> You can also run their tool in the command line, see [PyPI sp-repo-review](https://pypi.org/project/sp-repo-review/), rather than use their WASM tool in the browser.
> 
> I've adopted their `pre-commit` hook over on `geovista`, see [here](https://github.com/bjlittle/geovista/blob/main/.pre-commit-config.yaml#L97-L111) ... and documented (for my future self and sanity ) the sections that I still require to comply with.

Excellent. I had heard about their activities at the SciPy Conference, but I had no idea they maintained such detailed documentation. I am positive about adding their pre-commit hook :+1:

**Pull request merged**
