### PR TITLE
Improve `pyvista.version_info` and `pyvista.vtk_version_info`

### PR DESCRIPTION
**Pull request by kmarchais**
### Overview

The aim of this PR is to propose changes for PyVista's and VTK's version information:
- Provide access to the PyVista version as a tuple using `pyvista.version_info`, rather than accessing it through the private `_version` module with `pyvista._version.version_info`.
- Move `vtk_version_info` from `pyvista.report` to `pyvista.core._vtk_core` as suggested by @MatthewFlamm in #5655 to avoid circular import when checking for the VTK version in `pyvista/core/utilities/geometric_sources.py`.

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]
LGTM. Thanks!

**Comment by tkoyama010** [comment]
github-actions preview

**Comment by tkoyama010** [comment]
github-actions preview

**Review by tkoyama010 — DISMISSED** [review]
LGTM

**Comment by kmarchais** [comment]
> LGTM

I just fixed what seemed to be a typo.

**Review by tkoyama010 — APPROVED** [review]
Good catch. Thanks!

**Pull request merged**
