### PR TITLE
🚀 Release 0.42.1

### PR DESCRIPTION
**Pull request by tkoyama010**
Patch release of v0.34.1 which includes:

- #4844 
- #4841

### Merge Checklist

- [ ] Merge in local not to squash merge.

### Post Merge Checklist

- [ ] Tag `v0.42.1` and push the tag.
- [ ] Verify [docs](https://docs.pyvista.org/) and [PyPI](https://pypi.org/project/pyvista/) have updated.
- [ ] Update the [conda-forge feedstock](https://github.com/conda-forge/pyvista-feedstock).

### CODE REVIEW

**Review by akaszynski — APPROVED** [review]
LGTM. Thanks for taking care of this. I'm also fine if we go under 24 hours for this merge.

**Comment by tkoyama010** [comment]
Thank you for your review. It has been 24 hours since publication. I will release it.

**Comment by tkoyama010** [comment]
Now deploying the document seems to going well, but the page seems not updated yet.
https://github.com/pyvista/pyvista/actions/runs/6103082107/job/16565154300

**Comment by tkoyama010** [comment]
It seems that size is too big.
> Warning: Uploaded artifact size of 6383851520 bytes exceeds the allowed size of 1 GB. Deployment might fail.

https://github.com/pyvista/pyvista-docs/actions/runs/6104131440/job/16569074671#step:2:11

**Comment by tkoyama010** [comment]
I posted the question https://github.com/ansys/actions/discussions/338.

**Comment by akaszynski** [comment]
Uncompressed docs are ~600 MB:

```
$ du -sh doc/_build/html/
584M    doc/_build/html/
```

I'll have to investigate.

**Comment by tkoyama010** [comment]
Thanks. I have opened https://github.com/pyvista/pyvista/issues/4868 . Please let us know your mind.

**Pull request merged**
