### PR TITLE
pyvista.wrap is not needed for pyvista.PolyData

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

pyvsita.wrap is not need for pyvista.PolyData.

 
See https://github.com/pyvista/pyvista/pull/4145#discussion_r1140175163

### Details

- None

### CODE REVIEW

**Review by banesullivan — DISMISSED** [review]

**Comment by banesullivan** [comment]
@tkoyama010, would you look into why the tests are now failing for this? Otherwise, thanks for this clean up!

**Comment by tkoyama010** [comment]
The error occurs in the test when defining a wrapper for the subclass added in #1584. @MatthewFlamm I think this test is not necessary if Geometry functions do not use a wrapper. Am I right?
https://github.com/pyvista/pyvista/blob/0a43286293ef8cb922d0ac28428e8ce556f18a86/tests/test_helpers.py#L117-L121

**Comment by MatthewFlamm** [comment]
See https://github.com/pyvista/pyvista/pull/1584#issuecomment-901340448 for the thinking at the time for why it is like this.  I wanted it to be either 1) PyVista aims to make everything the subclass the user specifies, including geometric objects, or 2) the user is in charge of wrapping objects at every step of the way.

I'd welcome ideas on how this could be better (metaclass logic?).

**Comment by adeak** [comment]
> I'd welcome ideas on how this could be better (metaclass logic?).

Toying with an alternative in https://github.com/pyvista/pyvista/pull/4188.

**Comment by banesullivan** [comment]
Closing due to staleness and unclarity

**Pull request closed without merging**
