### PR TITLE
clarify line lengths

### PR DESCRIPTION
**Pull request by akaszynski**
Added a note regarding docstrings max lengths based on comments from @adeak in #1375.

### CODE REVIEW

**Comment by adeak** [comment]
Thanks for this.

One thing is not clear to me still (but this is sort of an edge case): is the first line of docstrings an exception? Or can the opening blurb be wrapped at 72 characters as long as there is an empty line afterward?

**Review by adeak — APPROVED** [review]

**Comment by akaszynski** [comment]
> One thing is not clear to me still (but this is sort of an edge case): is the first line of docstrings an exception? Or can the opening blurb be wrapped at 72 characters as long as there is an empty line afterward?

According to the numpydoc style, the short description should be a single sentence.  If this is line wrapped, things like autosummary won't give us a good description of each method.  For example, the summary looks pretty good here:
https://mapdldocs.pyansys.com/mapdl_commands/database/components.html

We should aim to do the same; write a short description in a single sentence.  If it's longer than 72, we should consider shortening the description and placing more information in the long description.

Let me know if that should be clarified in `CONTRIBUTING`

**Comment by adeak** [comment]
>  If this is line wrapped, things like autosummary won't give us a good description of each method.

That's what I suspected, which is why I thought to ask, thanks.

I don't feel too strongly about adding this; normally it's not an issue to keep blurbs under 72 characters. But in https://github.com/pyvista/pyvista/pull/1381 I ran into https://github.com/pyvista/pyvista/blob/master/pyvista/core/filters.py#L4531-L4532 with 87 characters that's hard to make shorter. (Well, we could take Dijkstra out of the blurb but I like it there.)

But going into too much details in the contributing guide would probably be counterproductive (too much text is less likely to be read). I think it's fine if we don't add this, just keep an eye on that in reviews. Comparatively speaking new functions don't get added too often.

**Comment by akaszynski** [comment]
Thanks @adeak.  This is one of those best practices things, but it's not a hill I'd like to die on.  At the end of the day, the code should be readable and usable and there's a balance between uniformity and dogma.

**Pull request merged**
