### PR TITLE
Add space cubemaps

### PR DESCRIPTION
**Pull request by akaszynski**
I figure that we need some cubemaps if we're going to be displaying planets in #2994.

Pinging @jorgepiloto because you love space.

Here's some totally unnecessary (but cool) pictures.

### Space Sphere

```py
import pyvista as pv
from pyvista import examples
import pyvista as pv
cubemap = examples.download_cubemap_space_16k()
pl = pv.Plotter(lighting=None)
_ = pl.add_actor(cubemap.to_skybox())
pl.set_environment_texture(cubemap, True)
pl.camera.zoom(0.4)
pl.add_mesh(pv.Sphere(), pbr=True, roughness=0.24, metallic=1.0)
pl.show()
```

spaceball

### Space Sphere Video

```py
import pyvista as pv
from pyvista import examples
import pyvista as pv
cubemap = examples.download_cubemap_space_16k()
pl = pv.Plotter(lighting=None, off_screen=True)
_ = pl.add_actor(cubemap.to_skybox())
pl.set_environment_texture(cubemap, True)
pl.camera.zoom(0.4)
pl.open_movie('sphere.mp4', quality=5, framerate=60)
pl.add_mesh(pv.Sphere(), pbr=True, roughness=0.24, metallic=1.0)
path = pl.generate_orbital_path(n_points=720, viewup=[0, 0, 1], shift=1.0)
pl.orbit_on_path(path, progress_bar=True, write_frames=True)
```

https://user-images.githubusercontent.com/11981631/180933317-357e8518-0df5-434c-b728-96c52d5f959b.mp4

### Space Stanford Bunny

```py
import pyvista as pv
from pyvista import examples
import pyvista as pv
cubemap = examples.download_cubemap_space_16k()
pl = pv.Plotter(lighting=None, window_size=[1920, 1080], off_screen=True)
_ = pl.add_actor(cubemap.to_skybox())
pl.set_environment_texture(cubemap, True)
pl.camera.zoom(0.4)
mesh = examples.download_bunny()
pl.add_mesh(mesh, pbr=True, roughness=0.0, metallic=0.4)
pl.camera_position = 'xy'
pl.show(screenshot='space_bunny.png')
```

space_bunny

### Space Frog (because I can)

```py
import pyvista as pv
from pyvista import examples
import pyvista as pv
cubemap = examples.download_cubemap_space_16k()
pl = pv.Plotter(lighting=None)
_ = pl.add_actor(cubemap.to_skybox())
pl.set_environment_texture(cubemap, True)
pl.camera.zoom(0.4)
mesh = examples.download_frog()
pl.add_volume(mesh, opacity='sigmoid_10')
pl.show()
```

space_frog

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]
Awesome job! #2994 will follow using this cubemap.

**Comment by jorgepiloto** [comment]
This is amazing! Thanks for implementing this @akaszynski. I saw there are cubemaps for constellation boundaries and figure too in https://svs.gsfc.nasa.gov/4851

**Comment by jorgepiloto** [comment]
I think I could follow this same implementation to include constellation cubemaps in case you want to implement those too.

**Comment by tkoyama010** [comment]
@jorgepiloto We are waiting for your PR.

**Comment by MaxJPRey** [comment]
@akaszynski The rendering is really nice!

**Pull request merged**
