### PR TITLE
Split DataObject, Common into their own files.

### PR DESCRIPTION
**Pull request by JevinJ**
### Overview

Test of splitting DataObject and Common into dataobject.py, dataset.py

### CODE REVIEW

**Comment by JevinJ** [comment]
@akaszynski, @banesullivan Since .25 is out and there are currently no open PRs affecting common.py, it might make sense to split DataSet, Common now.

**Comment by akaszynski** [comment]
> @akaszynski, @banesullivan Since .25 is out and there are currently no open PRs affecting common.py, it might make sense to split DataSet, Common now.

I think splitting this up after #1107 and #1110 is in order.  A bit late for 0.25, but let's have this out for 0.28.

I think abandoning this and starting a new PR would be best.

**Comment by akaszynski** [comment]
> I think abandoning this and starting a new PR would be best.

With 0.28 out, let's do a quick refactor for this.  Ideally we'd preserve history, but I think we can survive without it.

**Comment by JevinJ** [comment]
I have a type hints branch that touches common.py right now, I'll finish up that, then after #1143 do this, then remove ActiveArrayInfo as discussed in #1143. Preserving history with this method is a pain, I'll look into it again.

**Comment by akaszynski** [comment]
> Preserving history with this method is a pain

At this point I'm fine with trashing the history.  We can can always go back in time prior to the merge.  Still, it seems that there's a solution here:
https://stackoverflow.com/a/33992444/3369879

Otherwise, if it's too difficult to implement smoothly, we can commit and move on.

**Comment by akaszynski** [comment]
Recommend closing this as it's been done in #1160

**Pull request closed without merging**
