### PR TITLE
Make Sphinx Gallery Examples reproducible with `rng` seed

### LINKED ISSUE #6167: Fix failing doc image tests
### Overview
Issue to track and investigate failing tests with the documentation images.
The failing tests are initially reported in https://github.com/pyvista/pyvista/pull/5712, see the build failure [here](https://github.com/pyvista/pyvista/actions/runs/9278295702).

### Image Diff
Here's a diff of 54 failing test images:
https://github.com/pyvista/pyvista/compare/main...user27182:doc/failed_images

There appears to be two main categories of failed tests: 
1. failures from random numbers, i.e. examples that were not captured as part of #6106 but should have been, and
2. failures with MPLCharts, see #6141 

### Software Report Diff
Here's a diff between the Software Report from the successful build in https://github.com/pyvista/pyvista/pull/5718 (when the build images in the `doc_image_cache` were first generated) and the failed build linked above:
https://www.diffchecker.com/WGONBfLU/
From this diff it doesn't appear as though updates to any packages is the cause of the failures.

### Steps to reproduce the bug.

n/a

### System Information

```shell
n/a
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by user27182**
### Overview

Follow-up from #6106. Partly resolves #6167.

### CODE REVIEW

**Review by tkoyama010 — DISMISSED** [review]

**Comment by user27182** [comment]
There were 53 failures from the build in [c986f7e](https://github.com/pyvista/pyvista/pull/6169/commits/c986f7e687b5349a9e64627f1e882f4809fdcf1b)
32 images from that build were added in https://github.com/pyvista/pyvista/pull/6169/commits/66de22bb45052a182aa1f5d506db73f559ad71dd.

So, the checks should reduce the failure count to 21.

**Comment by user27182** [comment]
Draft to prevent merging until it is confirmed that the build is reproducible and the failure count is reduced to 21.

**Comment by user27182** [comment]
LGTM. None of the sphinx gallery tests are failing.

**Review by tkoyama010 — APPROVED** [review]
Thanks for your work :pray:

**Pull request merged**
