### PR TITLE
Fast merge PolyData

### LINKED ISSUE #3920: Make point-merging behavior of `PolyDataFilters.merge()` consistent with `MultiBlock.combine()` and `DataSetFilters.merge()`
### Describe the feature you would like to be added.

Currently, `MultiBlock.combine()` and `DataSetFilter.merge()` use `vtkAppendFilter`'s built-in point merging when point merging is requested. In contrast, `PolyDataFilters.merge()` delegates the point-merging to `vtkCleanPolyData`, which is considerably slower for large meshes.

Performance differences aside, since all of these are using `vtkAppendFilter` under the hood, I would expect the behavior to be consistent.

See performance numbers below for a simple test case.

```python
import pyvista as pv
import time

s = pv.Sphere(theta_resolution=2000, phi_resolution=2000)
h1 = s.clip(normal='x', invert=False)
h2 = s.clip(normal='x', invert=True)

t0 = time.time()
r = pv.MultiBlock([h1, h2]).combine(merge_points=True)
print('MultiBlock.combine():', time.time() - t0)

t0 = time.time()
r = h1.cast_to_unstructured_grid().merge(h2, merge_points=True)
print('UnstructuredGrid.merge():', time.time() - t0)

t0 = time.time()
r = h1.merge(h2, merge_points=True)
print('PolyData.merge():', time.time() - t0)
```

Outputs:
```
MultiBlock.combine(): 1.3390300273895264
UnstructuredGrid.merge(): 1.6437718868255615
PolyData.merge(): 9.812441110610962
```

### Links to VTK Documentation, Examples, or Class Definitions.

_No response_

### Pseudocode or Screenshots

_No response_

### PR DESCRIPTION
**Pull request by akaszynski**
Resolves #3920 by implementing @whophil's suggestion always using `vtkAppendFilter` when merging PolyData and then casting back.

The speedup is noticeable where it counts. Seems that the point merging algorithm grows quadraticly  with `vtkCleanPolyData`.

### 1M points example
```py
>>> import pyvista as pv
>>> sphere_a = pv.Sphere(theta_resolution=1000, phi_resolution=1000)
>>> sphere_b = sphere_a.copy()
>>> timeit sphere_a.merge(sphere_b, merge_points=True)
```

#### `main` branch
```
1.48 s ± 6.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
#### This branch
```
473 ms ± 3.39 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

### 4M points example
```py
>>> import pyvista as pv
>>> sphere_a = pv.Sphere(theta_resolution=2000, phi_resolution=2000)
>>> sphere_b = sphere_a.copy()
>>> timeit sphere_a.merge(sphere_b, merge_points=True)
```

#### `main` branch
```
17.4 s ± 29.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

#### This branch
```
1.97 s ± 21.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

### CODE REVIEW

**Review by banesullivan — APPROVED** [review]
That's quite the speedup

**Comment by whophil** [comment]
LGTM, thanks for implementing @akaszynski!

I just want to add that this change is slightly more than a mere performance twiddle. PyVista will no longer use the `vtkAppendPolyData` filter at all, when it used to do so when merging all-polydata sets. Perhaps this has some other implications.

**Review by whophil — APPROVED** [review]

**Comment by MbBrainz** [comment]
There is a very important implication of this change which is definitely breaking. I have a piece of code that relies on the order of the points after the merge, which is preserved in Pyvista v0.38.1, but not in v0.39.0. 

I've spent a week to figure this out. Of course this is a unstable release and its part of the usage risk, however it would be great to have this ordering of points as part of the testsuite. 

This change should be explicitly mentioned in the documentation or fixed. Im not familiar with the exact workings of the underneath vtk funtionality, but i can imagine that the changing of the filter usage discussed above may have introduced this different behaviour. In that case, a solution would be to add a flag to the PolyData.merge functionality. Something like "preserve_order"=True

**Comment by beroda** [comment]
@banesullivan @akaszynski I am experiencing the same issue as @MbBrainz.

Switching to pyvista 0.39 in our code base at work caused some tests to crash since we rely on the points order for FEM applications.
Is there a workaround ? If not, do you mind if I open an issue to solve that ?
I could propose a PR if needed.

**Comment by beroda** [comment]
@banesullivan No worries, an edge-case is ... an edge-case :wink:

If it is fine for you, I think I will go for the `PolyData.append_polydata` solution, and add a warning to the `merge` documentation.

**Comment by banesullivan** [comment]
Looks like @whophil's foresight was on the nose here -- sounds beneficial to add back a method to use `vtkAppendPolyData`. @beroda go ahead with that approach.

**Pull request merged**
