### PR TITLE
Version bump 0.24.1

### PR DESCRIPTION
**Pull request by akaszynski**
### Version Bump to 0.24.1

I figure since our @pyvista/developers group has gotten large and active, I'd put out a PR instead of just pinging everyone on slack that I'd like to push a release.  The main reasoning for this is due to #645, which turns out to be a deal breaker for using `pyvista` when `stderr` is unavailable for any reason.

This release will include the following commits to master:
- 8ea409ca master origin/master Change base class of pyvista_ndarray back to ndarray (#664)
- 127ec0a7 Fail CI step if any command fails in bash scripts (#666)
- faaf1b26 [doc] Improve installation instructions (#658)
- 582ad8b4 Speed up test_clip_surface (#661)
- bc8b9750 Additional geometry features (#449)
- 9b92ec54 Only volume render point data (#531)
- 75c000df Add PolyData verts setter/getter (#554)
- 2c93aced Add plotting floors (#423)
- 0499cc96 Fix import issues (#656)
- dcf24365 Add tqdm progress bar to filters (#608)
- 4d87fb35 Fix potential false negative in TestSetItem.test_setitem_should_change_value. (#655)
- fae1d500 Refactor pyvista_ndarray (#654)
- 7f78a8c1 Remove Cells or Faces (#653)
- bc41aaac Use Enum for FieldAssociation (#652)
- ea24bc54 fork/master Add basic API for background image (#594)
- bc80eeb4 FIX: Logging error (#648)
- dd163eb5 patched faulthandler when missing stdout (#645)
- ff02a2c6 Fix auto generation of spacing for 2d uniform grids (#643)
- aea0751a Use parent method to close BackgroundPlotter (#641)

Anyone who objects to this release, please let me know.  Otherwise, I need this release soon for the bugfix.

### CODE REVIEW

**Comment by banesullivan** [comment]
I'm all for this patch release! I'd like to make sure @GuillaumeFavelier is on board

**Comment by imsodin** [comment]
A comment that essentially comes back to something I brought up recently in slack (https://pyvista.slack.com/archives/CQ2L29K63/p1584440605018100) and I think it applies here:  
If the breaking change is #645, I'd do a dot release with just that commit. Otherwise you take the chance that it does fix something breaking, but one of the other commits just introduces something new. To do that properly you'd have to introduce any kind of branching scheme with a release branch, or stable version branches or something similar (relevant discussion is already in slack).

Maybe this is too late for this dot release, but I really think it would be beneficial to tackle this as soon as possible to have such a mechanism the next time a quick dot release is needed to fix some breakage.

**Comment by GuillaumeFavelier** [comment]
I'm catcing up here. 

> which turns out to be a deal breaker for using pyvista when stderr is unavailable for any reason.

I understand :+1: 

>  I'd do a dot release with just that commit.

+1 for this one. 

Taking this graph as example, our current `master` branch is closer to `develop` I think so if I understand what you mean @imsodin, we would need another branch with a slightly slower merge process like the `master` below right?

image

**Comment by GuillaumeFavelier** [comment]
In that case, I suggest a `stable` branch which is updated during release process or when a hotfix is needed.

**Comment by imsodin** [comment]
Yes and no. As I already explained in slack I don't like the approach shown in that schematic, it is too complex in my opinion. I like squash merging as we do now much more. My preferred way would be to create release branches: E.g. when releasing 0.24.0 (or it's first beta/RC if we had that) you create a new branch 0.24. That branch then only gets commits related to bugfixes and features newly introduced in 0.24. At the same time development on master can go on as usual and some time in the future, we cut the 0.25 branch from that.

**Comment by GuillaumeFavelier** [comment]
Oooh now I get it. I was thinking about only 2 main branches: `master` and `stable` but it's actually one for each version, thanks for explaning.

I know some projects using this branching system, I'm just not used to it.

So in the case of this PR, you would create a new branch from the latest release with just the relevant commit.

> That branch then only gets commits related to bugfixes and features newly introduced in 0.24. At the same time development on master can go on as usual and some time in the future, we cut the 0.25 branch from that.

Does it mean that you have to maintain all versions?

**Comment by imsodin** [comment]
I feel like I need to put this first:  
I am just letting my opinions loose here. I am no expert, I do believe (hope) my preferences are based on actual arguments and a bit of experience, but please do take this just as the suggestions they are, no need to follow them.

> So in the case of this PR, you would create a new branch from the latest release with just the relevant commit.

Yes.

> Does it mean that you have to maintain all versions?

No, how many old release still get bugfixes is a choice you make. The minimal way is to support the latest release branch with bugfixes (one anyway tries to do that I guess) until one does the next release. Then the old release branch doesn't get any more fixes, just the new one. At this stage of development I don't think there's any point in maintaining old releases.

**Comment by GuillaumeFavelier** [comment]
> create a new branch from the latest release with just the relevant commit.

I think it is a great feature to have whatever the chosen model is. To avoid releasing with unexpected/unintentional bugs, I think that focusing only on the hotfix is better.

This is not how we proceeded so far and this is not the topic of this PR so I will open an issue about it. Thanks for taking the time to clarify your comment @imsodin, I just suggest to move the discussion there.

To move forward, I'll approve @akaszynski

**Comment by akaszynski** [comment]
Excellent discussion, and I think we can actually start doing this now.  Here's a summary of the approach based on the discussion above:
- `master` becomes the de facto "stable" branch that we push releases to.
- Each minor release gets a branch that is effectively the `develop` branch named after the minor release vesion (to avoid our tag names, I'll name it something like `develop/0.24.0` unless someone comes up with a better naming convention.
- Features will be merged with the develop branch.  Hotfixes will be merged with both develop and master branches.  Hotfixes should be small and only for critical bugs.
- Prior to merging the develop branch we'll do extensive testing.

@banesullivan, I'd like your thoughts as well.  In my opinion this is overdue as our stability will be vastly improved by this change.

Next :
- I'll create a new branch from master named `develop/0.24.0` from latest master.
- I'll submit a PR to rollback master to the state it was at `0.24.0`.  If you're fine with it, I'll include the hotfix there as a commit and modify the version to `0.24.1`.

I'll also abandon this PR.

**Comment by banesullivan** [comment]
Why not just make a new branch called `develop/0.24.0` from that tag? We shouldn't rollback the `master` branch.

Then we can make a new branch called `develop/0.24.1` that only includes the hotfix for the fault handler

**Comment by GuillaumeFavelier** [comment]
Or we could merge this PR and start the branch synchronisation from there?

`master` stays `master` but from now gets only releases and we create `develop/0.24.1` as a new starting point.

This way, we don't rollback `master` and don't abandon the PR.

**Comment by akaszynski** [comment]
Rollback wasn't the right word.  Basically the PR for master will revert the changes made up until now, but will still include the history (force push is only cool in star wars).

The new branch `develop/0.25.0` will contain all the changes made to master to-date.

**Comment by akaszynski** [comment]
Ok, that works too @GuillaumeFavelier.  Our changes since then haven't been too drastic, and it's less time spent gitting around.

**Comment by akaszynski** [comment]
I'll also add @banesullivan's gallery PR.  Expect another merge with master and then I'll merge this upon passing CI.

Again, thanks to all the discussions here from everyone around the world @pyvista/developers.

**Comment by imsodin** [comment]
Maybe i am missing something, however the (approach outlined akaszynski)[https://github.com/pyvista/pyvista/pull/669#issuecomment-611040452] seems upside down - it's neither Git-Flow as in the schematic above nor the stable branches I proposed. Creating `develop/0.25.0` and in the future `develop/0.26.0` etc for the main development adds a lot of churn compared a single branch where the main development happens and one other branch for the currently released version, where only bugfixes happen.

> Why not just make a new branch called develop/0.24.0 from that tag? We shouldn't rollback the master branch.
> 
> Then we can make a new branch called develop/0.24.1 that only includes the hotfix for the fault handler

What's the advantage for separate branches for patch releases? I'd expect them all to be on a single continuous branch, as the happen one after the other. And the `develop/` prefix seems like a misnomer, given that's where only bugfixes, no new developments happen.

**Comment by GuillaumeFavelier** [comment]
From what I understand of https://github.com/pyvista/pyvista/pull/669#issuecomment-611040452 I think we gain a lot of flexibility compared to our current linear approach since we separate active development and testing (`develop/`) from stable (`master`). And I think we all agree on that goal.

> What's the advantage for separate branches for patch releases?

I have to trouble to understand the question so I will try to rephrase: you suggest that all development related to `0.24` should remains on the `develop/0.24'` without the need for the dot version branch, right?

**Comment by akaszynski** [comment]
@imsodin, are you proposing that `master` be the `develop` branch (see gitflow) where all the changes are pushed to, and we'd create a versioned branch that is the `stable` branch based on the version release where only hotfixes are pushed to.

Both work in my opinion and it's really about terminology.  In either case we have a stable branch where only hotfixes (patch releases) are pushed to.  That branch falls behind whatever our development branch is and is caught up once we're ready to test out the release candidate (maintained and tracked in a separate branch).  Once the RC is good to go, we merge to the "stable branch" and make a new development branch.

**Comment by akaszynski** [comment]
BTW, what @imsodin describes is actually how a certain large company does their devops.  They have release branches that get critical fixes for those who are using those versions of the software, no master branch, and then one develop branch.  If we did what @imsodin suggests, I think it would end up with less work as we can just keep master the way it is (master is basically the unstable develop branch), and we can support a limited number of branches (i.e. `release/0.24`).

**Comment by akaszynski** [comment]
I really think @imsodin's core approach as it makes the most sense and I've seen it in industry.  To summarize:
- PRs are always merged with `master`
- Releases get their own special branch based on the minor (and eventually major) release.  The upcoming release will be `release/0.24`.  Patch releases will be tagged from that branch.  Only hotfixes should be merged with the release branch.

I'd like to get this out soon as there's other issues cropping up on other packages ([pyansys #203](https://github.com/akaszynski/pyansys/issues/203) and within closed source development.  I would have merged it tonight, but I want a clear consensus since I know there's several groups now relying on the stability and development of `pyvista`.

**Pull request merged**
