### PR TITLE
Minor fixes for voxelize

### PR DESCRIPTION
**Pull request by banesullivan**
Here are some fixes for the `voxelize` method. This ensures any passed mesh type will now work as sometimes the `select_enclosed_points` would throw an error if the mesh wasn't `PolyData` or wasn't a closed surface.

Also, this now sets a default for `density` as 1/100th the mesh length - seemed reasonable to me.

With this, close https://github.com/pyvista/pyvista-support/issues/78

Data:  [salt_body.ply.zip](https://github.com/pyvista/pyvista/files/4082374/salt_body.ply.zip)

```py
import pyvista as pv
surf = pv.read("salt_body.ply")
grid = pv.voxelize(surf, check_surface=False)
grid.plot()
```

download

### CODE REVIEW

**Comment by banesullivan** [comment]
We should also add an example for this utility - it is super useful and probably difficult to find/realize is available

**Comment by bsburnham** [comment]
This is really great stuff! I'm curious, about the `density` method:
1) is the `length` of the mesh calculated along the _long_  axis of the mesh? 
1) is it possible to change it to generate voxel dimensions set by the user? (i.e., if someone wanted voxels that are 10m x 10m x 10m **or** 10km x 10km x 10km, they can set it?)

As far as examples go- I think one where voxels are used as input into a geocellular model instance where a user could 'fill' the voxels with property data (e.g., porosity, perm, Vp, Vs). This would be really awesome to use in Paraview (or a visualisation software of their choice) and would have wide applicability, I think.

**Comment by banesullivan** [comment]
> is the length of the mesh calculated along the long axis of the mesh?

the length is the distance of the diagonal of the bounding box.

> is it possible to change it to generate voxel dimensions set by the user? (i.e., if someone wanted voxels that are 10m x 10m x 10m or 10km x 10km x 10km, they can set it?)

The `density` argument is exactly that (The uniform size of the voxels. Defaults to 1/100th of the mesh length.)

> As far as examples go- I think one where voxels are used as input into a geocellular model instance where a user could 'fill' the voxels with property data (e.g., porosity, perm, Vp, Vs). This would be really awesome to use in Paraview (or a visualisation software of their choice) and would have wide applicability, I think.

Could you provide such an example?

**Comment by bsburnham** [comment]
> The density argument is exactly that (The uniform size of the voxels. Defaults to 1/100th of the mesh length.)

Ah yes, this makes sense! 

> Could you provide such an example?

Unfortunately I don't have a good clear example of this. I was thinking though.. is there a way to reverse engineer the fluvial channel example that you have? `load_channels`  I.e., create 3D meshes from the property model then voxelise the mesh and add the properties back into it? Might be a crazy idea??

**Comment by banesullivan** [comment]
I added something that should suffice for this in #581 see https://github.com/pyvista/pyvista/pull/581/commits/8a8bcf38fee0f4403ae1544aa7214928db676e0d

**Pull request merged**
