### PR TITLE
Fix module `vtkImageDilateErode3D` not found error

### PR DESCRIPTION
**Pull request by Arnav-2004**
### Overview

As stated by @banesullivan

> This sounds like an incompatibility with conda-forge's 9.0 VTK build. We need to handle vtkImageDilateErode3D's import with caution. Unfortunately, at this time, our testing matrix for VTK versions only validates the official wheels on PyPI.

We can gracefully handle this error.

Resolves: #4815 

### Details

- Bug: Module `vtkImageDilateErode3D` not found error on remote servers.

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]
LGTM. Thanks!

**Review by MatthewFlamm — APPROVED** [review]
I have some future looking comments for this type of usage, but it isn't relevant for this PR, I will start an issue.

**Review by banesullivan — APPROVED** [review]

**Comment by banesullivan** [comment]
@tkoyama010, could we issue a patch release with this change? Would you like me to do that or are you up for it?

**Comment by tkoyama010** [comment]
@banesullivan I will deploy the patch release. Thanks for your comment.

**Pull request merged**
