### PR TITLE
Rotate teapot for flip_z() doctest example

### PR DESCRIPTION
**Pull request by adeak**
The `flip_z()` doctest result looks like this:

two identical-looking teapots, before and after `flip_z()`

The teapots look identical because the xy plane in this configuration is parallel to the symmetry plane of the teapot.

If we first rotate the teapot around `x` we get a more meaningful result:

two teapots, one of them upside down

This makes the test slightly different from `flip_x()` and `flip_y()`, but it's probably more important to have the example be useful in isolation.

### CODE REVIEW

**Review by akaszynski — DISMISSED** [review]
LGTM. I thought the labeler was fixed...

**Comment by akaszynski** [comment]
> LGTM. I thought the labeler was fixed...

Actually, seems like this fails for forks... @tkoyama010, let's find a way to disable this for forks.

**Comment by adeak** [comment]
At worst I can start using feature branches on the main repo. Vast majority of PRs seems to come from members anyway.

**Comment by akaszynski** [comment]
> At worst I can start using feature branches on the main repo. Vast majority of PRs seems to come from members anyway.

I wouldn't want to discourage forks. Let's get it working for forks.

**Comment by tkoyama010** [comment]
@akaszynski Could you please check that the setting is the follwing?

**Comment by akaszynski** [comment]
> @akaszynski Could you please check that the setting is the follwing?

@banesullivan, are we fine with upping the scope on `GITHUB_TOKEN`? I doubt that we'll run into issues, but it's an additional security risk.

**Comment by tkoyama010** [comment]
I reverted the trigger of labeling which is dropping in https://github.com/pyvista/pyvista/pull/2877.

**Comment by banesullivan** [comment]
> @banesullivan, are we fine with upping the scope on GITHUB_TOKEN? I doubt that we'll run into issues, but it's an additional security risk.

I'm comfortable with this, just so long as we aren't using a Personal Access Token (PAT) which can have elevated permissions

**Review by akaszynski — DISMISSED** [review]
Still LGTM.

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Pull request merged**
