### PR TITLE
🗑️ Deprecate code that needs to be cleaned up.

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

🗑️ Deprecate code that needs to be cleaned up in import _vtk.py .

 

### Details

- None

### CODE REVIEW

**Review by tkoyama010 — COMMENTED** [review]
WFM

**Review by adeak — APPROVED** [review]
Good catch! I've found a few other duplicates. For each import block I passed the imported names to this function as a triple-quoted string:
```py
from collections import Counter

def find_duplicates(s):
    words = s.splitlines()
    cnt = Counter(map(str.strip, words))
    return [word for word, freq in cnt.items() if freq > 1]
```

Whatever comes out is a duplicate. Actually, I now see that I didn't account for the trailing comma on _most_ imports so there's a tiny chance that we still have a couple of duplicates where the second copy is the last one in the import list...

Going forward it would be nice if we could list these alphabetically to make spotting duplicates easier, but

1. that would be hard to maintain (I mean new items would likely be inserted in the wrong places, and
2. we already had duplicates on adjacent lines and they went under the radar until now.

**Comment by adeak** [comment]
OK, found a last one due to the comma. For the record here's the function:
```py
from collections import Counter

def find_duplicates(s):
    words = s.replace(',', '').splitlines()
    cnt = Counter(map(str.strip, words))
    return [word for word, freq in cnt.items() if freq > 1]
```

**Comment by tkoyama010** [comment]
Thank @adeak . It is nice function!

**Comment by adeak** [comment]
@tkoyama010 I hope you don't mind that I renamed the PR, but this way it will be a lot easier to find it in the future :)

**Pull request merged**
