### PR TITLE
Add support for wrapping TetGen and PyMeshFix meshes

### LINKED ISSUE #233: Support for pymeshfix and tetgen types
We should allow `pymeshfix.MeshFix` and `tetgen.TetGen` types to be passed around PyVista's plotting functions.

Current issue:

```py
import pyvista as pv
import pymeshfix as mf
from pyvista import examples
import numpy as np


mesh = examples.download_bunny()
bunny = mf.MeshFix(mesh)

# A nice camera location of the cow
cpos = [(-0.2, -0.13, 0.12),
        (-0.015, 0.10, -0.0),
        (0.28, 0.26, 0.9)]

holes = bunny.extract_holes()

# Render the mesh and outline the holes
p = pv.Plotter()
p.add_mesh(bunny, color=True)
p.add_mesh(holes, color='r', line_width=8)
p.camera_position = cpos
p.enable_eye_dome_lighting() # helps depth perception
p.show()
```

```py
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-f3dd0d84605a> in <module>
     17 # Render the mesh and outline the holes
     18 p = pv.Plotter()
---> 19 p.add_mesh(bunny, color=True)
     20 p.add_mesh(holes, color='r', line_width=8)
     21 p.camera_position = cpos

~/Documents/OpenGeoVis/Software/pyvista/pyvista/plotting.py in add_mesh(self, mesh, color, style, scalars, rng, stitle, show_edges, point_size, opacity, line_width, flip_scalars, lighting, n_colors, interpolate_before_map, cmap, label, reset_camera, scalar_bar_args, multi_colors, name, texture, render_points_as_spheres, smooth_shading, render_lines_as_tubes, edge_color, ambient, show_scalar_bar, nan_color, nan_opacity, loc, backface_culling, rgb, categories, **kwargs)
    770         # Convert the VTK data object to a pyvista wrapped object if neccessary
    771         if not is_pyvista_obj(mesh):
--> 772             mesh = wrap(mesh)
    773 
    774         if smooth_shading:

~/Documents/OpenGeoVis/Software/pyvista/pyvista/utilities.py in wrap(vtkdataset)
    335         'vtkMultiBlockDataSet' : pyvista.MultiBlock,
    336         }
--> 337     key = vtkdataset.GetClassName()
    338     try:
    339         wrapped = wrappers[key](vtkdataset)

AttributeError: 'MeshFix' object has no attribute 'GetClassName'
```

### PR DESCRIPTION
**Pull request by banesullivan**
Resolve #233

### CODE REVIEW

**Comment by akaszynski** [comment]
@banesullivan,

Saw a test failed due to a ``urllib.error.HTTPError``.  We should implement a try, catch for just these error types so we can still include these tests without having fail the builds.

**Comment by banesullivan** [comment]
Yeah I’m absolutely tired of these failing downloads. I’ve been avoiding adding decorations or try catch statements because each of the many download test would have to have their own and this would make that file a bit noisy

I’m wondering if we could make a separate directory under tests called `flaky` and have pytest run those but not mark the build as failed

**Comment by banesullivan** [comment]
The other issue is that we use several of these downloadable examples when generating the example gallery in the docs

**Comment by banesullivan** [comment]
One trick I did the a plane the other day (totally offline) was copy/paste the contents of the data directory from https://github.com/pyvista/vtk-data into `pyvista.EXAMPLES_PATH`. 


Perhaps cloning the data repo at the start of the build would be more reliable?

**Comment by banesullivan** [comment]
NOTE: I just turned off the downloads on Travis (environment variable can control this) since there are a lot of builds happening

**Pull request merged**
