### PR TITLE
Select type of event for slider widget

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR allows the user to specify how often the slider interacts with the callback.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Let me know what you think @banesullivan

**Comment by GuillaumeFavelier** [comment]
+1 for real interactive testing but I don't know where to start

**Comment by banesullivan** [comment]
Interactive testing is definitely needed for the widgets, picking features, and more... perhaps down the road, we can implement a module for automatically interacting with all of these features

**Comment by banesullivan** [comment]
This looks good to me!

**Comment by banesullivan** [comment]
@GuillaumeFavelier, you should have full "maintainer" access now, so feel free to merge when you're ready

**Comment by GuillaumeFavelier** [comment]
Wow! Thank you so much! Okay I'll merge then

**Comment by GuillaumeFavelier** [comment]
Whoops, I forgot to edit the commit message before merging. I'll be careful from now on, sorry.

**Pull request merged**
