### PR TITLE
MAJOR: reorganize internal modules and implement volume rendering

### LINKED ISSUE #189: describe system information
We should implement a function in `vtki` that will print a user's system information - i.e. all the details that would be useful when user experiences and reports a bug.

Inspiration from @mmagnuski in the comment on #186:

> additional info (as given by `import mne; mne.sys_info()`):
> ```
> Platform:      Windows-10-10.0.17763-SP0
> Python:        3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
> Executable:    C:\Users\mmagn\Continuum\anaconda3\python.exe
> CPU:           Intel64 Family 6 Model 158 Stepping 10, GenuineIntel: 12 cores
> Memory:        15.9 GB
> 
> numpy:         1.16.2 {blas=mkl_rt, lapack=mkl_rt}
> matplotlib:    3.0.2 {backend=module://ipykernel.pylab.backend_inline}
> mayavi:        4.6.2 {qt_api=pyqt5, PyQt5=5.9.2}
> ```

and @prisae's work with SimPEG's version info

### LINKED ISSUE #237: frog example broken
As mentioned in https://github.com/pyvista/pyvista/pull/231#issuecomment-496247649, the frog example dataset isn't working properly:

```py
>>> from pyvista import examples
>>> examples.download_frog()
MetaImage: Read: Cannot open data file
ERROR:root:MetaImage cannot read data from file.
UniformGrid (0x121c23d08)
  N Cells:	31594185
  N Points:	31960000
  X Bounds:	0.000e+00, 4.990e+02
  Y Bounds:	0.000e+00, 4.690e+02
  Z Bounds:	0.000e+00, 2.025e+02
  Dimensions:	500, 470, 136
  Spacing:	1.000e+00, 1.000e+00, 1.500e+00
  N Scalars:	1
```

### PR DESCRIPTION
**Pull request by banesullivan**
This implements a major restructuring of the internal modules to make management, refactoring, and implementing new features a bit easier moving forward.

The library has been in major need of this type of clean up/restructuring and with #231, it was required.

Closes #231: This has the changes from #231 in it already (which are incomplete). I needed to start modularizing the plotting code to implement the volume rendering properly so this PR is basically a whole lot of prep work to implement #231.

When complete, I will *SQUASH AND MERGE* these changes into the master branch - while closing #231. 

@akaszynski - I'd appreciate a close review on this one. Assuming I did everything right, usage of the API should not change to the user and all of the tests/examples have remained untouched.

If any external projects have absolute imports like `pyvista.pointset.PolyData` they may need to be changed to `pyvista.PolyData` or `pyvista.core.pointset.PolyData`

## The New Structure

There are now four main modules for the PyVista API:

- `core`: The underlying mesh types and filters to process those mesh types. This is the "mesh analysis" from our title
- `plotting`: All the code to handle 3D rendering/plotting of the `core` types and utilities around 3D plotting
- `utilities`: A conglomerate of tools for creating datasets, reading files, and the old utilities module for converting arrays, etc.
- `examples`: the good ole examples module that's always been there

## Next Steps

- [x] reorganize docs to reflect the internal reorganization
- [x] modularize the `add_mesh` method and borrow what we can for the new `add_volume` method.
- [x] create a class that will manage actors/mappers so that we can use volume mappers just like dataset mappers and implement color bars
- [x] implement volume rendering for ImageData (UniformGrids)
- [x] finish volume rendering example
- [x] address all items from #231 

# Features

Closes #189 with new `generate_report` function
Closes #237

### CODE REVIEW

**Comment by banesullivan** [comment]
@akaszynski: This is ready for your review

**Comment by banesullivan** [comment]
Once this lands, I'll handle pushing a pre-release to PyPI then trigger the CIs to test that pre-release for external projects. We need a green light from downstream dependencies before pushing a public release.

**Comment by banesullivan** [comment]
@GuillaumeFavelier, with you both being active lately and quite familiar with the PyVista API, would you being will to do a quick review on these changes to get some fresh eyes on this and make sure I haven't overlooked something?

**Comment by banesullivan** [comment]
@supersubscript, if you are able to do a quick review here on the re-implementation of your volume rendering code from #231 and/or the rest of these changes, it would be greatly appreciated.

I tackled quite a lot here so it'd be helpful to have fresh eyes on this to make sure I haven't overlooked the impact of some of these changes

**Comment by akaszynski** [comment]
@banesullivan,

I’ll be able to review and test it against my closed source code this weekend.

**Comment by banesullivan** [comment]
Sounds good, @akaszynski - I'm confident that usage of the overall API hasn't changed but always best to check befor pushing any releases!

**Comment by banesullivan** [comment]
Green light from `mne-python`, PVGeo, TetGen, PyMeshFix, `omfvista`, and `discretize`

**Comment by akaszynski** [comment]
This branch checks out with my closed source modules!

**Pull request merged**
