### PR TITLE
ENH: Expose tip_resolution in pyvista.Arrow

### LINKED ISSUE #623: Missing tip_resolution in pyvista.Arrow
This is partly a feature request. The API of `pyvista.utilities.geometric_objects.Arrow` exposes `shaft_resolution` and other parameters, but `tip_resolution` is missing. The documentation reflects this, so behaviour is consistent.

Example use of `shaft_resolution`:

```py
import pyvista as pv

plotter = pv.Plotter(shape=(1, 2))
for isub,resolution in enumerate([20, 50]):
    plotter.subplot(0, isub)
    arrow = pv.Arrow(shaft_resolution=resolution)
    plotter.add_mesh(arrow, show_edges=True)

plotter.show()
```
mcve_screenshot

[Documentation](https://docs.pyvista.org/utilities/geometric.html#pyvista.Arrow):
```
pyvista.Arrow(start=(0.0, 0.0, 0.0), direction=(1.0, 0.0, 0.0), tip_length=0.25, tip_radius=0.1, shaft_radius=0.05, shaft_resolution=20)
```

The request is so that `tip_resolution` is similarly exposed by the API.

### PR DESCRIPTION
**Pull request by adeak**
### Overview

The API of `pyvista.Arrow` was missing `tip_resolution`. Exposing this parameter is straightforward.

Resolves #623 

### Details
 
The change exposes the tip resolution setting of `vtkArrowSource` objects. Short example code demonstrating its use:

```py
import pyvista as pv

plotter = pv.Plotter(shape=(1, 3))
for isub,resparams in enumerate([{}, {'shaft_resolution': 50}, {'tip_resolution': 50}]):
    plotter.subplot(0, isub)
    arrow = pv.Arrow(**resparams)
    plotter.add_mesh(arrow, show_edges=True)

plotter.show()
```

mcve_screenshot_after

The first subplot is the default call to `Arrow()` which should be the same as the original default, the middle one changes the already existing `shaft_resolution` setting, and the third subplot demonstrates the new feature.

I chose a default resolution of `20` for the parameter, because that seemed like the current behaviour of `pv.Arrow`. I also snuck in a minor change in the docstring to make most of the parameter descriptions end in a fullstop.

I got four errors locally in pytest (3 in test_meshio and 1 in test_file_format) and an error during doctests, but none of them seem related to my change.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
> I got four errors locally in pytest

No worries, we are currently working on the CIs so this is expected

**Comment by adeak** [comment]
Thank you, Guillaume, and also for the failure feedback!

**Comment by adeak** [comment]
Is there a preference for force push vs merge commits? Or does it not matter because it all gets squashed anyway in the end?

**Comment by GuillaumeFavelier** [comment]
It's squashed but +1 for merge

**Comment by akaszynski** [comment]
Thanks for the PR @adeak!

@pyvista/developers, do we need to give him write access?

**Comment by adeak** [comment]
@akaszynski thank you very much for the vote of confidence, but I literally started playing with pyvista yesterday, and I'd much rather not be able to break anything :)

**Comment by banesullivan** [comment]
I'll merge. I'd like to move towards having a single gatekeeper for merging PRs who is aware of everything going on across all PRs to keep things clean and orderly. I'll ping Slack about this.

**Comment by adeak** [comment]
Thank you, @banesullivan. I imagine that a gatekeeper system would also help with issues such as the test failures that were in master :)

**Pull request merged**
