### PR TITLE
More parameters to configure the axes marker

### PR DESCRIPTION
**Pull request by liangwang0734**
### Overview

Expose more parameters in `create_axes_marker` and pipe them to `add_axes`.

This makes the marker more visible in some cases.

 
resolves https://github.com/pyvista/pyvista/issues/2288

### Details
An usage example:
```python
import pyvista

pl = pyvista.Plotter()
actor = pl.add_mesh(pyvista.Box(), show_edges=True)
marker_args = dict(cone_radius=0.6,
                   shaft_length=0.7,
                   tip_length=0.3,
                   ambient=0.5,
                   label_size=(0.4, 0.16))
_ = pl.add_axes(line_width=5, marker_args=marker_args)
pl.show(jupyter_backend='static')
```
- Some parameters might be usable for the box widget as well.
- We may expose more text control, like bold and shape.
- I'm not a Pyvista developer. Please feel free to reject this PR if the formatting and other things are not compliant. But I do hope such features could be implemented.
- Tested locally in Jupyter. But I didn't do any unit/regression test.
```
--------------------------------------------------------------------------------
  Date: Wed Mar 02 09:33:10 2022 EST

                OS : Linux
            CPU(s) : 4
           Machine : x86_64
      Architecture : 64bit
       Environment : Jupyter
       File system : unknown
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) HD Graphics 4600 (HSW GT2)
       GPU Version : 4.6 (Core Profile) Mesa 21.3.3

  Python 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0]

           pyvista : 0.34.dev0
               vtk : 8.2.0
             numpy : 1.21.2
           imageio : 2.6.1
           appdirs : 1.4.4
            scooby : 0.5.11
        matplotlib : 3.5.0
             PyQt5 : 5.9.2
           IPython : 8.0.1
        ipyvtklink : 0.2.2
             scipy : 1.7.1
              tqdm : 4.63.0

  Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by banesullivan** [comment]
@liangwang0734, thank you for the contribution! From a quick glance, this is looking fantastic but I'd like to check it out and review a bit further to see if there is anything additional we should add

**Review by tkoyama010 — CHANGES_REQUESTED** [review]
Thanks for the PR. The source change looks good. Is it possible to add a test on this feature?

**Comment by liangwang0734** [comment]
> 

I included a test in the doc of `add_axes` (which passed the check). Is that sufficient?

**Comment by tkoyama010** [comment]
It would be good to add the following location
https://github.com/pyvista/pyvista/blob/07993d56e135e28eb07a1f857cf35f1211e9cac0/tests/plotting/test_plotting.py#L753-L776

**Comment by liangwang0734** [comment]
> It would be good to add the following location
> 
> https://github.com/pyvista/pyvista/blob/07993d56e135e28eb07a1f857cf35f1211e9cac0/tests/plotting/test_plotting.py#L753-L776

Sorry, @tkoyama010 , how do I test the new function I added to `test_plotting.py` locally before committing?

I added a new function `test_add_axes_parameters`, and ran
```pytest tests/plotting/test_plotting.py::test_add_axes_parameters --reset_image_cache```
But there is no new image generated. Do I (and how do I) add the base image for the new test?

I added the following test
```python


def test_add_axes_parameters():
    plotter = pyvista.Plotter()
    plotter.add_axes()
    marker_args = dict(
        cone_radius=0.6,
        shaft_length=0.7,
        tip_length=0.3,
        ambient=0.5,
        label_size=(0.4, 0.16),
    )
    plotter.add_axes(
        line_width=5,
        marker_args=marker_args,
        viewport=(0, 0, 0.4, 0.4),
    )
    plotter.show(before_close_callback=verify_cache_image)
```

BTW, I tried to add `@skip_no_plotting` as directed by the [contribution page](https://docs.pyvista.org/extras/developer_notes.html) but it failed.

**Comment by tkoyama010** [comment]
Good question. Please check the following documentation If you have any questions, please feel free to ask.
https://dev.pyvista.org/extras/developer_notes.html#notes-regarding-image-regression-testing

**Review by tkoyama010 — APPROVED** [review]
LGTM. Thanks @liangwang0734 . We can merge this after @banesullivan 's review.

**Review by banesullivan — APPROVED** [review]
Looks great! Thanks, @liangwang0734

**Pull request merged**
