### PR TITLE
TST: Make CIs happy

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows https://github.com/pyvista/pyvista/pull/942#issuecomment-715430901, let's see how the CIs react

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
This reverts only a part of https://github.com/pyvista/pyvista/pull/959 and we should keep https://github.com/pyvista/pyvista/pull/942#issuecomment-715402292 in mind

**Comment by GuillaumeFavelier** [comment]
This confirms https://github.com/pyvista/pyvista/pull/942#issuecomment-715426680 so if we bring #959 back in, we need to find a solution to call `deep_clean()`. There is incompatibility between those 2 paradigms.

Either 1) we consider that closed means "it's over completely, nothing else to be done" and we 'clean' everything at that time or 2) we delay the memory cleaning like we do right now and we keep the 'close' and 'deep_clean' concepts separated.

Right now, I would say that the architecture follows 2)

**Comment by larsoner** [comment]
I think (2) is dangerous because end users will expect (1). But it's going to be tricky to switch, so I can live with either.

**Comment by akaszynski** [comment]
> Either 1) we consider that closed means "it's over completely, nothing else to be done" and we 'clean' everything at that time or 2) we delay the memory cleaning like we do right now and we keep the 'close' and 'deep_clean' concepts separated.

There are some features that might be needed once the plotter has been closed like `screenshot` and `camera_position`, so perhaps there's a way to reconcile this.  I think closing the plotter should take down the window and `deep_clean` should be executed when the plotter is collected.  This is sort of the best of both worlds as we can ensure/test garbage collection by either `del plotter` but we can still access the plotter until that point (or the user overwrites it, or it's out of scope).

**Comment by larsoner** [comment]
Okay let's revert #959 then to be safe

**Comment by akaszynski** [comment]
> Okay let's revert #959 then to be safe

@GuillaumeFavelier, I'll leave this up to you since you've started the PR.

**Pull request merged**
