### PR TITLE
Use pyvista-wheels package index

### PR DESCRIPTION
**Pull request by banesullivan**
Requires https://github.com/pyvista/pyvista-wheels/issues/8

I set up the pyvista-wheels repository to start publishing its wheels to GitHub pages and host a new package index at https://wheels.pyvista.org, making it much easier to install our custom wheels:

```bash
pip install --find-links https://wheels.pyvista.org/osmesa vtk
```

This is a bit better than hard coding the name of the wheel and it's path on github. Moving forward, we will provide more wheel variants in this package index.

### CODE REVIEW

**Comment by banesullivan** [comment]
Debugging an issue with the docker image...

**Comment by banesullivan** [comment]
W need the OSMesa wheels to be manylinux wheels in order for find-links to properly work

**Comment by akaszynski** [comment]
@banesullivan, this seems to work as is. Is this ready for review/merge?

**Comment by akaszynski** [comment]
@banesullivan, this seems to work as is. Is this ready for review/merge?

**Comment by banesullivan** [comment]
I'd like to hold off on this until we can properly make those wheels manylinux so the `--find-links` properly resolves

but if it works, it works 🤷🏻

**Comment by banesullivan** [comment]
I'm not convinced this is actually working:

```
Run pip install --find-links https://wheels.pyvista.org/osmesa vtk
  pip install --find-links https://wheels.pyvista.org/osmesa vtk
  shell: /usr/bin/bash -e {0}
  env:
    USE_CACHE: true
    PYVISTA_OFF_SCREEN: True
    ALLOW_PLOTTING: true
    SHELLOPTS: errexit:pipefail
    pythonLocation: /opt/hostedtoolcache/Python/3.8.1[2](https://github.com/pyvista/pyvista/runs/5610931969?check_suite_focus=true#step:6:2)/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
    VIRTUAL_ENV: /home/runner/.virtualenvs/.venv
Looking in links: https://wheels.pyvista.org/osmesa
Requirement already satisfied: vtk in /home/runner/.virtualenvs/.venv/lib/python[3](https://github.com/pyvista/pyvista/runs/5610931969?check_suite_focus=true#step:6:3).[8](https://github.com/pyvista/pyvista/runs/5610931969?check_suite_focus=true#step:6:8)/site-packages ([9](https://github.com/pyvista/pyvista/runs/5610931969?check_suite_focus=true#step:6:9).1.0.dev0)
```
(from the build log)

VTK was cached, so the install with --find-links is ignored. I'm almost certain that if we clear the cache, VTK will not properly resolve and it will default to the PyPI wheel

**Comment by akaszynski** [comment]
It might be be best to close this. It's no possible, at the moment to build wheels with OSMesa and have them "manylinux"-able.

**Pull request closed without merging**
