### PR TITLE
Save image only when necessary

### PR DESCRIPTION
**Pull request by akaszynski**
### Plot Optimization Patch
While testing out VTK9, I discovered that the unit tests were much slower.  It turns out part of the issue is that we're saving a screenshot when the `show` method is triggered in the `Plotter` class:

```python
self.last_image = self.screenshot(screenshot, return_img=True)
self.last_image_depth = self.get_image_depth()
```

In VTK < 9.0, this adds a small overhead, but in VTK 9, the overhead is quite noticeable.  In an effort to streamline `pyvista` regardless of the VTK version, this PR adds a the global variable `BUILDING_GALLERY` that is enabled while building the documentation.  Here's the timings for `vtk` 8.1.2.

#### No screenshots
```python
>>> pyvista.BUILDING_GALLERY = False
>>> timeit grid.plot(interactive=False)
134 ms ± 1.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

#### Screenshots
```python
>>> pyvista.BUILDING_GALLERY = True
>>> timeit grid.plot(interactive=False)
201 ms ± 1.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

### CODE REVIEW

**Comment by akaszynski** [comment]
@banesullivan, I'd like you to take a look at this since you originally implemented the `sphinx_gallery`.  I've built the gallery and can attest that it still builds the images.

**Comment by akaszynski** [comment]
@banesullivan,

I see `_prep_for_close` was added for fixing QtInteractor.  Is there any reason why we can't move it there and not have it within `BasePlotter`?  Seems unnecessary here.

**Comment by akaszynski** [comment]
Also, please note that unit testing is down by 50% on Mac OS.

@banesullivan, please take a look at this.  I'd really like to get tests cleaned up.

**Comment by banesullivan** [comment]
`_prep_for_close` was added for fixing the qt stuff but I think it is needed by the `BasePlotter` to make sure we never try to capture a screenshot after a user has destroyed the GL context. I think I implemented it as a failsafe for all the different behavior when exiting the plotter on different OS

**Comment by banesullivan** [comment]
i.e.I think taking it out might cause `Plotter` to segfault when a user hits the exit button on Windows

**Comment by akaszynski** [comment]
> i.e.I think taking it out might cause `Plotter` to segfault when a user hits the exit button on Windows

We should look into this later, but for the time being I'll leave it in since it's not going to affect our unit testing.

**Comment by banesullivan** [comment]
From the surface, it looks like we are causing builds to fail downstream in [`discretize`](http://discretize.simpeg.xyz/en/master/examples/plot_pyvista_laguna.html#sphx-glr-examples-plot-pyvista-laguna-py) from this PR and the concern I had in https://github.com/pyvista/pyvista/pull/732#discussion_r429588514.

pinging @jcapriot, @akaszynski. I will look into this more tonight to make sure this is the issue and try to patch a fix

See https://travis-ci.org/github/simpeg/discretize/jobs/694897879#L3023

**Comment by akaszynski** [comment]
They'll have to add
```python
# necessary when building the sphinx gallery
pyvista.BUILDING_GALLERY = True
```
Within `conf.py` for documentation building.

**Comment by jcapriot** [comment]
Thanks for the quick response @akaszynski I'll add that in

**Comment by banesullivan** [comment]
A lot of projects are using PyVista with Sphinx gallery... requiring them all to update with that variable isn’t ideal.

I’ll play with this tonight if we can preserve the original behavior

**Comment by akaszynski** [comment]
We can preserve the original behavior with:
```python
BUILDING_GALLERY = 'sphinx' in sys.modules
```

That way whenever sphinx has been imported (which always happens when building galleries), screenshots are always saved.

I'll make the hotfix right away.

**Pull request merged**
