### PR TITLE
Documentation - Use pydata-sphinx-theme

### LINKED ISSUE #1138: Discussion: Change Theme to PyData Sphinx Theme
### Documentation Theme Redesign
Recently, `numpy`, `pandas`, and `jupyterlab` have changed their sphinx themes to use the [The PyData Sphinx Theme](https://pydata-sphinx-theme.readthedocs.io/).  Personally, I really like it.  It's professional, the interface is clean and not busy, and it's immediately clear what's available on the landing page.   [pandas](https://pandas.pydata.org/docs/) has done a great job in particular developing their docs.

I've even implemented a fork of their theme with a different stylesheet for the `pyansys` project:
https://mapdldocs.pyansys.com/

#### Question:
Should we create a branch and demo the docs using the PyData theme?  I'm imagining that the top nav bar would contain 
5 categories:
- Getting Started
- User Guide
- API Reference
- Examples Gallery
- Development/Contributing

This isn't a mandatory change, but I would like to know how the @pyvista/developers and `pyvista` contributors/users feel about a documentation refactor.  Even if we propose redesigned documentation, it would be there for review until the next patch release (or thereafter).

Alternative proposals are welcome as well.

### PR DESCRIPTION
**Pull request by banesullivan**
Resolve #1138 

My first pass... still needs work/cleanup

https://user-images.githubusercontent.com/22067021/115902204-69266f00-a41f-11eb-8971-3f935663bbb2.mov

### CODE REVIEW

**Comment by akaszynski** [comment]
Starting to review/commit.  Thanks for your work @banesullivan, it looks good so far.

**Comment by akaszynski** [comment]
Looking at other doc pages that use the same theme, I feel like we're not bad actually:
https://pandas.pydata.org/docs/
https://numpy.org/doc/stable/

Our docs, especially the examples, look great and the landing page with graphics and badges makes a good first impression.

This won't be perfect anytime soon, but it's good for this release.

@adeak, if you want to take a look I think we're ready if you have time.

**Comment by adeak** [comment]
I keep getting an error while building doctests. Something might be off on my system, but I don't know what. The CI error seems unrelated.

I've started a new venv, installed pyvista, wheel and every `requirements*.txt`, and did
```sh
cd docs
make clean
make doctest; make doctest && make html
```

I consistently get an error in `user-guide/simple.rst` during the doctest step:
```
Document: user-guide/simple
---------------------------
**********************************************************************
File "user-guide/simple.rst", line 293, in python
Failed example:
    plotter = pv.Plotter()    # instantiate the plotter
    plotter.add_mesh(mesh)    # add a mesh to the scene
    cpos = plotter.show()     # show the rendering window
Exception raised:
    Traceback (most recent call last):
      File "/home/adeak/Python-3.8.7/Lib/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest python[0]>", line 2, in <module>
        plotter.add_mesh(mesh)    # add a mesh to the scene
    NameError: name 'mesh' is not defined
**********************************************************************
```
The file wasn't even changed by this PR, only moved, so I don't get why this suddenly breaks for me. But I also can't see what I might be doing wrong. It seems that the name `mesh` doesn't carry over from earlier code blocks.

Any ideas?

**Comment by akaszynski** [comment]
> I keep getting an error while building doctests

Reproduced this error locally and fixed it in https://github.com/pyvista/pyvista/pull/1284/commits/118b8b73b4498fe03961c53832cd24643a7551fd

**Comment by adeak** [comment]
I see, thanks. So perhaps CI didn't fail because it failed _sooner_ with the warnings turned to errors.

**Comment by akaszynski** [comment]
@banesullivan, I'm happy with this.  If you want, take a look at the changes I made, specifically to the main landing page.

**Review by akaszynski — APPROVED** [review]
Approving.  I'd like to merge this tomorrow to get a release out by end of the week.

**Comment by akaszynski** [comment]
Final doc revision includes a bunch of interactive examples.  I think interactive docs are a great way of demoing pyvista with zero install.  Though we're placing code on the main page, we're also placing browser enabled examples and most developers/researchers/coders want to know what they're getting into in the first few seconds of visiting a page.  This is why `tqdm`'s page is so effective with their GIF.  Show the user immediately what it takes to be up and running.

Not to be outdone by @banesullivan's fancy movies:

https://user-images.githubusercontent.com/11981631/116497789-6683a980-a865-11eb-8389-58fa539d68f0.mp4

**Comment by banesullivan** [comment]
I love the way this is looking! Especially with the examples on the home page - it lets folks know what PyVista can do right away

As for the issue about Ads (discussed on Slack), go ahead and remove them and I will follow up with another PR to better place/debate them so we can keep the🍺 / ☕ funds coming in 😉

**Comment by larsoner** [comment]
Just a drive-by comment since you mentioned ads, I remembered that pydata-sphinx-theme itself has ads presumably because it's on RTD:

https://pydata-sphinx-theme.readthedocs.io/en/latest/

They end up in the left column and seem mostly unobtrusive to me

Screenshot from 2021-04-29 11-11-12

(Also +1 for moving to pydata-sphinx-theme, it's great and well supported!)

**Comment by banesullivan** [comment]
The ads become quite annoying in a mobile/small browser view:
Screen Shot 2021-04-29 at 10 38 03 AM

I will try to update them to be n the right sidebar instead of the left to avoid this issue where the add is the first thing you see at the top of every page

**Comment by adeak** [comment]
Sorry, I won't be able to take a closer look until tomorrow. I've poked it a bit already and nothing stood out to me, and of course the interactive front page is amazing! Feel free to go ahead with this.

**Comment by adeak** [comment]
One thought just to put out there: the project landing page is now 19 MB due to the embedded data. `user-guide/index.html` is 23 MB.

I don't know if we can do anything to help users with expensive metered network connections. I suspect not, because the interactive content is not like images which can be _not_ downloaded from the server using common browser settings. Perhaps it would be possible to run some JS that fetches the data from the server, but I suspect disabling JS is not a typical user option for limiting bandwidth.

**Comment by adeak** [comment]
I've finally looked through the new page. I love it! :) Thank you @banesullivan and @akaszynski.

I have two more questions regarding the front page:
  1. As noted in https://github.com/pyvista/pyvista/issues/1123 and https://github.com/pyvista/pyvista/issues/1277, the mybinder examples are outdated and non-interactive right now. Do we still keep the link?
  2. The "translating" docs refers to Read The Docs, which I was surprised to learn that [it exists](https://pyvista-doc.readthedocs.io/en/latest/). What's the relationship between docs.pyvista.org and readthedocs? Is the English version a mirror? Will it be kept up-to-date? I haven't found readthedocs links in duckduckgo but we should be careful not to get users on the wrong page.

**Comment by akaszynski** [comment]
> One thought just to put out there: after this PR the project landing page will be 19 MB due to the embedded data. `user-guide/index.html` 23 MB.

It's a reasonable point, and one reason why I had recently trimmed down the gigantic `pyvista_banner.png` --> `pyvista_banner_small.png`.  I don't think there's anything that can be done about this, and I've run into issues with metered connections before.  On the plus side, the page will load over a slow connection with the three.js content loading more slowly afterwards, so at least over slow connections this works.

> As noted in #1123 and #1277, the mybinder examples are outdated and non-interactive right now. Do we still keep the link?

I need to look into this and we should open up a new issue for this.

> The "translating" docs refers to Read The Docs, which I was surprised to learn that it exists. What's the relationship between docs.pyvista.org and readthedocs? Is the English version a mirror? Will it be kept up-to-date? I haven't found readthedocs links in duckduckgo but we should be careful not to get users on the wrong page.

I didn't even realize we had a rtd page.  It's not linked by anything or even picked up by google, but even if it was, it seems to match our existing dev.pyvista.com page, so I don't think it's an issue.  I don't see any issue with doc duplication since it appears to be genuinely duplicated relative to master.  There might be some confusion as to why there isn't english pyvista on rtd as that's the most popular language for pyvista at the moment, so I'm fine with leaving it there.

**Comment by akaszynski** [comment]
> As noted in #1123 and #1277, the mybinder examples are outdated and non-interactive right now. Do we still keep the link?

Actually, @banesullivan, when you get a chance, can we take a look at this?  We might need to verify that all of this works with `ipyvtklink`.

**Comment by banesullivan** [comment]
I'll try to jump on this

**Pull request merged**
