### PR TITLE
Document `ImageData` inherited members `dimensions` and `dimensionality`

### PR DESCRIPTION
**Pull request by user27182**
### Overview

`ImageData.dimensions` and `ImageData.dimensionality` is not documented. This is because it inherits this from `Grid`, but `Grid` is not documented either. This PR fixes this by showing all inherited members for `ImageData`.

### CODE REVIEW

**Comment by user27182** [comment]
This PR should also fix this broken link in the notes of `points_to_cells` and `cells_to_points`
image

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Comment by user27182** [comment]
The new docs are showing but the ref to "dimensions" in points_to_cells is still broken, will fix as part of #6895

**Comment by user27182** [comment]
Not sure why it keeps disabling the auto- merge, I wasn't clicking it 🤔

**Pull request merged**
