### PR TITLE
Add loading NRRD image files

### PR DESCRIPTION
**Pull request by ralovich**
### Overview

Adds loading NRRD image files.

### CODE REVIEW

**Comment by banesullivan** [comment]
Do you know of any openly accessible example files of this format available online for us to test this?

**Comment by ralovich** [comment]
> Do you know of any openly accessible example files of this format available online for us to test this?

Yes, please see e.g. https://github.com/pyvista/vtk-data/blob/master/Data/beach.nrrd

**Comment by banesullivan** [comment]
Ah perfect! Could you please also add the following method to `pyvista/examples/downloads.py`:

```py
def download_beach():
    """Download the beach NRRD image."""
    return _download_and_read("beach.nrrd")
```

That way we can use that data as an example if needed down the road.

**Comment by ralovich** [comment]
> Ah perfect! Could you please also add the following method to `pyvista/examples/downloads.py`:
> 
> ```python
> def download_beach():
>     """Download the beach NRRD image."""
>     return _download_and_read("beach.nrrd")
> ```
> 
> That way we can use that data as an example if needed down the road.

Sure, see https://github.com/pyvista/pyvista/pull/679/commits/7cd513c501b392a258401e1b19db3b74e4d2ef03 .

**Comment by akaszynski** [comment]
@banesullivan, do we want to add a test for this?  I'm thinking we could make a separate tests for example files so I can use the cache.

**Comment by banesullivan** [comment]
@akaszynski, in this PR, no. There are already a number of tests for all the download methods which should be turned off on the CI because we had download issues at one point.

We could set that up in another PR with caching. In the meantime, I think this PR is good to go

**Comment by akaszynski** [comment]
@banesullivan, agreed.  That will be an issue for another PR.

**Pull request merged**
