### PR TITLE
Add codespell autocheck

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR follows this https://github.com/pyvista/pyvista/pull/458#issuecomment-555994068 and adds a `codespell` call in Travis configuration.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Better results are expected after https://github.com/pyvista/pyvista/pull/458 is merged.

**Comment by GuillaumeFavelier** [comment]
Also locally I couldn't manage to make `codespell` ignore the word `LOD` even if it's whitelisted. We'll see how it goes.

**Comment by GuillaumeFavelier** [comment]
As expected, Travis reproduces the behaviour I encountered locally:
https://travis-ci.org/pyvista/pyvista/jobs/615131972#L735

**Comment by GuillaumeFavelier** [comment]
Same result by using `-I ignore_words.txt`: https://travis-ci.org/pyvista/pyvista/jobs/615182013#L812

I honestly don't understand what's happening with `LOD` but worst case scenario, we can still mitigate this by rephrasing.

**Comment by GuillaumeFavelier** [comment]
Using lower case solved it!

https://travis-ci.org/pyvista/pyvista/jobs/615188964#L808-L809

**Comment by GuillaumeFavelier** [comment]
I expect the CIs to come back green.

What do you think @banesullivan, @akaszynski ?

I tried to keep the diff as short as possible so all the configuration is in `.travis` itself but there are many ways to change that. I checked and using `ignore_words.txt` gives the same result. It's a flexible way to ignore words too, it could be useful for future contributions. It's also possible to put the whole command in a `Makefile` as well.

**Comment by GuillaumeFavelier** [comment]
Let's go for `Makefile` with `ignore_words.txt` then.

**Comment by GuillaumeFavelier** [comment]
This should be it for now. Let me know if you want me to modify anything.

**Comment by banesullivan** [comment]
Thanks, @GuillaumeFavelier!

**Pull request merged**
