### PR TITLE
Use new cross-platform Action to setup headless display

### PR DESCRIPTION
**Pull request by banesullivan**
Uses https://github.com/pyvista/setup-headless-display-action

Cross-platform, so can be safely used on Windows, Mac, and Linux runners

### CODE REVIEW

**Comment by akaszynski** [comment]
This is a great idea!

**Comment by banesullivan** [comment]
After this, I may do some work to have a single job matrix for running the core tests on Windows/Linux (but still handle mac separately because of limited runners)

**Comment by banesullivan** [comment]
Before merging, @akaszynski, why is `xvfb-run` used in the `Linux` job in `.github/workflows/testing-and-deployment.yml`?

Should we remove that? Or should we have a second action to have a `with:` option to do call `xvb-run`?

**Comment by akaszynski** [comment]
> Or should we have a second action to have a with: option to do call xvb-run?

I'd prefer `with`. The nice thing about `xvfb-run` is it's completely isolated per run.

**Comment by banesullivan** [comment]
Perhaps we use https://github.com/marketplace/actions/gabrielbb-xvfb-action for this?

**Comment by banesullivan** [comment]
I may adopt what they did in that action to the one I created so we have a way of seamlessly handle virtual displays on windows as well

**Comment by akaszynski** [comment]
> Perhaps we use https://github.com/marketplace/actions/gabrielbb-xvfb-action for this?

Yes.

Don't feel bad. I have an entire 1000 line code project that hasn't seen the light of day that I spent a week on because I failed to do my research first.

**Review by tkoyama010 — APPROVED** [review]
LGTM. I am happy that we can remove `.ci/setup_headless_display.sh` .

**Pull request merged**
