### PR TITLE
A thank you to @user27182

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

Thank you for all of your contributions to PyVista, @user27182!!

Thank you for contributing to PyVista!! We are so grateful for contributors like you! Your efforts, like all of those who participate in the PyVista community, go a long way in making PyVista what it is. To show our appreciation, we want to put your names on the collective work, adding you to The PyVista Developers list.

When we asked you before, you said you only wanted your username to be displayed (https://github.com/pyvista/pyvista/pull/5029/files#r1350008431). You can select add you name or not - please let us know if you want to use your name (either in a comment here or DM). We just to short-circuit any potential implicit assumptions: please don't feel pressured in any way to use a real name in this document like @adeak said above thread.

@pyvista/developers, if there is anyone else you feel we should add, please let us know.

### Details

- Follow-up of https://github.com/pyvista/pyvista/pull/5029/files#r1350008431 .

### CODE REVIEW

**Comment by akaszynski** [comment]
Thanks @user27182!

**Comment by MatthewFlamm** [comment]
Great work! +100

**Review by user27182 — APPROVED** [review]
LGTM, thank you

**Review by adeak — APPROVED** [review]

**Review by banesullivan — APPROVED** [review]
@user27182, thank you for all of your fantastic contributions to PyVista!! We greatly appreciate your hard work and I look forward to continue seeing you foster so much growth in the community

**Pull request merged**
