### PR TITLE
Fix block splitter syntax to `# %%` in `sphinx-gallery`

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

This change was made because I noticed a difference between PyVista and Matplotlib script file when making the #6375 change.  

The following statement from the `sphinx-gallery` documentation is a good reason for making this change.

https://matplotlib.org/stable/gallery/

> The #%% and # %% syntax is consistent with the ‘code block’ (or ‘code cell’) separator syntax in [Visual Studio Code Python extension](https://code.visualstudio.com/docs/python/jupyter-support-py#_jupyter-code-cells), [Visual Studio Python Tools](https://learn.microsoft.com/en-us/visualstudio/python/python-interactive-repl-in-visual-studio?view=vs-2019#work-with-code-cells), [Jupytext](https://jupytext.readthedocs.io/en/latest/formats.html#the-percent-format), [Pycharm Professional](https://www.jetbrains.com/help/pycharm/running-jupyter-notebook-cells.html), [Hydrogen plugin (for Atom)](https://nteract.gitbooks.io/hydrogen/content/docs/Usage/Cells.html#example-definitions) and [Spyder](https://docs.spyder-ide.org/current/panes/editor.html#defining-code-cells).

### Details

- https://sphinx-gallery.github.io/stable/syntax.html#embed-rest-in-your-example-python-files

### CODE REVIEW

**Comment by tkoyama010** [comment]
@pyvista-bot LGTM

**Comment by adeak** [comment]
Late to the party, but good catch, thanks @tkoyama010!

**Comment by MatthewFlamm** [comment]
Not that this PR missed something, but I noticed that https://docs.pyvista.org/version/stable/examples/99-advanced/add-example is missing what this block does.  Should it be added there?

**Comment by adeak** [comment]
Sounds good to me @MatthewFlamm. I didn't even know we had such a page, very nice.

It also looks like the last section has broken syntax, making the last section a code block (probably a missing empty line?):
image

Would be nice to fix that in the same go.

**Pull request merged**
