### PR TITLE
[Hotfix] Remove codecov from requirements

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

codecov has deprecated pypi and requires an intention to GitHubActions. We will work on the migration to GitHubActions in the future, but first please merge this PR to fix the CI error.

Relevant Migration Article: https://docs.codecov.com/docs/deprecated-uploader-migration-guide#python-uploader
With example repo https://github.com/codecov/example-python/

### Details

- None

### CODE REVIEW

**Comment by akaszynski** [comment]
I think if we can fix this today, we should fix this now before we forget about codecov.

I'm fairly certain that it's as easy as using:

https://github.com/codecov/codecov-action

**Comment by tkoyama010** [comment]
It seems that we already set GitHubActions. Maybe all we have to do is remove the package (I will investigate this in more detail later.).
https://github.com/pyvista/pyvista/blob/f765afcdb0de88bcc09cb722496a18384ad9c8d2/.github/workflows/testing-and-deployment.yml#L207-L208

**Review by MatthewFlamm — APPROVED** [review]
This looks needed for our CI to work again.

**Comment by tkoyama010** [comment]
@MatthewFlamm Thanks. We also need to merge https://github.com/pyvista/pyvistaqt/pull/360 . Please approve it too if it is OK.

**Comment by akaszynski** [comment]
> I think if we can fix this today, we should fix this now before we forget about codecov.
> 
> I'm fairly certain that it's as easy as using:
> 
> https://github.com/codecov/codecov-action

Looks like we already have this implemented in 
https://github.com/pyvista/pyvista/blob/75961b6aae65dfe6d4e358a9f6b883e2d4cf0e98/.github/workflows/testing-and-deployment.yml#L207-L208

In this PR we've removed `codecov` from our requirements and it still works. See:
https://app.codecov.io/gh/pyvista/pyvista/pull/4269/commits

**Comment by akaszynski** [comment]
> @MatthewFlamm Thanks. We also need to merge [pyvista/pyvistaqt#360](https://github.com/pyvista/pyvistaqt/pull/360) . Please approve it too if it is OK.

Done. Integration tests all passing here. Thanks for everyone's work resolving this and sorry to be slow on the uptake. It's been a long week.

**Pull request merged**
