### PR TITLE
Fix internal links to core typing

### PR DESCRIPTION
**Pull request by user27182**
### Overview

The internal core typing links are currently broken. (See the build errors generated when setting `nitpicky=True` in #6203 for a full list of broken links).

The issue seems to stem from aliases not being documented as `py:class:` (aliases are `py:data:`). See https://github.com/sphinx-doc/sphinx/issues/10974#issuecomment-1315385037

The `pyvista.ColorLike` aliases work, however.  And @dcbr pointed out in https://github.com/pyvista/pyvista/pull/5621#discussion_r1532044361 that this could be because `ColorLike` uses `.. autosummary::`.

It would be preferable not to use autosummary, however, because it creates a separate entry (link and page) for the class. But for aliases I think it would be better if they were all shown in a single flat level, glossary-style.

I found this rst stub generated locally in the pyvista repo:
``` rst
pyvista.ColorLike
=================

.. currentmodule:: pyvista

.. autodata:: ColorLike
```

So, it seems like this is what `autosummary` generates.  This formatting was copied and applied to `typing.rst`. Let's see if it works.

### CODE REVIEW

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
It worked! E.g. see https://665fa649d4c47e72ddbd754d--meek-duckanoo-d2f5ec.netlify.app/api/core/_autosummary/pyvista.datasetattributes.set_array#pyvista.DataSetAttributes.set_array

**Review by tkoyama010 — APPROVED** [review]
Nice!

**Comment by dcbr** [comment]
Great, glad to see it finally work! Crazy how such subtleties can cause things to break or work.

**Comment by user27182** [comment]
> Crazy how such subtleties can cause things to break or work.

Yes definitely not an intuitive feature to implement! 

Unfortunately even this fix is only a partial fix. The aliases in the docstrings are linked, but not in the function signatures, e.g. see the `ArrayLike` alias used for `data`:
image.

Also, after this PR was merged, the number of broken links did not get reduced in https://github.com/pyvista/pyvista/pull/6203, so, this did not fix the broken links in that sense.

This seems to be a known bug, and may not be fixed any time soon. See https://github.com/sphinx-doc/sphinx/issues/10455#issuecomment-1872516960

There are apparently some hacky workarounds involving html mods, redefinitions, or custom extensions. But this doesn't seem worth the effort. For the `nitpicky` option in #6203, I think any missing ref warnings for type aliases will just need to be explicitly ignored.

**Pull request merged**
