### PR TITLE
Set number of labels to release as minimum

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

More than two labels are also possible for pull requests with multiple contents.

 

### Details

- None

### CODE REVIEW

**Review by akaszynski — APPROVED** [review]
LGTM. Thanks for fixing this.

**Comment by akaszynski** [comment]
I'd like to point out that it's a little annoying to see the red check on each and every commit, despite the fact that some of the commits might actually be valid. It makes walking back through looking for valid commits a bit more tedious. Since I like the approach of waiting, is there a way we could still include the labeler workflow but not have this behavior?

**Comment by tkoyama010** [comment]
I agree. I'm happy with the functionality but need a better way to display it than blocking the merge.

**Comment by akaszynski** [comment]
Abandoning. See #2860

**Pull request closed without merging**
