### PR TITLE
Specify optional parameters in mapper.py and plotting.py

### PR DESCRIPTION
**Pull request by puripant**
### Overview

Optional parameters in `mapper.py` and `plotting.py` as listed in #3347 are specified in docstring.

### Details

- "nan_color" in `set_scalars()` in `mapper.py`
- "bounds" in `add_cursor()` in `plotting.py`
- "return_img" in `show()` in `plotting.py`
- "cpos" in `show()` in `plotting.py`

### CODE REVIEW

**Comment by puripant** [comment]
I am not sure how this build error happens. I barely changed anything and all changes were in the comments :/

**Comment by akaszynski** [comment]
> I am not sure how this build error happens. I barely changed anything and all changes were in the comments :/

Looks like a simple build failure; these things happen from time to time. I've restarted it.

**Comment by MatthewFlamm** [comment]
This PR mixes use of `optional` and `default`.  See #3347 for discussion on this.  If we want to merge this quickly without too much discussion, I'd suggest using only `optional` here since it is the most prevalent in the code today.

**Comment by MatthewFlamm** [comment]
Looking a little closer, it looks like you've chosen to use `optional` when the default value is `None` and `default` when there is a specific value that is a default.  I actually like this approach.  So disregard my previous comment and we can await further comments on this.

**Comment by puripant** [comment]
> Looking a little closer, it looks like you've chosen to use `optional` when the default value is `None` and `default` when there is a specific value that is a default. I actually like this approach. So disregard my previous comment and we can await further comments on this.

Yes, that's my intention. Glad you like it. Let's see if other people agree on this.

**Comment by akaszynski** [comment]
> Looking a little closer, it looks like you've chosen to use optional when the default value is None and default when there is a specific value that is a default.

I prefer this as well. This needs to be implemented everywhere.

**Comment by akaszynski** [comment]
Doc failures are weird. Rerunning... I'm not seeing this happen anywhere else.

**Review by MatthewFlamm — APPROVED** [review]
With some concurrence on the style here, LGTM

**Comment by akaszynski** [comment]
Merging this soon regardless of the doc failure. I'll open a follow-up PR fixing this.

**Pull request merged**
