### PR TITLE
Fix typos and grammar in example gallery

### LINKED ISSUE #353: Polydata clean filter will merge points regardless of point_merging
The clean method for polydata objects seems to merge points regardless of the setting.

### PR DESCRIPTION
**Pull request by JasonTLin**
Relevant to #336

This PR is meant to fix the typos, grammatical errors and confusing sentences in the documentation and examples. Additionally, capitalization of words such as PyVista and NumPy were changed to be consistent.

This PR also resolves #353

### CODE REVIEW

**Comment by banesullivan** [comment]
Thanks do much for doing this @JasonTLin!! Fixing typos and grammar across the examples is a huge help!

Also thanks for catching #353!

**Comment by banesullivan** [comment]
I can merge this whenever you're ready

**Comment by JasonTLin** [comment]
Yeah do so anytime, sorry for all the redundant commits as this was my first pull request.

**Comment by akaszynski** [comment]
No worries, we can just squash and merge this so that it only shows up as one commit.  Thanks for your contribution!

**Pull request merged**
