### PR TITLE
Use numpy nightly wheel for 2.0 testing

### PR DESCRIPTION
**Pull request by MatthewFlamm**
### Overview

I did a quick test of a few functions and I did not get gc teardown errors with the new fixes.

See discussion in https://github.com/pyvista/pyvista/issues/5533#issuecomment-2136069025.  This change actually tests against numpy 2.1.0dev but we need it to test the fixes from https://github.com/numpy/numpy/issues/26545.  numpy is planning to release 2.0 in about 2 weeks, so we should try to iron out all the problems by then and this PR enables us to get to get it into our CI.

## Details

Once numpy 2.0 is released, we will need to rework the CI once again.

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
cc @adeak

**Comment by MatthewFlamm** [comment]
The plotting tests here had this result:

```
= 14 failed, 1654 passed, 5 skipped, 2 xfailed, 11 warnings, 19 errors in 1046.10s (0:17:26) =
```

compared to a recent PR which had this result for the plotting tests:
```
= 14 failed, 1654 passed, 5 skipped, 2 xfailed, 11 warnings, 181 errors in 1180.67s (0:19:40) =
```

Note the difference in 19 errors vs. 181 errors, which is indicative of the gc fixes from the numpy bug fix.  I suspect a large majority of the others have crept in due to regressions in PyVista because we do not have this in the regular CI.

**Comment by adeak** [comment]
Thanks for the ping. I'm close to opening a PR which locally has
```
= 2 failed, 7113 passed, 192 skipped, 5 xfailed, 18 warnings in 229.15s (0:03:49) =
```

I also switched to the nightly build on my local branch, but I can just remove that if we have this PR.

There are the two still failing tests and a few suspicious details I want to look into before opening a PR, at least to open a WIP where I can pin-point the things I still need to do. Not much is needed but I have very little bandwidth unfortunately.

**Review by adeak — APPROVED** [review]

**Review by tkoyama010 — APPROVED** [review]

**Comment by adeak** [comment]
@banesullivan if I understand github's slightly confusing UI correctly, this is partly waiting for your approval.

@tkoyama010 I can also see you disabled auto-merge; is this PR waiting on something else perhaps? Or is this good to go if approved?

**Comment by tkoyama010** [comment]
> @tkoyama010 I can also see you disabled auto-merge; is this PR waiting on something else perhaps? Or is this good to go if approved?

@adeak I disable auto-merge because @pyvista-bot auto merge branch main action is noisy. I am ready to go this if it is approved.

**Review by banesullivan — APPROVED** [review]

**Pull request merged**
