### PR TITLE
Add support for glTF

### LINKED ISSUE #1469: Expanded glTF support
As part of my usage of pyvista, I found the need to use 3D models in glTF format (see https://www.khronos.org/gltf/).
The glTF format has better support for physically-based rendering (PBR) materials than other model formats, and is useful for web display. It is the format expected by [three.js](https://threejs.org/) and [model-viewer](https://modelviewer.dev/), amongst others.

So far, I have two particular use cases:
- Exporting a plot as glTF. Currently the only supported formats are OBJ (which doesn't support materials well), and VTKJS, which I haven't experimented with, but cannot be integrated with other formats/models as far as I can tell. glTF export could be useful to get models into other 3D applications as well (such as Blender).
- Import and display of glTF models. Again, mostly for the PBR materials over other formats.

VTK already includes glTF support, so for file IO, it is mostly a matter of adding the existing implementation.
As far as I can tell, `vtkGLTFReader` can be added to the list of READERS at the top of `pyvista.utilities.fileio`, and everything will just work.
Similarly, I copied `export_obj` in `BasePlotter` and replaced `vtkOBJExporter` with `vtkGLTFExporter`, and everything worked.
Most of what else needs to happen is testing.

I have a few remaining issues/thoughts:
- Coordinate frames on export. glTF uses a different coordinate frame to pyvista/VTK with Y up and Z forward (see [here](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#coordinate-system-and-units)). The VTK exporter does not handle this, so exported models wind up on their side. I think it would be more intuitive if the export could handle this, but I couldn't find a way to apply a general transformation to an entire plot.
- Support for more export formats. While it would be straightforward to create an `export_gltf` alongside `export_obj`, it might be cleaner to support a single generic export function, and allow the format to be specified from either the file name or an override, similar to the `read` API in `fileio`.
- Display of models with embedded PBR materials is an issue. While the geometry imports easily, `plotter.add_mesh` does not seem designed to read detailed colour information from the mesh.  From some experimentation, material properties from the file are stored in named arrays on the `PolyData` object, which must be read into the correct values. A model may contain multiple materials with different properties, which are expressed as multiple `PolyData` objects inside a `MultiData` object. I've managed to get a glTF model with PBR materials to correctly display, but it required copying a significant chunk of `BasePlotter.add_mesh` to unpack the `MultiData` object and read the relevant properties for each `PolyData`. I'm also concerned that the particular named arrays that material properties are stored in depend on the model format the data was imported from, so there might not be a generic way to handle reading material data without some custom fiddling during import. This might be big enough to become a separate issue in the future.

### PR DESCRIPTION
**Pull request by akaszynski**
Resolve #1469 by adding support for gltf along with:
- Examples
- Export
- Import
- Documentation

### CODE REVIEW

**Comment by jskinn** [comment]
Thanks, this neatly solves the problem, and adds support. Two minor thoughts:
- '.glb' files should probably also be included in the READERS list in `fileio.py`. I'm not sure that some of these examples will actually work without it, all the example files are '.glb'.
- As a pedantic point, the axis conventions and need for rotation are not just a threejs thing, it's part of the glTF spec, so everything importing/exporting glTF files tends to expect those conventions. I'm glad addressing it was a simple solution.

**Comment by akaszynski** [comment]
> '.glb' files should probably also be included in the READERS list in fileio.py. I'm not sure that some of these examples will actually work without it, all the example files are '.glb'.

Added.

> As a pedantic point, the axis conventions and need for rotation are not just a threejs thing, it's part of the glTF spec, so everything importing/exporting glTF files tends to expect those conventions. I'm glad addressing it was a simple solution.

I'll add a note regarding that it's the glTF specification and not three.js

BTW, this is a ton of fun.  Even learned that VTK supports HDR textures, so I've been able to improve our example a bit:
tmp

**Comment by adeak** [comment]
Now the only question is how to recreate that scene from scratch in VTK :laughing:

**Comment by akaszynski** [comment]
Ran into some testing stability with docstring testing.  I've isolated the test into its own azure job so we can restart it at will.  Figure docstring testing can be confined to one version of Python since our unit testing already tests all four and that's where we actually need to test for coverage/validity.

**Comment by akaszynski** [comment]
Merging as I'd like to get support for this out in the next release in a week or two.

**Comment by xtassin** [comment]
Hi,

As far as I could see, texture coordinates are not exported to GLTF as a mesh primitive attribute (just like NORMAL and POSITION) but always as PBR material property even though PBR is not enabled.

If the plotter PBR argument is not set to true, one would expect the opposite behavior.

**Pull request merged**
