### PR TITLE
Improve docstrings and examples for `Property` class attributes

### PR DESCRIPTION
**Pull request by user27182**
### Overview

Follow up from #5029.

- Make the docstring examples more consistent: First show the default value of a property and visualize it, then show setting different values
- Update the docstrings to add ranges for some attributes

### CODE REVIEW

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Pull request merged**
