### PR TITLE
Add offscreen support in BackgroundPlotter

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR adds basic support for offscreen rendering in the `BackgroundPlotter` class.

The following is an example of what's possible now:
```py
import pyvista as pv

pv.OFF_SCREEN = True

p = pv.BackgroundPlotter(size=(500, 500))
p.add_mesh(pv.Cone())
p.screenshot('shot1.png')

p.camera_position = [(5, 2, 2), (0, 0, 0), (0, 1, 0)]
p.background_color = (0.0, 0.0, 0.0)
p.screenshot('shot2.png')

p.close()
```

**shot1.png** | **shot2.png**
-----------------|------------------
shot1 | shot2

**Known issues**:
* The axes are disabled by default when rendered offscreen.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Does it work for you too, what do you think @akaszynski, @banesullivan  ?

**Comment by akaszynski** [comment]
Any idea why ipy_tools is failing on appveyor for 3.7?

**Comment by GuillaumeFavelier** [comment]
I'm not sure. I modified the signature of `BackgroundPlotter.__init__()` could it be related?

**Comment by akaszynski** [comment]
Possibly.  It might also be related to not creating ``iren`` when off screen plotting is enabled as it is when testing.  Normally, I'd be fine with it, but it failed twice doesn't seem intermittent.  I'd try to see if it's ``iren`` causing the issue on Windows.

**Comment by GuillaumeFavelier** [comment]
Not sure but it could be somehow related to #310 too

**Comment by banesullivan** [comment]
This is failing the master branch on AppVeyor after merging - it seems like the Background plotter isn't closing properly. The tests finish and then its just hung and eventually times out

**Comment by banesullivan** [comment]
Notably only failing for Python 3.5 and 3.6 - 3.7 is all good.

**Comment by GuillaumeFavelier** [comment]
Could you point me to the failing test?

I created a Windows environment with Python 3.5.6 where I force `NO_PLOTTING=False` and I can't reproduce those issues when I use `pytest -vv tests/test_qt_plotting.py tests/test_ipy_tools.py`

**Comment by banesullivan** [comment]
Could you try checking out the `master` branch? All Appveyor branches built off `master` are failing right now: https://ci.appveyor.com/project/banesullivan/pyvista/history

Specifically, this one seems to be where it all started https://ci.appveyor.com/project/banesullivan/pyvista/builds/26087669/job/w1pmd7togvp5wqxe

Looks to me like the tests complete then successfully then get hung and the build times out.

Screen Shot 2019-07-19 at 9 12 37 AM

If appveyor would let me, I'd give you acess to retrigger builds but I don't think appveyor allows that. Let me know if you want to watch one, and I can retrigger one

**Comment by banesullivan** [comment]
After looking at some other builds, it seems a bit inconsistent... I'm wondering if this might be an AppVeyor issue....

Frankly I have a strong dislike for AppVeyor so maybe it would make sense to set up windows testing on Azure? I have an org account on Azure but haven't been able to figure out how to use because their UI isn't very obvious to me: https://dev.azure.com/pyvista/

If you know how, @GuillaumeFavelier, I'd be happy to add you to the org account on azure

**Pull request merged**
