### PR TITLE
🐛 Fix unremovable interactive scalar bar

### LINKED ISSUE #1055: unremoveable interactive scalar_bar
**Describe the bug, what's wrong, and what you expect:**

Interactive scalar_bar is not reacting to remove_scalar_bar() method.

scalar_bar should be removable even if **interavtive=True** is set.

-----

**To Reproduce**
```py
import sys

from PyQt5 import Qt
import numpy as np

import pyvista as pv
from pyvistaqt import QtInteractor
from vtkmodules.vtkFiltersSources import vtkConeSource


class MainWindow(Qt.QMainWindow):

    def __init__(self, parent=None, show=True):
        Qt.QMainWindow.__init__(self, parent)

        # create the frame
        self.frame = Qt.QFrame()
        vlayout = Qt.QVBoxLayout()

        # add the pyvista interactor object
        self.plotter = QtInteractor(self.frame)
        vlayout.addWidget(self.plotter.interactor)

        self.frame.setLayout(vlayout)
        self.setCentralWidget(self.frame)

        self.scatter_cones()
        self.plotter.add_scalar_bar(interactive=True)
        # self.plotter.remove_actor("temp")
        self.plotter.remove_scalar_bar()
        # self.plotter.enable_parallel_projection()
        self.plotter.add_axes(interactive=True, color=[0, 0, 0])
        self.show()

    def scatter_cones(self):
        centers = np.random.randint(20, 90, (20, 3))
        points = pv.PolyData(centers)
        directions = np.full((len(centers), 3), np.array([0, 1, 0]))
        points['vectors'] = directions
        glyphs = points.glyph(geom=pv.Cone(resolution=10), orient='vectors')
        self.plotter.add_mesh(glyphs, color="#0000ff", name="temp")


if __name__ == '__main__':
    app = Qt.QApplication(sys.argv)
    window = MainWindow()
    sys.exit(app.exec_())

```

-----

**System Information:**

```txt
--------------------------------------------------------------------------------
  Date: Sat Dec 12 11:51:24 2020 Mitteleuropäische Zeit
                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
             Intel : GPU Vendor
Intel(R) UHD Graphics : GPU Renderer
4.5.0 - Build 27.20.100.8729 : GPU Version
  Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
           pyvista : 0.25.3
               vtk : 9.0.1
             numpy : 1.19.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.0.16
        matplotlib : 3.2.2
         pyvistaqt : 0.1.1
             PyQt5 : 5.15.1
             scipy : 1.5.2
--------------------------------------------------------------------------------

```

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview
Resolve #1055

 

### Details
```python
import pyvista
pyvista.set_plot_theme("document")

plotter = pyvista.Plotter()
sphere = pyvista.Sphere()
plotter.add_mesh(sphere)
plotter.add_scalar_bar(interactive=True)
# scalar bar should also removed when interactive is True.
plotter.remove_scalar_bar()
plotter.show(screenshot="test.png")
```
|  master | PR |
|--------|--------|
|before|after|

### CODE REVIEW

**Review by tkoyama010 — COMMENTED** [review]
WFM

**Comment by akaszynski** [comment]
Added image verification.  This way, we can verify if the scalar bar is actually "visually" removed in the plotter.

#### Verification image:
plot_remove_scalar_bar

**Comment by tkoyama010** [comment]
Thanks @akaszynski  I understood image verification. It is useful. And I am thinkng why we get diffrent image with script.

**Comment by tkoyama010** [comment]
I updated the test.

**Verification image:**
remove_scalar_bar

**Comment by akaszynski** [comment]
I don't think this fixes this.  When we create `sphere = pyvista.Sphere()`, it's created without scalars.  We should use `sphere` fixture and test the addition and removal of the scalar bar.

**Comment by tkoyama010** [comment]
OK. I will continue to fix this.

**Comment by tkoyama010** [comment]
Now it is working.
plot_remove_scalar_bar

**Review by tkoyama010 — COMMENTED** [review]
WFM

**Comment by akaszynski** [comment]
Ended up just refactoring scalar bars.  Reasoning:
- `plotting` module is huge and getting bigger with every release.  I had a tough time determining the side-effects for removing scalar bars, including discovering a bonus `_remove_mapper_from_plotter` method in `Renderer`.  It's nowhere clean or maintainable at this point and this moves it in the right direction.
- This PR originally proposed adding an additional `scalar_bar` attribute.  I think this moves us in the right direction, but we really need a new class to track the additional scalar bar attributes that we maintain, clear, add, etc.
- Removing a scalar bar is easy when there's only one, but with multiple bars we have to start tracking which one we're moving and move the next one up in the queue.  Rather, we can just force the user to input the `title` of the scalar bar they wish to remove if there is more than one.
- In doing all this, I discovered a bunch of missing coverage, and when fixing it, discovered that we weren't handling certain cases well (e.g. interactive horizontal scalar bars).  This PR fixes it and adds additional testing specific to the scalar bar class.
- As always, we need to add examples to any new methods.  There's quite a few of those that are missing, and when doing test driven development, we can just copy over the tests as examples and kill two or three birds with one ~stone~ test.

**Comment by akaszynski** [comment]
@tkoyama010, please take a look at the changes.  @adeak, if you'd like, feel free take a look.

**Review by tkoyama010 — COMMENTED** [review]
@akaszynski Thanks for changes I'm a fan to split the scalar bar class.

**Review by akaszynski — APPROVED** [review]
image

This is sorta a self approval...

**Comment by adeak** [comment]
"My job here is done"

**Pull request merged**
