### PR TITLE
Refactor axes widget to be on any renderer

### PR DESCRIPTION
**Pull request by banesullivan**
Previously, the axes widget could only be added to a single renderer in any given Plotter. Now we can have axes widgets in any renderer!

Screen Shot 2020-01-14 at 11 10 28 PM

### CODE REVIEW

**Comment by banesullivan** [comment]
Yeah, I still need to update the docs for this - I was being lazy last night.

on this note... we should really try to figure out #470 so that we don't have to have docs for `Renderer` methods both on the `Renderer` and the `Plotter`

**Comment by akaszynski** [comment]
Have we considered using `functools.wraps`?  The docstring is copied as well, and you could even just use `*args, **kwargs` instead of duplicating the function signature.

**Comment by banesullivan** [comment]
Woah, awesome! decorating the `Plotter` methods like the following works perfectly! We could refactor all of those methods that wrap calls to the Renderer like:

```py
from functools import wraps

class Plotter:
...
    @wraps(Renderer.show_bounds)
    def show_bounds(self, *args, **kwargs):
        loc = kwargs.pop('loc', None)
        self._active_renderer_index = self.loc_to_index(loc)
        renderer = self.renderers[self._active_renderer_index]
        return renderer.show_bounds(*args, **kwargs)
```

Then in Jupyter/IPython, all of the args/kwargs are listed in the docstring/help:

**Comment by banesullivan** [comment]
Also, we may want to clean up the whole `loc` argument and just force users to use the `.subplot()` method to activate a renderer. What do you think @akaszynski? I never use the `loc` argument, do you?

**Comment by akaszynski** [comment]
I don’t use the `loc` argument, but we should probably add in a depreciated warning/error just in case anyone is using it.

**Comment by banesullivan** [comment]
It's very poorly documented and only implemented in a handful of methods, so I'm inclined to think not many people are using it or know about it. This might be one of those *"we're still at major version 0, so the API might change"* moments for me.

**Comment by akaszynski** [comment]
Ok.  If it’s an unused feature, it won’t matter anyway.

As for empty docstrings in #470, you could just add a token docstring saying you’re referencing/wrapping a different function, or a pragma for CI.

**Comment by banesullivan** [comment]
Ah, good idea! I'll get a PR going for this soon and play around with a few different ways of making this happen as simply as possible. 

In the meantime, I'm just going to leave this PR as is and use that PR to implement these decorators and make sure all arguments to `Renderer` methods are documented

**Comment by banesullivan** [comment]
So I was trying out using `functools.wraps`, and I can't get it to work for properties... there are a lot of properties (e.g. `camera_position`, `bounds`, etc.)

**Pull request merged**
