### PR TITLE
Add tqdm progress bar to filters

### PR DESCRIPTION
**Pull request by banesullivan**
Add a way to monitor specific filters/algorithms that might take a while to run, for example, the Dalunay 3D filter. This new `ProgressMonitor` class can be used in a `with` context to show a `tqdm` status bar of the algorithm's progress.

This PR is a WIP and here to demonstrate what is possible. Feedback would be appreciated.

```py
with ProgressMonitor(alg, message="Delaunay 3D"):
    alg.Update()
```

### CODE REVIEW

**Comment by banesullivan** [comment]
Some refactoring of `ProgressMonitor` and `Observer` is needed to make them more general/extensible

**Comment by akaszynski** [comment]
@pyvista/developers, this is ready for review.  One good example I've been using is:

```python
from pyvista import examples
dragon = examples.download_dragon()
ugrid = dragon.delaunay_3d(progress_bar=True)
```

**Comment by akaszynski** [comment]
@banesullivan, since this is your branch, can you let me know if you approve of the (signifiant) changes I made?

**Comment by akaszynski** [comment]
> I see that this is currently only implemented for notoriously slow algorithms. Down the road, we may want to make this a common feature of all filters. Perhaps I could handle that in the upcoming refactoring of the filters module.

We could add this as a decorator (`@progress_bar`) for all the filters.

Let's merge this and work on a refactor down the road.

**Pull request merged**
