### PR TITLE
🚧 Refactor and Cleanup

### PR DESCRIPTION
**Pull request by banesullivan**
Brings #408 and #468  up to date in a branch within the PyVista repo for @JevinJ, @banesullivan, @GuillaumeFavelier, and @akaszynski to collaborate on since this PR brings major changes to the internal codebase

Originally from @JevinJ
### To Do

This To Do list is mostly from @JevinJ in #468's description

- [ ] Write tests for `DataSetAttributes/pyvista_ndarray`.
- [ ] Get rid of `__new__` methods in abstract classes, with `abc.ABC` it should throw an error, but it's not working atm(maybe vtk overrides that behavior). It should also be possible to hide the abstract classes from the API.
- [ ] Move `active_scalars_info/active_vectors_info`. Currently, it's on the `DataSet` level, but it seems vtk can have 2 different ones for each dataset, one for `CellData` and one for `PointData`, accessible through `DataSetAttributes`.
- [ ] Move/redirect more methods from `dataset.py` if possible.
- [ ] Add `CompositeDataSetAttributes`, @JevinJ might not get to this.
- [ ] Fix line spaces in classes, currently, they are inconsistent(either 1 or 2) through the project, but this may be a stylistic change for later, can save lots of lines if made 1.
    - @banesullivan: Maybe this can be fixed by enforcing a codestyle like Black (see #516)
- [ ] Do a final pass to ensure everything is as it should be & API doesn't change. Run plotting tests since I can't currently.

Things @JevinJ would like to do but probably won't do since they change API:

- ~Remove duplicate methods, `n_cells`/`n_points` & `number_of_cells`, `number_of_points`. Both do the same thing.~, @JevinJ, these are here for backward compatibility and likely here to stay
- [ ] Rename methods/properties in `dataset.py`, they aren't _quite_ what @JevinJ thinks they should be.
- [ ] Give all pyvista objects their own file, it's a bit confusing(and exhausting scrolling wise) having semi-related classes grouped in one file. Won't do because it would overwrite change history.
    - @JevinJ, there are ways to handle this that will not overwrite the change history than @banesullivan can handle as it was done before in the `core` module.

### CODE REVIEW

**Comment by JevinJ** [comment]
Someone let me known if they need clarification on any of the todos, was kinda thrown together from memory.

**Comment by JevinJ** [comment]
@banesullivan What do you think about renaming Table.row_arrays, DataObject.field_arrays, DataSet.cell_arrays, DataSet.point_arrays to [class].[type]_data? This would be similar to vtk's Get[type]_data which returns a DataSetAttributes. As for a larger api change, what about removing methods which just point to the relevant DSA? For example Table has about 15 methods which just point to DSA.

**Comment by JevinJ** [comment]
@banesullivan What do you think about either renaming abstract classes using __new__ to _[name], or removing them from \_\_init\_\_. Both would remove them from public view. The first would also indicate privacy, but may be tricky with documentation.

**Comment by banesullivan** [comment]
Hey @JevinJ, I haven't forgotten about this, things are just super busy and this is pretty high hanging fruit so it might take a bit before I can circle back to this

**Comment by JevinJ** [comment]
@banesullivan As is I think the TODO's can be cut down as this branch is in a good state. If they're cut down to:

1. I'm working on this, should be done in a couple days.
2. Can be worked around pretty easy, just remove those abstract classes from __init__ so they're not visible to users in the package.
6. Can be done automatically once that's sorted out.
7. 

That's good enough for me.

**Comment by banesullivan** [comment]
@JevinJ, that's great to hear! This is **really amazing work** so ping me when you are finishing up and I'll try to review/tackle remaining TODOs as soon as possible!

thanks so much for all of this work! Absolutely awesome!

**Comment by JevinJ** [comment]
@banesullivan Tests are pretty much done. Can't do number 2 right now because of circular dependencies between utilities and some of the core modules. You can start working towards getting this merged. I'll look around some for some minor things to clean up or tests to do.

An overview of the major changes, this meant to be a /core/ only refactor/cleanup:

- Added DataSetAttributes a dict-like wrapper for vtkCell/Point/Field data.
    - This removes _ScalarsDict and related derived classes.
    - Point/move most method implementations(for /core/ at least) to DSA.
    - point/cell/row_arrays now returns DSA instead of a _ScalarsDict instance.
    - There are still methods that should be moved/implemented in DSA. The major ones being active_vectors/scalars_info, I'm not sure on a good 1:1 way to implement these at the moment.

- Added pyvista_ndarray. Technically it already existed but this fleshes it out for use in DSA/elsewhere.
    - Includes from_any(), from_vtk_data_array(), from_iter(), constructors.

- Implemented POINT_DATA_FIELD, ROW_DATA_FIELD, etc in helpers.py as a Python enum.

- Implemented a polymorphic way to do save(), _load_file(). All that needs to be done is implement _vtk_writers, _vtk_readers properties on a DataSet.

- Various readability, shortness, documentation improvements and typo fixes.

- Renamed Common->DataSet, common.py->dataset.py. This should be reflected in documentation as well.

For future attention:

- pointset.py and composite.py are relatively untouched. CompositeDataSetAttributes should be implemented, look to vtk.numpy_interface.dataset_adapter.py for inspiration.

- test_clip_surface alone takes over half the test time(excluding plotting tests). I don't know if it can be sped up, but something to look at.

- utilites is looking pretty scary. Lots of stuff there looks duplicated or should be a method on the class instead.

**Comment by banesullivan** [comment]
With this, we need to start an anaconda based CI testing workflow as there are `import` differences between VTK 8.1 and 8.2.

We should set up a pipeline to test every version of VTK on PyPI and the latest on conda-forge

**Comment by akaszynski** [comment]
I really would like this to be broken up into smaller PRs.  This will be good for both of us as it will be easier to merge as it will be much easier to view and evaluate.

We've had some features gone missing and with smaller commits, it's much easier to track which commit caused the issue.  Otherwise, if we have a multi-thousand line commit and something broke, it will be an absolute nightmare figuring out what caused the issue.

**Comment by banesullivan** [comment]
Agreed. I'd like to also pair this with increased testing coverage. perhaps over 95% on all `core` modules?

**Comment by JevinJ** [comment]
@banesullivan, @akaszynski, thoughts on removing private methods in dataset that add/remove arrays(Like _add_field_array)? They've been refactored down in this branch to just point to methods in DSA. Just want to be sure they're not there for some special reason, advantage or removing is less code and they don't need tested.

**Comment by akaszynski** [comment]
> @banesullivan, @akaszynski, thoughts on removing private methods in dataset that add/remove arrays(Like _add_field_array)? They've been refactored down in this branch to just point to methods in DSA. Just want to be sure they're not there for some special reason, advantage of removing is less code and they don't need tested.

@banesullivan, correct me if I'm wrong, but we should be able to just have them point to other methods.  Just as long as instances can still reach the private methods, we should be good.

I urge you to open PRs that makes the modifications of this PR in smaller steps.  We keep changing master, and you'll have to merge with master and it's impossible to keep track of all the changes at this point.  Start by refactoring the `Common` class.

I think your changes clean up the code, but it must be done in steps or this PR will never go through.  Lots of people are now using `pyvista` for both open and closed source projects, and I want the outwards pointing API to remain the same while ensuring we have full test coverage.

**Comment by JevinJ** [comment]
@akaszynski Good points, how can I easily split up the PR and what might be a good strategy? Right now I'm trying to branch off and rebase/pick commits that I want for each feature I added. Rough order that I think will work:

1. FieldAssociation enum.
2. pyvista_ndarray
3. DataSetAttributes
4. Renaming of Common->DataSet and various refactorings.
5. Integration of DataSetAttributes in DataSet.

**Comment by akaszynski** [comment]
Recommend closing this PR for the moment as we're breaking it up.  It's spring cleaning!

**Pull request closed without merging**
