### PR TITLE
Use -a for xvfb-run in Plotting Testing (uses GL)

### PR DESCRIPTION
**Pull request by MatthewFlamm**
### Overview

See https://github.com/pyvista/pyvista/pull/5029#issuecomment-1782683161

Previously, only the default server number, i.e. 99, would be attempted.  Using `-a` flag will allow it to use any free server number. This is hopefully the cause and then fix of the random errors `xvfb-run: error: Xvfb failed to start`

### Details

This probably needs to be run several times to test.

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
Passed will close/reopen to restart

**Comment by MatthewFlamm** [comment]
passed again will close/reopen for another round.

**Comment by MatthewFlamm** [comment]
Passed again, one more open/reclose

**Review by banesullivan — APPROVED** [review]
Thanks @MatthewFlamm!! I noticed this too and opened #5135 without realizing you had this

**Review by tkoyama010 — APPROVED** [review]
Thanks!

**Comment by tkoyama010** [comment]
Let us wait until @MatthewFlamm is ready to merge.

**Comment by banesullivan** [comment]
This is high priority IMO and I'm pretty confident it will do the trick. Treating as a hotfix

**Comment by tkoyama010** [comment]
@banesullivan OK.
@MatthewFlamm Please Open another PR if you want have addtional test.

**Comment by banesullivan** [comment]
Apologies if I'm overstepping, I've just triggered about 10-15 re-runs at this point

**Comment by tkoyama010** [comment]
@banesullivan No problem. Thanks for your fast work! I was relieved to hear that.

**Comment by MatthewFlamm** [comment]
I'm +1 for having this merged fast.  Fingers crossed it works.

**Pull request merged**
