### PR TITLE
Use relative paths in the offlineviewer directive

### PR DESCRIPTION
**Pull request by greschd**
### Overview

This is a follow-up to #4632 and its fix in #4636: 

The solution introduced in #4636 uses absolute paths to the `_static` and `_images` directories.

Absolute paths work only if the documentation is served from the root of the domain. This is not the case for example when serving multiple documentation versions from the same domain.
Example deployed documentation: https://composites.dpf.docs.pyansys.com/version/dev/examples/gallery_examples/003_short_fiber_example.html#plot-results

To get the relative path of the '_static' directory to the current HTML document, we assume that the output structure is the same as the source structure.

Use `.as_posix()` on paths used in the HTML to convert them from Windows convention (using backslashes) to using forward-slashes, when built on Windows.

### CODE REVIEW

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
#4569 has not added a test for this extension, causing the coverage error. Comment has been added to skip judgment as a sign to add a test in this area in the future.

**Review by tkoyama010 — APPROVED** [review]
I just checked the source because we haven't been able to maintain the test, but LGTM.

**Comment by tkoyama010** [comment]
@greschd Thanks. If you don't mind, could you raise an issue about it. I cannot do it right now.

**Comment by greschd** [comment]
Thanks again for the review @tkoyama010! I've tested `pyvista-docs-dynamic` locally, and opened https://github.com/pyvista/pyvista-docs-dynamic/issues/1 for CI.

**Pull request merged**
