### PR TITLE
Release 0.35.3

### PR DESCRIPTION
**Pull request by akaszynski**
Release 0.35.3 to address issues in the mne docbuild. Pinging @larsoner for visibility.

Includes:
- #3089
- #3088
- #3071
- #3075
- #3049
- #3048
- #3053
- #3028

### CODE REVIEW

**Comment by akaszynski** [comment]
Wrong branch...

**Comment by akaszynski** [comment]
Admins of GitHub. If you're listening, it would be really great if you could change the target branch of a PR.

**Comment by adeak** [comment]
> Admins of GitHub. If you're listening, it would be really great if you could change the target branch of a PR.

Does https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request not apply?

**Comment by larsoner** [comment]
Last time I knew you could, let me check

**Comment by larsoner** [comment]
I was able to try to change the base to 0.35.3 by clicking the edit button next to the title, but it says:

> There are no new commits between base branch 'release/0.35.3' and head branch 'release/0.35.3'

**Comment by larsoner** [comment]
... so I think you might have been able to. They just hide it within the same "edit" as the title, which is not super discoverable!

**Comment by akaszynski** [comment]
> ... so I think you might have been able to. They just hide it within the same "edit" as the title, which is not super discoverable!

They do! I always figured that was just for the title. Thanks!

**Pull request closed without merging**
