### PR TITLE
Add group update settings to `dependabot`

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

The setting to update multiple versions together in one PR has been added to `dependabot`! This frees you from a large number of `dependabot` PRs.

### Details

- [Grouped version updates for Dependabot public beta.
](https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/)
- https://github.com/dependabot/dependabot-core/issues/1190

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
This fixes a problem with having many PRs, but introduces a new problem that a breakage due to one version upgrade will be hard to debug.  The `requirements_test.txt` has dozens of lines for example.  Can we logically group them in some way.  For example, all `trame*` dependencies are grouped.  All documentation dependencies are grouped, etc.

**Review by bjlittle — DISMISSED** [review]
Nice one @tkoyama010 👍

**Comment by banesullivan** [comment]
+1 to @MatthewFlamm's comment. I think it would be great to delineate specific dependency groups that are allowed to be bumped together and leave the rest to be bump one-by-one

**Comment by tkoyama010** [comment]
I made `trame` and `artifact` group. Baby steps though ... let's try it first and see how that goes.

**Comment by tkoyama010** [comment]
@pyvista-bot LGTM

**Pull request merged**
