### PR TITLE
[CLOSE] Numpy Array Volume Rendering

### LINKED ISSUE #168: Feature Request: numpy array volume rendering
I'm having a hard time understanding how to integrate volume rendering (from numpy arrays) with the vtki toolkit. 

I have this very naive little piece of code that essentially does the job:

```python
def volume(img, res, offset, background_threshold, opacity, cmap, max_value):
    if max_value > 255:
        raise ValueError('Only values between 0 and 255 allowed.')

    # Normalise range
    img = (img.astype(np.float) / np.max(img) * max_value).astype(np.uint8)
    img = img.T # needs to be done due to different array ordering in numpy and vtk

    # Import data from array into VTK
    dataImporter = vtk.vtkImageImport()
    data_string = img.tostring()
    dataImporter.CopyImportVoidPointer(data_string, len(data_string))
    dataImporter.SetDataScalarTypeToUnsignedChar()
    dataImporter.SetNumberOfScalarComponents(1)

    # Set spatial aspects of image
    w, d, h = img.shape
    dataImporter.SetDataExtent(0, h - 1, 0, d - 1, 0, w - 1)
    dataImporter.SetWholeExtent(0, h - 1, 0, d - 1, 0, w - 1)
    dataImporter.SetDataSpacing(res[::-1])

    # Set colours and opacity
    if isinstance(cmap, (matplotlib.colors.ListedColormap, matplotlib.colors.Colormap)):
        pass
    elif isinstance(cmap, str):
        cmap = matplotlib.cm.get_cmap(cmap)
    else:
        cmap = matplotlib.cm.viridis

    if isinstance(opacity, (float, int)):
        opacity = [opacity] * 255
    elif isinstance(opacity, (list, tuple, np.ndarray)):
        if len(opacity) == 1:
            opacity = list(opacity) * 255
        elif len(opacity) != 255:
            raise ValueError('Given opacity must be of length 1 or 255.')
    elif opacity == 'linear':
        opacity = np.arange(0, 255) / 255.
    elif opacity == 'exp':
        opacity = (1. / np.e**np.arange(0, 255))[::-1]

    alphaChannelFunc = vtk.vtkPiecewiseFunction()
    colorFunc = vtk.vtkColorTransferFunction()
    for ii in range(background_threshold, 255):
        alphaChannelFunc.AddPoint(ii, opacity[ii])
        colorFunc.AddRGBPoint(ii, *cmap(ii - background_threshold)[:-1])
    for ii in range(background_threshold):
        alphaChannelFunc.AddPoint(ii, 0.0)
        colorFunc.AddRGBPoint(ii, 0, 0, 0)

    volumeProperty = vtk.vtkVolumeProperty()
    volumeProperty.SetColor(colorFunc)
    volumeProperty.SetScalarOpacity(alphaChannelFunc)

    # Define mapper, volume, and add the correct properties
    volumeMapper = vtk.vtkGPUVolumeRayCastMapper()
    volumeMapper.SetInputConnection(dataImporter.GetOutputPort())
    volume = vtk.vtkVolume()
    volume.SetMapper(volumeMapper)
    volume.SetProperty(volumeProperty)
    return volume
```

It's then possible to visualise this with
```python
v = volume(<some numpy array> + args)
pobj = vtki.Plotter()
pobj.add_actor(v)
pobj.show()

```
but the approach seems stupid and inefficient. I'm just not sure how to go about implementing this better. Any thoughts?

### PR DESCRIPTION
**Pull request by supersubscript**
Resolves #168 

This PR adds volume rendering of numpy arrays in accordance with #168. It uses the vtkGPURayCastMapper to generate an output volume that can be added to a plotter. 

### TODO and limitations

1. Does not currently allow for scalarbars
2. Currently downscales input data to range 0-255
3. Add methods for rotation/translation
4. In general, because the mapper used is different from e.g. the polydata mappers, some standard functionality is not currently available.
5. No tests available due to no (afaik) intensity data in examples.
6. No way of changing global opacity level (due to (4.)).

### Examples
```python
import pyvista as pv

data = <some intensity array data>
p = pv.Plotter()
p.add_volume(data, resolution='[.5, 1, 1])
p.show()
```
or
```python
import pyvista as pv

data = <some intensity array data>
pv.plot(data, resolution=[.5,1,1], opacity='linear')
```

### CODE REVIEW

**Comment by supersubscript** [comment]
Hmm, because I replaced the original plotting.py file with my local one when I created the branch, the diff now says that the whole file is new, which wasn't my intention. Will see if I can fix.

**Comment by akaszynski** [comment]
Do you have an example intensity array?  Would any structured grid work?

**Comment by supersubscript** [comment]
@akaszynski, in principle, yes. I'm working mainly with plant shoots, so I have a bunch of confocal data of that kind. They tend to look something like this:

```python
plotter = pv.Plotter()
v = plotter.add_volume(plot_data, resolution=resolution,
                   opacity='linear', cmap='viridis')
plotter.show(auto_close=False)
plotter.set_background('white')
plotter.open_gif('rotate.gif')
plotter.view_yz()
v.SetOrigin(v.GetCenter())
plotter.reset_camera()

nframe = 45
for phase in np.linspace(0, 360, nframe + 1)[:nframe]:
    v.RotateZ(phase)
    plotter.write_frame()
    v.RotateZ(-phase)
plotter.close()
```
rotate


Not sure what other kinds of data I could provide...

**Comment by akaszynski** [comment]
This looks like an excellent example to add to our gallery.  Is this data you'd be willing on sharing?

**Comment by supersubscript** [comment]
Thanks for the comments and suggestions, @banesullivan. I've added some comments below, which fill in some of the gaps you've mentioned. @akaszynski, I'll try to see if I can find a representative, high-quality dataset!

### Comments
> 
> Possible example datasets in response to [#168 (comment)](https://github.com/pyvista/pyvista/issues/168#issuecomment-495164971)
>     * `examples.download_frog()`

This one gives me the following error:
```python
ERROR:root:MetaImage cannot read data from file.
MetaImage: Read: Cannot open data file
``` 

I've also tried plotting the other datasets, which all work well except for the bolt and nut, which doesn't understand how to render the volumes on top of each other. At least they all plot in one way or another:
1_head
2_bolt_nut
3_knee

>     * Volume rendering is only for `vtkImageData` (`pv.UniformGrid`s), correct?
Yes, correct.

>     * With this current implementation, is it possible to have a volume rendered object in a scene with other datasets that are not volume rendered?
Yes. here's an example with a volume and a surface mesh side-by-side:
vol_vs_mesh

I also don't get any errors locally when running tests. Not sure why the travis checks are failing.  

### Corrections
>     * Is a GPU required for volume rendering? I.e. is `vtkGPUVolumeRayCastMapper` always available even if a GPU is not available? If not, we can't test this on Travis or have an example in the gallery.

I've now changed the mapper to a vtkFixedPointVolumeRayCastMapper (vtkVolumeRayCastMapper isn't available in 8.1 for some reason). A vtkFixedPointVolumeRayCastMapper can render up to four volumes at the same time. 

>     * Is the only difference between `add_volume` and `add_mesh` the mapper, piecewise function, and property used? If so what is the advantage to having this in a seperate method rather than as an option in `add_mesh`?
As far as I know, yes. Initially I'd say that that there is an important semantical difference, as volumes and meshes are distinct objects with fundamentally different properties (as in the VTK framework). As such, adding a volume through `add_mesh` would be somewhat confusing. 

>     * Can you abstract the volume function to take both numpy arrays and `pv.UniformGrid` objects?

Done.

>     * Add a user friendly error message if the data type is not appropriate for volume rendering or if the GPU rendering class is unavailable.

Corrected by now using a vtkFixedPointMapper instead.

**Comment by banesullivan** [comment]
Wow, thanks @supersubscript!! These examples are great!

Looks like the CI tests are failing due to a syntax error:

```py
    from pyvista.plotting import *
E     File "/home/travis/build/pyvista/pyvista/pyvista/plotting.py", line 1232
E       raise TypeError(f'Data type {type(data)} is not valid.')
E                                                             ^
E   SyntaxError: invalid syntax
```

I think that type of formatting is not available on all version of Python 3?

Perhaps

```py
raise TypeError('Data type {} is not valid.'.format(type(data)))
```

**Comment by banesullivan** [comment]
Thanks for addressing all of my comments in my review! I think these changes are looking awesome and ready to go! A few final details before we merge this:

- [ ] add tests for the new `add_volume` method in `tests/test_plotting.py` and ensure CI's can volume render
- [ ] add a new example file (`examples/02-plot/plot-volume-render.py`) with a few of the examples from above
- [ ] @banesullivan: check out locally and bug hunt
- [ ] @supersubscript: are the items in the original "TODO" list addressed? Let me know if I can help on some of those

**Comment by banesullivan** [comment]
@supersubscript: is this dataset one you'd be willing to share publicly in our examples? Also, what is it?

58427999-2b850400-8099-11e9-94cb-afe202eaead4

**Comment by banesullivan** [comment]
@supersubscript:

> except for the bolt and nut, which doesn't understand how to render the volumes on top of each other. At least they all plot in one way or another:

I loaded those same datasets into ParaView and used the default volume rendering options to yield the same issue:

Screen Shot 2019-05-27 at 12 44 22 PM

I wondering if this has more to do with the opacity mapping than the volume rendering internals. It looks to me (totally not sure about this) like the nut has higher intensity values than the bolt which is why the bolt becomes transparent allowing us to see through it to the more intense nut... maybe?

**Comment by banesullivan** [comment]
The frog example was fixed in fa0c21d (see #237)

```py
import pyvista as pv
from pyvista import examples

vol = examples.download_frog()

p = pv.Plotter()
p.add_volume(vol)
p.show()
```

Screen Shot 2019-05-31 at 12 52 13 PM

**Comment by banesullivan** [comment]
Let's mark off the items in https://github.com/pyvista/pyvista/pull/231#issuecomment-496261236 and get this on the next release

**Comment by supersubscript** [comment]
Sorry for the late reply, @banesullivan – I've been away for a bit. The volume argument looks good.

If you could help me with getting the scalar bar thing to work it'd be helpful. Currently, it's not possible to do this using the normal approach, as the vtkFixedPointVolumeRayCastMapper doesn't have ways of 1) setting the scalar range ('rng'), and 2) a vtkLookupTable needed for colouring the scalar bar.

Ok, so to straighten things out, we're currently at:

- [ ] Add argument for enabling scalar bars
- [ ] Allow data of all numeric types without down-scaling to uint8
- [ ] Add methods for rotation/translation (would benefit from a custom vtkVolume wrapper. Not sure where this would fit in the current framework.)
- [ ] Add way of changing global opacity (not sure how to implement this)
- [ ] Add tests for the new add_volume method in tests/test_plotting.py and ensure CI's can volume render
- [ ] Add a new example file (examples/02-plot/plot-volume-render.py) with a few of the examples from above

**Comment by banesullivan** [comment]
Thanks for outlining a list of action items, @supersubscript! I'm going to focus some attention on wrapping this up for the remainder of the week.

**Comment by banesullivan** [comment]
@supersubscript - I'm just now getting around to this

## Follow up from https://github.com/pyvista/pyvista/pull/231#issuecomment-502148096

> Add argument for enabling scalar bars

I'm working on getting scalar bars working...

> Allow data of all numeric types without down-scaling to uint8

With the current implementation, this might not be possible - I'm thinking I might need to refactor the `add_volume` method to focus on ImageData rather than NumPy arrays in order to implement a fix for this

> Add methods for rotation/translation (would benefit from a custom vtkVolume wrapper. Not sure where this would fit in the current framework.)

I'm hesitant to add a wrapper for the `vtkVolume` actor or any actors... I think it would be better to support volume rendering for structured grids and unstructured grids. That way if you need to rotate the mesh, you can rotate the actual mesh as a structured grid and not just the rendering/display of of the image data since image data (UniformGrids) cannot be rotated.

> Add way of changing global opacity (not sure how to implement this)

Is your current implementation not sufficient? I think it works as you can't (wouldn't want to?) add a global opacity after a opacity transfer function is used.

> Add tests for the new add_volume method in tests/test_plotting.py and ensure CI's can volume render

Done.

> Add a new example file (examples/02-plot/plot-volume-render.py) with a few of the examples from above

I started this and added a minimal example


## Additions

### Sigmoidal Opacity Transfer Functions

I also added some more opacity transfer functions - particularly a few different spreads of a sigmoid under `'sigmoid'` and `'sigmoid_*'` (where * can be numbers 3-10. `'sigmoid'` is `'sigmoid_10'`)

```py
import pyvista as pv
from pyvista import examples

vol = examples.download_knee_full()

cpos = [(-381.74, -46.02, 216.54),
        (74.8305, 89.2905, 100.0),
        (0.23, 0.072, 0.97)]

p = pv.Plotter(notebook=True)
p.add_volume(vol, cmap='viridis', opacity='sigmoid')
p.camera_position=cpos
p.show()
```

download


In contrast to the linear mapping:

```py
p = pv.Plotter(notebook=True)
p.add_volume(vol, cmap='viridis', opacity='linear')
p.camera_position=cpos
p.show()
```

download


## Next Steps

I'm going to do a lot of refactoring of the `plotting` module in a new PR and see I can clean up everything and re-implement all of this as well as the `add_mesh` method because it's become difficult to manage. This PR will have to pause in the meantime

**Comment by banesullivan** [comment]
Scalar bars for volume rendering have been implemented in #272!! 🎉 

```py
import pyvista as pv
from pyvista import examples

vol = examples.download_knee_full()

cpos = [(-381.74, -46.02, 216.54),
        (74.8305, 89.2905, 100.0),
        (0.23, 0.072, 0.97)]

p = pv.Plotter(notebook=False)
p.add_volume(vol, cmap='fire', 
             opacity='sigmoid',
             rng=[25, 175])
p.camera_position=cpos
p.show()
```

Screen Shot 2019-06-26 at 12 28 14 PM

**Comment by akaszynski** [comment]
Volume example is great!

**Comment by banesullivan** [comment]
> > Add methods for rotation/translation (would benefit from a custom vtkVolume wrapper. Not sure where this would fit in the current framework.)
>
> I'm hesitant to add a wrapper for the vtkVolume actor or any actors... I think it would be better to ?support volume rendering for structured grids and unstructured grids. That way if you need to rotate the mesh, you can rotate the actual mesh as a structured grid and not just the rendering/display of of the image data since image data (UniformGrids) cannot be rotated.

Support for volume rendering structured grids and tetraheadralized grids will have to come at a later date.

**Pull request closed without merging**
