### PR TITLE
Add sphinx-duration extension to measure sphinx processing times

### PR DESCRIPTION
**Pull request by user27182**
### Overview

See https://www.sphinx-doc.org/en/master/usage/extensions/duration.html#module-sphinx.ext.duration

Not sure if it shows total build times or per-file processing times or even  just the slowest files, but could help highlight some build-time bottlenecks

### CODE REVIEW

**Comment by user27182** [comment]
Output from this option. Apparently over 30 minutes is spent processing cube maps?!

image

**Comment by tkoyama010** [comment]
Awesome analysis. What about switching to a static display for those that run too slowly to save time?

**Comment by user27182** [comment]
> Awesome analysis. What about switching to a static display for those that run too slowly to save time?

Tried static display with #6526. Results from running that PR with `sphinx.ext.duration`:
times

Times haven't changed.

Maybe we can use `sphinx.ext.autodoc.between` to edit all docstrings and remove any/all the examples? Then we could have a "fast-build" version of the current build process which doesn't run any code. https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#event-autodoc-process-signature

Either way I think extension is valuable and will help with monitoring build times.

**Review by MatthewFlamm — APPROVED** [review]
Looks extremely useful to help reduce build times on CI for PRs.

**Pull request merged**
