### PR TITLE
Removing docstring and return statement

### LINKED ISSUE #2512: Fix docstring and return of export_obj
**Describe what maintenance you would like added.**

- A clear and concise description of the maintenance problem.
https://github.com/pyvista/pyvista/blob/04516fe3b1b556d8df4f105fb6f43ff874a9939b/pyvista/plotting/plotting.py#L4397-L4408
The docstring says that `export_obj` returns `vtkOBJExporter`, but it actually returns nothing. Please modify the docstring and remove the return.

- If you are requesting maintenance for a specific line of source code, please include the permanent link for that line.
None

- Feel free to include pseudocode or screenshots of the requested outcome.
None

-----
_Ref https://github.com/pyvista/pyvista/pull/2451#discussion_r857139720_

### PR DESCRIPTION
**Pull request by RobPasMue**
### Overview

Closes #2512 

Removing return statement for `pyvista.plotting.export_obj()` and adapting docstring accordingly.

### CODE REVIEW

**Review by tkoyama010 — COMMENTED** [review]
LGTM

**Review by banesullivan — DISMISSED** [review]
lgtm, thanks for the contribution!

**Comment by RobPasMue** [comment]
It looks like codecov/parch is complaining @tkoyama010 - is it okey to merge? The change shouldn't impact the way pyvista behaves.

**Comment by tkoyama010** [comment]
@RobPasMue I will add the test here in another pull request, so please wait until then. Or you can create a pull request for us.

**Comment by RobPasMue** [comment]
> @RobPasMue I will add the test here in another pull request, so please wait until then. Or you can create a pull request for us.

I will look into it and create it @tkoyama010

**Comment by akaszynski** [comment]
Surprised we're not testing the obj exporter...

**Comment by RobPasMue** [comment]
For some reason the object is not being written. I have just uploaded the test for now. I will look into it. The error check after the first assertion is valid once the plotter is closed (I tried this locally).

**Comment by akaszynski** [comment]
Good test. Thanks @RobPasMue.

**Review by tkoyama010 — DISMISSED** [review]
LGTM

**Comment by RobPasMue** [comment]
Thanks for looking into it @akaszynski!

**Review by akaszynski — APPROVED** [review]

**Pull request merged**
