### PR TITLE
Add `None` return type annotations to core `readers.py` and `observers.py`

### PR DESCRIPTION
**Pull request by user27182**
### Overview

I ran `python -m autotyping pyvista/core --none-return` to automatically add `None` return annotations and then I resolved all reported type errors:

<details>

``` python
pyvista/core/utilities/observers.py: note: In member "__init__" of class "Observer":
pyvista/core/utilities/observers.py:116: error: Need type annotation for "event_history" (hint: "event_history: list[<type>] = ...")  [var-annotated]
            self.event_history = []
            ^~~~~~~~~~~~~~~~~~
pyvista/core/utilities/reader.py: note: In member "SetFileName" of class "_PVDReader":
pyvista/core/utilities/reader.py:1960: error: Incompatible types in assignment (expression has type "str", variable has type "None")  [assignment]
            self._directory = str(Path(filename).parent)
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
pyvista/core/utilities/reader.py: note: In member "UpdateInformation" of class "_PVDReader":
pyvista/core/utilities/reader.py:1980: error: Incompatible types in assignment (expression has type "list[PVDDataSet]", variable has type "None")  [assignment]
            self._datasets = sorted(datasets)
                             ^~~~~~~~~~~~~~~~
pyvista/core/utilities/reader.py:1981: error: Incompatible types in assignment (expression has type "list[Any]", variable has type "None")  [assignment]
            self._time_values = sorted({dataset.time for dataset in self._datasets})
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pyvista/core/utilities/reader.py:1981: error: "None" has no attribute "__iter__" (not iterable)  [attr-defined]
            self._time_values = sorted({dataset.time for dataset in self._datasets})
                                                                    ^~~~~~~~~~~~~~
pyvista/core/utilities/reader.py:1982: error: "None" has no attribute "__iter__" (not iterable)  [attr-defined]
            self._time_mapping = {time: [] for time in self._time_values}  # type: ignore[var-annotated]
                                                       ^~~~~~~~~~~~~~~~~
pyvista/core/utilities/reader.py:1982: note: Error code "attr-defined" not covered by "type: ignore" comment
pyvista/core/utilities/reader.py:1983: error: "None" has no attribute "__iter__" (not iterable)  [attr-defined]
            for dataset in self._datasets:
                           ^~~~~~~~~~~~~~
pyvista/core/utilities/reader.py:1985: error: Value of type "None" is not indexable  [index]
            self._SetActiveTime(self._time_values[0])
                                ^~~~~~~~~~~~~~~~~~~~
pyvista/core/utilities/reader.py: note: In member "_SetActiveTime" of class "_PVDReader":
pyvista/core/utilities/reader.py:1993: error: Incompatible types in assignment (expression has type "list[Any]", variable has type "None")  [assignment]
            self._active_datasets = self._time_mapping[time_value]
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pyvista/core/utilities/reader.py:1996: error: "None" has no attribute "__iter__" (not iterable)  [attr-defined]
                for dataset in self._active_datasets
                               ^~~~~~~~~~~~~~~~~~~~~
pyvista/core/utilities/geometric_sources.py: note: In member "normal_sign" of class "OrthogonalPlanesSource":
pyvista/core/utilities/geometric_sources.py:3817: error: "_check_sign" does not return a value (it only ever returns None)  [func-returns-value]
                [_check_sign(s) for s in sign]
                 ^~~~~~~~~~~~~~
Found 11 errors in 4 files (checked 143 source files)
```

<\details>

### CODE REVIEW

**Comment by user27182** [comment]
Depends on #6795

**Comment by user27182** [comment]
The manual changes are isolated to four files, and there were 19 files with purely automatic changes (no errors to resolve). I can split up the auto vs manual into separate PRs if preferred

**Comment by user27182** [comment]
> The manual changes are isolated to four files, and there were 19 files with purely automatic changes (no errors to resolve). I can split up the auto vs manual into separate PRs if preferred

The automatic changes are included in #6820, which should be merged first

**Comment by user27182** [comment]
This PR now only includes changes to `readers` and `observers`.

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Pull request merged**
