### PR TITLE
Allowing user to specify a colormap with a list of strings

### PR DESCRIPTION
**Pull request by akaszynski**
You can now pass a color map with a list of strings:

```python
import numpy as np
import pyvista

sphere = pyvista.Sphere()

n = sphere.n_points

# specify scalars
scalars = np.empty(n)
scalars[:n//3] = 0
scalars[n//3:2*n//3] = 1
scalars[2*n//3:] = 2

sphere.plot(scalars=scalars, cmap=['red', 'green', 'blue'])
```

tmp

### CODE REVIEW

**Comment by akaszynski** [comment]
``pyvista`` is being used by a larger company and one of the users wanted to create a three color `cmap`.  This is a also a feature I would have liked to have, so I went ahead and added it here.  @banesullivan, let me know if you agree with adding this.

**Comment by akaszynski** [comment]
Panel looks great!  What backend is that using?  It's not ``itk``.

**Comment by banesullivan** [comment]
> Panel looks great! What backend is that using? It's not itk.

Wrong thread?

**Comment by banesullivan** [comment]
Ah, that notebook! - its just using `panel` with vtkjs out of the box from `panel`

**Pull request merged**
