### PR TITLE
Patch for auto_close warning

### PR DESCRIPTION
**Pull request by banesullivan**
### Overview

I believe this is a fix for #791 - haven't tested because I'd have to boot up a windows VM

@rodrigomologni, would you be able to test this for us?

### CODE REVIEW

**Comment by banesullivan** [comment]
We may want to test this manually with Panel and a few screenshotting scenarios to make sure it doesn't break anything

**Comment by xavArtley** [comment]
FYI to be sure panel will capture the renderWindow when the VTK pane is constructed you should add `serialize_on_instantiation =True`:
 disp = panel_display(self.ren_win, sizing_mode='stretch_width',
                                     height=height, serialize_on_instantiation=True)

**Comment by banesullivan** [comment]
Ah, thanks for catching this @xavArtley!

**Comment by rodrigomologni** [comment]
@banesullivan, sorry for the delay. I was offline for a few days. I build my code with your changes in Windows 10. The bug was fixed. Thank you! :-)

**Pull request merged**
