### PR TITLE
MAINT: Use the latest version of pydocstyle

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
Now that a [patch is available](https://github.com/PyCQA/pydocstyle/issues/434#issuecomment-563413927) in the version `5.0.1` of `pydocstyle`, we can use the latest version.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
[Travis failures](https://travis-ci.org/pyvista/pyvista/jobs/626107169#L691-L696) are not related. Apparently we missed some typos:
```
Running pydocstyle

pyvista/core/filters.py:2965 in public method `clip_with_plane`:

        D401: First line should be in imperative mood; try rephrasing (found 'DEPRECATED')

pyvista/core/common.py:694 in public method `active_scalar`:

        D401: First line should be in imperative mood; try rephrasing (found 'DEPRECATED')

Makefile:16: recipe for target 'pydocstyle' failed
```

I'll go ahead and fix theses in here since it's related to doc maintenance.

**Comment by GuillaumeFavelier** [comment]
If I understand the error correctly, [Travis fails](https://travis-ci.org/pyvista/pyvista/jobs/626131115#L793) because `pytest`'s `nbval` plugin requires `coverage<5`:

```
pluggy.manager.PluginValidationError: Plugin 'nbval' could not be loaded: (coverage 5.0 (/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages), Requirement.parse('coverage<5'))!
```

I have a hard time to believe that this is related to this PR, I will check on `master`.

**Comment by banesullivan** [comment]
I recently removed `nbval` from being installed on Travis because we deprecated the notebook features not too long ago... why is it still needed?

**Comment by GuillaumeFavelier** [comment]
I will rebase then

**Comment by GuillaumeFavelier** [comment]
It was still installed on the branch: https://travis-ci.org/pyvista/pyvista/jobs/626131115#L366-L367

**Comment by banesullivan** [comment]
Aha, makes sense. Thanks for updating this @GuillaumeFavelier! I had been getting the error in the comment above locally

**Pull request merged**
