### PR TITLE
Implement capsule mesh creation

### PR DESCRIPTION
**Pull request by namheegordonkim**
### Overview

Capsule objects are very commonly used in rigid body simulators. Adding support for capsules will increase the viability of PyVista as a renderer for physics simulators that have no mature headless rendering solution, e.g. Brax and Isaac.

### Details

- `utilities` module to load and register `Capsule` class
- `geometric_objects.py` to create capsules by deforming hemisphere vertex positions (test cases are included in the docstring)

### CODE REVIEW

**Comment by tkoyama010** [comment]
Thank you for your contribution. If you need help resolving the error, please reach out to us anytime.

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
github-actions preview

**Comment by kmarchais** [comment]
Hello, thank you for this feature, the `vtkCapsuleSource` is available in VTK since 9.0 and deprecated in 9.3, replaced by `vtkCylinderSource` with hemispherical capping ([vtkCylinderSource::SetCapsuleCap](https://vtk.org/doc/nightly/html/classvtkCylinderSource.html#ad110f7c59834fc9a7533f2c3e1034af1)).

Maybe it would be more efficient to use the native VTK capsule ?

**Comment by tkoyama010** [comment]
> Hello, thank you for this feature, the `vtkCapsuleSource` is available in VTK since 9.0 and deprecated in 9.3, replaced by `vtkCylinderSource` with hemispherical capping ([vtkCylinderSource::SetCapsuleCap](https://vtk.org/doc/nightly/html/classvtkCylinderSource.html#ad110f7c59834fc9a7533f2c3e1034af1)).
> 
> Maybe it would be more efficient to use the native VTK capsule ? I wanted to add this also but since different versions of vtk are involved, I was not sure how to set it up.

Great, I didn't know vtk offered such a feature. Please create a pull request with your ideas. I will fix the problem of version in your pull request.

**Pull request closed without merging**
