### PR TITLE
Fix PolyData inplace merge

### PR DESCRIPTION
**Pull request by adeak**
While working on another PR I noticed that `PolyData.merge` seems to mutate the wrong mesh when `inplace=True`:
https://github.com/pyvista/pyvista/blob/da0f24836ac43532378a1eb9e6d4a834a1539c56/pyvista/core/filters/poly_data.py#L317-L318
https://github.com/pyvista/pyvista/blob/da0f24836ac43532378a1eb9e6d4a834a1539c56/pyvista/core/filters/poly_data.py#L390-L392

This implies that
1. the "in-place" operation is not actually in-place on `mesh` in `mesh.merge(...)`
2. the operation mutates the mesh passed to `mesh.merge()`!

I can only imagine that this is a bug. For instance `DataSetFilters.merge` behaves in the way I'd expect.

We might also need some checks this way, because merging non-PolyData into a PolyData might work with the current implementation, but will break with the change (in particular, `poly.merge(unstructured_grid, inplace=True)`.

@akaszynski is this a bug?

### CODE REVIEW

**Comment by adeak** [comment]
OK, good thing that I added tests, because I had the logic backward for `main_has_priority`.

The regression test I added is more complex than what I'd ideally be happy with for a test, because `mesh.merge(other)` can mess up the order of points even if both input meshes have the points in the same order. The only solution to this I can think of is to loop over each point of the result mesh, find the corresponding point of the input mesh, and then compare the corresponding point data.

I can think of a more concise implementation for this check but it's probably more obscure than the explicit loop I have now. Something like
```py
lookup = dict(zip(tuple(mesh.points), mesh.point_data['present_in_both']))
assert all(val == lookup[point] for point, val in zip(tuple(merged.points), merged.point_data['present_in_both']))
```

**Comment by adeak** [comment]
The unrelated test failure is probably be due to vtk 9.1.0 in CI.

**Comment by akaszynski** [comment]
I can confirm that recent failures on windows are due to the release of 9.1.0

I'll try to work in a fix over this weekend.

As an aside, think we're due for a release soon once we merge several of the outstanding PRs?

**Comment by adeak** [comment]
> I can confirm that recent failures on windows are due to the release of 9.1.0

I fixed the Texture change here, but a bit differently from your approach in the new marching cubes PR. Since there are other issues too, it might be best if you open a separate PR to fix all of these, then we can merge those in the open, conflicted PRs.

> As an aside, think we're due for a release soon once we merge several of the outstanding PRs?

Works for me :) There's a small feature I want to implement still (which is why I ran into _this_ bug), but I think I can put that together and have it merged quickly once this one is done.

**Comment by adeak** [comment]
CI is green now after your patch in main, @akaszynski. Have you reviewed the changes since https://github.com/pyvista/pyvista/pull/1720/commits/b095c1f66bfff4d1008d2da9f428a1e816f4b3a8 yet? No rush, I just don't want to stall in case you have,

**Comment by akaszynski** [comment]
Reviewed the changes after b095c1f66bfff4d1008d2da9f428a1e816f4b3a8 and I see no issue with the changes. That's quite a find regarding the placement of the main mesh in regards to merge.

**Comment by adeak** [comment]
Thank you for the review; merging then. There's a related feature I want to implement before we release, and I wanted to get this sorted out first.

**Pull request merged**
