### PR TITLE
🚧 ⬆️ UPDATE code style by black

### PR DESCRIPTION
**Pull request by tkoyama010**
Hello pyvista project. I formatted python code by using [black](https://github.com/psf/black).  As you know, black is an auto Python code formatter by Python software foundation. And the good thing to use this tool are
- It will follow PEP8 automatically.
- It will set a rule beyond what is not mentioned in PEP8. We don't have to discuss where to start a new line.
- We don't have to discuss whether to use single quotes or double quotes.

This tool saves these times and we will be able to focus on development. If you like this change, let's set this tool in CI !

Feel free to comment, because I didn't spend so much time to make this patch. It is automated :-).

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Thank you for interest on this matter! A discussion about the integration of a code formatter started in https://github.com/pyvista/pyvista/issues/288, please free to chime in. AFAIK, it seems that you're not the only one in favour of `black`. Personally, It's not my case.

**Comment by tkoyama010** [comment]
Sorry.  🙇  I revert isort part. Because I couldn't spend time to fix it.

**Comment by banesullivan** [comment]
Thanks for taking this on, @tkoyama010! I've been wanting to enforce a codestyle for a while but I think this might have to wait until #468 as it brings major changes to the codebase and this would bring major code conflicts with those changes...

**Comment by tkoyama010** [comment]
@banesullivan Thank you for your commet. I agree that it is hard to decide this kind of change. Don't worry about withholding.

**Comment by banesullivan** [comment]
I am going to close this. I don't think this is feasible any time soon (also it would need to be redone since there are so many conflicts). Marking for future consideration - thanks for all the effort @tkoyama010!!

**Pull request closed without merging**
