### PR TITLE
Fix inplace return values

### PR DESCRIPTION
**Pull request by banesullivan**
### Overview

If `inplace=True` there should be *no return value*

### Details

Addresses concerns in #1855, see comment: https://github.com/pyvista/pyvista/issues/1855#issuecomment-979774232

The established PyVista syntax/convention is:
```py
result = source.filter(options)
```
There have been previous discussions that established this convention and these filters do not adhere by editing the `source` AND producing `result`. When a `filter` edits the `source` (the case with `inplace=True`) then there should be no `result`.

Futhermore, this is consistent with inplace operation like `random.shuffle`: https://docs.python.org/3/library/random.html#random.shuffle

### CODE REVIEW

**Comment by adeak** [comment]
And this is the result of conscious efforts to always return something, see eg. https://github.com/pyvista/pyvista/pull/1299

**Comment by banesullivan** [comment]
Thanks for pointing me there @adeak. I suppose its on me for not being around during that discussion. Nonetheless, I will work on this PR to resolve *ALL* of these cases and push hardly for the change to be reverted. I would be more than happy to write a documentation page dedicated to outlining this filtering convention and explaining why `inplace` operations should never return a value.

**Comment by adeak** [comment]
It would probably help your cause if you made an argument in light of the past discussion, in a compelling enough way to counter the conclusion achieved on that issue ;)

**Comment by banesullivan** [comment]
Closing this in favor of #1860 per my thoughts in https://github.com/pyvista/pyvista/issues/1296#issuecomment-980256872

**Pull request closed without merging**
