### PR TITLE
Resolve issues with scalars in cell_data_to_point_data API docs

### LINKED ISSUE #1625: fix cell_data_to_point_data example
See: 
https://dev.pyvista.org/api/core/_autosummary/pyvista.DataSetFilters.cell_data_to_point_data.html#pyvista.DataSetFilters.cell_data_to_point_data

### PR DESCRIPTION
**Pull request by RobPasMue**
### Overview

Resolves #1625 

### Details

After some testing, it was seen that the Area values were not being shown. The bug fix consisted on including the `Area` as a `scalars` to be plotted. This was also fixed in the API docs for `compute_cell_sizes()`. Smooth shading has also been deactivated to provide more visual information regarding the cell/point values.

### CODE REVIEW

**Comment by RobPasMue** [comment]
Pinging @tkoyama010 @akaszynski for review

**Review by akaszynski — APPROVED** [review]
LGTM

**Comment by RobPasMue** [comment]
FYI, local version of the docs. Now the API example will look like this

image

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Pull request merged**
