### PR TITLE
Change base class of pyvista_ndarray back to ndarray

### PR DESCRIPTION
**Pull request by akaszynski**
### Partial Revert `pyvista_ndarray` Refactor

There are several code breaking changes in #654 that aren't covered by our tests, to include:

```python
def test_setting_points_from_self():
    grid = GRID.copy()
    grid.points = GRID.points
    assert allclose(grid.points, GRID.points)
```
This will raise a `TypeError` exception unless these changes are reverted.

Additionally, there's really no reason to wrap all possible array types.  We just need to wrap `vtk` objects so we can trigger `Modified`.

Also, depending on how quickly we need to resolve this revert, it would be more helpful to add in a bunch of methods to `pyvista_ndarray` that trigger `Modified` as it's not triggered in all cases.  For example:

```python
import pyvista as pv

sphere = pv.Sphere()
pl = pv.BackgroundPlotter()
pl = pl.add_mesh(sphere)

pts = sphere.points
```
Running `pts[:10] = 0` triggers `Modified`, but running `pts *= 2` will not trigger `Modified`.  This is because we've only implemented `__setitem__` in `pyvista_ndarray`.  We should add methods like:
- `__imul__`
- `__iadd__`
- `__ipow__`

I'm in favor of adding back in the testing, but there's no reason at all to include `from_vtk_data_array` when it that method should be implemented in `__new__` and no other init methods are necessary.

### CODE REVIEW

**Comment by JevinJ** [comment]
I don't immediately see anything wrong with reverting this. My thought process at the time for the from_iter method was to provide the option, but since DataSetAttributes or numpy can handle that itself, there's no reason to.

**Comment by banesullivan** [comment]
I also have been having issues when trying to create `PolyData` point clouds from the points of some meshes (e.g. `pv.PolyData(mesh.points)`).

**Comment by akaszynski** [comment]
Agreed, and it needed a refactor.  There were just some unforeseen consequences to changing the base class of `pyvista_ndarray`.  I'll work on those recommendations @JevinJ.

As for the issues, we can directly handle `np.ndarray`:
```python
import pyvista
sphere = pyvista.Sphere()
pyvista.plot(sphere.points)
```
But this will raise an exception with our current master:
```
TypeError: Object type (<class 'pyvista.core.pyvista_ndarray.pyvista_ndarray'>) not supported for plotting in PyVista.
```

**Comment by akaszynski** [comment]
Overall, I really like your contributions @JevinJ.  We do need a refactor, and having fresh eyes on this is super helpful.  As I'm learning though, we need to do this slowly, and really improve our unit testing.  This refactor has really showed me the limits of the module.

**Comment by banesullivan** [comment]
Agreed. Let's revert and focus on improving testing then come back to these PRs

**Comment by JevinJ** [comment]
Since we're talking about testing overhaul, have you considered [hypothesis](https://hypothesis.readthedocs.io/en/latest/)? 

Some advantages:

- It gives you a wide range of testing parameters of any type including None, and edge cases.
- When it fails it tries to give you the simplest failing example and caches the failure for the next run.
- You can specify your own parameter rules or create an object factory.

[What you can generate and how](https://hypothesis.readthedocs.io/en/latest/data.html)
[Hypothesis for the Scientific Stack](https://hypothesis.readthedocs.io/en/latest/numpy.html)

**Comment by akaszynski** [comment]
@JevinJ, hypothesis might be something we leverage in the future to enable better unit testing for pyvista.  Our current approach using `pytest` works quite well, but writing these tests is still quite intensive.

If you want, you can open up a PR that includes hypothesis.

**Comment by akaszynski** [comment]
For the time being, I'm going to merge this and we can refactor in a later PR.  @JevinJ, would you mind contributing to that PR?  The features we really need are hooks into the inplace operators so we call modified when the array is modified and not just set.

**Comment by akaszynski** [comment]
@JevinJ: `__array_finalize__` was removed and `proxy` was renamed to `_proxy`

**Comment by JevinJ** [comment]
@akaszynski yeah I'll look into the next PR. Hypothesis actually works alongside pytest, it's more like an advanced '@parameterize'.

**Pull request merged**
