### PR TITLE
A few more examples for the gallery

### PR DESCRIPTION
**Pull request by banesullivan**
This adds 6 new examples to the gallery

### CODE REVIEW

**Comment by akaszynski** [comment]
Examples look great.  I have some super nit-picky comments, as my IDE is giving me:
```
E231 missing whitespace after ‘,’
```

This also matches `numpy` documentation style and the PEP8 style:
https://stackoverflow.com/questions/31741418/pep8-space-after-a-comma

**Review by akaszynski — APPROVED** [review]

**Comment by banesullivan** [comment]
I'll fix those... I must have disabled linting in my IDE on this machine...

I may also add a few more examples

**Comment by akaszynski** [comment]
Hi @banesullivan.  Is this ready for merge?  Would be great to have 0.27.0 out this week

**Comment by akaszynski** [comment]
Looked through the examples after building locally and I'm happy with them.  Really liked the animation on the moving isolvalue example.

**Review by akaszynski — APPROVED** [review]

**Comment by akaszynski** [comment]
Going to merge this to get `0.27.0` through.

**Pull request merged**
