### PR TITLE
Add Poster section to document

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

I will share the PyVista community poster created for SciPy2023 is released under the [Creative Commons Attribution 3.0 Unported (CC BY 3.0) license](https://creativecommons.org/licenses/by/3.0/deed.en).
poster

### Details

- None

### CODE REVIEW

**Comment by banesullivan** [comment]
Thanks for putting together this poster, @tkoyama010! I appreciate your time and effort on this. This is a great start but I'm curious if we could hold off on adding this until after it is presented at SciPy and has a DOI? Further, I'd love for more of the PyVista community to be involved in the creation of this poster to hone in on the best way to present PyVista in this format. Let's refine this in the corresponding repository for now

**Comment by tkoyama010** [comment]
Sure. I am also concerned about the lack of DOI. No problem waiting to merge until Scipy 2023 is over.

**Comment by adeak** [comment]
Side note: is it not weird to have "the" poster (singular) in the root of the "[pyvista-posters](https://github.com/pyvista/pyvista-posters)" (plural) repository?

**Comment by tkoyama010** [comment]
Now is not the time to add posters to the section yet. This PR is to be closed.

**Pull request closed without merging**
