### PR TITLE
Add `auto-approve.yml` to allow review request by bot

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

I apologize for the burden I have recently placed on other maintainers with my PullRequest reviews. I do not have the authority to merge into main without approval by review and I believe that should continue to be the case. However, if other maintainers are unable to review for an extended period of time, I request that the project allow approval by the bot so that development is not stalled.

This is a proven method used by https://github.com/ansys/pymapdl.

- https://github.com/ansys/pymapdl/blob/main/.github/workflows/approver.yml

By this GitHub Actions, an approved maintainer who makes a comment with "LGTM" and the bot approves it.
Of course, this is a last resort, as I recognize that the best way to improve quality is to have it reviewed by a human maintainer.

### Details

- [ ] Test that it works correctly after merging.

### CODE REVIEW

**Comment by akaszynski** [comment]
Given the quality of our automated testing, I'm fine with this. I'm also sorry that I'm not always able to merge in time, and I'm fine with giving you the ability to do so. In the past, I've used the Admin permission to overwrite the need for an approver provided I gave everyone a reasonable amount of time to respond.

For now, I think we can pick one of two strategies:
- Give you more permissions
- Add in a bot for autoreview

I'm leaning for giving your admin since you're more than a regular contributor and both Bane and I may not have enough time to review every pull request.

Pinging @pyvista/developers for any thoughts regarding this. @tkoyama010 has been super helpful and I'd be happy giving him elevated permissions provided that there are no objections from the group (not predicting any).

**Comment by tkoyama010** [comment]
Thank you for your response, I will continue to be careful about merging into the main. I will keep the changes to the source code PR open for a week.

**Comment by banesullivan** [comment]
+1 for giving @tkoyama010 more privledges. You’ve more than earned it, Tetsuo!

**Comment by MatthewFlamm** [comment]
+1 as well for elevated permissions

**Pull request merged**
