### PR TITLE
Fix spelling of "set up" when used as a verb

### PR DESCRIPTION
**Pull request by RichardScottOZ**
Set up

### Overview

Word use

### Details

Set up

### CODE REVIEW

**Comment by adeak** [comment]
There's actually a bunch of places in the codebase where I've come across "setup" as a verb, and I kind of assumed it's correct in USian. But [the wiktionary](https://en.wiktionary.org/wiki/setup#Verb) indeed says it's incorrect.

If one of the USian devs can confirm that "setup" is incorrect as a verb then we should probably also hunt down the other occurences while we're at it.

**Comment by RichardScottOZ** [comment]
Yes, as far as I am aware setup is a noun - e.g. config.

**Comment by RichardScottOZ** [comment]
so fixing all at once makes sense.

**Comment by adeak** [comment]
I figured that's your stance, but I'm always nervous about subtle differences across US-UK-Oz-Canada :sweat_smile: Most of the library seems to follow US conventions, in agreement with the two USian maintainers. So that's why I'm open to the possibility that it's correct in American English (although the wiktionary is a pretty strong signal).

**Comment by tkoyama010** [comment]
If you think, "Hey I want the PyVista documentation in UK-Oz-Canada English," you can join [the PyVista documentation translation project](https://dev.pyvista.org/#translating).

**Comment by tkoyama010** [comment]
BTW, as a non-native speaker, I'm curious how well their English is communicated to each other 😅

**Comment by RichardScottOZ** [comment]
Merriam-Webster, Oxford or Macquarie will all define this the same way.

**Comment by banesullivan** [comment]
Agreed, we should change all occurrences of "setup" as a verb to "set up" at once.

I don't think there are any differences with "setup" across US/NZ/UK/etc versions of English and indeed "setup" is a noun and should be changed to "set up" in most places in the documentation.

**Review by tkoyama010 — APPROVED** [review]

**Review by banesullivan — CHANGES_REQUESTED** [review]
Requesting all occurrences be changed at once here

**Comment by tkoyama010** [comment]
Fixed a typo I found. @RichardScottOZ Please check for any omissions.

**Review by RichardScottOZ — COMMENTED** [review]
Set up the plotter, open a movie and write a frame after moving the sphere.

**Comment by adeak** [comment]
I think I got the rest of them, please review.

**Review by tkoyama010 — APPROVED** [review]
@adeak Good catch. Thanks.

**Review by banesullivan — APPROVED** [review]

**Review by RichardScottOZ — COMMENTED** [review]
Yes, looks good.

**Pull request merged**
