### PR TITLE
MAINT: Fix documentation typos

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR is a follow-up of https://github.com/pyvista/pyvista/issues/336#issuecomment-555940828 and fixes typos in the documentation. It doesn't change the style or add any features.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Using:

`codespell pyvista examples -S "*.pyc,*.txt,*.jpg,*.ply,*.vtk,*.vti"`

Returns:

```
pyvista/plotting/plotting.py:3645: LOD  ==> LOAD
pyvista/plotting/export_vtkjs.py:94: byteorder  ==> byte order  | disabled due to java class
```

**Comment by GuillaumeFavelier** [comment]
We can tweak `codespell` to ignore those two words `LOD` and `byteorder` and it should be fine.

**Comment by GuillaumeFavelier** [comment]
And now that I think about it, we can even add a `codespell` call in Travis. Don't hesitate to tell me what you think.

**Comment by banesullivan** [comment]
Wow, thanks @GuillaumeFavelier! I'm definitely the main culprit when it comes to these typos so having a checking routine like codespell is awesome - I just ran it locally and this is far better than any of the other spell checking utilities I have tried.

> we can even add a codespell call in Travis. Don't hesitate to tell me what you think.

This might be a good idea just to have in one of the builds, but it might be best to set up a way for folks to run this as a pre-commit hook

**Comment by akaszynski** [comment]
In @banesullivan ‘s defense, he’s also the one who’s written most of the documentation!

**Comment by banesullivan** [comment]
@GuillaumeFavelier, I'm ready to merge this when you are

**Comment by GuillaumeFavelier** [comment]
Thank you @banesullivan , feel free to merge.

**Comment by GuillaumeFavelier** [comment]
For reference, in the end, I ran this: 

`codespell docs pyvista examples -S "*.pyc,*.txt,*.gif,*.png,*.jpg,*.ply,*.vtk,*.vti"`

And got the following, we can see how to ignore those words in another PR:

```
docs/external_examples.rst:295: FLEM  ==> PHLEGM
docs/external_examples.rst:299: flem  ==> phlegm
docs/external_examples.rst:300: flem  ==> phlegm
docs/external_examples.rst:302: FLEM  ==> PHLEGM
docs/external_examples.rst:313: FLEM  ==> PHLEGM
docs/external_examples.rst:313: flem  ==> phlegm
pyvista/plotting/plotting.py:3645: LOD  ==> LOAD
pyvista/plotting/export_vtkjs.py:94: byteorder  ==> byte order  | disabled due to java class
```

**Pull request merged**
