### PR TITLE
Change documentation theme to sphinx-book-theme

### PR DESCRIPTION
**Pull request by banesullivan**
These changes switch us to sphinx-book-theme which may work a bit better for our content and sections. Feedback welcome here! Which theme do you like better?

| Before | After |
|---|---|
| PyVista _ PyVista 0_44_1 documentation | PyVista _ PyVista 0_45_dev0 documentation · 10 17pm · 07-22 | 
| Examples _ PyVista 0_44_1 documentation | Examples _ PyVista 0_45_dev0 documentation · 10 17pm · 07-22 |

### CODE REVIEW

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
@pyvista-bot preview

**Comment by banesullivan** [comment]
Hm. For some reason its showing a bunch of these "click to expand" messages on UI elements. I'm not seeing this in other projects. @bjlittle, have you seen this before?
Screenshot 2024-07-11 at 2 57 03 PM

**Comment by bjlittle** [comment]
You can control the depth via options in the `conf.py` ... Perhaps play with the max_navbar_depth, show_navbar_depth and show_toc_level options

**Review by bjlittle — APPROVED** [review]

**Comment by banesullivan** [comment]
Not ready to merge, a few issues remain:

1. The primary sidebar will not open/close with the button
2. The social buttons are both in the navbar and the primary sidebar (need to remove from navbar)
3. The "click to expand"/"click to collapse" labels are on every dropdown - this should be removed IMO

I can't immediately tell whats causing these issues here, but likely some custom CSS we are including.

**Comment by banesullivan** [comment]
Okay, all of the remaining issues are resolved now. If we all think this is a better theme, then this is good to merge. However, I'd like to get a handful of opinions here if possible

**Comment by tkoyama010** [comment]
> Okay, all of the remaining issues are resolved now. If we all think this is a better theme, then this is good to merge. However, I'd like to get a handful of opinions here if possible

I discussed about of sphinx-book-theme with @bjlittle at https://github.com/bjlittle/geovista/issues/815 . The discussion turned me into an advocate of the sphinx-book-theme.

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Comment by MatthewFlamm** [comment]
Is the preview link in https://github.com/pyvista/pyvista/pull/6369#issuecomment-2224225468 current? 

I'm seeing that the new design looks terrible on mobile devices.  But the current docs look ok.  

This PR:
Screenshot_20240723-174753


Current docs:
Screenshot_20240723-175609

**Comment by banesullivan** [comment]
That link is current, but it looks a bit better for my on iPhone 


image
imageimage

**Comment by MatthewFlamm** [comment]
There must have been a cache problem, it is fine now.  I do not have a strong opinion either way.  The new style looks good to me.

**Comment by akaszynski** [comment]
> I do not have a strong opinion either way.

Same. Both are quite similar, but with sphinx book theme coming out on top with section links being combined with the header on the left. Makes navigation clearer.

**Pull request merged**
