### PR TITLE
Remove "Edit on Github" button

### PR DESCRIPTION
**Pull request by akaszynski**
### Move gallery examples to docs directory

#636 noted that the "Edit on GitHub" link in the top right of all the gallery example pages is broken.  This is due to the examples directory where the examples are built from is outside of the `docs` directory.  To fix this, this PR moves `examples` to `docs/sphinx_examples` and changes the reference in `conf.py`. 

Note:
You can see the latest development docs at:
https://github.com/pyvista/pyvista-docs-dev

It's tagged to the last build, so you'll have to build this branch to see the changes.  I've verified that the edit on github link works.

### CODE REVIEW

**Comment by akaszynski** [comment]
@pyvista/developers, ready for review.

**Comment by akaszynski** [comment]
> I'd keep the dir name at just examples, as they are not specific to sphinx and can be looked at/used outsider of compiled docs.

Good point.  I had to rename the output directory from the gallery examples from `examples` to `gallery_examples` so that it doesn't overwrite `examples` in `docs`.

**Comment by akaszynski** [comment]
@GuillaumeFavelier, could you review this real quick?

**Comment by GuillaumeFavelier** [comment]
I built the documentation locally and except a few warnings, I got a failing example: 

```
Exception occurred:
  File "/home/guillaume/source/anaconda3/envs/mne-pyvista/lib/python3.7/site-packages/sphinx_gallery/gen_gallery.py", line 544, in summarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/home/guillaume/source/pyvista/docs/examples/02-plot/volume.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/guillaume/source/anaconda3/envs/mne-pyvista/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/home/guillaume/source/anaconda3/envs/mne-pyvista/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/home/guillaume/source/pyvista/docs/examples/02-plot/volume.py", line 113, in <module>
    large_vol = examples.download_damavand_volcano()
  File "/home/guillaume/source/pyvista/pyvista/examples/downloads.py", line 589, in download_damavand_volcano
    volume = _download_and_read("damavand-volcano.vtk")
  File "/home/guillaume/source/pyvista/pyvista/examples/downloads.py", line 62, in _download_and_read
    return pyvista.read(saved_file, file_format=file_format)
  File "/home/guillaume/source/pyvista/pyvista/utilities/fileio.py", line 203, in read
    return read_legacy(filename)
  File "/home/guillaume/source/pyvista/pyvista/utilities/fileio.py", line 140, in read_legacy
    raise AssertionError('No output when using VTKs legacy reader')
AssertionError: No output when using VTKs legacy reader
```

I don't think it's related to this PR but I don't know how to fix that. Anyway, after building, I don't see the "Quick examples" section anymore:

`live` | PR
-------|--------
image | image

**Comment by GuillaumeFavelier** [comment]
Actually I realized I can't run the test suite on:

```
...
 tests/test_polydata.py::test_remove_points_any ✓                                                                                                                                                     89% ████████▉ 
 tests/test_polydata.py::test_remove_points_all ✓                                                                                                                                                     90% ████████▉ 
 tests/test_polydata.py::test_remove_points_fail ✓                                                                                                                                                    90% █████████ 
 tests/test_polydata.py::test_vertice_cells_on_read ✓                                                                                                                                                 90% █████████ 
 tests/test_polydata.py::test_center_of_mass ✓                                                                                                                                                        90% █████████ 
 tests/test_polydata.py::test_project_points_to_plane ✓                                                                                                                                               91% █████████▏
 tests/test_polydata.py::test_tube ✓                                                                                                                                                                  91% █████████▏
 tests/test_polydata.py::test_delaunay_2d ✓                                                                                                                                                           91% █████████▏
 tests/test_polydata.py::test_lines ✓                                                                                                                                                                 91% █████████▎
 tests/test_polydata.py::test_ribbon_filter ✓                                                                                                                                                         91% █████████▎
 tests/test_polydata.py::test_is_all_triangles ✓                                                                                                                                                      92% █████████▎
 tests/test_qt_plotting.py::test_qt_interactor ✓                                                                                                                                                      92% █████████▎
[1]    7200 segmentation fault (core dumped)  python -m pytest -v --cov pyvista
```

But this should be solved in https://github.com/pyvista/pyvista/pull/619

**Comment by akaszynski** [comment]
@GuillaumeFavelier, I'm encountering that problem too (missing link on the docs page).  I'm looking into it.

**Comment by akaszynski** [comment]
@GuillaumeFavelier, I ended up just removing the "Edit on GitHub" button as it wasn't possible to move the examples folder for `sphinx`.  I think keeping the docs folder in the root directory is a good idea, because that way if someone clones the repo, the examples are right there in the source.

I think having the examples in the root directory is worth the price of not being able to edit the page right on github (which I don't think many were using anyway).

It's up for review again.

**Comment by imsodin** [comment]
I guess there's no way to disable it on examples only? In another project I found the edit on github button a nice way to on-board docs-contributions from non-technically-minded and "git-is-the-devil" people :)  
But overall definitely agree it's a valid trade-off, you can still point them at githubs online editor directly.

**Comment by GuillaumeFavelier** [comment]
> I guess there's no way to disable it on examples only?

Sadly I did not find any @imsodin. It does not mean it's not possible but this situation with a broken link is a bit confusing.

**Comment by GuillaumeFavelier** [comment]
I'll rename this PR if you don't mind @akaszynski

**Comment by akaszynski** [comment]
Going to merge this.  I appreciate the feedback and testing, even while @banesullivan is on vacation!  I agree that it's not an idea solution, but I'd rather have a non-feature than a broken feature.

**Pull request merged**
