### PR TITLE
Add plotting floors

### PR DESCRIPTION
**Pull request by banesullivan**
This adds a helper method to add a floor/wall at the boundary of the rendering scene

```py
import pyvista as pv
from pyvista import examples

mesh = examples.download_dragon()

p = pv.Plotter()
p.add_mesh(mesh)
p.add_floor('-y')
p.add_floor('-z')
p.show()
```

download

### CODE REVIEW

**Comment by akaszynski** [comment]
Weird that my example caused it to fail since I only modified the examples.  Potentially due to a change in master?

**Comment by GuillaumeFavelier** [comment]
I noticed that it's possible to add multiple floors with `add_floor()` but you can only remove the last one with `remove_actor()`

**Comment by banesullivan** [comment]
> I noticed that it's possible to add multiple floors with `add_floor()` but you can only remove the last one with `remove_floor()`

Indeed - this still needs to be worked out

**Comment by GuillaumeFavelier** [comment]
> I noticed that it's possible to add multiple floors with add_floor() but you can only remove the last one with remove_floor()

With more toughts, I think it depends on the API for it. What would be best?

* one call to `remove_floor()` for each call to `add_floor()`
* one call to `remove_floor(all=True)` or `remove_floors()` to remove everything

**Comment by akaszynski** [comment]
> > I noticed that it's possible to add multiple floors with add_floor() but you can only remove the last one with remove_floor()
> 
> With more thoughts, I think it depends on the API for it. What would be best?
> 
> * one call to `remove_floor()` for each call to `add_floor()`
> * one call to `remove_floor(all=True)` or `remove_floors()` to remove everything

I went ahead and implemented `remove_floors` as it's the cleanest API, and there's not a good way to track which floor is removed.  Full example is:
```python
import pyvista as pv
from pyvista import examples

mesh = examples.download_dragon()

p = pv.Plotter()
p.add_mesh(mesh)
p.add_floor('-y')
p.add_floor('-z')
p.remove_floors()
p.show()
```
Which will just plot the dragon.

**Pull request merged**
