### PR TITLE
MAINT: Fix documentation style

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR is a follow-up of this https://github.com/pyvista/pyvista/pull/457#issuecomment-556389769 and fixes the documentation style. It doesn't add any features.

I iterate locally using:

`pydocstyle pyvista`

___

**Current status**

- [x] plotting.py 
- [x] qt_plotting.py 
- [x] renderer.py
- [x] widgets.py
- [x] export_vtkjs.py
- [x] colors.py
- [x] picking.py
- [x] mapper.py
- [x] helpers.py
- [x] tools.py
- [x] theme.py
- [x] examples.py
- [x] downloads.py
- [x] parametric_objects.py
- [x] fileio.py
- [x] geometric_objects.py
- [x] errors.py
- [x] features.py
- [x] sphinx-gallery.py
- [x] composite.py
- [x] common.py
- [x] pointset.py
- [x] filters.py
- [x] objects.py
- [x] grid.py

**Fancy progress bar**

🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵🔵 100% :tada:

### CODE REVIEW

**Comment by banesullivan** [comment]
This is a major improvement to the docs!! Thanks for getting this going @GuillaumeFavelier!

**Comment by banesullivan** [comment]
I just made some changes to the `picking.py` module - I can resolve that merge conflict in #463 as this might want to land prior to that PR

**Comment by GuillaumeFavelier** [comment]
I noticed that several functions are either alias, deprecated or kept for compatibility. Thus, their documentation are just duplicates. The cost of maintaining those could be decreased by implementing a decorator that would copy the documentation of the 'reference' function.

**Comment by GuillaumeFavelier** [comment]
Locally on the latest state of this, `pydocstyle` does not complain anymore. Hopefully, that will help #457 

I did my best to rephrase the doc without losing any information and stay consistent as much as possible. Feel free to modify anything or let me know if you any comments @pyvista/developers. This is a fairly big diff. 

This **does not change the code style**, just the documentation.

**Comment by banesullivan** [comment]
This all looks great to me so I'm going to go ahead and merge so I can push a few other things forward

**Pull request merged**
