### PR TITLE
🚧 Refactor and cleanup 

### PR DESCRIPTION
**Pull request by JevinJ**
Brings #408 up to date and reverts all/most style changes.

TODO:
- Write tests for DataSetAttributes/pyvista_ndarray.
- Get rid of \_\_new\_\_ methods in abstract classes, with abc.ABC it should throw an error, but it's not working atm(maybe vtk overrides that behavior). It should also be possible to hide the abstract classes from the api.
- Move active_scalars_info/active_vectors_info. Currently it's on the DataSet level, but it seems vtk can have 2 different ones for each dataset, one for CellData and one for PointData, accessible through DataSetAttributes.
- Move/redirect more methods from dataset.py if possible.
- Add CompositeDataSetAttributes, I might not get to this.
- Fix line spaces in classes, currently they are inconsistent(either 1 or 2) through the project, but this may be a stylistic change for later, can save lots of lines if made 1.
- Do a final pass to ensure everything is as it should be & api doesn't change. Run plotting tests since I can't currently.

Things I'd like to do but probably won't do since they change api:
- Remove duplicate methods, n_cells/n_points & number_of_cells, number_of_points. Both do the same thing.
- Rename methods/properties in dataset.py, they aren't _quite_ what I think they should be.
- Give all pyvista objects their own file, it's a bit confusing(and exhausting scrolling wise) having semi-related classes grouped in one file. Won't do because it would overwrite change history.

### CODE REVIEW

**Comment by banesullivan** [comment]
@JevinJ, this is looking really good - thank you!!

Let me and @pyvista/developers know when it is ready for review. Considering this has a lot of refactoring and introduces `vtkDataSet` into the mix, we'll want all hands on deck for the review.

**Comment by JevinJ** [comment]
@banesullivan What is the minimum supported Python version? From the readme I'm guessing >= 3.5?

**Comment by akaszynski** [comment]
Min version is `python>=3.5`.

**Comment by banesullivan** [comment]
@akaszynski and I still leverage PyVista on Python 2.7 for a few external projects, so we try to keep the core API from breaking usability on 2.7 but officially, we only support >=3.5 as Alex said above

If you could make sure the optional 2.7 test on Travis still passes for this PR, that would be great. It looks like it is currently failing due to `super()` calls which is a pretty easy thing to manage fro backward compatibility.

**Comment by akaszynski** [comment]
I've actually just dropped support for 2.7 internally, so you're good to go on my end.  Since Python 2.7 EOL is in 31 days, I think we should just support 3.5+.

**Comment by banesullivan** [comment]
I feel **very strongly** about leaving Python 2.7 behind but I want to wait until ParaView is pushing public builds with Python 3 on all OS before we totally drop the core API support. Currently, Linux and Windows have 3.7 but not Mac 😞 : https://www.paraview.org/download/

(this is because [PVGeo](https://github.com/OpenGeoVis/PVGeo) requires PyVista inside ParaView's Python environment)

**Comment by JevinJ** [comment]
This won't currently pass, mostly because bool arrays are unhandled. DataSetAttibutes will remove a lot of duplicated code in common.

TODO: add tests for DataSetAttributes/pyvista_ndarray. Work on removing/replacing scalar/vector info in dataset, all that information is already in DataSetAttributes. Patch up DataSet/Object, there are likely still incorrect references since adding dsa.

**Comment by akaszynski** [comment]
I can't see anything wrong with this refactoring, and I agree with most of the code changes.  Some changes are purely stylist, but I'd rather not split hairs given that 99% of this improves readability.

Thanks for your work thus far!  Once you're ready to merge, please let me know and I'll test this out on my closed source software.  I'd like to make sure it passes my function integration testing first.

**Comment by banesullivan** [comment]
@akaszynski, @GuillaumeFavelier, and @JevinJ: #472 officially breaks Python 2.7 compatibility so this is good to move forward without Python 2.7 builds passing.

@JevinJ, can you update the branch to the current master branch and put a todo list in the first post of what is left/unfinished?

**Comment by banesullivan** [comment]
`0.23.0` is landing soon and these changes won't be able to make it. To me, these changes are major (in a good way) and warrant a minor release. I'm going to go ahead and mark this for `0.24.0`

**Comment by JevinJ** [comment]
@banesullivan Done. Will write TODO shortly.

**Comment by banesullivan** [comment]
Thanks for updating this, @JevinJ! I am going to go ahead and merge this into a `development` branch in the repo for us all to be able to tackle the remaining To Do items.

@JevinJ, I will add you to the org account so that you can push directly to that new branch

**Pull request merged**
