### PR TITLE
Add example changing mapped scalars

### PR DESCRIPTION
**Pull request by banesullivan**
Users often request how to change the mapped scalars that have already been plotted. Here is a full fledged example with Trame

For https://github.com/pyvista/pyvista/discussions/4131

Screen Shot 2023-03-15 at 10 21 53 AM

### CODE REVIEW

**Comment by akaszynski** [comment]
While we can't add this to the gallery, I would like for this to be rendered in our documentation somehow. We could use [literalinclude](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-literalinclude) or just a link, but it needs to have a "copy button". Not everyone will go source diving.

**Comment by akaszynski** [comment]
Also, is there any way we could test these? Even just a smoke test?

**Comment by akaszynski** [comment]
I'm fine with adding this "as-is", but we should have a follow-up with testing and adding to documentation.

**Review by akaszynski — APPROVED** [review]

**Comment by banesullivan** [comment]
Merging this as is and will try to make a proper example demonstrating how to modify the mapper, prop, and lut in more ways

**Pull request merged**
