### PR TITLE
🚧 Fix window exit crash

### LINKED ISSUE #186: exit button causes crash
**EDIT:** *this is a duplicate of #135*

I've run the example you suggested in my previous issue:

```python
from vtki import examples
mesh = examples.download_st_helens()
warped = mesh.warp_by_scalar()
warped.plot(notebook=False)
```
It worked very well but when I closed the window and returned control to the jupyter lab I got the following stream of `list index out of range` errors:

<details>

```python-traceback
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:Shader object was not initialized, cannot attach it.
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in __call__(self, obj, event, message)
     47         self.__event_occurred = True
     48         self.__message_etc = message
---> 49         kind, path, address, alert = self.parse_message(message)
     50         self.__message = alert
     51         if self.__log:

~\Continuum\anaconda3\lib\site-packages\vtki\errors.py in parse_message(message)
     32         # Message format
     33         regex = re.compile(r'([A-Z]+):\sIn\s(.+),\sline\s.+\n\w+\s(.+):\s(.+)')
---> 34         kind, path, address, alert = regex.findall(message)[0]
     35         return kind, path, address, alert
     36 

IndexError: list index out of range
ERROR:root:#version 120
```

</details>

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
Considering the following simple code snippet:

```py
from pyvista import examples
import pyvista as pv
mesh = examples.download_st_helens()
p = pv.Plotter(notebook=False)
p.add_mesh(mesh)
p.show()
```

Running this on Windows on a IPython environment either on a `jupyter notebook` or `Spyder` terminal for example will open a window:

image

But a few issues have been reported:

- [ ]  **1)** Closing the window with the X button crashes the kernel with `ERROR:root:Shader object was not initialized, cannot attach it.` (see https://github.com/pyvista/pyvista/issues/186#issuecomment-545598442 or https://github.com/pyvista/pyvista/issues/500#issue-537459287)
- [ ]  **2)** Closing the window with `q` closes correctly but if you run the cell again, the window will open and close instantly. You need to restart the kernel to have the correct behaviour: only the first run of the cell opens a window that actually stays opened. (see https://github.com/pyvista/pyvista/issues/186#issuecomment-550993270)

Closes #186 and #500

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
In my experiments, I found a way to mitigate **bug 2)** by modifying the code snippet slightly:

```py
from pyvista import examples
import pyvista as pv
mesh = examples.download_st_helens()
p = pv.Plotter(notebook=False)
p.add_mesh(mesh)
p.update()  # <--- This keeps the window opened
p.show()
```

@WeiGong123 or anyone else can maybe try this one to double-check?

Then we can decide to integrate this change in the code without the need for the user to modify anything. But I will remind that closing with `q` requires the `show()` function to have **`auto_close=True`** (default value).

---

Also, by discussing offline with @banesullivan, we discovered a way to fix **bug 1)** as well. The idea is to set **`auto_close=False`**. First I will say that I'm not familiar with `spyder` so in my test, even though I didn't encounter the `Shader error` anymore, I had issues with Spyder 3:

image

But after updating to Spyder 4, I didn't get any error message from `spyder`.

---

But the thing is, those 2 patches are **incompatible** since they both rely on different values of `auto_close`. There is maybe another way to fix those issues but anyway I wanted to know your opinion on this @pyvista/developers

**Comment by GuillaumeFavelier** [comment]
Also, a code snippet without an explicit call to `show()` should work too:

```py
from vtki import examples
mesh = examples.download_st_helens()
warped = mesh.warp_by_scalar()
warped.plot(notebook=False)
```

**Comment by GuillaumeFavelier** [comment]
Another solution would be to modify the `_close_callback()` function called when `q` is pressed so that it actually calls `close()`. This modification requires  `auto_close=False` by default and fixes **1)** and **2)** in my tests.

**Comment by GuillaumeFavelier** [comment]
What would be the impact of changing permanently the default of `auto_close` to `False`? Is `auto_close` still needed in this case? @banesullivan, @akaszynski

**Comment by banesullivan** [comment]
So we should keep auto close as true, turning it to false just tells us that the `close` call is trying to access the render window after it’s destroyed which is causing the crash on windows. 

Also if auto close if false and the user hits q, the window should not disappear but be inactive which currently works as expected. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
It took me a while, but I figured out how to get OpenGL working on a Windows VM and I can hack away at this to fix the issues... will report back

**Comment by banesullivan** [comment]
The issue just lies in the `close()` routine:

Screen Shot 2019-12-14 at 12 52 24 PM


Patching a fix in #502

**Pull request closed without merging**
