### PR TITLE
First try at smooth shading

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This is a follow-up to [#9](https://github.com/pyvista/pyvista-support/issues/9) as a attempt to add smooth shading for PolyData as a first step.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
When I try the following snippet:
```py
import pyvista as pv
import numpy as np
import vtk

sphereSource = vtk.vtkSphereSource()
sphereSource.SetThetaResolution(16)
sphereSource.SetPhiResolution(16)
sphereSource.Update()
mesh = sphereSource.GetOutput()

plotter = pv.Plotter()
plotter.add_mesh(mesh, color='grey')
plotter.show()
```
I obtain the following:

image

**Comment by GuillaumeFavelier** [comment]
But when I use the internal `Sphere` object with for example:
```py
import pyvista as pv
import numpy as np
import vtk

mesh = pv.Sphere()

plotter = pv.Plotter()
plotter.add_mesh(mesh, color='grey')
plotter.show()
```
Although the shading is smooth too, the interaction with the camera is slightly different, it's as if the light is moving too.

image

**Comment by akaszynski** [comment]
Good find with ``SetInterpolationToPhong``.  I agree it looks much better and would be a great addition to the code.  The camera issue is a problem though.

I've noticed this exact same problem when implementing lighting using ``vtkLightKit``.  When pre-calculated normals are present, the lights no longer track the camera, despite explicitly setting it in ``LightFollowCameraOn``.

Paraview has it figured out, and I'll look through their source for inspiration.

**Comment by akaszynski** [comment]
Figured it out!  The interpolation shading relies on normals being calculated and these aren't updated when the mesh is translated or rotated.  To fix this, recalculate the point normals:
```python
import pyvista as pv
import vtk

mesh = pv.Sphere(theta_resolution=10, phi_resolution=10)
mesh.compute_normals(cell_normals=False, inplace=True)

plotter = pv.Plotter()
plotter.add_mesh(mesh, color='grey', smooth_shading=True)
plotter.show()
```
You could add a hook to have the normals computed immediately prior to rendering when the not using flat shading to make sure this doesn't happen and the user doesn't have to manually compute normals.

**Comment by GuillaumeFavelier** [comment]
I'm not sure about the exact location for the hook so I put it just after the wrapping in the `add_mesh` function. Also, maybe there is a way to test if the normals are already computed or not?

**Comment by akaszynski** [comment]
That's a good spot for now.  We can change it down the line if we need it for animations.

You can check normals have been computed with:
```python
'Normals' in mesh.point_arrays
```

However, this won't tell you if normals need to be recomputed because the mesh has moved...

**Comment by akaszynski** [comment]
May I merge this?

**Comment by GuillaumeFavelier** [comment]
I modified the `requirements.txt` file to test Travis but it's okay for me if you wanna merge.

**Comment by akaszynski** [comment]
You're good to merge.  We can change it later if necessary.

**Pull request merged**
