### PR TITLE
Test label action from forks

### PR DESCRIPTION
**Pull request by akaszynski**
This PR simply tests if the label action works for PRs from forks.

### CODE REVIEW

**Comment by akaszynski** [comment]
@tkoyama010 and @adeak, this works from forks!

**Comment by adeak** [comment]
I don't see any labels, but as long as it works :smile:

**Comment by tkoyama010** [comment]
Great thanks.

**Comment by tkoyama010** [comment]
> I don't see any labels, but as long as it works 😄

@adeak  It is because this branch didn't hit any rule of labeling. It works fine.

**Pull request closed without merging**
