### PR TITLE
Switch default color to lightblue for document theme

### PR DESCRIPTION
**Pull request by banesullivan**
The default `tan` color for the document theme has fallen out of my favor and IMO looks dated -- it's time we freshen things up, and this times well with the defaule theme changing to be `Document` in #4516 

Some history: the original `tan` color was chosen somewhat arbitrarily in 4583baf and was first `orange` in a8e5a8b.

I'd appreciate feedback on this and suggestions for other, perhaps better default colors for the document theme. 

Maybe it makes sense to use Matplotlib's first color in their default cycler `#1f77b4`

| `tan` (`#D2B48C`) | `lightblue` (`#ADD8E6`) | MPL's default `#1f77b4` |
|---|---|---|
screenshot (28) | screenshot (29) | screenshot (30) |
|  screenshot (33) | screenshot (32) | screenshot (31) |
| screenshot (34) | screenshot (35) | screenshot (36) |

Personally, I think `lightblue` (`#ADD8E6`) looks the best all around. Not too light or washed out and not dark.

### CODE REVIEW

**Comment by akaszynski** [comment]
I also feel that `lightblue` looks the best, especially considering how these look with black edges.

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Review by adeak — APPROVED** [review]
Blue is always better 😁

**Comment by bjlittle** [comment]
FWIW I vote for light blue too 👍

**Comment by banesullivan** [comment]
Well alright! I didn't expect this to be embraced so enthusiastically and quickly... suppose I'm not the only one who was tired of `tan`

**Pull request merged**
