### PR TITLE
fix typos in example code

### PR DESCRIPTION
**Pull request by Spectre5**
### Overview
When browsing the examples online, I found some typos.  This is a simple PR to fix some typos in the examples.

### Details

- all changes are in comments

### CODE REVIEW

**Review by akaszynski — APPROVED** [review]
That's a ton of mistakes you found.  Thanks!  We rely on `codespell` to identify spelling errors in our code, but clearly it still misses quite a bit.

Thanks for your contribution!

**Comment by banesullivan** [comment]
We should try to add these to the codespell dictionary. @Spectre5, would you be up for trying that? It is rather easy.

See https://github.com/codespell-project/codespell#sending-pull-requests

**Comment by Spectre5** [comment]
Ya I can do it.  I assume you want me to submit these to the actual codespell repo, not start a new custom dictionary for pyvista?

**Comment by akaszynski** [comment]
> I assume you want me to submit these to the actual codespell repo, not start a new custom dictionary for pyvista?

Exactly.  That way everyone can benefit.

**Pull request merged**
