### PR TITLE
removed _add_row_array

### PR DESCRIPTION
**Pull request by Chaitu-Tatipamula**

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]
LGTM. Thanks!

**Comment by Chaitu-Tatipamula** [comment]
> LGTM. Thanks!

is that done this process was quite confusing

**Comment by tkoyama010** [comment]
Yes. Perfect. Thank you for your contribution. I will merge to the main branch and this work is complete.

**Comment by Chaitu-Tatipamula** [comment]
> Yes. Perfect. Thank you for your contribution. I will merge to the main branch and this work is complete.

Oo thanks 😀

**Pull request merged**
