### PR TITLE
Optionally run osmnx-example

### PR DESCRIPTION
**Pull request by banesullivan**
Potential solution to #1791

cc @adam-grant-hendry

Note: I am having issues building the docs locally so I can't really test this

### CODE REVIEW

**Comment by akaszynski** [comment]
I agree with this change.

**Comment by MatthewFlamm** [comment]
What it be better, or perhaps a separate issue, to have a flag that runs all non-standard examples?  For example the gltf examples require external internet connection to build the docs, which throws errors when I try to build.

**Comment by banesullivan** [comment]
> For example the gltf examples require external internet connection to build the docs, which throws errors when I try to build.

All examples that use `examples.download_*()` need an internet connection unless you have the data cached

**Comment by MatthewFlamm** [comment]
We added the ability to use a local vtk-data repository.  But some examples use other data stores, which makes maintaining a local version extremely tedious.

**Review by akaszynski — APPROVED** [review]
LGTM. Merging to clean up stale PRs.

**Comment by akaszynski** [comment]
Pinging @banesullivan to merge.

**Pull request merged**
