### PR TITLE
Enable status bars for the glyph filter

### PR DESCRIPTION
**Pull request by banesullivan**
The glyph filter has a reputation for taking a long time... this enables a bit more transparency to what it's up to. (Typically its the clean operation that will take a while...)

### CODE REVIEW

**Comment by banesullivan** [comment]
I don't think this actually works...

**Comment by akaszynski** [comment]
Seems to work.
```python
import vtk
import numpy as np
import pyvista as pv
from pyvista import examples

mesh = pv.PolyData(np.random.random((100000, 3))*1000)

source = vtk.vtkSphereSource()
source.Update()
geom = source.GetOutput()

glyphed = mesh.glyph(geom=geom, progress_bar=True)
```

```
Cleaning: 100%|███████████████████████████████████████████████████████████[00:00<00:00]
Computing Glyphs: 100%|███████████████████████████████████████████████████[00:00<00:00]
```

PyVista_188

**Comment by akaszynski** [comment]
Progress bar genuinely moves during the glyphing, though I had to make the "star field" quite dense to get it to actually need the progress bar.

**Comment by banesullivan** [comment]
Ah, thanks for testing this... I was having weird issues with the status bar going from 0 to 100 the other day without updating.

This “star field” is really cool btw

**Comment by akaszynski** [comment]
> This “star field” is really cool btw

Had fun with that one.  I wanted to make a quick video/gif following the camera angle.  It would be super cool if we could "record" the camera angle and then replay that.  We could accomplish this by starting a thread that records the camera position at various timesteps and then creates another video, or perhaps a "watch" feature that simply saves frames every timestep until the user closes out the plotter.

Perhaps `record(filename, timestep)`?  That way you don't need an external recorder to save gifs.

**Comment by akaszynski** [comment]
Also could include a "press r to start recording" so the user could setup the camera angle.

Actually, this is something I'd really make use of...

**Comment by banesullivan** [comment]
Agreed. That would be incredibly useful and I can help implement this.

**Pull request merged**
