### PR TITLE
Release 0.37.0

### PR DESCRIPTION
**Pull request by akaszynski**
### Release 0.37.0

- [ ] Bump main to `0.38.dev0` (this PR)
- [ ] Keep this branch (`release/0.37`) and update the version to `0.37.0`. And commit the change to this branch.
- [ ] Tag `v0.37.0` and push the tag.
- [ ] Update the conda-forge build.

---

### Breaking Changes
* Make MultiBlock meshes MutableSequence with some dict-like features for setting and getting. by @MatthewFlamm in https://github.com/pyvista/pyvista/pull/3031
* Lessen memory usage for wrapping vtk datasets by @MatthewFlamm in https://github.com/pyvista/pyvista/pull/3179
* Pyvista -> PyVista by @banesullivan in https://github.com/pyvista/pyvista/pull/3231
* Add area to DataSet and make pointgrid volume exact by @MatthewFlamm in https://github.com/pyvista/pyvista/pull/3160

### New Features
* Add separate cells feature by @akaszynski in https://github.com/pyvista/pyvista/pull/3112
* Add example datasets by @akaszynski in https://github.com/pyvista/pyvista/pull/3127
* Support complex64 and save complex data by @akaszynski in https://github.com/pyvista/pyvista/pull/3105
* Add various grid filters by @akaszynski in https://github.com/pyvista/pyvista/pull/3110
* Add composite dataset mapper by @akaszynski in https://github.com/pyvista/pyvista/pull/2941
* Expose triangle strips (polystrips) in API by @AlejandroFernandezLuces in https://github.com/pyvista/pyvista/pull/3208
* Expose more options of `MultiBlockPlot3DReader` (`vtkMultiBlockPlot3DReader`) by @whophil in https://github.com/pyvista/pyvista/pull/3150
* Improve pass rendering by @akaszynski in https://github.com/pyvista/pyvista/pull/2948
* Add CellType enumerate class by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3115
* Add linear cells example by @akaszynski in https://github.com/pyvista/pyvista/pull/3259
* Pickle DataObjects with XML readers/writers by @whophil in https://github.com/pyvista/pyvista/pull/3286
* Add support for NIFTI files with .nii and .nii.gz extensions. by @jmargeta in https://github.com/pyvista/pyvista/pull/3284
* Add extent to extract_geometry filter by @banesullivan in https://github.com/pyvista/pyvista/pull/3256
* Rename method: overwrite -> copy_from by @banesullivan in https://github.com/pyvista/pyvista/pull/3230
* 3D Celestial Bodies (planet3D) by @tkoyama010 in https://github.com/pyvista/pyvista/pull/2994
* Wrap the lookup table by @akaszynski in https://github.com/pyvista/pyvista/pull/3336
* Add lookup table opacity by @akaszynski in https://github.com/pyvista/pyvista/pull/3390
* Use pooch by @akaszynski in https://github.com/pyvista/pyvista/pull/3218
* add use all points to the extract edges filter by @akaszynski in https://github.com/pyvista/pyvista/pull/3409
* Add new type to add_point_scalar_labels by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3408
* Add support for backface properties by @adeak in https://github.com/pyvista/pyvista/pull/3135
* Add other views to `Camera.tight` by @MatthewFlamm in https://github.com/pyvista/pyvista/pull/3391
* pythreejs: support surface mesh front/back face culling by @darikg in https://github.com/pyvista/pyvista/pull/2983
* implement gaussian_points representation style by @banesullivan in https://github.com/pyvista/pyvista/pull/2898
* Add simple ellipse to available geometric objects by @chadqueen in https://github.com/pyvista/pyvista/pull/3461
* Add slice_implicit filter for slicing with arbitrary implicit functions: spheres, cylinders, etc by @banesullivan in https://github.com/pyvista/pyvista/pull/3516

### Bug fixes or behavior changes
* Remove vtk requirement by @akaszynski in https://github.com/pyvista/pyvista/pull/3117
* warn invalid texture dtype by @akaszynski in https://github.com/pyvista/pyvista/pull/3129
* Report number of scalars instead of size in error about scalars shape mismatch by @adeak in https://github.com/pyvista/pyvista/pull/3124
* Skip flaky windows test by @akaszynski in https://github.com/pyvista/pyvista/pull/3133
* Fix rectilinear X coordinates int edge case by @akaszynski in https://github.com/pyvista/pyvista/pull/3109
* Fix filesystem races caused by pyvista.examples.downloads by @lukaszmoroz in https://github.com/pyvista/pyvista/pull/3146
* More descriptive error message when no geodesic path exists between vertices on a mesh by @p-j-smith in https://github.com/pyvista/pyvista/pull/3155
* fix(add_volume): use memory-efficient rescaling by @adam-grant-hendry in https://github.com/pyvista/pyvista/pull/3170
* update for ipywidgets 8.0 by @akaszynski in https://github.com/pyvista/pyvista/pull/3183
* hotfix Pyvista --> PyVista by @akaszynski in https://github.com/pyvista/pyvista/pull/3247
* BUG: Provide default for renderer.enable_anti_aliasing by @larsoner in https://github.com/pyvista/pyvista/pull/3254
* Update vtkThreshold API usage by @banesullivan in https://github.com/pyvista/pyvista/pull/2881
* Prevent warning in polystrips example coming from extrude by @adeak in https://github.com/pyvista/pyvista/pull/3266
* Fix Plotter garbage collection by @akaszynski in https://github.com/pyvista/pyvista/pull/3245
* set active scalars to be visible in collision example by @banesullivan in https://github.com/pyvista/pyvista/pull/3287
* fix wireframe color by @akaszynski in https://github.com/pyvista/pyvista/pull/3296
* [HOTFIX] Interactive plotter callback errors by @rodrigomologni in https://github.com/pyvista/pyvista/pull/3310
* FIX: Wrap vtkPointSet by @MatthewFlamm in https://github.com/pyvista/pyvista/pull/3311
* Fix planet download deprecation messages by @adeak in https://github.com/pyvista/pyvista/pull/3372
* Fix the error of fmt in add_point_scalar_labels method. by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3399
* Minor cleanup of lookup table opacity by @adeak in https://github.com/pyvista/pyvista/pull/3402
* Triangulate for voxelization to prevent some artifacts by @adeak in https://github.com/pyvista/pyvista/pull/3361
* Pass kwargs to create_axes_marker by @Abhijnan-Bajpai in https://github.com/pyvista/pyvista/pull/3421
* Fix error message in `set_active_time_value` by @MatthewFlamm in https://github.com/pyvista/pyvista/pull/3449
* remove unused arg by @akaszynski in https://github.com/pyvista/pyvista/pull/3456
* Set stereo type before turning on stereo by @adeak in https://github.com/pyvista/pyvista/pull/3462
* Patch default scalars plotting edge case by @akaszynski in https://github.com/pyvista/pyvista/pull/3512
* Fix issues with cell picking by @banesullivan in https://github.com/pyvista/pyvista/pull/3515

### Documentation
* Automated PR: Update Local Intersphinx by @github-actions in https://github.com/pyvista/pyvista/pull/3111
* Distance along spline example by @akaszynski in https://github.com/pyvista/pyvista/pull/3131
* Add tetra to the unstructured grid example by @akaszynski in https://github.com/pyvista/pyvista/pull/3101
* Fix small typo by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3136
* Correct vtk-data url in _download_file docstring by @PuffinDev in https://github.com/pyvista/pyvista/pull/3138
* fix clean example by @darikg in https://github.com/pyvista/pyvista/pull/3177
* Speed up documentation build by @akaszynski in https://github.com/pyvista/pyvista/pull/3168
* Typo fix by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3191
* Typo fix by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3204
* Fix the error of pip option by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3209
* Add linkcheck periodically by @laysauchoa in https://github.com/pyvista/pyvista/pull/3166
* Extend cell-center example with edges by @akaszynski in https://github.com/pyvista/pyvista/pull/3199
* Bump pydata-sphinx-theme from 0.9.0 to 0.10.1 and fix warnings by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3238
* Automated PR: Update Local Intersphinx by @github-actions in https://github.com/pyvista/pyvista/pull/3250
* Add the example of "Add labels to cells" by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3264
* Use stable version python for intersphinx links by @MatthewFlamm in https://github.com/pyvista/pyvista/pull/3285
* Add PyViewFactor to Connections by @banesullivan in https://github.com/pyvista/pyvista/pull/3295
* Move utility methods out of core subpackage by @banesullivan in https://github.com/pyvista/pyvista/pull/3321
* Create Mapper and Actor classes by @akaszynski in https://github.com/pyvista/pyvista/pull/3332
* Fix typo by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3341
* Automated PR: Update Local Intersphinx by @github-actions in https://github.com/pyvista/pyvista/pull/3394
* Fix typo by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3397
* Delete sidebar-nav-bs.html by @akaszynski in https://github.com/pyvista/pyvista/pull/3410
* Fix the format of document by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3419
* Add constrained triangulation example by @akaszynski in https://github.com/pyvista/pyvista/pull/3448
* fix dataset mapper copy docstring by @akaszynski in https://github.com/pyvista/pyvista/pull/3455
* Improve main landing page by @akaszynski in https://github.com/pyvista/pyvista/pull/3459
* Fix small typo by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3464
* Specify all optional parameters in #3347 by @puripant in https://github.com/pyvista/pyvista/pull/3457
* Quick spelling fix by @akaszynski in https://github.com/pyvista/pyvista/pull/3507
* Small fix of the docstring by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3500\
* Polyhedron examples and unit test by @AlejandroFernandezLuces in https://github.com/pyvista/pyvista/pull/3521
* Update CONTRIBUTING.rst with docstring guidelines by @akaszynski in https://github.com/pyvista/pyvista/pull/3472

### Maintenance PRs

* Render window refactor by @akaszynski in https://github.com/pyvista/pyvista/pull/2964
* Use the latest test env by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3130
* Add typing_extensions install dependency for Python < 3.8 by @adeak in https://github.com/pyvista/pyvista/pull/3156
* Fix issue template typo and code placeholders by @adeak in https://github.com/pyvista/pyvista/pull/3140
* disable caching of build directory by @akaszynski in https://github.com/pyvista/pyvista/pull/3162
* Use Mamba to speed up the conda build by @akaszynski in https://github.com/pyvista/pyvista/pull/3163
* Define pytest markers for skipping tests based on vtk version by @adeak in https://github.com/pyvista/pyvista/pull/3167
* Small fix of indent by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3182
* MAINT: More descriptive comment about optional import by @whophil in https://github.com/pyvista/pyvista/pull/3200
* Update flake8 URL for precommit by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3229
* CI: Workflow to test downstream packages starting with MNE by @larsoner in https://github.com/pyvista/pyvista/pull/3255
* Clean up CI job conditions to prevent PRs on forks by @banesullivan in https://github.com/pyvista/pyvista/pull/3291
* use apt-pkgs v1.1.1 by @akaszynski in https://github.com/pyvista/pyvista/pull/3300
* Remove .codeclimate.yml by @banesullivan in https://github.com/pyvista/pyvista/pull/3327
* Use PyVista start headless display action by @akaszynski in https://github.com/pyvista/pyvista/pull/3393
* Improve PointSet class testing by @sgaist in https://github.com/pyvista/pyvista/pull/3395
* Migrating from sphinx-panels to sphinx-design by @tkoyama010 in https://github.com/pyvista/pyvista/pull/3159
* Add force_float test (pyvista#3333) by @sgaist in https://github.com/pyvista/pyvista/pull/3396
* Remove pip cache in docker-package.yml by @akaszynski in https://github.com/pyvista/pyvista/pull/3424
* Add fixture for verify_image_cache by @MatthewFlamm in https://github.com/pyvista/pyvista/pull/3454
* [maint] update conda environment by @banesullivan in https://github.com/pyvista/pyvista/pull/3329

## New Contributors
* @PuffinDev made their first contribution in https://github.com/pyvista/pyvista/pull/3138
* @lukaszmoroz made their first contribution in https://github.com/pyvista/pyvista/pull/3146
* @laysauchoa made their first contribution in https://github.com/pyvista/pyvista/pull/3166
* @AlejandroFernandezLuces made their first contribution in https://github.com/pyvista/pyvista/pull/3208
* @sgaist made their first contribution in https://github.com/pyvista/pyvista/pull/3395
* @Abhijnan-Bajpai made their first contribution in https://github.com/pyvista/pyvista/pull/3421
* @andrewrgarcia made their first contribution in https://github.com/pyvista/pyvista/pull/3452
* @chadqueen made their first contribution in https://github.com/pyvista/pyvista/pull/3461

### CODE REVIEW

**Comment by adeak** [comment]
Shouldn't the title be
> Release 0.37.0
?

**Comment by akaszynski** [comment]
> Shouldn't the title be
> 
> > Release 0.37.0
> 
> ? And is there a release notes preview somewhere?

Correct on both accounts:
- Title has been corrected.
- Release notes preview has been generated. The trick to do this is to create a [new release](https://github.com/pyvista/pyvista/releases/new), specify a new temporary tag, and generate the release notes relative to the last minor release (in this case, `v0.36.0`).

**Comment by adeak** [comment]
Some thoughts after perusing the release notes draft (thanks!):
1. In https://github.com/pyvista/pyvista/pull/3230 we deprecated `overwrite`, it's still available but raises a warning. Do I understand correctly that we should only mark it as "breaking change" when we decide to remove this entirely?
2. I was going to point out that in https://github.com/pyvista/pyvista/pull/3160 we changed pointgrid volume calculation to be _better_ (different algorithm, seems to be faster, and more exact). And I was going to ask if we should note somewhere that the exact values from the filter will silently change. But now that I'm looking at the diff again it's not clear to me where this supposed change in behaviour is coming from...
3. Regarding the release notes preview in the PR comment: not a huge deal, but the folded "maintenance" section has broken markdown. Will the final release notes have the same format, and if yes, can we fix it?
4. Still regarding the release notes: there's a tiny, folded "Details" section at the bottom, which actually hides the "New Contributors" list. It would be nice to have this unfolded by default to praise our newcomers :)

**Comment by akaszynski** [comment]
> Still regarding the release notes: there's a tiny, folded "Details" section at the bottom, which actually hides the "New Contributors" list. It would be nice to have this unfolded by default to praise our newcomers :)

Good catch. This was only mean to hide dependabot PRs from taking all the credit.

**Comment by akaszynski** [comment]
> Regarding the release notes preview in the PR comment: not a huge deal, but the folded "maintenance" section has broken markdown. Will the final release notes have the same format, and if yes, can we fix it?

Fixed as well.

**Comment by adeak** [comment]
> > Regarding the release notes preview in the PR comment: not a huge deal, but the folded "maintenance" section has broken markdown. Will the final release notes have the same format, and if yes, can we fix it?
> 
> Fixed as well.

Thanks! It would be nice if at one point in the future we could factor out dependabot and similar auto-PRs specifically for hiding. Now we have stuff like https://github.com/pyvista/pyvista/pull/2964 (which is a fairly major refactor) and https://github.com/pyvista/pyvista/pull/3396 (which is the PR of a new contributor) which are indeed "maintenance" but would be nice to see directly in the release notes.

**Comment by adeak** [comment]
Actually, one more: https://github.com/pyvista/pyvista/pull/3521 is also from a new contributor, but it also adds a gallery example so we should file it with "Documentation".

**Comment by akaszynski** [comment]
> Do I understand correctly that we should only mark it as "breaking change" when we decide to remove this entirely?

After reading through https://github.com/pyvista/pyvista/issues/3032, I don't think we specified what a breaking change was. There's a continuum of definitions from [everything](https://xkcd.com/1172/), to the narrower definition of "[potentially causes other components to fail](https://en.wiktionary.org/wiki/breaking_change)". I'd say anything that we can't make backwards compatible without a least a warning (e.g. #3431), is a "breaking change", like changing the Python `print` statement from 2 to 3.

Yes we should document it. No, not this release.

**Comment by akaszynski** [comment]
> Thanks! It would be nice if at one point in the future we could factor out dependabot and similar auto-PRs specifically for hiding. Now we have stuff like #2964 (which is a fairly major refactor) and #3396 (which is the PR of a new contributor) which are indeed "maintenance" but would be nice to see directly in the release notes.

We should probably just ignore `dependabot` and `github-actions` in future release notes (if possible) in `release.yml`. I've deleted them here since many maintenance PRs are helpful.

**Comment by akaszynski** [comment]
Only remaining item is:

> I was going to point out that in Add area to DataSet and make pointgrid volume exact #3160 we changed pointgrid volume calculation to be better (different algorithm, seems to be faster, and more exact). And I was going to ask if we should note somewhere that the exact values from the filter will silently change. But now that I'm looking at the diff again it's not clear to me where this supposed change in behaviour is coming from... (cc @MatthewFlamm)

I'm not going to block the release for it, but we might want to point this out somewhere.

**Review by adeak — APPROVED** [review]
Approving pending potential action regarding https://github.com/pyvista/pyvista/pull/3160. Thanks for the quick adjustments @akaszynski!

**Comment by akaszynski** [comment]
> Approving pending potential action regarding #3160. Thanks for the quick adjustments @akaszynski!

After some sleuthing, made a note [here](https://github.com/pyvista/pyvista/pull/3160#issuecomment-1299345756). Forgot that @MatthewFlamm did this and it's a good fix.

**Comment by MatthewFlamm** [comment]
> But now that I'm looking at the diff again it's not clear to me where this supposed change in behaviour is coming from...

I view the changes in #3160 as fixing a bug although I agree it is on the continuum of a breaking change.  If the user wants the volume for those data types, it now provides the exact volume rather than an approximate volume.

The change occurred by removing the overriding method that used the approximate volume.

**Comment by adeak** [comment]
Thank you both!

**Pull request merged**
