### PR TITLE
Move example dataset fixtures to conftest.py

### PR DESCRIPTION
**Pull request by JevinJ**
### Overview

Pytest requires fixtures available to all testing files to be in a file called conftest.py, this moves the example dataset fixtures in test_common.py to conftest.py.

### CODE REVIEW

**Comment by akaszynski** [comment]
I think we should only move fixtures that need to be accessed across multiple tests to `conftest.py`

**Comment by JevinJ** [comment]
Good point, I'll just move the example fixtures for now.

**Comment by akaszynski** [comment]
You should be able to squash and merge this at your convenience.  Let me know if you can't.

**Comment by JevinJ** [comment]
@akaszynski Says I'm not authorized.

**Comment by akaszynski** [comment]
Please message me on slack when you get a chance.

**Pull request merged**
