### PR TITLE
Fix `mypy` errors which is raised by running mypy pyvista

### PR DESCRIPTION
**Pull request by user27182**
Fix some of the errors and notes reported in #5563. 
Running `mypy pyvista` with this PR reports 134 errors, down from 144.

### CODE REVIEW

**Comment by user27182** [comment]
To be clear, the errors were fixed manually. I ran `mypy pyvista`, looked through the list of generated errors, and fixed a few of them.

**Comment by tkoyama010** [comment]
Thanks, I have reflected it in the title.

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Review by tkoyama010 — APPROVED** [review]

**Pull request merged**
