### PR TITLE
Add MacOS CI

### PR DESCRIPTION
**Pull request by akaszynski**
This PR adds MacOS testing to Azure pipelines as requested/suggested by @GuillaumeFavelier.

### CODE REVIEW

**Comment by akaszynski** [comment]
@banesullivan, there are two tests that fail because we're not properly rendering on macOS.  `pyvista` says plotting is supported, but I'm not actually sure what's going on since image sizes from the image filter are zero.

As I don't have a mac handy, it's difficult to test out installing a headless server locally.  Have any idea how to do this?

@GuillaumeFavelier, for the time being should we skip these two tests when on mac, or wait until we've figured out the headless server?

**Comment by GuillaumeFavelier** [comment]
I would prefer to wait until we understand what's going on but if this takes very long, it can become a blocker for https://github.com/pyvista/pyvista/pull/619

Did you try this test with `off_screen=False`?

I'll see what I can do about it tomorrow.

**Comment by akaszynski** [comment]
Tried your suggestions in bd33b76c06b6d2662d859fd6f22c3a61b118b38c, but sadly it didn't work.  Setting up a headless server for MacOS on Azure doesn't seem straightforward, and that's probably what we need to cover these two tests.

I'm traveling tomorrow and won't be able to help until Friday.

**Comment by GuillaumeFavelier** [comment]
I asked help from my colleague @gzanitti which uses macOS and this patch fbe3518 did the trick for us. Let's see how the CIs react

**Comment by GuillaumeFavelier** [comment]
What do you think @pyvista/developers?

**Comment by akaszynski** [comment]
Nice job @GuillaumeFavelier and @gzanitti!  I'm going to add back in the other tests and then merge once someone approves this.  I've disabled the CI on other OSes and need to add those back in again.

**Pull request merged**
