### PR TITLE
Add built-in datasets to the Dataset Gallery

### PR DESCRIPTION
**Pull request by user27182**
Follow-up from #5822. The changes from that branch were first patched into this one before adding new commits for this PR.

This PR:

- Refactors the dataset loading mechanism for built-in datasets in `pyvista.examples.examples`. This is similar to what was done in #5787.
- Adds a new 'Built-in' carousel to the Dataset Gallery for browsing the 18 built-in datasets
- Adds a new explicit structured grid carousel (made possible since there is exactly one such dataset built-in)
- Updates the `dataset_loader` module and classes. Most notably, most classes are renamed for clarity and there is some restructuring to accommodate a new use-case for built-in datasets where a dataset is loaded without a file.
- Uses the build images directly, eliminating the need to store local copies in the repo

### CODE REVIEW

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by tkoyama010** [comment]
Please wait until #5822 is merged.

**Comment by tkoyama010** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
https://github.com/pyvista/pyvista/pull/5872/commits/8d946d5c62683f43e60bcb2a940dec66de698118 attempts to address https://github.com/pyvista/pyvista/pull/5822#issuecomment-2041953301

**Comment by tkoyama010** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Review by tkoyama010 — DISMISSED** [review]

**Comment by user27182** [comment]
Needed a few minor changes, should be good now, I'll review the docs one final time after it succeeds

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
LGTM.

Still trying to fix the field formatting when the value doesn't fit on one line, e.g. the explicit structured grid data type should look like this, with the type aligned on the right. Hopefully fixed with [522fd30](https://github.com/pyvista/pyvista/pull/5872/commits/522fd303140b60f5df874529ea20c74f45019225) but if not I'll try to fix it in a later PR
image

**Comment by user27182** [comment]
@pyvista-bot preview

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Pull request merged**
