### PR TITLE
Add new docs section with file and dataset metadata for examples in `downloads.py`

### LINKED ISSUE #5784: Add file and instance metadata to documentation for meshes in `pyvista.examples`
### Describe the feature you would like to be added.

There are hundreds of meshes available for use and/or download in `pyvista.examples`. However, when trying to find a specific kind of mesh to use for testing, generating documentation, or experimentation, it's difficult to know which mesh may be suitable for the task. E.g. perhaps a point cloud or surface mesh is needed, either with many points/cells or with few. Maybe several image volumes are needed, or maybe 2D images for textures. It's also helpful to know if the example includes array data. Since some downloadable meshes may be hundreds of MB in size, it would be helpful to know the file size beforehand.

Ideally, this feature would:

- Add file info to the documentation (e.g. file extension, file size)
- Add mesh instance info to the documentation (e.g. mesh type, num cells, num points, num arrays)
- Summarize this info in a single table for easy lookup/reference (instead of inside individual docstrings)
- BONUS: Add a small preview image of the example in the table

### Links to VTK Documentation, Examples, or Class Definitions.

A custom table could be generated using similar code in [make_tables.py](https://github.com/pyvista/pyvista/blob/3068f5c54de10da55fa16824939666c60bf7f844/doc/source/make_tables.py#L5), for example, which is already used to generate the [Color scheme table](https://docs.pyvista.org/version/stable/api/plotting/charts/plot_color_schemes.html#id1)

### Pseudocode or Screenshots

_No response_

### PR DESCRIPTION
**Pull request by user27182**
### Overview

Follow up from #5787 (this is directly branched from that PR). Resolves #5784. 

TODO:

- [x] Add rst files to publish docs
- [ ] Fix any table formatting issues
- [x] Improve preview images (e.g. use camera.tight)

Preview of new documentation:
image
Link to full metadata page:
https://65feb528fe5188e96875a0f9--meek-duckanoo-d2f5ec.netlify.app/api/examples/metadata

### CODE REVIEW

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by tkoyama010** [comment]
This is a masterpiece! Thank you so much.
https://65feb528fe5188e96875a0f9--meek-duckanoo-d2f5ec.netlify.app/api/examples/metadata

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
Almost finished with the formatting... check out the latest version. The cards and grid layouts looks great on mobile and auto-adjust the content to fit the screen nicely:

image
image

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by tkoyama010** [comment]
> https://github.com/pyvista/pyvista/pull/5818 introduced too many breaking changes to this PR which I am unable to recover from. Closing in favour of #5822.

Sorry. I didn't notice that. Thank you for opening new PR.

**Comment by user27182** [comment]
> > #5818 introduced too many breaking changes to this PR which I am unable to recover from. Closing in favour of #5822.
> 
> Sorry. I didn't notice that. Thank you for opening new PR.

It's ok. I think it would have been fine if the CI checks allowed me to continue without first merging. But, once #5818 was merged I was required to resolve any merge conflicts that were created before the CI checks could continue to run. So, I felt forced to merge even though I was mid-way through adding new features that still needed to be tested.

Compounding the issue is that the dataset loaders were written with the fundamental assumption that paths were strings, not Path objects, and a lot of the code here was modified since #5787, so resolving the merge was a disaster. For #5822 I patched in any work from here and simply added `noqa` for now to ignore the `PTH` errors from `ruff`.

**Pull request closed without merging**
