### PR TITLE
Fix 32bit Python ID type issue on windows

### LINKED ISSUE #16: numpy type check failure
When running the demo for advanced numpy plotting from the docs http://vtkinterface.readthedocs.io/en/latest/index.html

I get the following error:
  File "C:\Users\aniranjan\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\vtkInterface\plotting.py", line 1090, in AddArrows
    pdata = vtkInterface.CreateVectorPolyData(cent, direction * mag)
  File "C:\Users\aniranjan\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\vtkInterface\utilities.py", line 138, in CreateVectorPolyData
    vcells.SetCells(npts, numpy_to_vtkIdTypeArray(cells, deep=True))
  File "C:\Users\aniranjan\AppData\Local\Continuum\anaconda3\envs\py35\lib\site-packages\vtk\util\numpy_support.py", line 192, in numpy_to_vtkIdTypeArray
    'Expecting a numpy.int32 array, got %s instead.' % (str(dtype)))
ValueError: Expecting a numpy.int32 array, got int64 instead.

The issue appears to be in numpy_to_vtkIdTypeArray(), or at least how it's called in AddArrows()->CreateVectorPolyData()->vtk.vtkCellArray().SetCells()

### PR DESCRIPTION
**Pull request by banesullivan**
Resolve #16 

@kinverarity1 - would you be able to check if this fixes your issue locally?

@akaszynski - does this seem implemented correctly? It could have major implications if not done correctly, so I'm a bit nervous to merge this without someone double-checking

### CODE REVIEW

**Comment by banesullivan** [comment]
Tests are failing because of https://github.com/pyvista/pyvista/pull/309#issuecomment-513002633

**Comment by kinverarity1** [comment]
@banesullivan Yes this PR fixes it for my system (32-bit python on a 64-bit Windows machine). Thank you.

Does it have something to do with vtk giving you the OS size of int vs the Python size of int? Is it possible to test this scenario on an OS other than Windows?

**Comment by banesullivan** [comment]
> Does it have something to do with vtk giving you the OS size of int vs the Python size of int?

I think that's it

> Is it possible to test this scenario on an OS other than Windows?

I'm not sure... I never run into these issues on Mac/Linux. Maybe we could specify a 32bit vs 64bit Python build on Travis? Is this possible?

**Comment by banesullivan** [comment]
Update - from some quick googling, it seems Travis has no plans to support 32bit systems

**Comment by banesullivan** [comment]
I added 32bit Python tests on AppVeyor for Windows and its passing

**Pull request merged**
