### PR TITLE
Add `compute_line_length` to `PolyData` class

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

Follow up in #5044.

### Details

- None

### CODE REVIEW

**Comment by tkoyama010** [comment]
@pyvista-bot preview

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
@pyvista-bot preview

**Comment by MatthewFlamm** [comment]
What is the use case here?  A `DataSet` already has `length` which is the length of the bounding box.  We can get the length of each 1D cell using `compute_cell_sizes`. This isn't actually a `line_length` but the distance between two points. This feels more like a user routine if they need to determine the distance between various points, which could be an example.

**Comment by tkoyama010** [comment]
> What is the use case here? A `DataSet` already has `length` which is the length of the bounding box. We can get the length of each 1D cell using `compute_cell_sizes`. This PR isn't actually a `line_length` but the distance between two points. This feels more like a user routine if they need to determine the distance between various points, which could be an example.

Thanks for the feedback. After some cool thinking, I found that this method can be easily written as follows.
```python
np.linalg.norm(self.points(start_vertex) - self.points(end_vertex))
```
I added this method for the calculations in #5044, but this method is redundant clearly. I will close this proposal.

**Pull request closed without merging**
