### PR TITLE
🎉 HAPPY NEW YEAR 2020 🎉

### PR DESCRIPTION
**Pull request by tkoyama010**
:tada: HAPPY NEW YEAR 2020 :tada: . I updated the year of LICENSE to 2020.

### CODE REVIEW

**Comment by banesullivan** [comment]
We also need to update the copyright in the `conf.py`: https://github.com/pyvista/pyvista/blob/2ea63d5e9dff54991801f99a4a3872f48e938066/docs/conf.py#L55

**Comment by banesullivan** [comment]
Perhaps in the conf, we could change that to use `datetime` to fetch the current year? @tkoyama010, would you be for implementing that?

**Comment by banesullivan** [comment]
Here is an example:

https://github.com/fatiando/verde/blob/master/doc/conf.py#L82-L84

```py
import datetime
year = datetime.date.today().year
copyright = '2017-{}, The PyVista Developers'.format(year)
```

**Comment by tkoyama010** [comment]
@banesullivan Thank you for your review :+1:

**Comment by tkoyama010** [comment]
I couldn't reproduced travis error in my environment :confused:  Do anyone have idea :question:

**Comment by banesullivan** [comment]
Thanks @tkoyama010!

**Pull request merged**
