### PR TITLE
release/0.30

### PR DESCRIPTION
**Pull request by akaszynski**
### Release 0.30

We've added several features and master has diverged enough from 0.29 that it's time for a release.  Support for `jupyterlab` is a growing concern, and I think we can expand our user base with features like:
https://dev.pyvista.org/jupyter/index.html

There's a release candidate out on pypi, which can be installed with:
```
pip install pyvista==0.30.0rc1
```

This was created to allow early testing, but also in support of #1256.

---
### Remaining Issues

We still have a ton of issues to work on, and I'm like to setup a milestone so we can fix a few of these before finalizing the release.  Please post here if there are any issues here the @pyvista/collaborators or @pyvista/developers feel we need to work on.  Please add to the 0.30 milestone or post it here.

### CODE REVIEW

**Comment by adeak** [comment]
I've noted this in slack: the current master (so this release too) seems to break current pyvistaqt:
```py
>>> import pyvistaqt
>>> pyvistaqt.BackgroundPlotter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/pyvistaqt/pyvistaqt/plotting.py", line 491, in __init__
    super(BackgroundPlotter, self).__init__(
  File "/home/user/pyvistaqt/pyvistaqt/plotting.py", line 254, in __init__
    self._add_observer("KeyPressEvent", self.key_press_event)
  File "/home/user/tmp_test_env/lib/python3.8/site-packages/vtkmodules/qt/QVTKRenderWindowInteractor.py", line 335, in __getattr__
    raise AttributeError(self.__class__.__name__ +
AttributeError: BackgroundPlotter has no attribute named _add_observer
```
If this is not just some fluke on my side (I can't see what I'm doing wrong) this definitely has to be fixed with a pyvistaqt release.

The problem is that I see the same thing with pypi-installed `pyvista==0.29.0` and `pyvistaqt==0.3.0` releases.

**Comment by akaszynski** [comment]
image

**Comment by akaszynski** [comment]
> I've noted this in slack: the current master (so this release too) seems to break current pyvistaqt:

@GuillaumeFavelier, looks like I broke this on #1254 with the usage of ``pyvista.plotting.RenderWindowInteractor``.  Is this a change you can work with for 0.30, or do we need to fix something on our end?  You could just add `_add_observer` on your side.

Also, since we now create a window interactor by default, can we move that to `BasePlotter` and then you don't have to bother with creating the render interactor?  We moved to create the interactor by default a while back.

**Comment by adeak** [comment]
OK, I only thought it was broken in the last release because I was inside the pyvista repo when I tested it :sweat_smile:

**Comment by GuillaumeFavelier** [comment]
> You could just add _add_observer on your side.

Good idea @akaszynski ! We won't have all the benefits of `RenderWindowInteractor` for now but it's a good enough workaround in my opinion :+1:

**Comment by akaszynski** [comment]
> If you think something like that is feasible, I could open the PR and take care of checking the compatibility between packages.

Thanks for taking care of this @GuillaumeFavelier.

**Pull request merged**
