### PR TITLE
Remove `mypy` from pre-commit

### PR DESCRIPTION
**Pull request by user27182**
### Overview

Part of #6279. We have two mypy configs and the pre-commit version is causing problems since we can't install the necessary dependencies (e.g. VTK), see https://github.com/pyvista/pyvista/issues/6279#issuecomment-2181326986 and #6368.

I propose:
1. Dropping `mypy` from `pre-commit` entirely (this PR)
2. Use a GitHub workflow for running `mypy` instead (#6738)
3. ~Since the workflow generates a number of dependency-related errors, we can ignore these errors first (for now) i.e. merge #6739 and #6740, in order to separate config changes from the ignores.~

This should allow us to complete the changeover now and prevent more type errors from being introduced. This means devs will need to run `mypy pyvista` manually for local checks.

In the future, it would be nice to:

1. Revisit ~#6740~ #6738 and fix some or many of the type errors that were ignored.
2. Add `mypy` back as a `pre-commit` hook, but use a local environment instead of one managed by `pre-commit`

### CODE REVIEW

**Comment by user27182** [comment]
The new type checking job in #6738 is passing, so the change-over from `pre-commit` to using the new workflow is ready to go. The suggested merge order for this is: merge this PR first, then #6739, then #6740, then #6738.

**Review by akaszynski — APPROVED** [review]
LGTM. Thanks for your work!

**Comment by user27182** [comment]
> 2. Add `mypy` back as a `pre-commit` hook, but use a local environment instead of one managed by `pre-commit`

Instead of using a local environment, we can keep the pre-commit venv for mypy if we can somehow point to the `requirements_test.txt` file in the pre-commit config for the mypy dependencies instead of listing them explicitly.


Then, we can prevent mypy from running in pre-commit.ci (which can't run due to the 250MB dependency limit) with
```
ci:
    skip: [mypy]
```

That way we can continue to use `pre-commit` locally but run our own workflow for CI, and both should have the same dependencies and mypy config

**Comment by MatthewFlamm** [comment]
I agree with the plan, I would order the merging this way:

1) merge any needed fixes
2) drop  pre-commit
3) immediately after 2 add the mypy CI action

**Comment by MatthewFlamm** [comment]
If we can't merge the fix PRs before dropping pre-commit, which is likely, then we need to follow your order.  It will take a concerted effort to not merge in any other PR after dropping pre-commit until the sequence is complete. 

Or, we put all the fixes into the PR that adds the CI job.

The complexity is driven by the squash merge model, otherwise we could have separate commits in one PR.

**Comment by user27182** [comment]
> If we can't merge the fix PRs before dropping pre-commit, which is likely, then we need to follow your order. It will take a concerted effort to not merge in any other PR after dropping pre-commit until the sequence is complete.
> 
> Or, we put all the fixes into the PR that adds the CI job.
> 
> The complexity is driven by the squash merge model, otherwise we could have separate commits in one PR.

I think the main block preventing us from merging the new workflow before dropping it from pre-commit is that the pre-commit config complains about unused `type: ignore`s. So, we can probably remove this line first (as a new PR):
https://github.com/pyvista/pyvista/blob/636a578208e9600ecd280f3681fdaa90011b341c/.pre-commit-config.yaml#L50

and then we should be able to merge the VTK ignores and new workflow without issue since the CI should pass without that line. And then drop `mypy` from pre-commit. That way we'll have uninterrupted mypy coverage without any need to worry about merging other PRs in between.

**Comment by user27182** [comment]
> I agree with the plan, I would order the merging this way:
> 
> 1. merge any needed fixes
> 2. drop  pre-commit
> 3. immediately after 2 add the mypy CI action

Ignore my previous response, let's just do this. Specifically, this would look like:

1. Merge #6739. After review, it now only has a single type error fix. And pre-commit.ci is passing. So we can merge that first without issue.
2. Merge this PR
3. Merge #6738.

We can then close #6740 (these changes are included as part of #6738). We can also close #6742 (not needed).

**Comment by user27182** [comment]
I was able to get pre-commit to work properly with `mypy` in #6744. That PR is currently an all-in-one solution: it splits requirements into `test` and `typing`, adds the project dependencies (e.g. vtk), adds the type ignores, and adds the new workflow. New tests are also added to ensure that the `mypy` pre-commit dependencies are always in sync with those in `requirements_typing.txt`.

So, we don't really need to drop `mypy` from pre-commit after all.

I'll leave it up to reviewers how or if we want to break up that PR. We could, for example, close all these other PRs and only merge #6744. Or, we continue as above, and merge the PRs separately in stages.

**Review by tkoyama010 — APPROVED** [review]
For the sake of understanding, I will merge these separately.

**Pull request merged**
