### PR TITLE
Disable anti-aliasing on cells example and fix doc path for CI

### PR DESCRIPTION
**Pull request by beroda**
### Overview

Resolves https://github.com/pyvista/pyvista/issues/4159

### CODE REVIEW

**Comment by beroda** [comment]
@banesullivan your sugggestion worked. This is what I get from the documentation artifacts.
image

However, for some unknown reason, the job failed. I guess this is not related to this PR as the same occurred for https://github.com/pyvista/pyvista/pull/3643 and might be a github-related issue.

**Comment by adeak** [comment]
The build failure's log is
```
Run mkdir _notebooks
  mkdir _notebooks
  find doc/examples -type f -name '*.ipynb' | cpio -p -d -v _notebooks/
  shell: /usr/bin/bash -e {0}
  env:
    USE_CACHE: true
    PYVISTA_OFF_SCREEN: True
    ALLOW_PLOTTING: true
    SHELLOPTS: errexit:pipefail
    pythonLocation: /opt/hostedtoolcache/Python/3.11.2/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.2/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.2/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.2/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.2/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.2/x64/lib
    CACHE_KEY: d5d140c775ff98650123de5571919abf
    PYVISTA_EXAMPLE_DATA_PATH: /home/runner/.cache/pyvista_3
find: ‘doc/examples’: No such file or directory
0 blocks
Error: Process completed with exit code 1.
```
Looks like some leftovers of the `doc/*` -> `doc/source/*` move. Cc @akaszynski.

**Comment by akaszynski** [comment]
Thanks @adeak. Fixed in [8667314](https://github.com/pyvista/pyvista/pull/4160/commits/866731482ae454f92554c10a30d3a4b8bf13616a).

**Comment by akaszynski** [comment]
This will have to be merged soon to unblock other PRs. Recommending merge today as soon as CI passes.

**Review by akaszynski — APPROVED** [review]

**Review by adeak — APPROVED** [review]

**Pull request merged**
