### PR TITLE
Fix the popup text which is also in the first person

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

See https://github.com/pyvista/pyvista/pull/2046#issuecomment-1017744357

 
https://github.com/pyvista/pyvista/pull/2046

### Details

- None

### CODE REVIEW

**Comment by adeak** [comment]
Thanks for the fix @tkoyama010.

@stla are you happy with this version?

**Comment by adeak** [comment]
I guess we should also consider changing the popup text which is also in the first person. Less critical, as most people won't even find it, and with the full name it's clearer whom it refers to.

**Comment by tkoyama010** [comment]
I agree. Let's do it in this PR!

**Comment by banesullivan** [comment]
Closing in favor of #2086

**Pull request closed without merging**
