### PR TITLE
Switch to using sphinx keep-going flag

### PR DESCRIPTION
**Pull request by akaszynski**
This PR changes our documentation build to use `--keep-going` rather than our custom error catching script. See [sphinx-build](https://www.sphinx-doc.org/en/master/man/sphinx-build.html) options.

Within the [PyAnsys project](https://github.com/pyansys), we've discovered that it's a brittle script and it's better to use a tried and true method rather than potentially letting warnings slip by. Plus, it's one less script to maintain.

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]
Good catch. LGTM.
Reference: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-keep-going

**Comment by tkoyama010** [comment]
Recommending merge on 1 June 2022 unless further comments are given or issues are raised.

**Comment by akaszynski** [comment]
> it's a brittle script

```
 File "<string>", line 5, in <module>
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/helpers.py", line 241, in plot
    plotter.add_mesh(var_item, **kwargs)
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/plotting.py", line 2224, in add_mesh
    mesh, scalars = prepare_smooth_shading(
  File "/home/runner/work/pyvista/pyvista/pyvista/plotting/_plotting.py", line 88, in prepare_smooth_shading
    mesh.point_data[indices_array] = np.arange(arr_sz, dtype=np.int32)
  File "/home/runner/work/pyvista/pyvista/pyvista/core/datasetattributes.py", line 227, in __setitem__
    self.set_array(value, name=key)
  File "/home/runner/work/pyvista/pyvista/pyvista/core/datasetattributes.py", line 613, in set_array
    vtk_arr = self._prepare_array(data, name, deep_copy)
  File "/home/runner/work/pyvista/pyvista/pyvista/core/datasetattributes.py", line 769, in _prepare_array
    raise ValueError(f'data length of ({data.shape[0]}) != required length ({array_len})')
ValueError: data length of (12) != required length (20)
```

Turns out we're already not capturing these warnings.

**Comment by akaszynski** [comment]
Main issue here is somehow the `split_sharp_edges` setting is persisting despite restoring the cache. I've fixed that by simply adding to the split_sharp_edges example.

Since the underlying issue will be fixed anyway in #2695, I think this is sufficient for now to clean up these errors.

**Review by tkoyama010 — APPROVED** [review]
Approving after checking the CI pass.

**Comment by tkoyama010** [comment]
Suggest merging on June 5th.

**Pull request merged**
