### PR TITLE
Fix missing `read_func` in  openfoam download

### PR DESCRIPTION
**Pull request by MatthewFlamm**
### Overview

Fix problem noted in https://github.com/pyvista/pyvista/discussions/6376#discussioncomment-10040234

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
image

**Comment by MatthewFlamm** [comment]
@user27182 The doc image regression should be very useful to prevent these sort of regressions in the future.  Also, great work on the image regression, it is really well thought out and convenient to use.

**Comment by MatthewFlamm** [comment]
I suspect the sphinx gallery cache is causing this to fail as the failed build images are still the old ones in the artifacts.

**Comment by user27182** [comment]
> @user27182 The doc image regression should be very useful to prevent these sort of regressions in the future. Also, great work on the image regression, it is really well thought out and convenient to use.

Glad it's working out well! Pretty sure I caused this bug in the first place as part of #5822 , so hopefully adding the doc image tests redeems me. In hindsight it would have been better to merge these tests _before_ that PR since the downloads otherwise have very little test coverage.

> I suspect the sphinx gallery cache is causing this to fail as the failed build images are still the old ones in the artifacts.

We ran into this issue before, e.g. a bunch of tests suddenly failed in #6167 when the build cache was updated, those errors should have been caught earlier but weren't due to the re-use of an out-of-date build cache. I wonder if we could run a workflow, maybe daily, which fully updates the build cache along with all the gallery examples.

**Comment by MatthewFlamm** [comment]
> > I suspect the sphinx gallery cache is causing this to fail as the failed build images are still the old ones in the artifacts.
> 
> We ran into this issue before, e.g. a bunch of tests suddenly failed in #6167 when the build cache was updated, those errors should have been caught earlier but weren't due to the re-use of an out-of-date build cache. I wonder if we could run a workflow, maybe daily, which fully updates the build cache along with all the gallery examples.

I looked into this more, and I'm not so sure what is going on now.  The `tests/doc/doc_image_cache` are not cached in the CI.  Are the images cached in the gallery examples used as the `from_build` output in the artifact?  If so, then I think my original assessment is correct.

I propose a label to avoid the cache, since every time we build on main, we will always get the incorrect images in the cache.

**Comment by user27182** [comment]
> I looked into this more, and I'm not so sure what is going on now. The `tests/doc/doc_image_cache` are not cached in the CI. 

Correct, for the generated artifacts, images in `from_cache` are copied directly from images in the repo in `tests/doc/doc_image_cache`. 

> Are the images cached in the gallery examples used as the `from_build` output in the artifact? If so, then I think my original assessment is correct.

Cached gallery examples are not used directly, in the sense that the doc image tests do not go out of their way to make use of them.  Rather, images in `from_build` are copied from the locally-generated build, however it was generated. So, if the build is generated using cached gallery examples, then those cached images will part of the build output, and then yes the doc image tests will use those cached images for the tests (and will be part of any artifact uploads from the doc image tests).

> If so, then I think my original assessment is correct.

Yes I think you are right, i.e. that:

 > the sphinx gallery cache is causing this to fail as the failed build images are still the old ones in the artifacts.

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Pull request merged**
