### PR TITLE
Add sphinx-codeautolink extension for automatic links in code blocks

### PR DESCRIPTION
**Pull request by adeak**
I was recently pointed to [sphinx-codeautolink](https://github.com/felix-hilden/sphinx-codeautolink). I tried to give it a spin with PyVista, to see how it fares.

In its current stage I haven't figured it all out, and there are some serious cons:
  1. I haven't figured out how to make it run for our Examples section, only the API reference.
  2. Where it works, it only seems to work for top-level names in a given module, so `pv.Sphere()` will become a link but then `sphere.clean()` will not. I don't know if it would be possible to make it guess, or run each line to do runtime checks.
  3. If we _could_ make it more dynamic, it would probably take a lot longer to build the docs. Even with the current "API reference only" stage I suspect it's significantly slower, although this is hard to make sure of since the doc building has been so slow anyway.
  4. Even in files where it runs, it seems to emit a warning for each code block where it couldn't find a single link to include. This means a _lot_ of code blocks, especially ones where every non-import line has `DOCTEST:+SKIP`. This can be annoying and it might raise a flag in CI.
  5. To make it work on `>>> `-style code blocks, I had to change the corresponding blocks from `:: python` to `:: pycon`, which I'm not sure what it does... but it seems to look the same overall, and with a line of config in `doc/conf.py` the extension is able to parse these correctly.
  6. It's a small and recent github project, so things are more likely to break (or stop being maintained) than with other dependencies.
  
The pros would be the obvious ones:
  1. We'd get links from our examples to other parts of the docs, including external links (anything that intersphinx knows, I think).
  2. The cost of this would be negligible, see the small changes in this PR. Potential unforeseen side-effects not withstanding.
  
So I think we should probably _not_ add it to PyVista (at least not in this form), hence the WIP PR. But I want to present the opportunity for others to give it a look if they so feel. And the first commit contains one (and a half) fix where examples had broken syntax. We probably want to keep that even if this stays out of PyVista.

### CODE REVIEW

**Comment by tkoyama010** [comment]
Thank you for showing this. Linking method and class from example is what I really want to have.

**Comment by adeak** [comment]
I noticed something that might suggest that something could be done to make methods work.

The [Plotting Time Series Data](https://dev.pyvista.org/api/plotting/plotting.html#plot-time-series-data) example mostly works. In this example, `pyvistaqt.BackgroundPlotter` is a link:

Screenshot from 2021-11-26 11-11-18_crop
(sorry, I can't capture my mouse cursor with screenshots, I tried multiple ways).

On the next line `plotter.add_mesh` is not a link:

Screenshot from 2021-11-26 11-08-18_crop
(Imagine the mouse hovering over it :D)

Now, the interesting thing is that not only `threading.Thread` is a link:

Screenshot from 2021-11-26 11-08-29_crop

But also `thread.start()` on the next line!

Screenshot from 2021-11-26 11-08-33_crop

I'm starting to think this has to do with the intersphinx inventories. In python's inventory we have
```
[...]
threading.Thread py:class 1 library/threading.html#$ -
threading.Thread.daemon py:attribute 1 library/threading.html#$ -
threading.Thread.getName py:method 1 library/threading.html#$ -
threading.Thread.ident py:attribute 1 library/threading.html#$ -
threading.Thread.isDaemon py:method 1 library/threading.html#$ -
threading.Thread.is_alive py:method 1 library/threading.html#$ -
threading.Thread.join py:method 1 library/threading.html#$ -
threading.Thread.name py:attribute 1 library/threading.html#$ -
threading.Thread.native_id py:attribute 1 library/threading.html#$ -
threading.Thread.run py:method 1 library/threading.html#$ -
threading.Thread.setDaemon py:method 1 library/threading.html#$ -
threading.Thread.setName py:method 1 library/threading.html#$ -
threading.Thread.start py:method 1 library/threading.html#$ -
threading.Timer py:class 1 library/threading.html#$ -
[...]
```

In pyvistaqt's inventory we have
```
[...]
pyvistaqt.BackgroundPlotter py:class 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.ICON_TIME_STEP py:attribute 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.add_callback py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.add_editor py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.add_menu_bar py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.add_toolbars py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.clear_camera_positions py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.close py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.counters py:attribute 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.default_camera_tool_bar py:attribute 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.editor py:attribute 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.main_menu py:attribute 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.reset_key_events py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.save_camera_position py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.saved_camera_positions py:attribute 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.saved_cameras_tool_bar py:attribute 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.scale_axes_dialog py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.set_icon py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.update_app_icon py:method 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.url py:attribute 1 api_reference.html#$ -
pyvistaqt.BackgroundPlotter.window_size py:property 1 api_reference.html#$ -
pyvistaqt.MultiPlotter py:class 1 api_reference.html#$ -
[...]
```

It's probably not a coincidence that `thread.start()` is found but `plotter.add_mesh` is not. The question is whether this has anything to do with internal PyVista methods not being linked... I have no idea.

**Comment by akaszynski** [comment]
Cleaning out old PRs. I suggest we close this one and revisit it later.

**Comment by adeak** [comment]
Agreed.

**Pull request closed without merging**
