### PR TITLE
Add pythreejs backend

### PR DESCRIPTION
**Pull request by akaszynski**
Jupyterlab support within pyvista is decent, but we still lack a great client side rendering backend.  ``ipygany`` is great, but it used Geometry vs. BufferedGeometry, resulting in lower quality scenes that use more bandwidth.  Additionally, these scenes only support a small subset of the representations avaialble in pyvista (i.e. wireframe and edges are not supported, nor is physically based rendering or flat shading).  Furthermore, since pythreejs is a lower level library, you can modify the camera and scene to get it to match the pyvista scene more accurately.

`pythreejs` brings us closer to faithfully representing a scene directly within a browser from VTK without using `vtk.js`.  In fact, many of our plots are broken due to a reliance on `panel` and `vtk.js` (see [What is a mesh?](https://github.com/jupyter-widgets/pythreejs/issues), though it's unclear who the culprate is.  This may only be broken on my end...

I still feel that three.js is a better javascript plotting backend, though this may change at a later date.  For now, this brings us much closer to being able to render many of our plots within our online documentation interactively.

- [x] Add basic scene support
- [x] Add lighting support
- [x] Add camera support 
- [x] Add scalar support
- [x] Add documentation
- [x] Add section explaining pythreejs in the notebook plotting section
- [x] Include an example of exporting to html.
- [x] Fix color saturation
- [x] RGBA Point scalars
- [x] RGBA Cell scalars
- [x] Add multiple render windows.
- [x] Textures
- [x] Add unit testing

https://user-images.githubusercontent.com/11981631/127816855-a5cf17fd-534d-4570-a950-f776dc7f60f3.mp4

---

For a follow-up PR.

- Create a ipyvista library that directly exposes features from threejs.  It seems that pythreejs isn't as well maintained as it should be: https://github.com/jupyter-widgets/pythreejs/issues

### CODE REVIEW

**Comment by renefritze** [comment]
I've just tried the example mentioned in #1559 with this branch (3c6281e6821be9e5c25a7f23aadd02ed4f03090a to be exact) and `backend=pythreejs`. I still only get the last added mesh displayed however.  It also seems the global theme (at least `camera_position` and `show_edges`) is only applied to the first subplot.

**Comment by akaszynski** [comment]
> I've just tried the example mentioned in #1559 with this branch (3c6281e to be exact) and backend=pythreejs. I still only get the last added mesh displayed however. It also seems the global theme (at least camera_position and show_edges) is only applied to the first subplot.

Adding this to the todos... turns out I don't (yet) support multi-renderers.  I'll ping you once it's implemented.

**Comment by dstansby** [comment]
If it's helpful for debugging anything, I've tried this out in https://github.com/sunpy/sunkit-pyvista/pull/67 and our readthedocs build is erroring with:
```python
reading sources... [ 71%] examples/3d_map
executing 3d_map

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/nbclient/client.py", line 841, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/jupyter_sphinx/execute.py", line 259, in execute_cells
    executenb(notebook, **execute_kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/nbclient/client.py", line 845, in async_execute_cell
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 295, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 307, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 414, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 435, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 475, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/sphinx/io.py", line 188, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 86, in apply_transforms
    super().apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/jupyter_sphinx/execute.py", line 153, in apply
    self.config.jupyter_execute_kwargs,
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunkit-pyvista/envs/67/lib/python3.7/site-packages/jupyter_sphinx/execute.py", line 261, in execute_cells
    raise ExtensionError("Notebook execution failed", orig_exc=e)
sphinx.errors.ExtensionError: Notebook execution failed (exception: Kernel died)
```

**Comment by adeak** [comment]
@akaszynski I don't know when I'll be able to take a look, and I won't be able to review the py3js-specific parts. I can take a look at docs though, but if you're in a hurry go ahead with the merge.

**Comment by akaszynski** [comment]
> I can take a look at docs though, but if you're in a hurry go ahead with the merge.

That's always helpful.  The three.js part is a bit nuanced and I'm not sure how much of the code will be sticking around; your review of the docs would make the most sense.

**Pull request merged**
