### PR TITLE
Split up filters.py into one file per filter class

### PR DESCRIPTION
**Pull request by darikg**
I find PyCharm really chugs on filters.py, and there seemed to be support for the idea in general in #757, so I figured I'd take a stab at it.

This implementation does some import/export juggling to keep the exports from the filters module exactly the same, so it's a non-breaking change, but does this make the module structure a little more confusing than a breaking change would. Thoughts?

### CODE REVIEW

**Comment by akaszynski** [comment]
Just a note, this was attempted a while back and if you're going to go through with this, it needs to be done in fairly short order, otherwise we risk severe merge conflicts or even the loss of features on the merge to `master`.

Let me know when you think this is good to review.  Looks like the code style is failing still...

**Comment by darikg** [comment]
@akaszynski I think the codestyle failing is just from missing module docstrings. I guess I can just duplicate/move the class docstrings to the top of the modules?

**Comment by akaszynski** [comment]
Module documentation strings can be really basic.  A single line summary will work for these, and you can just copy the class docstring.

**Comment by whophil** [comment]
Here is what happened the last go around, maybe there is something useful in the discussion https://github.com/pyvista/pyvista/pull/1165

**Comment by akaszynski** [comment]
Let's get this merged soon before your work goes stale and we deal with merge conflicts.  A simple copy/pasta to the module docstrings will make the style check CI happy.

**Comment by akaszynski** [comment]
> This implementation does some import/export juggling to keep the exports from the filters module exactly the same, so it's a non-breaking change, but does this make the module structure a little more confusing than a breaking change would. Thoughts?

I think backwards compatibility is a priority.  We can cleanup the structure later, but the main point is to break up `filters.py` and if we can get that done in one PR it's a good start.

**Comment by akaszynski** [comment]
Also, just saw that #1385 is waiting on this.

**Review by akaszynski — APPROVED** [review]
Added the module docstrings and I see no issue with merging this, especially as I don't want to loose continuity with existing PRs and have to abandon this PR.

Thanks @darikg for working on this.

**Comment by darikg** [comment]
Thanks @akaszynski!
 
A random thought: the polydata and dataset filter files are still in the 2-3kLOC range. A design that might allow more subdivision is some sort of decorator based approach, so you'd have something like 

```python
@dataset_filter
def streamlines_from_source(dataset, ...):
    ...
```

so individual filters could easily live in their own files, or end-users could add custom filters without having to modify pyvista itself. Just throwing that out there.

**Comment by akaszynski** [comment]
> A random thought: the polydata and dataset filter files are still in the 2-3kLOC range. A design that might allow more subdivision is some sort of decorator based approach, so you'd have something like

That's not a bad idea.  One other approach would be to create classes that assemble individual functions.  See:
https://github.com/pyansys/PyMAPDL/blob/master/ansys/mapdl/core/commands.py

Original file was 74k LOC, so we had to split it up.  Following this approach might be the best strategy.

**Pull request merged**
