### PR TITLE
Use f-strings where possible.

### PR DESCRIPTION
**Pull request by JevinJ**
### Overview

With #905, f-strings can be used.

Converts .format and % syntax to f-strings where possible, including docs.

Some of the conversion was automated so have some caution reviewing.

### CODE REVIEW

**Review by banesullivan — APPROVED** [review]
LGTM - I didn't look over every change but I assume the tests should catch any issues arising from this.

Thanks for doing this, @JevinJ!

**Review by akaszynski — APPROVED** [review]
Agree with the change.  We had a mix of old (`%`) and newer `format` methods and it's a good refactor to just use `f-strings` now that they're supported.

**Comment by akaszynski** [comment]
I can merge this since it looks like the Python3.5 checks won't be reported since we're not building those.  Not sure why it's still requiring those...

Let me know when you're good for me to merge this.

**Comment by banesullivan** [comment]
I just turned off the 3.5 required checks in the branch protection rules

**Comment by akaszynski** [comment]
> I just turned off the 3.5 required checks in the branch protection rules

Thanks, totally forgot about that.  I'll do the same for `pyvistaqt` if you've not done so.

**Comment by JevinJ** [comment]
@akaszynski Good to go.

**Pull request merged**
