### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3`

### CODE REVIEW

**Comment by luzpaz** [comment]
apologies..should of named the branch`doc/typos`

**Review by MatthewFlamm — APPROVED** [review]
LGTM. Thanks!

It is curious that the CI codespell check did not pick this up yet you found them using codespell.  This is something that could be looked into outside this PR.

**Comment by luzpaz** [comment]
I use other non-standard dictionaries with codespell + more targeted search and replace routines (outside of codespell) + I also am using a codepell-git version.

**Review by adeak — APPROVED** [review]
LGTM too, thanks a lot!

**Pull request merged**
