### PR TITLE
🚧 Refactor and cleanup

### PR DESCRIPTION
**Pull request by banesullivan**
@JevinJ, I saw you had some refactoring and cleanup commits, so I thought I would open a PR to see a diff of your work

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
This is huge! A big part of the refactor seems to be related to #288 though

**Comment by JevinJ** [comment]
I'd wait until I make the pull request before considering merging any of it. It's very much WIP and I've had a full plate the last few weeks. Though I do have a question while I'm here. 

Is the scope of pyvista to be a wrapper for vtk objects, or extend them. If wrapping(with numpys wrapper class), it can be made so that only "pythonic/snake case" apis are visible(through documentation or intellisense), but old CamelCase method names will still work. 

Another question, I'd like to clean up/add documentation as well but I don't known what program you're using to generate docs.

**Comment by GuillaumeFavelier** [comment]
> Is the scope of pyvista to be a wrapper for vtk objects, or extend them. If wrapping(with numpys wrapper class), it can be made so that only "pythonic/snake case" apis are visible(through documentation or intellisense), but old CamelCase method names will still work.

I'm not sure to understand what you mean by that.

> I'd like to clean up/add documentation as well

This is great! thanks a lot for your interest/motivation in improving pyvista. I would strongly recommend to tackle the documentation in a different/follow-up PR though.

> I don't know what program you're using to generate docs.

Taken from the [PyVista Contributing guide](https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md), this is the procedure to build the doc locally (output in `docs/_build/html` directory):

```sh
cd ./docs/
make doctest
make html
```

And AFAIK, the doc is generated by `sphinx` (c.f. `requirements_docs.txt`).

**Comment by banesullivan** [comment]
> I'd obviously wait until I make the pull request before considering merging any of it. It's very much WIP and I've had a full plate the last few weeks. Though I do have a question while I'm here.

I opened this PR draft to keep an eye on what you were doing as it looks really valuable! I definitely understand that it is a WIP, which is why I’d like this PR to be a place where we can discuss these changes and help guide any questions/concerns you may have as this looks like a pretty serious refactoring.

> Is the scope of pyvista to be a wrapper for vtk objects, or extend them. If wrapping(with numpys wrapper class), it can be made so that only "pythonic/snake case" apis are visible(through documentation or intellisense), but old CamelCase method names will still work.

For PyVista, the scope is definitely to *extend VTK objects with intuitive attributes/methods* such that a PyVista object is a VTK object; i.e. a `pyvista.StructuredGrid` is a `vtk.vtkStructuredGrid`. This allows for PyVista routines and objects to be used throughout existing python-based VTK code - you could use PyVista to perform a few routines in the middle of an existing VTK pipeline and no one will complain! We want to make sure all existing attributes and methods on VTK objects are still visible. So the goal is: make VTK data object more accessible such that you can use PyVista to learn the data structures, plotting, and filtering then **easily** transition into more sophisticated code with pure-VTK (and advantage for other developers making VTK-dependent software more than users)

> Another question, I'd like to clean up/add documentation as well but I don't know what program you're using to generate docs.

@GuillaumeFavelier‘s comment should be enough to get up and running with the docs. Note that the sphinx-gallery will take a while to build on the first run but after that the results will be cached and the docs will build much faster.

———

One point of concern from me is that this PR is adding a lot of sylistic changes (perhaps you have an autoformatter in your IDE that did all of this automattically?). These changes introduce a ton of conflicts making the PR unable to be merged. I’d like to remove those changes as we are working on properly setting up styling in #288 and #419

**Comment by JevinJ** [comment]
> I'm not sure to understand what you mean by that.

Yeah I wasn't able to remember what exactly I meant either. More precisely, there is a VTKObjectWrapper class in vtk/numpy_interface/dataset_adapter.py. Instead of having pyvista objects inherit from their vtk object, they would be wrap it instead. This way, instead of having the default vtk methods visible with code completion(possibly adding confusion/pollution), only the pyvista methods are visible, but the old ones will still be callable.(And "pointer" methods with pythonic names can easily be added). 

> One point of concern from me is that this PR is adding a lot of sylistic changes (perhaps you have an autoformatter in your IDE that did all of this automattically?). These changes introduce a ton of conflicts making the PR unable to be merged. I’d like to remove those changes as we are working on properly setting up styling in #288 and #419

Can you point out a couple examples? I'm just using default Pycharm, I can set up rules when I get back to this.

**Comment by banesullivan** [comment]
> I'm just using default Pycharm, I can set up rules when I get back to this and formatting is decided. I did run a pep8 autoformat, mainly to make line spaces between classes/methods consistent, but I couldn't find a simple way to keep it from changing things like 'a*b' to 'a * b' which I prefer, but don't seem to be the style used.

Unfortunately, we'll need to separate those formatting/styling changes from feature changes and refactoring as we are working to properly handle styling in other PRs. Also, there a lot of concurrent development going on at the moment so each PR needs to focus on very specific tasks to minimize conflicts

**Comment by JevinJ** [comment]
@banesullivan Has a style been chosen yet/is there anything I need to install/set up? I've rebased/updated my branches so most/all of the style changes are removed.

**Comment by banesullivan** [comment]
If you've gone ahead and rebased your changes from the latest state of the master branch, then I think it would be good to get a new PR going. Some recent PRs did a major overhaul to the documentation style, but not the code style.

**Pull request closed without merging**
