### PR TITLE
Fix `MultiBlock` self-mutates during iteration and breaks `zip`

### LINKED ISSUE #6600: `MultiBlock` self-mutates during iteration and breaks `zip`
### Describe the bug, what's wrong, and what you expected.

`MulitBlock.__next__` stores an internal counter which self-mutates during iteration. This breaks things like `zip` when iterating over multiple copies of the same `MultiBlock` instance.

### Steps to reproduce the bug.

``` python
# Zip a MultiBlock with two blocks
import pyvista as pv
multi = pv.MultiBlock([pv.Sphere(), None])
multi2=multi
print(list(zip(multi, multi2)))

# Expected four items, but got two instead.
[(PolyData (0x130847ca0)
  N Cells:    1680
  N Points:   842
  N Strips:   0
  X Bounds:   -4.993e-01, 4.993e-01
  Y Bounds:   -4.965e-01, 4.965e-01
  Z Bounds:   -5.000e-01, 5.000e-01
  N Arrays:   1, None)]

# Compare with 4 items returned by `tuple` (as expected):
tup = (1,2)
tup2=tup
print(list(zip(tup, tup2)))
[(1, 1), (2, 2)]
```

### System Information

```shell
Dev branch
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by MatthewFlamm**
### Overview

closes #6600 .  After #3031, `MultiBlock` is a `MutableSequence` and therefore we can inherit the methods from there.

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
Test was more or less directly copied from #6600 .  @user27182 I'm not sure how to give you credit for it in this PR.  One thought is you could make a suggested change (to the comment in the test for example) and commit it (or I commit it), then you would get added to the git history on the main branch.

**Comment by MatthewFlamm** [comment]
Looks like we also need to do this for PartionedDataSet https://github.com/pyvista/pyvista/blob/262e2d217f612b644442e5e14ccfa0ccd950b126/pyvista/core/partitioned.py#L111-L122

**Comment by user27182** [comment]
This suggested change could also be made now that `zip` is fixed, either this PR or separate if preferred, cc @tkoyama010 

https://github.com/pyvista/pyvista/pull/6599/files#r1739929981

**Review by tkoyama010 — APPROVED** [review]
LGTM. Thanks!

**Comment by tkoyama010** [comment]
> This suggested change could also be made now that `zip` is fixed, either this PR or separate if preferred

Fixed in 8b90fd5f500219e9aeac48a242d9fe63d547ef36 :+1:

**Review by tkoyama010 — APPROVED** [review]

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Review by tkoyama010 — APPROVED** [review]

**Review by banesullivan — APPROVED** [review]

**Pull request merged**
