### PR TITLE
🌐 Add Options for gettext output

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

Add Options for gettext output. This option is need for translate the raw contents in sphinx document.

 
relate to: https://github.com/enthought/mayavi/pull/841

### Details
This is where I want to translate.
https://pyvista-doc.readthedocs.io/ja/latest/

image

### CODE REVIEW

**Review by akaszynski — APPROVED** [review]
LGTM

**Comment by tkoyama010** [comment]
Thanks a lot for review. Could somebody merge this?

**Comment by akaszynski** [comment]
> Thanks a lot for review. Could somebody merge this?

Sorry, thought you had write permissions.  Want me to add you to the developers team?

**Comment by tkoyama010** [comment]
> Sorry, thought you had write permissions. Want me to add you to the developers team?
@akaszynski Yes thanks. It is an honor for me to join the pyvista team :-)

**Pull request merged**
