### PR TITLE
Add the Grad-Descent-Visualizer package to the external examples.

### PR DESCRIPTION
**Pull request by JacobBumgarner**
### Overview
As discussed in #3078, this PR adds the [grad-descent-visualizer]() package to the external examples.

Also seen in discussion #3074.

### CODE REVIEW

**Comment by akaszynski** [comment]
The GIF is huge. Can we trim/compress that a bit?

**Comment by JacobBumgarner** [comment]
Yes, absolutely. I should've checked the other gif sizes beforehand. 

Looks like they range from 1-5mb, so I cut trimmed & compressed this one down to 4.7mb.

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Comment by JacobBumgarner** [comment]
Sorry for the closing confusion here.

**Pull request merged**
