### PR TITLE
Add note to widget docs about significance of the name kwarg in add_mesh

### PR DESCRIPTION
**Pull request by adeak**
# Details

It's not obvious [in the excellent widget docs](https://docs.pyvista.org/plotting/widgets.html) that the `name` kwarg set in `Plotter.add_mesh` is crucial for callbacks to function seamlessly. E.g. in the sphere slider example:
```python
def create_mesh(value):
    res = int(value)
    sphere = pv.Sphere(phi_resolution=res, theta_resolution=res)
    p.add_mesh(sphere, name='sphere', show_edges=True)
    return
```
the fact that `name='sphere'` is passed is responsible for discarding meshes from previous calls to the callback.

The meat of this PR is to take explicit note of this keyword argument being passed. While I'm at it I also fixed a few typos and semantic mistakes on the same doc page. 

# Issues during build
I've also run into a few warnings and errors while I was building the docs locally. I can't tell whether some of these are actual issues (and not just misconfiguration on my side), so I'll post these here. I followed [the contributing guide](https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md) so I executed the following commands from the `docs/` directory. I didn't run the pytest suite first, but I wouldn't expect that to be a problem in light of `make clean`.

### During `make doctest`
a. 15 different warnings of the kind:
```
WARNING: image file not readable: core/../images/auto-generated/structured_cube.png
```
b. Two indentation warnings:
```
/home/user/pyvista/pyvista/plotting/plotting.py:docstring of pyvista.BasePlotter:7: WARNING: Unexpected indentation.
/home/user/pyvista/pyvista/plotting/plotting.py:docstring of pyvista.Plotter:23: WARNING: Unexpected indentation.
```

### During `make html -b linkcheck`:
c. two warnings:
 ```
/home/user/pyvista/docs/examples/02-plot/depth-peeling.rst:15: WARNING: 'any' reference target not found: pyvista.rcParams
/home/user/pyvista/docs/plotting/plotting.rst:63: WARNING: undefined label: qt_ref (if the link has no caption the label must precede a section header)
```

Four link errors in three files:
```
writing output... [ 86%] getting-started/installation
(line  115) broken    https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md#testing - Anchor 'testing' not found
```
d. This is weird, from what I can tell the anchor exists and works.

```
writing output... [ 89%] index
(line   52) broken    https://dev.azure.com/pyvista/PyVista/_build/latest?definitionId=3&branchName=master - 404 Client Error: Not Found for url: https://dev.azure.com/pyvista/PyVista/_build/latest?definitionId=3&branchName=master
```
e. This link is indeed broken for me; I suspect the existence of the link has to do with CI.

```
writing output... [ 91%] plotting/itk_plotting
(line   18) broken    https://github.com/InsightSoftwareConsortium/itkwidgets#installation - Anchor 'installation' not found
(line    6) broken    https://github.com/InsightSoftwareConsortium/itkwidgets#installation - Anchor 'installation' not found
```
f. Again this anchor seems to exist and work.

g. And with both runs of `sphinx` I got a deprecation warning:
```
/home/user/pyvista_test_env/lib/python3.7/site-packages/sphinx/deprecation.py:52: RemovedInSphinx40Warning: sphinx.builders.html.DirectoryHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
```

## TODO

- [x] add significance of the `name` kwarg
- [x] fix existing typos 
- [x] reorder so that examples come before documentation
- [x] fix indentation warnings in plotting.py (point b. above)
- [x] fix the Qt reference, point to pyvistaqt (point c. above)

### CODE REVIEW

**Comment by akaszynski** [comment]
I'm noticing that the CI is failing when trying to upload to the testing PyPi when the branch is outside of `pyvista/pyvista`.  I've disabled that so we avoid these failures in the future.

**Comment by banesullivan** [comment]
@adeak, thanks for this!!!

I have edited your post with some numbers to easily respond:

a. these errors should go away after generating those images with `make doctest` first.

b. fix these if you're up for it, otherwise, ignore.

c. We need to remove the Qt reference or point it to http://qtdocs.pyvista.org. The `any` reference needs to be fixed.

d. This is a known issue for Sphinx. See https://github.com/sphinx-doc/sphinx/issues/6779

e. We need to fix that... I had noticed the Azure badge was broken.

f. same as d.

g. Ugh. I'm so tired of Sphinx's deprecations.

**Comment by adeak** [comment]
@banesullivan thank you for the edit! I started out with an enumeration but I couldn't bend code blocks to my will...

a. I see, sorry!

b. Will do.

c. I'll take a look at that too.

d., f. Noted!

e., g. I'll leave these for others :)

**Comment by adeak** [comment]
A quick update regarding this PR.

1. I've fixed most of the build issues.
2. I realized that issue a. is still present: I get those warnings after `make clean` and `make doctest`, from the latter command itself. If I subsequently `touch` an affected file the warning goes away (and I can see that the images are there at the end). During the build I can see that the missing files indeed don't appear until the warnings are thrown, and appear almost immediately after, gradually. Might be some kind of race condition perhaps? Seems that `make doctest` complains about images that itself should generate, and which it eventually generates.
3. I've switched the order of examples and documentation as suggested by @banesullivan. For the latter I added a section titled "Widget API", for want of a better idea.
4. I think we should add an example for the spline widget as well. I can do this sometime next week, but I'll be away from an unlimited internet connection (needed for fancy example datasets) until then.
5. To fix a merge conflict I've removed the `pyvitaqt` from a mention of `pyvistaqt.BackgroundPlotter`, calling it "the former `BackgroundPlotter` class". Seemed logical to me at the time :) I also fixed a new broken qt_ref ref in the "Basic API Usage" docs.

**Comment by adeak** [comment]
And one more thing. @banesullivan you said that
>  The any reference needs to be fixed.

I couldn't figure out how to do this. To be more specific, I couldn't find a description of `rcParams` in the docs that I could link to, only a few scattered uses of `rcParams`. I saw that it's defined in `plotting/theme.py`, which doesn't have a dedicated doc page. Perhaps it would make sense to mention the defaults at the beginning or end of https://docs.pyvista.org/examples/02-plot/themes.html?

**Comment by banesullivan** [comment]
@adeak, don't worry about that `any` reference for now - We'll make a new PR for documenting `rcParams` likely in a dedicated section in the Plotting chapter and point to that from the example you mention

**Comment by banesullivan** [comment]
> I realized that issue a. is still present: I get those warnings after make clean and make doctest, from the latter command itself. If I subsequently touch an affected file the warning goes away (and I can see that the images are there at the end). During the build I can see that the missing files indeed don't appear until the warnings are thrown, and appear almost immediately after, gradually. Might be some kind of race condition perhaps? Seems that make doctest complains about images that itself should generate, and which it eventually generates.

Are you executing sphinx in a docker container or some other virtualized environment? This is very odd... Frankly, if it's working, then we likely won't spend much time debugging this. but it may be worth opening a new issue if it is reproducible

------

Everything else sounds great, thanks @adeak!

**Comment by adeak** [comment]
OK, thanks, I've removed the `any` bit from the PR TODOs. I'm done for review then :)

> Are you executing sphinx in a docker container or some other virtualized environment? This is very odd... Frankly, if it's working, then we likely won't spend much time debugging this. but it may be worth opening a new issue if it is reproducible

This is a simple, proper debian system in a venv. I'll see if I can repro in a fresh venv and open an issue if necessary.

**Comment by akaszynski** [comment]
Thanks for cleaning this up!

**Pull request merged**
