### PR TITLE
Add `.vtkhdf` as an extension of `pyvista.HDFReader`

### PR DESCRIPTION
**Pull request by awoimbee**
### Overview

Hi, I downloaded [ParaViewTestingDataFiles-v5.13.1.tar.xz](https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.13&type=data&os=Sources&downloadFile=ParaViewTestingDataFiles-v5.13.1.tar.xz) to test `Testing/Data/vtkHDF/pdc_multi.vtkhdf`.

The first issue I encountered was:
```python
>>> m = pv.get_reader('ParaView-v5.13.1/Testing/Data/vtkHDF/pdc_multi.vtkhdf')
# [...]
ValueError: `pyvista.get_reader` does not support a file with the .vtkhdf extension
```

This PR fixes that. Also the docs moved to I updated the link.

BTW I only added `.vtkhdf` and not `.hdf`, the docs state:

> The VTKHDF format generally uses the .vtkhdf extension. The .hdf extension is also supported but is not preferred.

---

Then I got errors about `Unknown data set type: PartitionedDataSetCollection`, but I guess I need to wait for VTK 9.4 and the followup to #5833

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
> Then I got errors about Unknown data set type: `PartitionedDataSetCollection`, but I guess I need to wait for VTK 9.4 and the followup to https://github.com/pyvista/pyvista/pull/5833

You are right that PyVista does not have a wrapper for `PartitionedDataSetCollection` yet.  I do not think this is a limitation of vtk <v9.4, it is a limitation of PyVista.

**Review by MatthewFlamm — APPROVED** [review]
Thanks!

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Comment by tkoyama010** [comment]
We usually merge 24 hours after the final approval to give reviewers in different time zones a fair chance to review it. Please be patient :)

**Pull request merged**
