### PR TITLE
Fix inplace filters usage of copy_from

### LINKED ISSUE #3069: Adding a mesh to a plotter with smooth_shading=True leads to a deep copy of the mesh
### Describe the bug, what's wrong, and what you expected.

Hi,

I'm not sure if this behaviour is intended or not, but when a mesh is added to a plotter, if `smooth_shading=True` then a deep copy of the mesh is created.

This is because [point normals are calculated inplace](https://github.com/pyvista/pyvista/blob/2f77c141794de181d1f9cd9a1c39e7a0321d34b5/pyvista/plotting/_plotting.py#L86-L88):
```py
mesh.compute_normals(cell_normals=False, inplace=True)
```

Perhaps calculating normals and adding point data would be preferable? Something like:
```py
normals = mesh.compute_normals(cell_normals=False, inplace=False)['Normals']
mesh.point_data.set_array(normals, 'Normals')
```

Or if this behaviour is intended, perhaps it's worth adding a note to the docstring to clarify a deep copy of the mesh will be made.

### Steps to reproduce the bug.

This test was added in #2888, but it fails if `smooth_shading=True` when adding the mesh to the plotter.
```py
import numpy as np
import pyvista

sphere = pyvista.Sphere()
sphere.point_data['numbers'] = np.arange(sphere.n_points)
sphere2 = sphere.copy(deep=False)

sphere['numbers'] *= -1  # sphere2 'numbers' are also modified

assert np.array_equal(sphere['numbers'], sphere2['numbers'])
assert np.shares_memory(sphere['numbers'], sphere2['numbers'])

plotter = pyvista.Plotter()
plotter.add_mesh(sphere, scalars=None, smooth_shading=True)

sphere[
    'numbers'
] *= -1  # sphere2 'numbers' are also modified after adding to Plotter.  (See  issue #2461)

assert np.array_equal(sphere['numbers'], sphere2['numbers'])
assert np.shares_memory(sphere['numbers'], sphere2['numbers'])

```

### System Information

```shell
Date: Mon Jul 25 18:06:02 2022 BST

                OS : Darwin
            CPU(s) : 20
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon Pro 5700 XT OpenGL Engine
       GPU Version : 4.1 ATI-4.6.21

  Python 3.9.12 (main, Jun  1 2022, 06:36:29)  [Clang 12.0.0 ]

           pyvista : 0.36.dev0
               vtk : 9.0.3
             numpy : 1.22.4
           imageio : 2.19.3
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.2
         pyvistaqt : 0.10.dev0
           IPython : 8.3.0
             scipy : 1.8.1
              tqdm : 4.64.0
            meshio : 5.3.4
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by banesullivan**
Resolves #3069 and closes #3087 

cc @akaszynski and @p-j-smith

`copy_from()` is being used throughout internally as an assumed shallow copy (see its use for the `inplace=True` scenarios of filters). This PR corrects the internal usage of `copy_from()` to be a shallow copy operation where needed by adding a keyword argument to opt-in to a shallow copy if desired

### CODE REVIEW

**Review by akaszynski — DISMISSED** [review]
Thanks. This was missing in the original implementation as well. Thanks for making it backwards compatible. Checking from the past (for my edification), it was indeed a `DeepCopy`:

https://github.com/pyvista/pyvista/blob/d13ead8bbc6968447cb25cd9614d7c5b853404c2/pyvista/core/dataobject.py#L57-L66

I think it's ok to have this without a depreciation warning since it's only going to be there for one minor release.

**Comment by banesullivan** [comment]
@akaszynski, I actually changed my mind on this. I am keeping `copy_from()` to default as a deep copy for consistency with all other `copy*()` methods (as `deep=True` is the default everywhere else). This PR is now updating where `copy_from()` was used in-place as an assumed shallow copy operation to be explicitly `deep=False`. 

Please re-review if you would

**Review by akaszynski — APPROVED** [review]
>  This PR is now updating where copy_from() was used in-place as an assumed shallow copy operation to be explicitly deep=False.

Personally, I'm fine either way, but I agree that consistency is paramount, though there's a performance hit with always having a shallow copy. Either way, as long as we can explain our reasoning, I'm good with it.

**Comment by banesullivan** [comment]
> though there's a performance hit with always having a shallow copy.

Not sure I follow? Do you mean for deep copy? Either way, this method is rarely used

**Pull request merged**
