### PR TITLE
A thank you to @MatthewFlamm and @darikg

### PR DESCRIPTION
**Pull request by banesullivan**
Thank you for all of your contributions to PyVista, @MatthewFlamm and @darikg!!

Thank you for contributing to PyVista!! We are so grateful for contributors like you! Your efforts, like all of those who participate in the PyVista community, go a long way in making PyVista what it is. To show our appreciation, we want to put your names on the collective work, adding you to The PyVista Developers list.

I hope it is safe to assume consent to add your name here (approve this PR if so) - please let us know otherwise (either in a comment here or privately on Slack)

@pyvista/developers, if there is anyone else you feel we should add, please let me know

### CODE REVIEW

**Comment by adeak** [comment]
Wait, I thought he was already there :laughing: +:infinity:

**Review by MatthewFlamm — APPROVED** [review]
Thanks for the recognition!  It is a pleasure to be involved in such a great project.

**Comment by tkoyama010** [comment]
13 authors. Yeah!

**Comment by tkoyama010** [comment]
Please add @dcbr  after merging such a huge contribution https://github.com/pyvista/pyvista/pull/1432.

**Comment by darikg** [comment]
thanks @banesullivan @adeak @akaszynski @MatthewFlamm @tkoyama010 !

**Pull request merged**
