### PR TITLE
add trivial module for backwards compatability

### PR DESCRIPTION
**Pull request by akaszynski**
This PR adds a trivial file to make our recent theme changes compatible with `pyvistaqt`.  I don't want our theme changes to be a breaking change as this needs to be out soon in support of another project https://github.com/pyansys/pymapdl.

### CODE REVIEW

**Comment by akaszynski** [comment]
Merging as this is a trivial fix.

**Comment by adeak** [comment]
Out of curiosity, where/how is this new module used in pyvistaqt? I tried looking for `theme` in that repo but couldn't find it.

**Comment by akaszynski** [comment]
Full traceback:
```
~/tmp/tmp10.py in <module>
      1 import pyvista
----> 2 from pyvistaqt import BackgroundPlotter
      3 
      4 # mesh = pyvista.Sphere()
      5 # mesh['scalars'] = mesh.points[:, 2]

~/python/pyvistaqt/pyvistaqt/__init__.py in <module>
      1 """PyVista package for 3D plotting and mesh analysis."""
      2 from pyvistaqt._version import __version__
----> 3 from pyvistaqt.plotting import BackgroundPlotter, MainWindow, MultiPlotter, QtInteractor
      4 
      5 __all__ = [

~/python/pyvistaqt/pyvistaqt/plotting.py in <module>
     53 import vtk
     54 from pyvista.plotting.plotting import BasePlotter
---> 55 from pyvista.plotting.theme import rcParams
     56 from pyvista.plotting.render_window_interactor import RenderWindowInteractor
     57 from pyvista.utilities import conditional_decorator, threaded, try_callback

ModuleNotFoundError: No module named 'pyvista.plotting.theme'
```

**Comment by adeak** [comment]
Ah, I see, this was fixed in https://github.com/pyvista/pyvistaqt/pull/108 which is why the search didn't turn up anything. Thanks.

**Pull request merged**
