### PR TITLE
Add parallel_projection and parallel_scale to Theme; make `camera` setting a first class `_ThemeConfig`

### PR DESCRIPTION
**Pull request by MatthewFlamm**
### Overview

Addresses part of #5619.

### Breaking Change

The `Theme.camera` attribute is now a `_ThemeConfig` object.  It is still supported to set the `position`, `viewup`, etc. via a `dict`, for example `theme.camera = {'position': [1.0, 1.0, 1.0]}`, but the returned value will no longer be a dict, i.e. `camera = theme.camera` will not be a `dict` itself.

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
The current PR is a naive implementation with no deprecations.  This puts `parallel_projection` and `parallel_scale` as direct `Theme` attributes.  These are camera options however.  I want to propose deprecating setting `Theme.camera` as a `dict` and instead make it a `_ThemConfig`.  This might also be possible to do without deprecation.

**Comment by MatthewFlamm** [comment]
This PR has converted the `Theme.camera` into using a `_CameraConfig` class object.  But, for backwards compatibility, we convert any dict passed into a `_CameraConfig`.  This is not a breaking change for setting the config via dict, but is a breaking change for anyone inspecting the `camera` attribute and expecting a `dict`.

This sort of casting dict into a `_ThemeConfig` was also suggested in #5119, and might be worth a separate PR to expose for all `_ThemeConfig`.

**Comment by MatthewFlamm** [comment]
@MarkusZimmerDLR if you want to test

**Comment by MatthewFlamm** [comment]
I made a quick scan of the other attributes of `Theme` and did not see any other candidates for this conversion.  For consistency and flexibility in the future, we should discourage using a `dict` for any theme setting, particularly on the top level `Theme`.

**Review by tkoyama010 — APPROVED** [review]
LGTM. As far as breaking backward compatibility, I guess it is not a problem in this case. Let's only notify on the release note.

**Pull request merged**
