### PR TITLE
Update trame-vtk to 2.8.6

### PR DESCRIPTION
**Pull request by ChristosT**
The new version brings fixes exporting interactive views that include multiblock data
I built the examples with the latest master of pyvista and trame-vtk `2.8.6` on https://pyvista-experimental-dynamic.netlify.app

### Overview
Compare:

- slicing example:
	- Broken: https://docs.pyvista.org/version/stable/examples/01-filter/slicing#multiple-slices-in-vector-direction
	- Fixed: https://pyvista-experimental-dynamic.netlify.app/examples/01-filter/slicing#sphx-glr-examples-01-filter-slicing-py
	
- Multiblock API:
	- Broken: https://docs.pyvista.org/version/stable/api/core/_autosummary/pyvista.multiblock
	- Fixed: https://pyvista-experimental-dynamic.netlify.app/api/core/_autosummary/pyvista.multiblock
	
### Details
The culprit was missing the registration of `vtkCompositePolydataMapper` in the serialization methods of `vtk-trame`.
The issue was found by installing `vtk-osmesa` as recommended [here](https://github.com/pyvista/pyvista/issues/5802#issuecomment-2013188854), exporting `TRAME_SERIALIZE_DEBUG=1` and compiling an example that contains multiblock data.

### Related issues:
- https://github.com/pyvista/pyvista/issues/5361
- https://github.com/pyvista/pyvista/issues/5437
- https://github.com/pyvista/pyvista/issues/5802

cc: @banesullivan , @MatthewFlamm

### CODE REVIEW

**Review by banesullivan — APPROVED** [review]

**Review by tkoyama010 — APPROVED** [review]

**Comment by RobPasMue** [comment]
Would it be possible to get a patch release with these changes? It's awesome that MultiBlocks are now also interactive!

https://pyvista-experimental-dynamic.netlify.app/api/core/_autosummary/pyvista.multiblock

**Comment by tkoyama010** [comment]
However, since we have not made any changes to pyvista itself, I believe we can still use this PR change if we upgrade trame-vtk in its current state.

**Comment by RobPasMue** [comment]
Ha you are right. I thought you pinned down depencies for the "jupyter" target but they are free on the upper limit

https://github.com/pyvista/pyvista/blob/371062296c8d1bf56a29d8d720bfd03f8ebb8d3b/pyproject.toml#L49-L59

We can use it as is in that case! :)

**Comment by user27182** [comment]
This is a great fix! Thank you 🙏

I have noticed that colors are not rendered in the multiblocks. E.g. have a look at the interactive view for the `add_composite` docs:

https://pyvista-experimental-dynamic.netlify.app/api/plotting/_autosummary/pyvista.plotter.add_composite

Should I raise a new issue or is this expected ?

**Comment by ChristosT** [comment]
> This is a great fix! Thank you 🙏
> 
> I have noticed that colors are not rendered in the multiblocks. E.g. have a look at the interactive view for the `add_composite` docs:
> 
> https://pyvista-experimental-dynamic.netlify.app/api/plotting/_autosummary/pyvista.plotter.add_composite
> 
> Should I raise a new issue or is this expected ?

Thank you for pointing this out ! Please open a new issue. I am not sure what we are missing there but we should  definitely keep track of it.

**Pull request merged**
