### PR TITLE
Move Slack to GitHub Discussions to announce

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

We will announce releases in GitHub Discussions.

### Details

- None

### CODE REVIEW

**Comment by bjlittle** [comment]
@tkoyama010 Don't know if this helps, but thought I'd share anyways ...

Over on [Scitools/iris](https://github.com/SciTools/iris) we use a dedicated GH Discussion category for all releases, and a dedicated GH Discussion for each release e.g., [🐺 v3.6.x](https://github.com/SciTools/iris/discussions/5106), where all comms with the community and the current status of release is curated.

Not sure if this applies to the `pyvista` workflow or how you're planning to use GH Discussions for `pyvista` releases, but it kinda works for `iris` :+1:

**Comment by tkoyama010** [comment]
That's cool! So you are making a place call for having a discussion in each release. I will try this in the next release. Is there a procedure in place at iris document for making this discussion?

**Comment by bjlittle** [comment]
@tkoyama010 There's no documented procedure to follow as such, but I can mention this to the other `iris` core devs, as it might be generally useful as a living process.

**Comment by tkoyama010** [comment]
@bjlittle Nice. By the way, I really like the following animal on the head of the release project. This way each release can be given a code name.

[GH Project](https://github.com/orgs/SciTools/projects/11)

**Comment by bjlittle** [comment]
Yeah, sometimes it's easier to remember the 🐙 or 🦊 release rather than a version number.

TBH it's a bit of fun, and helpful to some and not others, but we're giving it a try. 

We have a different release manager for each release, so the all core devs get the experience of performing a release. More importantly, it's a great way to incrementally add some quality control and improvements into the release process, as it's see through the eye's of another core dev. That's genuinely been quite a rewarding feedback loop.

Additionally, we also have a release do nothing script, see https://github.com/SciTools/iris/blob/main/tools/release_do_nothing.py

We use it as a tool to remind the release manager the steps to take in the release process. Personally, I find this invaluable, and takes the stress and human error risk out of the release. Again, we all use it and take turns to improve it, thus hopefully tending towards release nirvana 😂

HTH

**Comment by bjlittle** [comment]
Yeah, sometimes it's easier to remember the 🐙 or 🦊 release rather than a version number.

TBH it's a bit of fun, and helpful to some and not others, but we're giving it a try. 

We have a different release manager for each release, so the all core devs get the experience of performing a release. More importantly, it's a great way to incrementally add some quality control and improvements into the release process, as it's see through the eye's of another core dev. That's genuinely been quite a rewarding feedback loop.

Additionally, we also have a release do nothing script, see https://github.com/SciTools/iris/blob/main/tools/release_do_nothing.py

We use it as a tool to remind the release manager the steps to take in the release process. Personally, I find this invaluable, and takes the stress and human error risk out of the release. Again, we all use it and take turns to improve it, thus hopefully tending towards release nirvana 😂

HTH

**Comment by tkoyama010** [comment]
This is exactly what we should value in our daily work. Although described in the text as a script that does nothing, this script does the important thing of clarifying the workflow of the job.

Do-nothing scripting: the key to gradual automation https://blog.danslimmon.com/2019/07/15/do-nothing-scripting-the-key-to-gradual-automation/

**Comment by tkoyama010** [comment]
LGTM

**Comment by tkoyama010** [comment]
> Do-nothing scripting: the key to gradual automation https://blog.danslimmon.com/2019/07/15/do-nothing-scripting-the-key-to-gradual-automation/

This is a really great article. I have an upcoming opportunity to teach a tutorial and this will help me organize what I will explain.

**Pull request merged**
