### PR TITLE
🚀 Add full featured notebook rendering 🚀 

### LINKED ISSUE #285: orientation axes for off screen plotting
As outlined in https://github.com/pyvista/pyvista/issues/130#issuecomment-475150808, the orientation marker cannot currently be shown when plotting off-screen.

This means that it won't appear in any examples in the documentation gallery 😞 

I think we should implement a default size/scale for the marker if off-screen plotting is being used (this contradicts my previous thoughts in https://github.com/pyvista/pyvista/issues/130#issuecomment-475322174 😏 )

### LINKED ISSUE #364: Interactive canvas within Jupyter Notebooks
Pyvista output appears in Jupyter Notebooks as a static image, not as an interactive canvas.
This happens both in Jupyter Lab and Notebook. I also noticed that the same happens on pyvista's binder.

I can only get interactivity by using `notebook=False` in `plot()` method, which opens a separate window. It would be great to have it within a notebook, under the code cell. I think it worked for me until recently, but after updating my conda environment it doesn't.

I noticed there are some ongoing issues with widgets and pyvista (e.g. #332), but since widgets work fine in my case, I thought maybe there is a simple solution to my current problem.

Thanks.

Notes:
* I am using a separate conda environment for `pyvista`.
* The `ipywidgets` package works OK, with the widgets showing up and responding correctly.
* I tried installing `panel` and `pyviz_comms` within the same environment, but the only thing that changed is that `ipywidgets` output now appears with a grey background (see screenshot below).

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
# Insert code here
import pyvista as pv
sphere = pv.Sphere()

sphere.plot()
```

**Screenshots**

Screenshot from 2019-08-16 16-28-56
-----

**System Information:**
 Please run the following code wherever you are experiencing the bug and paste the output below. This report helps us track down bugs and it is critical to addressing your bug:

```py
# Get system info
import pyvista as pv
print(pv.Report())
```

```txt
# Paste system info here
--------------------------------------------------------------------------------
  Date: Fri Aug 16 16:34:13 2019 BST

             Linux : OS
                 8 : CPU(s)
            x86_64 : Machine
             64bit : Architecture
           31.3 GB : RAM
           Jupyter : Environment

  Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
  [GCC 7.3.0]

            0.21.4 : pyvista
             8.2.0 : vtk
            1.17.0 : numpy
             2.5.0 : imageio
             1.4.3 : appdirs
             0.4.3 : scooby
             3.1.1 : matplotlib
             5.9.2 : PyQt5
             7.7.0 : IPython
             7.5.1 : ipywidgets
             0.6.2 : panel
--------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by banesullivan**
### Overview

This unapologetically removes the previous `panel` notebook plotting code in favor of [`ipyvtk_simple`](https://github.com/Kitware/ipyvtk-simple). Why? Because this approach lets us utilize PyVista's ***entire feature set*** interactively in notebooks. Plus, I think we’ve fallen behind on correctly utilizing panel 😞 

### Details

- By the entire feature set, I really mean everything! Widgets, sub-plotting, eye dome lighting... you name it and now you can use it within a notebook (these features simply aren't possible with panel/VTKjs)
- Note that now we have an interactor and render window even when off-screen plotting. @akaszynski, are you okay with this? This will easily resolve #285 too
    - No more hacky checking if the plotter has an `iren` in random places
- Resolve #364 
- Relevant to #313  
- @pyvista/developers, I'd like a critical review on this one. There is a discussion in https://github.com/Kitware/ipyvtk-simple/issues/6 on whether or not this should be included directly in PyVista. With a few changes (always having an interactor), then including the two lines needed to do this in a bare try/except is well worth it in my mind. It'll give all users a quick way to utilize PyVista's full feature set directly in a notebook environment.
- @pyvista/collaborators, sorry to spam you, but it'd be great to get your feedback on this as well
- `ipyvtk_simple` is not yet on PyPI so this won't land until that happens
- this also fixes a bug when trying to fetch a screenshot before the `show()` call in some scenarios

Possible concerns
- plotters aren’t ever closed/cleaned up in this approach. The user must call `.close()`. But the implementation with panel was the same way

### CODE REVIEW

**Comment by akaszynski** [comment]
@banesullivan, nice work!  I think this will be the one widget to rule them all, though I think we should keep support for `PlotterITK` as the frame rate is a bit better for smaller meshes.

However, for large meshes, this is really the way to go.  I've got a few closed source projects (one of which will become open one day) that would benefit from client side rendering.  Having to transfer the mesh over is time consuming and one of the biggest bottlenecks.

I'm going to test this out on my end and let you know how it works out.

---

> * Note that now we have an interactor and render window even when off-screen plotting

Totally fine with this.  We have to get `xvfb` up and running anyway, so this is ideal.  If we could use this to generate our off-screen plots, we could finally get #285 solved.

**Comment by banesullivan** [comment]
@prisae is reporting some issues where the render window appears and disappears briefly on Linux - this will need to be resolved. Also, tests still aren't happy with the use of render window in all offscreen plotting - we'll have to dive into what's happening here

**Comment by banesullivan** [comment]
Also, for anyone reporting issues with the widget itself, please track those here: https://github.com/Kitware/ipyvtk-simple/issues

The big one holding up deployment is https://github.com/Kitware/ipyvtk-simple/issues/2

**Comment by GuillaumeFavelier** [comment]
Thanks for starting this @banesullivan, this is great work!

> for anyone reporting issues with the widget itself, please track those here

I am currently experimenting with the slider widgets, I will report there

>  issues where the render window appears and disappears briefly on Linux

I do not experience this on my manjaro, what example did you use @prisae ?

**Comment by prisae** [comment]
Just the one in his gif.

**Comment by GuillaumeFavelier** [comment]
I just tried it. My render window does not disappear but the "accuracy" if the dragging event seems buggy. Do you use jupyter notebook/lab? What is your web browser?

**Comment by prisae** [comment]
Jupyter Notebook. And I think I tried Firefox and Chrome.

**Comment by GuillaumeFavelier** [comment]
I can't reproduce. And on chromium, I don't have the issue with dragging either.

**Comment by prisae** [comment]
Works on another machine I just tried now...

**Comment by larsoner** [comment]
@banesullivan worth getting this one in before release?

**Comment by banesullivan** [comment]
> worth getting this one in before release?

I'd like to. Let me see if I can make time to handle this

**Comment by akaszynski** [comment]
I'd really like this as well, and I'm about ready to move forward and start testing this in earnest.

**Comment by banesullivan** [comment]
I'm now thinking maybe not. Performance is simply awful on MyBinder ([Binder](https://mybinder.org/v2/gh/Kitware/ipyvtk-simple/master)). 

There are other things in the works still that will step us away from `ipyvtk_simple` and towards a vtk.js-based approach for the client-side rendering, so I'm not going to push this any further and hold off until we can leverage that as the client-server communication/data transfer will be massively better

This is cool, but no longer something I want to include in PyVista. I think we should keep some of the work done here though to make `iren` mandatory and strip out the `panel` code. I will adjust the PR as necessary and then if someone wants to use `ipyvtk_simple` it would be a straightforward layer on top of PyVista

**Comment by larsoner** [comment]
Sounds good to me

**Comment by akaszynski** [comment]
> I'm now thinking maybe not. Performance is simply awful on MyBinder

I'm seeing that as well (but not as bad locally) on binder.  Could it also be that MyBinder uses weak computers on kubernetes, and that's hurting our performance?  For example, the cylinder vtk example is rendered quickly, but the other (more complex) examples are much slower.

Abandon this draft for the moment @banesullivan?

**Comment by banesullivan** [comment]
> Abandon this draft for the moment

For the moment... I'd like to land the majority of these changes so that we can resolve #285 but I'll throw out all the code linking to `ipyvtk_simple`. I don't think it'd be wise to land this in the next release as having an interactor in off-screen plotting can have side-effects that we still need to work out

**Comment by banesullivan** [comment]
Closing in favor of #983

**Pull request closed without merging**
