### PR TITLE
🚀 more examples for the gallery 🚀

### PR DESCRIPTION
**Pull request by banesullivan**
Some new examples and updates to make existing examples better.

Resolve https://github.com/pyvista/pyvista-support/issues/83
Resolve https://github.com/pyvista/pyvista/issues/510

Note: this will increase the docs build time on Travis... (currently at 40 minutes on this branch and 32 minutes on `master`) 

Changes:

- More example downloads
- New `compute_implicit_distance` filter
- Add ability to close loops in `lines_from_points`
- Improve docs for `delaunay_2d`

### CODE REVIEW

**Comment by akaszynski** [comment]
Also, considering that Azure devops allows 10 parallel jobs, we should pull off the following from travis and distribute it into Azure jobs:
```
    # Test the core API on Python 3.5, 3.6, and 3.7
    - name: Core API 3.5
      python: 3.5
      # Run the test suite and generate coverage report
      script: pytest -v --cov pyvista
    - name: Core API 3.6
      python: 3.6
      # Run the test suite and generate coverage report
      script: pytest -v --cov pyvista
    - name: Core API 3.7
      python: 3.7
      env:
        - REPORT_COVERAGE: true
        # Deploy to PyPI when core testing passes on 3.7 on tags
        - PYVISTA_DEPLOY: true
      # Run the test suite and generate coverage report
      script: pytest -v --cov pyvista

    # Test the package docstrings on Python 3.5, 3.6, and 3.7
    - name: Package Docstrings 3.5
      python: 3.5
      # Run all code examples in the docstrings
      script: pytest -v --doctest-modules pyvista
    - name: Package Docstrings 3.6
      python: 3.6
      # Run all code examples in the docstrings
      script: pytest -v --cov --doctest-modules pyvista
    - name: Package Docstrings 3.7
      python: 3.7
      env:
        - REPORT_COVERAGE: true
      # Run all code examples in the docstrings
      script: pytest -v --cov --doctest-modules pyvista
    # Build/test/deploy documentation on 3.7 only
    - name: Documentation Testing 3.7
      python: 3.7
      script: |
        pip install codespell pydocstyle;
        make doctest;
    - name: Documentation Build/Deploy 3.7
      python: 3.7
      env:
        - REPORT_COVERAGE: false
        - DEPLOY_DOCS: true
```

We could pull it all off of TravisCI in fact.  Loath I am to admit it, Microsoft has done something right with Devops.  I've done that for a closed source project and could probably do that here.

Maybe we should simply merge this and then optimize the tests in another branch, especially if you need `0.23.2` out soon.

**Comment by banesullivan** [comment]
We could stop building the example gallery on every PR and only build on the `master` branch which is where they are deployed. That would greatly speed up dev builds. Also, it's pretty rare that the examples fail and not the other jobs... We'd just need to ask folks to locally build the docs on bigger PRs so that we don't catch issues after PRs merge.

**Comment by banesullivan** [comment]
If we can get the pytest suite to over 90% coverage, I think it would be safe to only build the example gallery on the master branch.

**Comment by agramfort** [comment]
Mne builds on PRs only examples that have been edited in the PR

We use CircleCI for this 

Cc @larsoner

**Comment by larsoner** [comment]
@banesullivan if you check out [our CircleCI config](https://github.com/mne-tools/mne-python/blob/master/.circleci/config.yml), you'll see a few things that might be useful:

1. merge with upstream master before build
2. commit-message checks for `[circle full]` (run all examples) or `[circle front]` (build our four front-page examples)
3. `diff`-based selection of which examples to run -- only build changed examples. We actually use this as a selection mechanism, too, for example if we expect some to change a bit due to underlying changes to plotting functions, we ask contributors just to touch some relevant examples if they haven't (e.g., update some wording in `plot_visualize_evoked.py` whenever they have messed with evoked plotting functions `mne/viz/evoked.py`)
4. full building and uploading when on `upstream/master` or `upstream/maint/X.XX`
5. if not on `master` or `maint`, no examples changed, and nothing in the `diff` showing code changes to examples, no examples get built

Most of this gets run through [make html_dev-pattern](https://github.com/mne-tools/mne-python/blob/master/doc/Makefile#L48-L51) in our doc Makefile.

**Pull request merged**
