### PR TITLE
UnicodeDecodeError

### PR DESCRIPTION
**Pull request by beroda**
### Overview
This should fix https://github.com/pyvista/pyvista/issues/3574

### Details

- see comments in https://github.com/pyvista/pyvista/issues/3574

### CODE REVIEW

**Review by banesullivan — APPROVED** [review]
Thank you!

**Review by tkoyama010 — APPROVED** [review]
Ah, this was also happening in the Japanese environment; it seems to happen all the time in the utf-8 language environment. Thanks for resolving this.

**Comment by tkoyama010** [comment]
@beroda Is this ready for merge? (I am asking because of the Draft mark.)

**Comment by beroda** [comment]
> @beroda Is this ready for merge? (I am asking because of the Draft mark.)

It is indeed ready for merge with the last commit.
All tests are ok on my platform
image

@banesullivan Following your advice on the issue https://github.com/pyvista/pyvista/issues/3574#issuecomment-1309040459 , I found two other places where **Popen** was used so I added utf8 encoding.

**Review by banesullivan — APPROVED** [review]
Thanks for finding the other spots too!

**Comment by akaszynski** [comment]
Ignoring coverage failure and merging. Thanks @beroda!

**Pull request merged**
