### PR TITLE
🌇 Sunset of Python3.5

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

🌇 Python3.5 security support Ended 1 week and 3 days ago (13 Sep 2020). Let's finish support for it.

 

### Details

- https://endoflife.date/python
- See https://github.com/pyvista/pyvistaqt/pull/47
- See https://github.com/pyvista/pyvistaqt/pull/60

### CODE REVIEW

**Comment by akaszynski** [comment]
I'm all for dropping support for Python3.5.  We don't need to do anything outright to eliminate support for Python 3.5, but disabling CI for this means that adding things like f-strings won't cause our builds to fail.

Thanks for adding this @tkoyama010!

**Review by akaszynski — APPROVED** [review]

**Review by larsoner — APPROVED** [review]

**Review by larsoner — CHANGES_REQUESTED** [review]
Actually here and in pyvistaqt this should be updated, too:

https://github.com/pyvista/pyvista/blob/master/setup.py#L70
https://github.com/pyvista/pyvista/blame/master/README.rst#L139

**Comment by akaszynski** [comment]
Just made those changes.

**Comment by tkoyama010** [comment]
Thanks @akaszynski  @larsoner .

**Review by larsoner — APPROVED** [review]

**Review by akaszynski — APPROVED** [review]

**Pull request merged**
