### PR TITLE
🚧 Overhaul VTKjs export script for use with panel

### PR DESCRIPTION
**Pull request by banesullivan**
**WORK IN PROGRESS - this will be a somewhat major PR when complete. I'm getting this going now to outline what is needed and to provide place for folks to discuss these changes**

This PR will resolve https://github.com/pyviz/panel/issues/408 when completed

This isn't something I'll be able to complete on my own, so please feel free to chime in with suggestions/comments or tackle a feature request/bug if you can 

Pinging folks that might be interested and who's help/expertise I'd appreciate:

- @akaszynski 
- @GuillaumeFavelier
- @philippjfr
- @xavArtley 

### Features

- [ ] Leverage new changes in `panel` to plug in our VTKjs converter (mentioned in https://github.com/pyviz/panel/issues/408#issuecomment-500153052)
- [ ] modularize `export.py` module to either save a scene as a VTKjs file (many files if subplotting) or send the scene to `panel`
- [ ] Send subplots/individual renderers to their own pane in `panel` and handle displaying the panes in a grid
- [ ] Enforce panes to display when `.show()` is called (see https://github.com/pyvista/pyvista-support/issues/12)

### Bugs to Squash

- [ ] Send text/labels to VTKjs or at least don't throw an error (text added with `add_point_labels` and `add_text`)
- [ ] Fix how VTKjs doesn't always plot the active scalar - see https://github.com/pyvista/pyvista-support/issues/15
- [ ] Ensure all PyVista mesh types work - sometimes I run into issue with `StructuredGrid`s
- [ ] Make sure scalar/color mapping is working - sometimes the mapping is totally wrong. [Blood vessels example](https://docs.pyvista.org/examples/01-filter/streamlines.html#blood-vessels) shows this
- [ ] See if we can send lighting options to VTKjs (smooth versus default)
- [ ] Make sure things like legends don't through an error when converting to VTKjs
- [ ] Handle front and back face culling
- [ ] Issue with `float64` compatibility
- [ ] fix issue with `int` points array
- [ ] custom colormaps (see #345)

### CODE REVIEW

**Comment by xavArtley** [comment]
It's not merged for the moment but I already made a small example how to connect pyvista exporter with panel. https://github.com/pyviz/panel/pull/475

**Comment by banesullivan** [comment]
Awesome! Thanks so much @xavArtley - I'll expand up that here!

**Comment by philippjfr** [comment]
Let me know if there's any features or improvements you'd like to see in Panel to improve the experience here. We potentially have some funding to work on that.

**Comment by banesullivan** [comment]
@xavArtley - I'm getting started on this now that https://github.com/pyviz/panel/pull/475 is merged.

I'm curious does the converter you all have in `panel` write to the disk? It looks like it does to me... and the implementation you shared to use our current serializer definitely has to write the archive to the disk.

I'm starting to attempt implementing our serializer in a way that will serialize each renderer in memory and then either save to a `.vtkjs` archive on this disk OR pass the archive in memory to `panel` for loading.

Do you see any issues with that?

Also, I plan to implement this in a way that will handle different renderers in a render window separately so that we could send subplots to their own panel panes.

**Comment by banesullivan** [comment]
@philippjfr that's super exciting!! I will definitely keep that in mind and see what I come across as I implement this

**Comment by xavArtley** [comment]
No in panel no file is wrote on the disk. I use an in memory buffer of the zip file.
For the example it was just to demonstrate how the serializer can be pluggued with a custom serializer.
Writing the file on the disk is not a problem. It just some io steps unecessary

**Comment by xavArtley** [comment]
Concerning the panel widget i think to be more complete it will requires to extend the javascript part to have more compkete deserializers. However it needs time i don't have for the moment and i don't know when i'll have it.

**Comment by banesullivan** [comment]
@xavArtley and @philippjfr - Panel hasn't been working with PyVista for a few weeks now on our demo site -> http://playground.pyvista.org which is hosted at https://github.com/pyvista/pyvista-examples

I've tried `panel` versions 0.6.0 and 0.6.1 both having blank outputs. Any help would be greatly appreciated:

Screen Shot 2019-08-09 at 2 29 51 PM

**Comment by xavArtley** [comment]
I have same problem but only with pyvista version > 0.21.2

**Comment by banesullivan** [comment]
Did something on the panel side change? That's very strange that pyvista>0.21.2 is having issues as I don't think any of this has changed:

https://github.com/pyvista/pyvista/blob/0dc24a1cfb517b8724acd19b4bfe94c58e29833d/pyvista/plotting/plotting.py#L3583-L3585

**Comment by xavArtley** [comment]
Nothing has changed on panel side for the VTK panel for more than one month

image
image

**Comment by xavArtley** [comment]
To make it works with recent versions you must use this:
```python
plotter = pv.Plotter()
actor = plotter.add_mesh(pv.Sphere())
plotter.show(auto_close=False)
```

**Comment by banesullivan** [comment]
FYI, I just enabled a system flag for autoclosing plotters by using the `PYVISTA_AUTO_CLOSE` environment variable on the `master` branch. Now all the examples on MyBinder should be working again as I set that flag to false in https://github.com/pyvista/cookiecutter-pyvista-binder

**Comment by xavArtley** [comment]
Future possibilities of panel:
https://xavartley.github.io/panel/vtk_examples/vtkEnhancement.html

**Comment by banesullivan** [comment]
@xavArtley, holy 💩!! that's so awesome and is a complete game-changer for Panel+VTK... makes it compete quite well with [`itkwidgets`](https://github.com/InsightSoftwareConsortium/itkwidgets)

**Comment by xavArtley** [comment]
FYI panel 0.7 is out with various enhancement for vtk support.
https://panel.pyviz.org/gallery/demos/VTKInteractive.html#gallery-vtkinteractive
https://panel.pyviz.org/reference/panes/VTK.html#gallery-vtk
https://panel.pyviz.org/reference/panes/VTKVolume.html#gallery-vtkvolume

**Comment by akaszynski** [comment]
@banesullivan,

I'd really like for notebook visualization to be native for `pyvista`.  Any way we could get this branch merged to master with updates for the latest `panel` and `itk-widgets`?

**Comment by banesullivan** [comment]
@akaszynski - I'd be happy to wrap up the few PRs around notebook rendering and catchup this PR with he recent release of `panel`. However, we may need to think about what makes sense to put in PyVsita and what might make sense to seperate.

also, https://github.com/pyvista/pyvista/issues/422#issuecomment-547018729:
> I propose we create pyvista_notebook (or pick a better name) and start adding features there to include several of the plotting backends.

**Comment by xavArtley** [comment]
Hello, for the next imrpovement I will work on this task `Send text/labels to VTKjs or at least don't throw an error (text added with add_point_labels and add_text)`
I succeed to create something similar to axes (for the moment in pure javacript) :
https://xavartley.github.io/#dev/vtkjs/vtk_axes.html

Points label should not be very different of the axes ticks

**Comment by banesullivan** [comment]
I am closing this in favor of the new vtkjs scene graph exporter introduced in VTK9: https://github.com/Kitware/VTK/blob/master/IO/Export/vtkJSONRenderWindowExporter.cxx

See #698

**Comment by xavArtley** [comment]
Hello, you can view what's coming next in panel here:
https://github.com/holoviz/panel/pull/1248

**Pull request closed without merging**
