### PR TITLE
Add `nitpicky` option to doc config to prevent broken links

### PR DESCRIPTION
**Pull request by user27182**
### Overview

Continued from #6203

### CODE REVIEW

**Comment by user27182** [comment]
Woohoo! Docs are finally passing. 

This is ready, waiting on #6896 #6899 #6901 #6904. I can probably push another "fix" PR too to update broken links not fixed by #6896 or #6899. I will also clean up the nitpick ignores a bit.

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Review by tkoyama010 — CHANGES_REQUESTED** [review]
Waiting #6896 to merge.

**Review by tkoyama010 — APPROVED** [review]

**Comment by user27182** [comment]
looks like merging #6835 created new broken links which need to be fixed first

**Pull request merged**
