### PR TITLE
Release 0.42.4

### PR DESCRIPTION
**Pull request by AlejandroFernandezLuces**
If that's okay, I would like to make a patch release with some features that are needed for some projects. If any other commit needs to be included, please let me know. Also, if for any reason this release shouldn't be done right now, feel free to close the PR and delete the branch. Patch release of v0.42.4 includes:

- https://github.com/pyvista/pyvista/pull/5197
- https://github.com/pyvista/pyvista/pull/5194

### Merge Checklist

- [ ] Merge in local not to squash merge.

### Post Merge Checklist

- [ ] Tag `v0.42.4` and push the tag.
- [ ] Verify [docs](https://docs.pyvista.org/) have updated.
- [ ] Verify [PyPI](https://pypi.org/project/pyvista/) have updated.
- [ ] Update the [conda-forge feedstock](https://github.com/conda-forge/pyvista-feedstock).

### CODE REVIEW

**Review by tkoyama010 — CHANGES_REQUESTED** [review]
Sorry to depress you, but it is our policy in the PyVista project that patch releases are **bug fixes only**. Let's work to release [version 0.43](https://github.com/pyvista/pyvista/pull/5138) as soon as possible to release your great feature.

**Comment by AlejandroFernandezLuces** [comment]
No problem @tkoyama010 , thanks for letting me know 🙂 

I'll close this PR and delete the branch if I have permissions

**Comment by AlejandroFernandezLuces** [comment]
I can't delete the branch myself, so please feel free to delete it if necessary.

**Comment by tkoyama010** [comment]
> No problem @tkoyama010 , thanks for letting me know 🙂
> 
> I'll close this PR and delete the branch if I have permissions

Thank you for your thought. We shall do the release on the 30th of this month.

**Comment by banesullivan** [comment]
@AlejandroFernandezLuces, I'm hoping to get some free time and volunteer my time to get the next release out in the coming days. Stay tuned

**Pull request closed without merging**
