### PR TITLE
Fixed improper argument usage with tuples for Trame elements

### PR DESCRIPTION
**Pull request by Sgoodridge96**
### Overview

Vuetify 3 expects tuples for v_slot_activator and v_bind properties.  This fixes the warnings thrown below.

image

### CODE REVIEW

**Comment by ConnorNoddin** [comment]
This is fantastic, and will greatly benefit me. Hope it gets approved!

**Review by annehaley — APPROVED** [review]
LGTM, thank you!

**Comment by banesullivan** [comment]
Is this worth issuing a patch for in our latest release?

**Review by banesullivan — APPROVED** [review]

**Comment by jourdain** [comment]
Those are only warnings when we enable debug info. In truth, none of those changes are needed. They are just good for consistency. Mainly for beginners to catch mistakes.

**Pull request merged**
