### PR TITLE
Move Common, DataObject to dataset.py, dataobject.py

### PR DESCRIPTION
**Pull request by JevinJ**
### Overview

Preserves history.

Split Common, DataObject into their own files. dataset.py, dataobject.py.

Rename Common->DataSet

### CODE REVIEW

**Review by akaszynski — APPROVED** [review]
Nice work preserving the history, and it's nice to have this split up and organized like how VTK does it.

**Comment by JevinJ** [comment]
Hold off on merging this, just realized I need to check if docstrings changed.

**Comment by JevinJ** [comment]
@akaszynski  Ok, check the last commit and this is good to merge.

**Comment by akaszynski** [comment]
https://github.com/pyvista/pyvista/pull/1160/commits/3580901cbc5fee6fcdbaf00ca9d314a1747b0116 looks good.  I'm surprised the CI didn't pick up on the bad sphinx build.

**Pull request merged**
