### PR TITLE
Add `auto-approve-dependabot.yml` to auto approve Dependabot PR

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

This GitHub Actions solve the problem that we have to approve all the Pull Request of [dependabot](https://github.com/dependabot).

### Details

- None

### CODE REVIEW

**Comment by bjlittle** [comment]
@tkoyama010 Are there any rare situations that you can think of whereby we don't want the auto merge to merge? 

Just curious. I'd don't think this is a blocker to merging this PR BTW 👍

**Comment by tkoyama010** [comment]
@bjlittle
Good point. Actually, we don't have it. It would be perfect if there were GithHubActions where `dependabot` creates a PR and `pyvista-bot` merges it if they approve it. just having them approve it would reduce the burden, so I created this PR as a bonus for #4941. If there are any GitHubActions that can also merge, I would appreciate suggestions.

**Comment by tkoyama010** [comment]
@bjlittle I raised an issue in https://github.com/bjlittle/geovista/issues/453 . We can discuss about this there.

**Comment by tkoyama010** [comment]
LGTM

**Pull request merged**
