### PR TITLE
Make rendering optional when adding meshes and actors

### PR DESCRIPTION
**Pull request by math-artist**
There are 2 main reasons for this:

- Huge speed gain when hiding and displaying meshes.

- It looks much more professionnal when clicking a button to see all the changes at once.

This was executed in my app, but just to show the speed difference:

```
@timeit
def test_render(render=True):
    for i in range(20):
        actor = self.vtk_widget.add_mesh(s.mesh, None, scalars=scalars, clim=clim, cmap=cmap,
                                         label=None, reset_camera=reset_camera, scalar_bar_args=settings,
                                         show_scalar_bar=True, name="{0}".format(i), annotations=annotations,
                                         stitle=scale.title, pickable=s.pickable, render=render)
    if not render:
        self.vtk_widget.render()
```

```
test_render(False)
'test_render'  180.01 ms
test_render(True)
'test_render'  2520.14 ms
test_render(False)
'test_render'  185.01 ms
test_render(False)
'test_render'  178.01 ms
test_render(True)
'test_render'  2518.14 ms
```

That's a nice 14X increase in speed.

### CODE REVIEW

**Comment by math-artist** [comment]
I would like to point out that when using add_mesh, it does render twice if the mesh already exist: once after removing the actor and another time when adding the actor. 

I think that rendering once is enough for a function like add_mesh. Maybe it would be better to always not render inside remove_actor when calling remove_actor from add_actor (when another actor of the same name already exists).

**Comment by akaszynski** [comment]
> That's a nice 14X increase in speed.

Seems that this occurs only when you've already started rendering, as I'm not seeing any speed improvements locally for speed.  However, I think it's important to have a render parameter when adding a mesh and I appreciate this fix.

**Review by akaszynski — APPROVED** [review]

**Comment by akaszynski** [comment]
Also, @math-artist, I can add you as a developer to the project so you can create branches within the project and merge (once CI is passing and you've gotten approval).

**Comment by math-artist** [comment]
> Seems that this occurs only when you've already started rendering, as I'm not seeing any speed improvements locally for speed.

Yes, I always update live the same renderer with new objects, so this is my use case.

**Pull request merged**
