### PR TITLE
Opacity by scalar array or custom transfer function

### PR DESCRIPTION
**Pull request by banesullivan**
These changes enable a user to specify all kinds of options for the opacity:

- a scalar array on the mesh be used for opacity mapping to enable us to see two arrays at once 
- predefined transfer functions by string name
- custom built transfer functions
- single value for global opacity

### Why?

Maybe you have an uncertainty array - these changes make it so that you could make regions with high values of uncertainty be transparent. Or maybe you have a mesh with a modeled scalar array on another array of your modeling variance. This would allow you to control the opacity of the mesh by the variance.

### Example

Here I have a mesh with a modelled scalar array from Kriging and an associated kriging variance array which I'd like to use to make my mesh transparent:

```py
temp_grid = pv.read('temp_grid.vtk')
temp_grid
```
<table><tr><th>Header</th><th>Data Arrays</th></tr><tr><td><table><tr><th>UnstructuredGrid</th><th>Information</th></tr><tr><td>N Cells</td><td>2841790</td></tr><tr><td>N Points</td><td>551724</td></tr><tr><td>X Bounds</td><td>3.299e+05, 3.442e+05</td></tr><tr><td>Y Bounds</td><td>4.253e+06, 4.271e+06</td></tr><tr><td>Z Bounds</td><td>-2.700e+03, 2.300e+03</td></tr><tr><td>N Arrays</td><td>2</td></tr></table></td><td><table><tr><th>Name</th><th>Field</th><th>Type</th><th>N Comp</th><th>Min</th><th>Max</th></tr><tr><td><b>Temperature</b></td><td>Points</td><td>float64</td><td>1</td><td>6.729e+00</td><td>2.738e+02</td></tr><tr><td>Temperature_var</td><td>Points</td><td>float64</td><td>1</td><td>2.214e+02</td><td>1.107e+04</td></tr></table></td></tr> </table>

```py
# Make some contours
cntrs = temp_grid.contour(10, scalars='Temperature')

p = pv.Plotter(notebook=0)
p.add_mesh(cntrs, scalars='Temperature', 
           opacity='Temperature_var', 
           flip_opacity=True, cmap='bwr')
p.show()
```

Screen Shot 2019-07-07 at 4 09 40 PM

Which looks a bit more informative than just the scalar array alone:

Screen Shot 2019-07-07 at 4 05 30 PM

### Todo:

- [x] fix issue where the scalar bar is not appearing
- [x] fix the issue where the added `__custom_rgba` array is set as active and would be plotted wrong on the second iteration.
- [x] Add tests
- [x] Add the ability to use user-specified mappings/transfer functions per #301  
- [x] throw error if scalars and opacity arrays are on different fields (cell/point)
- [x] refactor and implement for `add_volume` as well (`add_volume` doesn't currently support RGBA plotting - this will come later)
- [x] add examples!

### CODE REVIEW

**Comment by banesullivan** [comment]
Example using custom-defined transfer function:

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_uniform()
opacity = [0,0.2,0.9,0.2,0]

p = pv.Plotter()
p.add_mesh(mesh, scalars='Spatial Point Data', opacity=opacity, 
           cmap='Reds_r')
p.show()
```

download

**Comment by banesullivan** [comment]
Note the new exclusion list for when accessing the active scalar. We might want to add more names to this like `'vtkOriginalPointIds'` to mitigate users experiencing #303

**Comment by marcomusy** [comment]
looks cool!!

**Comment by akaszynski** [comment]
Might consider adding “Normals”.

**Pull request merged**
