### PR TITLE
🚀 Release 0.42.2

### PR DESCRIPTION
**Pull request by tkoyama010**
Patch release of v0.42.2 which includes:

- #4863
- #4853
- #4879
- #4884

### Merge Checklist

- [ ] Merge in local not to squash merge.

### Post Merge Checklist

- [ ] Tag `v0.42.1` and push the tag.
- [ ] Verify [docs](https://docs.pyvista.org/) have updated.
- [ ] Verify [PyPI](https://pypi.org/project/pyvista/) have updated.
- [ ] Update the [conda-forge feedstock](https://github.com/conda-forge/pyvista-feedstock).

### CODE REVIEW

**Comment by akaszynski** [comment]
We might consider including some of the other bug fix PRs.

**Comment by tkoyama010** [comment]
Thanks for the review. I added the other bug fix PRs.

**Comment by akaszynski** [comment]
I'll also manually deploy the docs until we have a solution that works. I'm still not sold on readthedocs.

**Comment by tkoyama010** [comment]
@akaszynski
Thank you. I have consulted with other Scientific Python maintainers and it seems that deploying to Netrify via GitHubAction is the way to go(https://github.com/pyvista/pyvista/issues/4868#issuecomment-1718466141). It is expected to have a low impact as it only changes the deployment location.

I will report back once the investigation is complete.

**Comment by akaszynski** [comment]
> Verify [docs](https://docs.pyvista.org/) have updated.

I'll do the best I can to update the docs manually over the weekend. It won't scale, but it's something.

**Comment by tkoyama010** [comment]
Thanks a lot for your work!

**Comment by tkoyama010** [comment]
@akaszynski
I'm thinking of proposing to the [ansys/actions](https://github.com/ansys/actions) the ability upload documents to Netlify using [actions-netlify](https://github.com/nwtgck/actions-netlify).
Please share your opinion on this before I raise an issue with them.

**Comment by akaszynski** [comment]
That's fine, but I'd recommend demonstrating a MWE first to show how it works and to demonstrate that it's better than the existing approach and worth the complexity.

**Comment by tkoyama010** [comment]
I noticed that even if Netlify is used, the old version of document data still needs to be stored somewhere. I will keep it as is. Sorry, I misunderstood the problem.

**Pull request merged**
