### PR TITLE
Fix Trame Viewers in Jupyter

### PR DESCRIPTION
**Pull request by annehaley**
### Overview

This PR is intended to address any oversights from #4811.
Related to #4835.

### Changes

- [x]  Initialize UI-related state variables in the constructor of the `BaseViewer` class. This makes calling the `ui` function not mandatory for using the viewer.

### CODE REVIEW

**Comment by tkoyama010** [comment]
Thanks @annehaley for the quick PR. And sorry that we didn't test this in our Jupyter environment. I will release 0.42.1 when this PR is merged.

**Review by tkoyama010 — APPROVED** [review]

**Comment by johannes-mueller** [comment]
LGTM. Thanks for the quick fix @annehaley

**Comment by larsoner** [comment]
I was about to open an issue about #4811 breaking things based on a `git bisect` but I can confirm that this PR seems to fix them!

**Comment by tkoyama010** [comment]
@annehaley When you are ready to merge, could you please push the ready for review button?

**Pull request merged**
