### PR TITLE
🚧 Force Close Render Window on VTK9

### PR DESCRIPTION
**Pull request by akaszynski**
This is a redo of #1007, but tested on Python 3.9 to with the VTK wheel provided by @larsoner at https://osf.io/kej3v/

Trivial example now runs, along with the full testing suite on Python 3.9

```
Python 3.9.0 (default, Oct  6 2020, 02:47:17) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> pv.Report()

--------------------------------------------------------------------------------
  Date: Wed Nov 25 15:59:40 2020 MST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro M620/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 390.138

  Python 3.9.0 (default, Oct  6 2020, 02:47:17)  [GCC 7.5.0]

           pyvista : 0.27.0
               vtk : Version unknown
             numpy : 1.19.4
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.4
--------------------------------------------------------------------------------
```

### Original PR
----
Many thanks to @adeak, we've figured out how to close the render windows on VTK9.

Rather than wait for the next wheel to come out (which might take another year), this PR proposes closing the render window using a ctypes interface to libX11 with:

```py
X11 = ctypes.CDLL("libX11.so")
```

Turns out you can handily close the display with ``XCloseDisplay`` provided that you have the DisplayID from the VTK render window.  Fortunately, VTK provides this in ``vtkRenderWindow.GetGenericDisplayId``.  @adeak was able to discover that you have to pass this as a ``ctypes.c_size_t``.  There's even an embrassing [SO question](https://stackoverflow.com/questions/64811503/python-memory-addresses-variation-across-python-3-5-3-9-on-linux/64814361#64814361) where I get schooled on python memory management.

This is only implemented for linux and VTK>=9.0, and docs/tests build just fine.  I'd really like this out for a 0.27.3 patch release.

### CODE REVIEW

**Comment by akaszynski** [comment]
@larsoner, any chance you could get this branch tested out?  If it's too much work, we can merge, check if this causes a failure, and revert if necessary.

**Comment by larsoner** [comment]
I am on holiday until Monday but I can test then. In the meantime @GuillaumeFavelier might be able to try it out using the wheel, IIRC he has a Linux x86_64 box (and can probably get Python 3.8 running on it if it's not already).

A quick look at the code makes me think it might not work, though, since IIRC the version of the wheel is 9.0.0, but we'll see when I actually get to test it!

**Comment by adeak** [comment]
On this branch and python 3.9 with @larsoner's vtk wheel I get a segfault during tests in `tests/test_picking.py::test_cell_picking`:
```
Python 3.9.0+ (default, Oct 19 2020, 09:51:18) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvista as pv
>>> pv.Report()

--------------------------------------------------------------------------------
  Date: Thu Nov 26 02:27:36 2020 CET

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 15.5 GB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics 620 (WHL GT2)
       GPU Version : 4.6 (Core Profile) Mesa 20.2.2

  Python 3.9.0+ (default, Oct 19 2020, 09:51:18)  [GCC 10.2.0]

           pyvista : 0.27.0
               vtk : Version unknown
             numpy : 1.19.4
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.3.5
        matplotlib : 3.3.3
           IPython : 7.19.0
          colorcet : 1.0.0
           cmocean : 2.0
     ipyvtk_simple : 0.1.3
             scipy : 1.5.4
              tqdm : 4.53.0
--------------------------------------------------------------------------------
```

I should note that I see a segfault in the same place on python 3.8 and a vtk wheel `vtk-9.0.20201118-cp38-cp38-linux_x86_64.whl` I built myself earlier. I know I mentioned this before, so I'm not sure if this is expected...

**Comment by akaszynski** [comment]
I'm going to put this on hold until I investigate if further.  @adeak, can you upload your wheel somewhere for me to look at?

**Comment by adeak** [comment]
@akaszynski only in case you'd miss it: I posted the wheel to slack (for want of a better place).

**Comment by akaszynski** [comment]
> @akaszynski only in case you'd miss it: I posted the wheel to slack (for want of a better place).

Saw that and I'll take a look at it after thanksgiving.  Thanks!

**Comment by larsoner** [comment]
> On this branch and python 3.9 with @larsoner's vtk wheel I get a segfault during tests in tests/test_picking.py::test_cell_picking:

I also get these on `master`, though. So I think it's a separate issue.

I checked and on my wheel `vtk.vtkVersion().GetVTKVersion()` is `9.0.0` as I suspected. So the name `VTK_EARLY` at least is a misnomer -- you'll have to detect their build version with something like:
```
>>> vtk.vtkVersion().GetVTKBuildVersion()
20201117
```
However, despite this, it seems to work / there is no segfault for `python3.9 -m mne sys_info`. Is there same additional fix? If so, maybe `VTK_EARLY` isn't even necessary?

**Comment by larsoner** [comment]
It looks like this PR also breaks pyvistaqt

**Comment by akaszynski** [comment]
Going to abandon this in hopes of a patch with the next release of VTK.

**Pull request closed without merging**
