### PR TITLE
Add CT image whole body segmentation dataset

### PR DESCRIPTION
**Pull request by user27182**
Add two new downloadable datasets, `download_whole_body_ct_male` and `download_whole_body_ct_female`. See https://github.com/pyvista/vtk-data/pull/38 for details and preview images. Check out the docstrings of the new downloads as well.

Note: The datasets won't have thumbnails in the Dataset Gallery until #5872 is merged.

### CODE REVIEW

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
@pyvista-bot preview

**Review by tkoyama010 — APPROVED** [review]
LGTM

| download_whole_body_ct_male  | download_whole_body_ct_female |
| ------------- | ------------- |
| image  | image|

**Review by tkoyama010 — APPROVED** [review]

**Pull request merged**
