### PR TITLE
🚧 DataSetAttributes debugging. 

### PR DESCRIPTION
**Pull request by JevinJ**
### Overview

This is #659 but I will be progressively enabling certain changes to suss out testing errors.

### CODE REVIEW

**Comment by JevinJ** [comment]
@akaszynski Why might this fail now unless master is failing? I have everything commented out...

**Comment by akaszynski** [comment]
That is odd.  I'm going to push a test PR to see if the same occurs.

**Comment by akaszynski** [comment]
I see the problem.  Wheels for `vtk` were just updated to 9.0 and we've yet to verify that it works and we're hitting some segfaults on windows and mac.  I'm setting the master branch to use 8.1.2 for testing for the moment so all future branches don't fail.  We can fix 9.0 compatibility in a later branch.

**Comment by akaszynski** [comment]
Please merge with master and glory in passing tests.  Also, if I were you I'd comment out the azure doc tests until the core api works.

**Pull request closed without merging**
