### PR TITLE
Add typing overloads to `is_pyvista_dataset`

### PR DESCRIPTION
**Pull request by user27182**
### Overview

Follow-up to #6840. The overloads here are included as part of that PR.

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]
Thanks! Great to see using overload.

**Review by tkoyama010 — CHANGES_REQUESTED** [review]
@user27182 I talked to a friend in the Python community and they told me that the following pep might be the feature you are looking for. Could you please share your thoughts on this before merging?
https://peps.python.org/pep-0647/
https://peps.python.org/pep-0742/

**Comment by user27182** [comment]
> @user27182 I talked to a friend in the Python community and they told me that the following pep might be the feature you are looking for. Could you please share your thoughts on this before merging? https://peps.python.org/pep-0647/ https://peps.python.org/pep-0742/

Thanks for looking into this. Is this for solving the `DataSet` is not a `vtkDataSet` type issue? `TypeIs` looks to be useful, though I'm not sure if it can help here. `TypeIs` does type-narrowing, here I think we want something a bit different, more like registering `DataSet` as a subclass of `vtkDataSet` even though it isn't. [ABCMeta.register](https://docs.python.org/3/library/abc.html#abc.ABCMeta.register) could work but it is [not supported by mypy](https://github.com/python/mypy/issues/2922).

**Comment by user27182** [comment]
Or are you suggesting using `TypeIs` for this PR? Instead of or in addition to the overloads?

**Review by tkoyama010 — APPROVED** [review]
Thank you for your comments. I just wanted to get your opinion on this for my own future inspirations. Not being implemented in mypy, etc. is indeed a major barrier. Let's keep this PR as it is.

**Pull request merged**
