### PR TITLE
:heavy_plus_sign: PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by tkoyama010**
Subject: :heavy_plus_sign: PULL_REQUEST_TEMPLATE.md

### Feature or Bugfix
- Feature

### Purpose
- Add PULL REQUEST TEMPLATE to make it easy to review.

### Relates
- I referenced template from [sphinx project](https://github.com/sphinx-doc/sphinx/blob/2.0/.github/PULL_REQUEST_TEMPLATE.md).

### CODE REVIEW

**Comment by tkoyama010** [comment]
If you have any opinions on usability, please let us know :eyes:

**Comment by GuillaumeFavelier** [comment]
I think it's a good idea @tkoyama010, thank you for adding this. I would vote to move it in `.github` though, what do you think @pyvista/developers ?

**Comment by tkoyama010** [comment]
@GuillaumeFavelier Thanks.

**Comment by akaszynski** [comment]
Agreed, looks good.

**Comment by GuillaumeFavelier** [comment]
Also out of curiosity, does the :heavy_plus_sign: icon is displayed correctly for you? I see only the raw text, maybe it's an issue with my browser or something.

**Comment by akaszynski** [comment]
Plus icon displays for me.  Might be a problem with your os 😛, @banesullivan.

**Comment by akaszynski** [comment]
Sorry, @GuillaumeFavelier, it works for me on chromium on Linux.  I had hoped it wasn't displaying right for @banesullivan since he used Mac, but no luck there :)

**Comment by banesullivan** [comment]
I'm using Safari and it doesn't render correctly...

Screen Shot 2020-02-10 at 10 24 30 AM


But it will if I change the title to actually have the emoji's character in it rather than the `:emoji:` syntax

**Comment by banesullivan** [comment]
But it does look correct in the commit... 

Screen Shot 2020-02-10 at 1 17 16 PM

**Comment by tkoyama010** [comment]
Thank you for merge.

**Pull request merged**
