### PR TITLE
Update `cartopy` feature download for GeoVista integration test 

### PR DESCRIPTION
**Pull request by user27182**
### Overview

~Revert~ Follow-up to #5452.

Attempt to fix current GeoVista integration test failures.

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]
LGTM

**Comment by user27182** [comment]
I'm getting a 404 error with the new link, so this probably won't work :/
https://raw.githubusercontent.com/SciTools/cartopy/main/tools/cartopy_feature_download.py

**Comment by tkoyama010** [comment]
@bjlittle Any ideas about this?

**Comment by user27182** [comment]
This does not fix the problem. I believe the issue stems from this issue with `shapely` and NumPy 2.1
https://github.com/shapely/shapely/pull/2099 

And NumPy 2.1 was [released yesterday](https://numpy.org/news/). So that would explain why this started breaking yesterday.

This PR is still good to merge though, as I think it's a proper fix for https://github.com/pyvista/pyvista/issues/5451

**Comment by bjlittle** [comment]
If this is causing issues then we could simply opt to not download the Cartopy assets?

I'm AFK ATM, so this might be a simple way to unblock things

**Comment by user27182** [comment]
A patch for `shapely` has been released. This should be automagically fixed soon once it makes it way to pypi https://github.com/shapely/shapely/releases/tag/2.0.6

**Comment by EwoutH** [comment]
It's on PyPI: https://pypi.org/project/shapely/

**Review by tkoyama010 — APPROVED** [review]
Thanks all !!!

**Pull request merged**
