### PR TITLE
add file drop functionality to BackgroundPlotter

### PR DESCRIPTION
**Pull request by akaszynski**
`BackgroundPlotter` now accepts dropped files.  Right now, it just adds the mesh directly to the plotter using no kwargs.  We need to add the option to have an object tree like `pyvista-gui` so we can change the way a mesh is plotted from within the GUI.

forpyvista

### CODE REVIEW

**Comment by banesullivan** [comment]
This is really awesome!!! With this, it would be huge to have an object tree that can control the scalars array that is plotted, opacity, representation style, etc. This could get complicated real quick.

**Comment by akaszynski** [comment]
I'll keep this open and add some of the features from `pyvista-gui` over to here.  True, it can get complicated, but it would be great if `pyvista` had a fully functional background plotter.

**Comment by GuillaumeFavelier** [comment]
I tested and it works well for me! Let me know when you think it's ready for reviews.

**Comment by akaszynski** [comment]
It’s ready now.  I’ll add in the other features (feature tree) later.

**Pull request merged**
