### PR TITLE
Add vtk 9.2 release candidate to ci

### PR DESCRIPTION
**Pull request by MatthewFlamm**
### Overview

Adds vtk 9.2.0* to CI as information only.  Unfortunately, the CI still will show a green check mark, so it requires manually checking the result.

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
Current failures with newer vtk have to be manually inspected, but the overall CI still passes.


5 currently failing tests:
https://github.com/pyvista/pyvista/runs/6991189698?check_suite_focus=true#step:10:2280

**Comment by adeak** [comment]
Most of those seem to be AttributeErrors, as expected. I can take a look at the numpy-smelling error from `tests/test_charts.py`.

**Comment by MatthewFlamm** [comment]
Not sure how long the run logs are available, so a short summary of the failing tests, unfortunately with cutoff lines:

```
=========================== short test summary info ============================
FAILED tests/test_charts.py::test_axis - ValueError: operands could not be br...
FAILED tests/test_filters.py::test_compute_cell_quality - AttributeError: 'vt...
FAILED tests/test_regression.py::test_compare_images_two_plotter_different - ...
FAILED tests/utilities/test_reader.py::test_read_hdf - AttributeError: 'NoneT...
FAILED tests/utilities/test_reader.py::test_hdf_reader - AttributeError: 'Non...
======= 5 failed, 1404 passed, 3 skipped, 2 xfailed in 431.83s (0:07:11) =======
```

**Comment by adeak** [comment]
Here's the result of a local run:
```
============================================================================================= short test summary info =============================================================================================
FAILED tests/test_charts.py::test_axis - ValueError: operands could not be broadcast together with shapes (11,) (0,)
FAILED tests/test_filters.py::test_compute_cell_quality - AttributeError: 'vtkmodules.vtkFiltersVerdict.vtkCellQuality' object has no attribute 'SetQualityMeasureToAspectBeta'
FAILED tests/test_regression.py::test_compare_images_two_plotter_different - assert 0.0 > 10000
FAILED tests/utilities/test_reader.py::test_read_hdf - AttributeError: 'NoneType' object has no attribute '_post_file_load_processing'
FAILED tests/utilities/test_reader.py::test_hdf_reader - AttributeError: 'NoneType' object has no attribute '_post_file_load_processing'
```

**Comment by adeak** [comment]
Heads-up: this PR might be superseded by https://github.com/pyvista/pyvista/pull/2863#discussion_r907174157 as per this comment thread and change.

**Comment by akaszynski** [comment]
Closing this in favor of #2863. Feel free to reopen.

**Pull request closed without merging**
