### PR TITLE
Fix PVD reader, allow no part

### PR DESCRIPTION
**Pull request by beroda**
### Overview
Resolves https://github.com/pyvista/pyvista/issues/3423

### Details

Set the default `part` attribute to 0 when missing from PVD file.

### CODE REVIEW

**Comment by beroda** [comment]
Unit tests failed because the PVD file is not yet merged in vtk-data. See https://github.com/pyvista/vtk-data/pull/24

**Comment by beroda** [comment]
Since https://github.com/pyvista/vtk-data/pull/24 has been accepted, how can I relaunch GitHub actions ?

**Comment by MatthewFlamm** [comment]
I reran tests, and some failures look real `tests/utilities/test_reader.py::test_pvdreader_no_part_group - FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/runneradmin/AppData/Local/pyvista_3/pyvista_3/Cache/PVD/paraview/dualSphereAnimation.zip.unzip\\dualSphereAnimation4NoPart.pvd'` or it might be a cache issue

**Comment by beroda** [comment]
I think it might be a cache issue, since locally on my laptop I had to delete the old unzipped folder inside my vtk-data cache location so that the new zip file (containing the new missing file) was correctly downloaded/unzipped from the vtk-data repo.

I don't really know how to fix this, has it seems to only affect windows but not python 3.8 ? Weird ...

**Comment by MatthewFlamm** [comment]
> I don't really know how to fix this, it is beyond my CI knowledge.
> It seems to only affect windows but not python 3.8 ? Weird ...

It is passing all Linux and MacOs tests, so it is something about windows path or filling naming I suspect.

**Comment by beroda** [comment]
> Edit: however if this is the case, it is curious since you've more or less copied the preceding test. I'll have my fingers crossed that when we can merge with main after the next PR merge that we find out that it is a cache issue.

I guess that the preceding test I copied was working because the zip file that was needed by the test was new to `vtk-data`. Therefore, Pooch downloaded-it and unzipped it for all CIs because it could not find it in its registry.

In the current case, I had to modify the zip file in order to add another pvd file. And because we don't check the hash of files in `examples/downloads.py` (see comments at line 83) , Pooch never updates the zip file (at least for Windows ?).
I might be wrong since I am a Pooch beginner (only read the some small parts of the doc) but it seems logical to me.

Maybe we should delete all downloads when starting a new CI action ? (at least for Windows CI ?). There is a `examples.delete_downloads()` command available in pyvista.

**Comment by MatthewFlamm** [comment]
Im not that familiar of why we have these caches for the downloads, but I'm wondering whether we need to separate the caches according to os, currently they all use the same key.

https://github.com/pyvista/pyvista/blob/72c7d62ea01ec61c73d5970215d4aa5d84d11d8e/.github/workflows/testing-and-deployment.yml#L247

**Comment by beroda** [comment]
I am not familiar with github actions and I have no idea how to deal with these fails.

**Comment by akaszynski** [comment]
Working on this one locally.

**Comment by akaszynski** [comment]
> Im not that familiar of why we have these caches for the downloads, but I'm wondering whether we need to separate the caches according to os, currently they all use the same key.

Potentially, yes. Strangely, the test above this one `test_pvdreader_no_time_group`, doesn't fail.

Skipping this until I get my hands on a windows box.

**Review by akaszynski — APPROVED** [review]
LGTM.

**Review by MatthewFlamm — APPROVED** [review]
Nice!

**Pull request merged**
