### PR TITLE
Add widgets support

### LINKED ISSUE #328: add widgets in the render window for filtering
I would like to add to be able to edit the distance q in the viewer as user input. How can I make this work? The pts_array takes only the rows that are <=q.

This is what I have written:
image

### PR DESCRIPTION
**Pull request by banesullivan**
This adds box, plane, and line widgets that can be leveraged via callback functions. Several helper methods are also implemented to use the widgets for tasks like clipping, slicing, and thresholding.

Example of box clipping:

```py
from pyvista import examples
import pyvista as pv

mesh = examples.download_st_helens().warp_by_scalar()

p = pv.Plotter(notebook=False)
p.add_mesh(mesh, name='mesh')

def callback(box):
    clipped = mesh.clip_surface(box)
    p.add_mesh(clipped, name='mesh')
    
p.enable_box_widget(callback=callback)

p.show()
```

Ping @jsfraser1

- Resolve #328

### CODE REVIEW

**Comment by banesullivan** [comment]
And now there's a convienance method (`add_mesh_clip_box()`) that is just like `add_mesh` but a box widget can clip it and update the mesh:
 
```py
from pyvista import examples
import pyvista as pv

mesh = examples.download_st_helens().warp_by_scalar()

p = pv.Plotter(notebook=False)
p.add_mesh_clip_box(mesh)
p.show()
```

**Comment by banesullivan** [comment]
And also a plane widget!

```py
import pyvista as pv

mesh = pv.Sphere()

p = pv.Plotter(notebook=False)
p.add_mesh_clip_plane(mesh, opacity=0.5, normal=(1,0,1))
p.add_axes()
p.show()
```

**Comment by banesullivan** [comment]
And a slicing widget!

```py
from pyvista import examples
import pyvista as pv

p = pv.Plotter(notebook=False)

p.add_mesh_slice(mesh, normal='x')

p.add_axes()
p.show()
```

**Comment by banesullivan** [comment]
Here's another pretty cool example of using a widget to define a source location in a simulation - I use the `streamlines` filter to integrate a vector field in a model given a line source of points:

```py
from pyvista import examples
import pyvista as pv
import numpy as np

pv.set_plot_theme('doc')

mesh = examples.download_kitchen()
furniture = examples.download_kitchen(split=True)

arr = np.linalg.norm(mesh['velocity'], axis=1)
clim = [arr.min(), arr.max()]

p = pv.Plotter(notebook=False)
p.add_mesh(furniture, name='furniture', color=True)
p.add_mesh(mesh.outline(), color='black')
p.add_axes()

def simulate(pointa, pointb):
    streamlines = mesh.streamlines(n_points=10, max_steps=100,
                                   pointa=pointa, pointb=pointb,
                                   integration_direction='forward')
    p.add_mesh(streamlines, name='streamlines', line_width=5,
               render_lines_as_tubes=True, clim=clim)
    
p.enable_line_widget(callback=simulate, use_vertices=True)
p.show()
```

**Comment by banesullivan** [comment]
Should the `callback` arguments be mandatory since the widgets are useless without a callback function?

**Comment by akaszynski** [comment]
This is really cool!

**Comment by banesullivan** [comment]
@akaszynski - what do you think of the function names:

- `add_mesh_clip_box`
- `add_mesh_clip_plane`
- `add_mesh_slice`

These helpers both add a mesh to the scene and enable a widget to update that mesh... I'm not sure how we should name those methods

**Comment by laserman781** [comment]
Is there a way you can apply these clips or widgets to multiple meshes at once?

**Comment by banesullivan** [comment]
> Is there a way you can apply these clips or widgets to multiple meshes at once?

The best way would be to use a `MultiBlock` dataset. At first, I didn't support this, but I just fixed the issues with it and will post a release today as there was a serious bug with the plane widget that needs to be resolved.

**Comment by banesullivan** [comment]
Reference 36cab08

**Comment by leminhson** [comment]
Is it possible to disable / hide all normal vectors of the clip plane ? I need this method because, when I apply set_scale to the plotter, the corresponding normal vector is scaled as well and it will be distorted.

In addition, sometime we do not want users to rotate the clip plane, only slide them along the axis.

**Comment by banesullivan** [comment]
@leminhson, can you open a new issue for these feature requests, please? 

There are some current workarounds I'd be happy to elaborate on in a new issue focus to that specific topic.

**Pull request merged**
