### PR TITLE
Add bounds to view methods on renderer

### PR DESCRIPTION
**Pull request by MattTheCuber**
### Overview

This pull request add a keyword argument, `bounds` to the renderer view methods.

Relates to #5692 

### Details

In #5692 I was directed to use `pl.reset_camera(bounds=scene_bounds)`. This works great, but I also need to use `pl.view_isometric()` which does not have a `bounds` argument. This PR adds that.

### CODE REVIEW

**Review by tkoyama010 — CHANGES_REQUESTED** [review]
@MattTheCuber Thanks for this! Cloud you provide a sample code for this?
I want to add it to the test.

**Comment by MattTheCuber** [comment]
> @MattTheCuber Thanks for this! Cloud you provide a sample code for this? I want to add it to the test.

Here is an example using trame:

``` python
import pyvista as pv
import trame.widgets.vuetify3 as v3
from pyvista.trame.ui import plotter_ui
from trame.app import get_server
from trame.ui.vuetify3 import SinglePageLayout

pv.start_xvfb()
pv.OFF_SCREEN = True
pv.set_plot_theme("paraview")

server = get_server(client_type="vue3")
state, ctrl = server.state, server.controller


small_mesh = pv.Sphere(center=(0, 0, 1))
large_mesh = pv.Plane(i_size=100, j_size=100)

# Add regular meshes normally
pl = pv.Plotter()
pl.add_mesh(small_mesh)

# The large mesh should be added as an actor
large_mesh_actor = pv.Actor(mapper=pv.DataSetMapper(large_mesh))
pl.add_actor(large_mesh_actor)

# use vtk methods directly to compute bounds of the scene ignoring the large mesh actor
large_mesh_actor.visibility = False
scene_bounds = pl.renderer.ComputeVisiblePropBounds()
large_mesh_actor.visibility = True


def reset_camera():
    pl.reset_camera(bounds=scene_bounds)


def view_isometric():
    pl.view_isometric(bounds=scene_bounds)


with SinglePageLayout(server) as layout:
    with layout.toolbar:
        v3.VBtn("Reset Camera", click=reset_camera)
        v3.VBtn("Isometric View", click=view_isometric)
    with layout.content:
        view = plotter_ui(pl, add_menu=True)

server.start()
```

**Review by tkoyama010 — APPROVED** [review]
LGTM. Thanks!

**Comment by tkoyama010** [comment]
@pyvista-bot preview

**Pull request merged**
