### PR TITLE
🚧 Add type hints to majority of public core methods.

### PR DESCRIPTION
**Pull request by JevinJ**
### Overview

Type hints(added in 3.5), make it easier for the user and IDEs to determine parameter and return types of functions, especially if there is no explicit documentation. 

It should also be possible to have the types automatically added to documentation. https://pypi.org/project/sphinx-autodoc-napoleon-typehints/

This adds type hints to most of the public methods in /core/. Please ensure that pyvista.Texture is the correct type for the texture related methods in common.py, I'm unsure if it's that or vtk.vtkTexture.

### CODE REVIEW

**Comment by JevinJ** [comment]
@banesullivan Sure.

**Comment by banesullivan** [comment]
I've always stayed away from type hinting in Python. IMO it does not add any advantage, tangible benefit, or reassurances to the API. Also, I personally play loose and fast with Python's lack of restrictions and duck-typing which is probably reflected throughout much of PyVista as my priority in contributing to PyVista was to create an API that would *just work* even when a user threw a variety of different scenarios (arguments) at the code (e.g. the `plot()` function can handle a ton of different data types).

Another qualm: what about keyword arguments?... type hinting tends to not play well with `kwargs`, right?

I don't want this to convey that I am not open to type hinting in PyVista down the road; if we do it, I want to make sure we do it right and completely. I'd hate for us to have half of the API type-hinted and then no one maintaining/enforcing those hints. It'd be better (IMO) to do the entire API at once and then enforce a strict type hinting policy for new PRs (this sort of thing might warrant a bit of refactoring and a MINOR release in itself)

In the meantime, I am much more in favor of well-written docstrings as you get the exact same benefit with generated documentation as you would with type hinting.

**Comment by JevinJ** [comment]
For input arguments and kwargs/args I kind of agree the benefit is minimal, especially if you have obvious names. But the return type hint is usually the more useful. In my IDE(PyCharm) in some cases auto completion doesn't work without the return type hint, it's happened quite a few times and I have to go back and check what I'm working with. 

As an example:

https://medium.com/@shamir.stav_83310/the-other-great-benefit-of-python-type-annotations-896c7d077c6b

**Comment by banesullivan** [comment]
Thanks, I'll have to give that a read! Also @tkoyama010's https://github.com/pyvista/pyvista/issues/288#issuecomment-584454361

**Comment by akaszynski** [comment]
I'm not used to using type hints, but for the code that I've used that has them, it does cleanup autocompletion.  Additionally, we could use `mypi` to improve our CI.

While adding this will take some time, as our codebase expands type hints will make the code easier to maintain.  I agree with @banesullivan; if we do this, we do it for everything and then add the code style to `contributing`.

There's no urgency to this at the moment, and we shouldn't have this out for `0.25.0`.

**Comment by akaszynski** [comment]
Looking at old PRs and I think that we should implement type hinting, especially since `numpy` [seems to be doing it](https://numpy.org/devdocs/reference/typing.html).

@JevinJ, you fine with implementing this?  Maybe for 0.28.0, which I'd like to have out in a week or two.

Actually, the more I read about type hinting, the more I think we should implement it.  In fact, we might even be able to use [pytype](https://github.com/google/pytype) for code verification.  This seems like a really cool feature to have for this project.

In the end, I don't want to require typehinting, but considering how many people use pycharm, I think it's a good idea to at least encourage it.

**Comment by JevinJ** [comment]
@akaszynski Yeah I can start a new PR in a day or two.

**Comment by akaszynski** [comment]
@JevinJ, I'll let you pull the trigger on this since we're moving towards smaller PRs for implementing this (along with `mypy` testing`).  Please close this at your convenience.

**Pull request closed without merging**
