### PR TITLE
Small change to avoid raising exception

### PR DESCRIPTION
**Pull request by germa89**
Small change to avoid raising an exception.

### CODE REVIEW

**Comment by adeak** [comment]
Thanks for the PR! Do you mean that there was a bug that caused an error here in certain situations?

**Comment by germa89** [comment]
> Thanks for the PR! Do you mean that there was a bug that caused an error here in certain situations?

No, but I was debugging another package allowing "caught exceptions" and I saw this one, which was quite easy to fix.

**Comment by adeak** [comment]
OK, thank you. I wasn't sure if there was some edge case I was missing :)

**Review by adeak — APPROVED** [review]
Looks good to me, thanks again. This is a lot more readable.

**Pull request merged**
