### PR TITLE
BUG: test_read failures

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR tries to reproduce `test_read` failures encountered in: https://github.com/pyvista/pyvista/pull/619#issuecomment-587566464

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
I'm able to reproduce in here but I can't fix it at the moment @pyvista/collaborators

**Comment by akaszynski** [comment]
I'll have time to work on this later this evening.

**Comment by GuillaumeFavelier** [comment]
It seems related to the brand new release of `meshio 4.0.1`:

image

I mitigated locally in #619 by changing the requirements but we probably need to catch up to some changes in the API

**Comment by akaszynski** [comment]
Thanks @GuillaumeFavelier, I've got a moment to work on this now.

**Comment by GuillaumeFavelier** [comment]
@akaszynski you can take a look at #621, @keurfonluu started working on it I think

**Comment by akaszynski** [comment]
I see that.  Ok.  Should we abandon this branch then and merge his first?

**Comment by GuillaumeFavelier** [comment]
I'm totally fine with closing this. The original intention was to reproduce the issue.

**Pull request closed without merging**
