### PR TITLE
[TESTING] Replace AppVeyor with Azure

### PR DESCRIPTION
**Pull request by banesullivan**
Adds Azure windows testing because AppVeyor is regularly a pain to deal with.

Azure allows collaborators where AppVeyor does not

### CODE REVIEW

**Comment by banesullivan** [comment]
@GuillaumeFavelier  - It looks like the issues from #309 are an AppVeyor issue - Azure is giving the green light so far

**Comment by akaszynski** [comment]
Wow!  This is great!

**Comment by banesullivan** [comment]
Assuming this is all working, then I'll delete the AppVeyor script.

@akaszynski - do you remember why we don't test any Qt plotting with Windows?:

https://github.com/pyvista/pyvista/blob/c3038b7e3b3d588589a355e488046abc43586c22/appveyor.yml#L42

**Comment by akaszynski** [comment]
Couldn’t get pyqt5 to import on windows without installing additional dependancies.

**Comment by banesullivan** [comment]
One thing that's currently missing - how do I test both the branch and the PR? Travis does this where it checks out the branch from the PR and runs the tests but also merges the branch into the base branch and runs the test as two separate builds.

**Pull request merged**
