### PR TITLE
Add Numerical Tours of Computational Mechanics with FEniCSx

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

Add awesome external example of Numerical Tours of Computational Mechanics with FEniCSx by @bleyerj.
[image](https://bleyerj.github.io/comet-fenicsx/)

### Details

- https://bleyerj.github.io/comet-fenicsx/

### CODE REVIEW

**Comment by tkoyama010** [comment]
@pyvista-bot preview

**Comment by tkoyama010** [comment]
Pinnig @akaszynski @adtzlr interested in computational mechanics

**Comment by tkoyama010** [comment]
@pyvista-bot LGTM

**Comment by adtzlr** [comment]
> Pinnig @akaszynski @adtzlr interested in computational mechanics

Thanks for the reference! I've seen already a post on another platform from @bleyerj and wrote him a *thanks* message for writing such great articles 🚀.

**Pull request merged**
