### PR TITLE
Update master to main in README

### PR DESCRIPTION
**Pull request by MatthewFlamm**
### Overview

Master to main fix in README

 

### Details

- < feature1 or bug1 description >
- < feature2 or bug2 description >

### CODE REVIEW

**Comment by adeak** [comment]
How do you feel about taking care of every `master` -> `main` change while we're at it?

I've gathered what I believe would be false positives in `git grep master` in https://github.com/pyvista/pyvista/issues/1389#issuecomment-866054541

**Comment by MatthewFlamm** [comment]
I very much misread that comment.  I thought those were the list of remaining references to master, and they all didn't need to be changed.  That clearly isn't what you wrote. There are quite a few changes to make, so I'll close this as I don't have time to get to a more thorough parsing in the next few days.  It makes sense to do it all in one PR.

**Comment by adeak** [comment]
Sorry, I should probably have also been clearer myself :) I also only had time to glance at the workload. It's not huge but more than what's available.

We can get back to this when we have the time.

**Comment by MatthewFlamm** [comment]
I think I got sidetracked by the dawizards link 😜

**Pull request closed without merging**
