### PR TITLE
Grab screenshot when plotter is closed

### PR DESCRIPTION
**Pull request by banesullivan**
This adds support for the `BackgroundPlotter` with sphinx-gallery

ping: @GuillaumeFavelier 

I'm running into issues controlling the size of the window when using the `BackgroundPlotter` with sphinx gallery... its always super small

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Thanks foir this! I'll try the work on my end and see what happens.

**Comment by GuillaumeFavelier** [comment]
I created a quick example `bgplot.py` and built the doc locally. So if I change the size before adding a mesh I obtain the following:

image

But if I change the window size after, I got an empty frame:

image

I will investigate further and meanwhile I whill push the example on this branch to share our results.

**Comment by GuillaumeFavelier** [comment]
Nevermind, when I cleaned the cache inside `docs/` with :

```sh
$ make clean
$ rm -r examples errors.txt images/auto_generated
```
and re-built everything:

```sh
$ make doctest
$ make html
```

Then it worked for me. What about you @banesullivan ?

**Comment by banesullivan** [comment]
I think this is good to go. All good from you @GuillaumeFavelier?

**Comment by banesullivan** [comment]
Let's get rid of that example and maybe add a better `BackgroundPlotter` example down the road to showcase the callback function to help users figure out how to use the `BackgroundPlotter` like in #387

**Comment by banesullivan** [comment]
Thanks, @GuillaumeFavelier - once the tests pass, I'll merge

**Pull request merged**
