### PR TITLE
Make intersphinx update script more robust

### PR DESCRIPTION
**Pull request by adeak**
https://github.com/pyvista/pyvista/pull/2285 introduced a broken SciPy intersphinx mapping file, because the URL changed and the older path became a redirect (see also https://github.com/scipy/scipy/issues/14267). `curl` doesn't follow redirects automatically so instead of the intersphinx mapping file the redirect's HTML response was saved instead.

In hindsight the -88 KB change of the corresponding file at https://github.com/pyvista/pyvista/pull/2285/files is suspicious, but I wouldn't have noticed this either.

I've updated every intersphinx mapping while I'm at it.

### CODE REVIEW

**Review by MatthewFlamm — APPROVED** [review]
LGTM

**Comment by bskinn** [comment]
FYI: In case you didn't see it, scipy [implemented a full docs layout fix](https://github.com/scipy/scipy/issues/14267#issuecomment-1133138841). This includes fixing the aberrant hosting location of the v1.8.0 docs, so if you have anything pointing specifically to 1.8.0, it'll need an update.

**Comment by adeak** [comment]
Thanks a lot @bskinn. I did see it today on the SciPy mailing list, but haven't had the time yet to look into this regarding PyVista. After a cursory glance earlier today it seemed to me that we don't even _use_ any SciPy intersphinx links (but we could/should in a few places which I intend to look into).

**Comment by adeak** [comment]
According to https://github.com/scipy/scipy/issues/14267#issuecomment-1133874666 we are using the correct final intersphinx URL as of this PR.

**Pull request merged**
