### PR TITLE
Skip action workflows on `no-ci/*` branches

### LINKED ISSUE #2062: Update GH Actions to ignore some branches
We follow [a branch naming scheme](https://github.com/pyvista/pyvista/blob/main/CONTRIBUTING.md#branch-naming-conventions) and should probably ignore building/publishing on some branches: e.g., `junk/`, `maint/`, `doc/`, `no-ci/`.

We can do this by adding an `branches-ignore` list to the `push` trigger:

```yml
on:
  push:
    branches-ignore:
      - 'no-ci/**'
```

For each of the Actions, we should evaluate which, if any, branches should be ignored.

For example. On `doc/` we may not want/need the core API tests.

### PR DESCRIPTION
**Pull request by banesullivan**
Resolve #2062

This utilizes the `branches-ignore` field of the `pull_request` trigger to limit which jobs are run depending on [the branch naming convention](https://github.com/pyvista/pyvista/blob/main/CONTRIBUTING.md#branch-naming-conventions)

### CODE REVIEW

**Review by tkoyama010 — APPROVED** [review]
LGTM. It is a good idea to add this.

**Comment by banesullivan** [comment]
Huh. this isn't working...

**Comment by banesullivan** [comment]
The docs for this were super misleading to me: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-branches-and-tags

[This thread](https://github.community/t/branches-ignore-filter-not-working-for-pull-request-events/166746) makes it clear that this condition is evaluating on the base branch rather than the push branch... I'd rather not muck up the workflows with a bunch of `if:` conditions to handle this

**Comment by banesullivan** [comment]
We could switch our actions to be `push` triggered... I typically like using only `on: [pull_request]` though

**Comment by banesullivan** [comment]
Take a look at how verbose and error-prone these conditionals can become in #2092

**Comment by banesullivan** [comment]
I've updated this PR to skip testing and docs building on ``no-ci/*` branches

**Comment by akaszynski** [comment]
Calling this good to go despite the missing checks, which is as intended.

**Comment by banesullivan** [comment]
Turns out this isn't working...

**Pull request merged**
