### PR TITLE
Bump pydata-sphinx-theme from 0.9.0 to 0.10.1 and fix warnings

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

Fix deprecated warning of #3236 .
 

closes #3236 

### Details

- https://github.com/pydata/pydata-sphinx-theme/pull/878

### CODE REVIEW

**Comment by banesullivan** [comment]
@tkoyama010, can you do this directly in #3236 ?

**Comment by adeak** [comment]
> @tkoyama010, can you do this directly in #3236 ?

@banesullivan I recommend against doing that. I think there's great value in knowing that dependabot PRs are trivial for what they are: version bumps. If changes are necessary to accommodate version bumps, have a dedicated PR that does that. It's great for transparency, it's great for `git bisect`, it's the right call in my opinion.

**Comment by banesullivan** [comment]
Fair enough -- I typically like to see any needed changes included in the dependabot PRs. My typical mode of operation is to let Dependabot bump the deps, if it fails, make the changes in that existing PR, squash and merge to see the bump and the needed changes together. This is just how I, personally, like to manage dependency issues.

Whichever approach we take is unimportant. If you all prefer, we can keep the changes here, we just need to close #3236 then

**Comment by adeak** [comment]
> If you all prefer, we can keep the changes here, we just need to close #3236 then

Why do we have to close that?

**Comment by banesullivan** [comment]
The version of the package *has* to be bumped with these changes (AFAICT) due to the API changing at that version. Also, I think it's cleaner to have the bump and the needed changes for the bump all in the same PR and thus same commit

**Comment by banesullivan** [comment]
> Did the newest version introduce the non-deprecated alternative?

Even if so, IMO, we should track all of this in a single PR since we pin our dependencies for a cleaner history

**Comment by banesullivan** [comment]
Actually, the issue is that we run `make html` with the `-W` flag to turn warnings/deprecations into errors. So if we bump there version, we have to include the needed changes. And we can't just merge the needed changes, because that part of the API doesn't exist in the previous version

**Comment by banesullivan** [comment]
> I'd prefer this PR for my aforementioned reasons

Fair enough! I added a `closes` command to the root description to supersede #3236

**Review by banesullivan — APPROVED** [review]
Thank you for handling this, @tkoyama010!!

**Pull request merged**
