### PR TITLE
🚧 Orthographic Slicer

### LINKED ISSUE #111: Orthographic Slicer
I'd like to implement a new orthographic slicer where I use a 2 by 2 multi-window plotter. 

Features needed:

- [x] ability to enable a 2D perspective (3 of 4 renderers need to be 2D)
- [x] convenience methods for orienting camera to view certain planes (XY, XZ, YZ) (see #115)
- [ ] capture scroll event for moving the slicing planes
- [x] ability to lock the camera view for a renderer so the user cannot change it (see #115)

## Starting Point

```py
import vtki
from vtki import examples

data = examples.load_uniform()
data.set_active_scalar('Spatial Cell Data')

slices = data.slice_orthogonal()

# Orthographic Slicer

p = vtki.Plotter(shape=(2,2), notebook=False)

p.subplot(1,1)
p.add_mesh(slices, clim=data.get_data_range())

p.subplot(0,0)
p.add_mesh(slices['XY'])
p.view_xy()
p.disable()

p.subplot(0,1)
p.add_mesh(slices['XZ'])
p.view_xz(negative=True)
p.disable()

p.subplot(1,0)
p.add_mesh(slices['YZ'])
p.view_yz()
p.disable()

p.show()
```

download

## Goal

I want this to behave similarly to ParaView's orthographic slicer:

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by banesullivan**
A new tool for orthographically slicing meshes which is a subclass of `Plotter`. Resolves #111.

Todo:

- [x] make the 3 views of the slices have a parallel projection (2D)
- [ ] add lines in each view to show locations of other slices (see #111 and the gif from ParaView for an example) - the code is there, it causes the plotter to get hung though; not sure why.
- [ ] should we use a sphere widget or plane widgets?
- [x] show axes grid in 2D views by default

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_channels()

plotter = pv.OrthographicSlicer(mesh)
plotter.show()
```

### CODE REVIEW

**Comment by mtkilic** [comment]
is Orthographic Slicer supports embeddable 3D rendering in Jupyter notebook?

**Comment by banesullivan** [comment]
At the moment, no - we'd need to update the converter to `panel` in order to put each renderer into their own `pane`. This is doable and would likely be encompassed in https://github.com/pyviz/panel/issues/408

**Comment by banesullivan** [comment]
@mtkilic: the `OrthogonalSlicer` might be of interest to you: https://docs.pyvista.org/tools/ipy_tools.html#orthogonal-slicer

slicer-tool

**Comment by mtkilic** [comment]
@banesullivan `OrthogonalSlicer` is exactly what I am looking for, however plot is not embedded in jupyter notebook.  My goal is upload my notebook to cloud, where people can launch instance of jupyter and run the code. So in that case server and client will be two different machine, because of this I need everything to be done on browser.

**Comment by banesullivan** [comment]
@mtkilic - how familiar with VTK are you? Is your dataset by chance `vtkImageData` (`pyvista.UniformGrid`)? If so, there is a tool that might work for you: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets

**Comment by mtkilic** [comment]
@banesullivan not so much, but lately I have been testing libraries powered by VTK. My dataset is 3D numpy array (seismic data). Thank you for sharing to tool. I will see if I can convert my numpy array to `vtkImageData`

**Comment by banesullivan** [comment]
The `pyvista.UniformGrid` class is an instance of `vtkImageData` - we directly inherit VTK types. You should see this example: https://docs.pyvista.org/examples/00-load/create-uniform-grid.html

**Comment by banesullivan** [comment]
This PR will sit until #268 is complete - as this is clearly needed in notebooks

**Comment by banesullivan** [comment]
Finally revisiting this...

I reimplemented this tool to use the new widgets (specifically a sphere widget) to choose the location of where the three slices should intersect.

```py
import pyvista as pv
from pyvista import examples

slicer = pv.OrthographicSlicer(examples.load_uniform(), 
                                 show_bounds=True)
```

**Comment by banesullivan** [comment]
And now I have reimplemented this as a subclass of `pyvista.Plotter` so that a user could add more data to the scene if they'd like:

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_channels()

plotter = pv.OrthographicSlicer(mesh)
plotter.show_grid()
plotter.add_mesh(mesh.threshold(3))
plotter.show()
```

**Comment by banesullivan** [comment]
@prisae, I'd love to hear your thoughts on this and if you think having a sphere widget like that is useful (I implement it using a sphere because it required minimal effort using the previous version of this)

Also, is it straightforward how one might use this as a subclass of `pyvista.Plotter`?

**Comment by prisae** [comment]
Yes, I think such a widget would be great!
- I assume it is not straight forward the collocate the three subplots, like in the 3d_slicer in discretize? 3d_slicer
- If not, it might still helpful if the axis would be synchronized. E.g., top-left and bottom-left plots start end end now at different x-positions; if these could be synchronized, it would probably make interpretation easier. 

Definitely cool. However, I am not sure I follow you with your last question though (subclassing of Plotter), can you make an example?

**Comment by banesullivan** [comment]
> I assume it is not straight forward the collocate the three subplots, like in the 3d_slicer in discretize? 

Unfortunately not straightforward at all... there are many workarounds to achieve this, but they get messy. One solution would actually be to have a Qt window with four frames and only the bottom right be the 3D PyVista view with the widgets, then convert the slices to a something that could be plotted with Matplotlib (see https://github.com/pyvista/pyvista-support/issues/70) and display matplotlib collocated figures in the other three frames just like you have in discretize.

> f not, it might still helpful if the axis would be synchronized. E.g., top-left and bottom-left plots start end end now at different x-positions; if these could be synchronized, it would probably make interpretation easier.

Ah, I think I am displaying the plots from the wrong angle... I'll fix

> Definitely cool. However, I am not sure I follow you with your last question though (subclassing of Plotter), can you make an example?

All I meant was that this class is a subclass of the `pyvista.Plotter` which means you can slice a single mesh and you can and any other dataset to the main 3D window by calling any method on it like you would if you were normally plotting with PyVista. I.e. you could turn something like this:

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_channels()

p = pv.Plotter(notebook=False)
p.add_mesh_slice_orthogonal(mesh)
p.add_mesh(mesh.threshold(3))
p.show()
```




into a new window like this with only changing 2 lines of code (when you instantiate the plotter):

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_channels()

p = pv.OrthographicSlicer(mesh)
p.add_mesh(mesh.threshold(3))
p.show()
```




And of course, you could change. that to add other meshes like topography, etc. instead of just thresholding the mesh.

**Comment by banesullivan** [comment]
The views have been fixed:

```py
import pyvista as pv
from pyvista import examples

mesh = examples.load_channels()

p = pv.OrthographicSlicer(mesh)
p.show()
```

Screen Shot 2019-10-17 at 8 00 13 PM

**Comment by banesullivan** [comment]
I’m not going to have the time to finish this properly and I don’t know if anyone would really use this, so I’m closing. To anyone coming back to this: feel free to adopt as you please!

**Pull request closed without merging**
