### PR TITLE
Add enable_stereo_render() and disable_stereo_render()

### LINKED ISSUE #1585: Add Stereo API to Pltoter
See https://github.com/pyvista/pyvista/discussions/1583

Would be nice to have:

```py
p = pv.Plotter(notebook=True)
p.add_mesh(pv.Cube())
p.enable_stereo_render()
p.show()
```

### PR DESCRIPTION
**Pull request by puripant**
### Overview

Following the example in #1583 I added two functions `enable_stereo_render()` and `disable_stereo_render()` to Plotter to support Stereo API. This should resolve #1585  

### Details

- `enable_stereo_render()` to enable stereo rendering
- `disable_stereo_render()` to disable stereo rendering and follow the existing pattern of `enable_*` and `disable_*`. Not sure if it is necessary though.

### CODE REVIEW

**Comment by puripant** [comment]
1. Sure, I can add tests for these functions. Do I understand correctly that they should be similar to the docstring examples except the last line `pl.show(before_close_callback=verify_cache_image)`?
2. The results with stereo rendering enabled and disabled are as follows
enable_stereo
disable_stereo
.

**Comment by adeak** [comment]
> Do I understand correctly that they should be similar to the docstring examples except the last line pl.show(before_close_callback=verify_cache_image)?

That sounds reasonable to me, I don't think we can do any better than checking the figures to the cache. Just check that the baseline images make sense when you add them. And I'd try exaggerating the perspective for the images, to make the anaglyph effect more pronounced if possible. One way I could find was setting `plotter.camera.distance = 0.1`. The larger the visual effect of the anaglyph stereo, the more likely it is that our test suite will catch breakage. (Wonkier hacks include `plotter.camera.SetEyeAngle(50)` but I'd avoid that because it uses VTK stereo functionality outside the implemented API.)

**Comment by adeak** [comment]
@tkoyama010 just to double-check the CI changes here, @akaszynski said something about xvfb breaking builds. This might be unrelated, I just want to make sure that he knows we're touching this in this seemingly unrelated minor PR (I wouldn't expect the change to be harmful).

**Comment by puripant** [comment]
> @puripant In plotting tests, we need to add images to `image_cache` directory. Can you add the following files?
> 
> ```shell
> /tests/plotting/image_cache/disable_stereo_render.png
> /tests/plotting/image_cache/enable_stereo_render.png
> ```

Thank your for pointing this out. At first, I thought the tests would create test images in their first run. I have just committed images in `image_cache` and also edited the test codes as suggested. Please let me know if I need to add anything else.

**Comment by adeak** [comment]
> At first, I thought the tests would create test images in their first run. 

That is exactly what happens. So in order to use them as benchmarks, new versions of these images must be added to version control, so that when someone runs the tests (including CI) they are already there to compare.

**Comment by adeak** [comment]
This was closed by unfortunate phrasing in https://github.com/pyvista/pyvista/pull/1728, reopening.

**Comment by puripant** [comment]
> Please merge main branch after #1728 is merged. CI will be pass after it and we can merge this to main branch.

CI has passed. I still have no permission to merge to the main branch though.

**Comment by tkoyama010** [comment]
@puripant I merged. Thanks for your great contribution!

**Pull request merged**
