### PR TITLE
Rename local intersphinx inventories, add pyvistaqt

### PR DESCRIPTION
**Pull request by adeak**
It turns out that pyvistaqt already has intersphinx hooked up, so https://qtdocs.pyvista.org/objects.inv is absolutely a thing. We just have to tell that path to sphinx to make our cross-referencing work (e.g. in doc/user-guide/simple.rst).

Side note: we locally store these object.inv files under the path `doc/intersphinx/library-inv.txt`. Any willingness to change this? `.txt` suggests text files, but these are very much binary files (4 human-readable ascii lines and then a zlib-compressed binary blob containing the references). Would it be OK to change these to `doc/intersphinx/library-object.inv` (because naming things is hard)?

### CODE REVIEW

**Comment by adeak** [comment]
cc @MatthewFlamm because I think you named these files :)

**Comment by MatthewFlamm** [comment]
I'm for renaming the suffix.  I followed the intersphinx documentation, but it is weird with `.txt` if only because the online file has a `.inv` file type.  

Can you also change https://github.com/pyvista/pyvista/blob/959cbaceb844e59941e6c0a70bb3d9819b44f948/.github/workflows/intersphinx-update-pull-request.yml#L28 if you do so?  We should probably have a comment on `conf.py` to keep this file up to date as well.

**Comment by adeak** [comment]
Yeah, sure, I intended to keep all related machinery updated. If @akaszynski also agrees we can go forward. Thanks for the feedback.

**Comment by akaszynski** [comment]
> Yeah, sure, I intended to keep all related machinery updated. If @akaszynski also agrees we can go forward.

Yep, I'm fine with changing the names.  I didn't even realize that they weren't binary.

**Comment by akaszynski** [comment]
We still have to update the inventory files.  @adeak, if you're busy I can get to this tonight.

**Comment by adeak** [comment]
Bah, of course, sorry. I'm just about to go to bed so if you want to merge this in the next 12 hours then yes, please do.

**Review by akaszynski — APPROVED** [review]
Looks good to me.  Feel to check over and then merge.  Planning to draft release tomorrow provided #1557 is merged.

**Pull request merged**
