### PR TITLE
Make line breaks consistent.

### PR DESCRIPTION
**Pull request by JevinJ**
### Overview

Make line breaks consistent in all modules by using PEP8 recommendation. (1 line break between class methods)

Depends on #736

### CODE REVIEW

**Comment by banesullivan** [comment]
I've always used 2 blank lines between functions as I thought that was PEP8 - looking at PEP8 guidelines, its vague but I think 1 line is actually the standard? If we do this, we need to do it everywhere at once and enforce the convention moving forward.

**Comment by akaszynski** [comment]
It’s somewhat confusing, but it’s two blank lines between functions and classes, and one blank line between methods in a class.

Here’s something in more plain English. 
https://realpython.com/python-pep8/#blank-lines

**Comment by JevinJ** [comment]
As I've known it:

Between methods in a class - 1

Between imports and free function or class - (I think this is 1 but I'm not sure)

Between classes - 2

Between free functions - 2

**Comment by banesullivan** [comment]
@JevinJ, can you please add those guidelines to the CONTRIBUTING.md wherever you feel appropriate as a part of this PR and see how much more of these lines you can knock out?

**Comment by JevinJ** [comment]
Both done, please check that the contributing addition looks good.

**Comment by banesullivan** [comment]
or maybe let @akaszynski handle the conflicts when he is ready to merge

**Comment by akaszynski** [comment]
I'm afraid with all the recent changes to master that it might be best to hold off for this until master settles down as it's going to be tough to manage all the conflicts without messing up.  I honestly mess something up every time I merge.

**Comment by JevinJ** [comment]
This was built on top of #736, also. I could separate the two in the meantime if you want, but whatever will be easier.

**Comment by akaszynski** [comment]
Let's merge #736 and I'll see how much work merging this will be.

BTW, what's your editor/IDE @JevinJ?

**Comment by JevinJ** [comment]
Pycharm.

**Comment by akaszynski** [comment]
I'm still stuck in the past with emacs, but it works and I get all the inside xkcd jokes.

For your other PRs, feel free to merge with master.  It will really speed up tests now that we're not saving screenshots, building the docs each time, etc.

**Comment by JevinJ** [comment]
Ok, I somehow messed up the branches but rebasing and force push hides my sins and got everything where it needs to be. #736 needs review and approval.

**Comment by akaszynski** [comment]
@JevinJ, could you please fix the conflicts?

**Comment by JevinJ** [comment]
Ok, looks up to date.

**Pull request merged**
