### PR TITLE
Add pydocstyle autocheck

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
Follow-up of #427 and especially https://github.com/pyvista/pyvista/issues/427#issuecomment-548427121. The goal of this PR is to add automatic testing of the documentation.

My first idea is to add a Travis job that runs `pydocstyle`. 

*Note: a small documentation style hotfix was necessary.*

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
As expected, Travis is not happy:

https://travis-ci.org/pyvista/pyvista/jobs/614464283#L807-L4320

**Comment by banesullivan** [comment]
I like this - i think having a dedicated job for codestyle and possibly spell checking with `codespell` (#458) is warranted and useful!

As for making this job pass.... it looks like we have some work to do...

**Comment by GuillaumeFavelier** [comment]
If https://github.com/pyvista/pyvista/pull/460 is merged, we can imagine using `pydocstyle` through a new `Makefile` target instead:

```
all: codespell docstyle

docstyle:
  pydocstyle pyvista

...
```

**Comment by banesullivan** [comment]
@GuillaumeFavelier, I caught this up with the master branch and the changes in #460. This is in the same documentation job on Travis.

**Comment by GuillaumeFavelier** [comment]
Thanks for updating this branch @banesullivan !

**Comment by GuillaumeFavelier** [comment]
It was so close! But `pydocstyle` is still complaining apparently:

https://travis-ci.org/pyvista/pyvista/jobs/616098859#L744-L749

**Comment by GuillaumeFavelier** [comment]
I updated the `Makefile` with the new `pydocstyle` target explained in https://github.com/pyvista/pyvista/pull/457#issuecomment-557520932

**Comment by GuillaumeFavelier** [comment]
Hopefully after updating this with https://github.com/pyvista/pyvista/pull/467, Travis will return green.

Feel free to merge if you're happy.

**Comment by GuillaumeFavelier** [comment]
For some reason I can't reproduce [Travis result](https://travis-ci.org/pyvista/pyvista/jobs/616330198#L738-L739) locally:

```
pyvista/core/filters.py:1 at module level:

        D412: No blank lines allowed between a section header and its content ('Example')
```

I pushed an hotfix.

**Comment by banesullivan** [comment]
I had that issue locally

**Comment by GuillaumeFavelier** [comment]
Okay. Everything is green now :+1:

**Pull request merged**
