### PR TITLE
Add prototype itkwidgets plotter

### PR DESCRIPTION
**Pull request by banesullivan**
Ping @thewtex and @akaszynski 

This is a seriously rough prototype but it works for general visualization of meshes and their scalars using `itkwidgets`. Much, much, much refactoring and implementation is still needed but here's a prototype to show what is possible

There are lots of issues with this... so be careful what keyword argument you give to the `add_mesh` method

### Example

Use the `pv.PlotterITK` class just like you might use a `pv.Plotter` class.

(segmenting of colors is because this is a GIF)
```py
import pyvista as pv
from pyvista import examples

import pyvista as pv
from pyvista import examples

# Example dataset with normals
mesh = examples.load_random_hills()

# create a subset of arrows using the glyph filter
arrows = mesh.glyph(scale="Normals", orient="Normals", tolerance=0.05)

p = pv.PlotterITK()
p.add_mesh(arrows, color="black")
p.add_mesh(mesh, scalars="Elevation")
p.show()
```

### CODE REVIEW

**Comment by banesullivan** [comment]
We need to figure out https://github.com/InsightSoftwareConsortium/itkwidgets/issues/166#issuecomment-537634950 to properly reimplement this

**Comment by banesullivan** [comment]
@thewtex, there appear to be a bug when adding multiple geometries to the scene where the coolwarm colormap is set as the default and not the viridis colormap - it can be seen in the gif above and as soon as I select that geometry using the UI, it corrects to a viridis colormap

**Comment by banesullivan** [comment]
We should probably create an internal, abstract class defining all of the methods we want in common between the `BasePlotter` and `PlotterITK` class that those classes can override

**Comment by akaszynski** [comment]
This is perfect!

**Comment by thewtex** [comment]
@banesullivan absolutely phenomenal! :1st_place_medal:  :rocket: :guitar: 



> @thewtex, there appears to be a bug when adding multiple geometries to the scene where the coolwarm colormap is set as the default and not the viridis colormap - it can be seen in the gif above and as soon as I select that geometry using the UI, it corrects to a viridis colormap

Thanks for the note. I am almost finished with a refactor that add selection of colormaps via icons and improves state management of the colormaps on the JavaScript side. I am eager to learn if it helps with this issue.

**Comment by banesullivan** [comment]
The code above is causing the follwoing error using the latest `itkwidgets`

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-e150c7fc2f79> in <module>
     14 p.add_mesh(arrows, color="black")
     15 p.add_mesh(mesh, scalars="Elevation")
---> 16 p.show()

~/Software/pyvista/pyvista/pyvista/plotting/itkplotter.py in show(self, ui_collapsed)
     76                          ui_collapsed=ui_collapsed,
     77                          actors=self._actors,
---> 78                          cmap=self._cmap)
     79         return plotter

~/anaconda3/envs/dev/lib/python3.7/site-packages/itkwidgets/widget_viewer.py in __init__(self, **kwargs)
    223         if 'geometry_colors' in kwargs:
    224             proposal = { 'value': kwargs['geometry_colors'] }
--> 225             color_array = self._validate_geometry_colors(proposal)
    226             kwargs['geometry_colors'] = color_array
    227         self.observe(self._on_geometries_changed, ['geometries'])

~/anaconda3/envs/dev/lib/python3.7/site-packages/itkwidgets/widget_viewer.py in _validate_geometry_colors(self, proposal)
    385         result = np.zeros((n_colors, 3), dtype=np.float32)
    386         for index, color in enumerate(value):
--> 387             result[index,:] = matplotlib.colors.to_rgb(color)
    388         if len(value) < n_colors:
    389             for index in range(len(value), n_colors):

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by thewtex** [comment]
@banesullivan thanks for the report.

I tried reproducing with this branch, but did not succeed:

image

What is `itkwidgets.__version__`?

**Comment by banesullivan** [comment]
@thewtex, my bad! I had installed `itkwidgets` from the `conda-forge` channel earlier today thinking it would go to the latest version. However, conda is not happy about my environment so it installed a very old version (`0.17.0`) 🤦‍♂ due to conflicts.

**Comment by banesullivan** [comment]
@akaszynski and I were chatting and we think it would be beneficial to include this experimental feature directly in PyVista as basic support is better than nothing. Also, this might catch the right folks' eyes who are looking for mesh management, filtering, and 3D viz in Jupyter notebooks.

**Comment by GuillaumeFavelier** [comment]
Also thank you for keeping it as an optional dependency with an `ImportError` :+1:

**Pull request merged**
