### PR TITLE
Add camera position class

### PR DESCRIPTION
**Pull request by banesullivan**
This doesn't change any behavior but lets us represent the camera position as its own object with the various parts of it (position, focal point, and viewup) be accessible under attributes. This will probably reduce folks confusion about what exactly the camera position is since the current implementation of a list of three tuples is not self-describing. Now, an object is returned which can still be treated like a list or accessed by each component to be a little more intuitive

### CODE REVIEW

**Comment by banesullivan** [comment]
Also, when plotting from notebooks with a pop-out window, the shown position is a little sexier with these changes:

Screen Shot 2019-12-08 at 9 43 59 PM

**Comment by banesullivan** [comment]
in hindsight, I copy/paste the output camera position all the time when I'm trying to find a good cpos... maybe we don't want the HTML repr...

**Comment by agramfort** [comment]
i looks nice but is there a point is reading these numbers as a human?
and yes I agree that suddenly copy/paste of values to your python code does
not work anymore :(

>

**Comment by akaszynski** [comment]
I copy and paste all the time, so it would be helpful to leave the numbers as Python readable.  Perhaps just have the __repr__ print the raw camera position?

**Comment by akaszynski** [comment]
Additionally, I didn't see that the setter command for the `camera_position` accepts a simple list.  We should have it allow lists and `CameraPosition` objects to make it backwards compatible.

Honestly, given the added complexity, this isn't something I'd attempt except that it cleans up sphinx gallery.

**Comment by banesullivan** [comment]
> Additionally, I didn't see that the setter command for the camera_position accepts a simple list. We should have it allow lists and CameraPosition objects to make it backwards compatible.

So there's a little bit of magic happening here so that the setter allows lists or the new `CameraPosition` objects. If you look at the `camera_position` setter, it simply grabs the needed values by index so it can be a list or the new class as i implemented a `__getitem__` method, no problem

Basically all these changes do is return this class when fetching the camera position. There are tests for the `camera_position` left unchanged that set with lists, view vectors, and strings so this is completely backward compatible.

Let's keep an eye on  https://github.com/sphinx-gallery/sphinx-gallery/pull/577 as if they don't want to add ignored types, then this isn't really needed.

However, it might be nice to have an object that behaves like the list we have always used but also self-describing by making the position available as `.position`, etc.

**Comment by banesullivan** [comment]
Since we all copy/paste those camera positions and there's no point in having a human-readable form, I removed the `_repr_html_` method

**Pull request merged**
