### PR TITLE
Add `PlanesAssembly` class adding orthogonal planes to a scene

### PR DESCRIPTION
**Pull request by user27182**
### Overview

This class uses the `OrthogonalPlanesSource` from #6366 to create a new assembly class.

It inherits from `XYZAssembly` and is similar to the [`AxesAssembly`](https://docs.pyvista.org/version/stable/api/plotting/_autosummary/pyvista.AxesAssembly.html#pyvista-axesassembly) class with the following main differences:

1. `AxesAssembly` uses [`AxesGeometrySource`](https://docs.pyvista.org/version/stable/api/utilities/_autosummary/pyvista.AxesGeometrySource.html#pyvista-axesgeometrysource) for its geometry, whereas `PlanesAssembly` uses `OrthogonalPlanesSource`
2. `AxesAssembly` uses the [`Label` ](https://docs.pyvista.org/version/stable/api/plotting/_autosummary/pyvista.Label.html#pyvista.Label) class for its labels, whereas `PlanesAssembly` uses a customized `vtkAxisActor`

Here's a preview of this feature using similar a similar example to the [AnatomicalOrientation](https://examples.vtk.org/site/Cxx/VisualizationAlgorithms/AnatomicalOrientation/) vtk example. Unlike that example, which uses `vtkVectorText` for the plane labels which remain static and will appear "backwards" if viewed from behind the plane, the labels for this new class instead follow the camera.

``` python
import pyvista as pv
from pyvista import examples
human = examples.download_human()
labels = 'Transverse', 'Sagittal', 'Coronal'
planes_assembly = pv.PlanesAssembly(bounds=human.bounds, labels=labels, label_size=25)
plot = pv.Plotter() 
plot.add_mesh(human, color='yellow')
plot.add_actor(planes_assembly) 
planes_assembly.camera = plot.camera 
plot.show()
```

https://github.com/user-attachments/assets/c7631fea-79c1-4515-a794-7e412412e1f0

### CODE REVIEW

**Comment by tkoyama010** [comment]
This is awesome! Thanks for working for this :)

**Comment by user27182** [comment]
The `doc_image_cache` still needs to be updated to reflect the fix in https://github.com/pyvista/pyvista/pull/6379/commits/535924db0db28e62e1823f1ba442f3b2fd3ae2e3 but otherwise this PR is ready

**Review by tkoyama010 — CHANGES_REQUESTED** [review]

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Review by tkoyama010 — APPROVED** [review]
LGTM Thanks!

**Pull request merged**
