### PR TITLE
Remove deprecated jupyter backends

### PR DESCRIPTION
**Pull request by banesullivan**
Removes deprecated Jupyter backends in favor of the Trame backend

### CODE REVIEW

**Comment by alesgenova** [comment]
Is there anything missing in this PR, other than fixing the conflicts?

As I explain [here](https://github.com/pyvista/pyvista/issues/4684#issuecomment-1681078374) I think this PR is critical to get pyvista and jupyter v4.x to work properly

**Comment by akaszynski** [comment]
> Is there anything missing in this PR, other than fixing the conflicts?
> 
> As I explain [here](https://github.com/pyvista/pyvista/issues/4684#issuecomment-1681078374) I think this PR is critical to get pyvista and jupyter v4.x to work properly

I'd like this merged soon. I also think it's time for another release given this is a fairly high priority and this won't be easy to `cherry-pick`.

**Review by alesgenova — APPROVED** [review]
I tested this branch on a clean virtual environment:
```
pip install 'pyvista[all,trame]' jupyterlab ipywidgets
```
and I'm happy to report that jupyter 4 and ipywidgets are installed and both work correctly with pyvista.

On an existing virtual environment you would want to uninstall `ipyvtklink` before running:
```
pip install -U 'pyvista[all,trame]' jupyterlab ipywidgets
```

Finally, in some doc pages such as [this](https://tutorial.pyvista.org/getting-started.html#getting-started), we ask the users to install ipywidgets < 8
```
pip install 'pyvista[all,trame]' jupyterlab 'ipywidgets<8.0.0'
```
which is a mistake and ends up giving us jupyterlab v4 and ipywidgets v7, which are not compatible with each other.

**Comment by akaszynski** [comment]
> Finally, in some doc pages such as [this](https://tutorial.pyvista.org/getting-started.html#getting-started), we ask the users to install ipywidgets < 8

Addressed in https://github.com/pyvista/pyvista-tutorial/pull/156

**Pull request merged**
