### PR TITLE
[HOTFIX] Interactive plotter callback errors

### LINKED ISSUE #3309: Callback errors
### Describe the bug, what's wrong, and what you expected.

```shell
WARNING:root:Encountered issue in callback (most recent call last):
  File "D:\Users\Rodrigo\GitHub\pyvista\pyvista\plotting\render_window_interactor.py", line 886, in _press
    if len(parent.plotter.renderers) > 1:
AttributeError: 'RenderWindowInteractor' object has no attribute 'plotter'
WARNING:root:Encountered issue in callback (most recent call last):
  File "D:\Users\Rodrigo\GitHub\pyvista\pyvista\plotting\render_window_interactor.py", line 895, in _release
    if len(parent.plotter.renderers) > 1:
AttributeError: 'RenderWindowInteractor' object has no attribute 'plotter'
```

### Steps to reproduce the bug.

```python
import pyvista as pv
cone = pv.Cone()
cone.plot()
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Tue Sep 13 09:41:08 2022 Hora oficial do Brasil

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
               RAM : 15.9 GiB
       Environment : Python
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon (TM) R9 370
       GPU Version : 4.5.13571 Core Profile Context 19.30.02 26.20.13002.133

  Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64
  bit (AMD64)]

           pyvista : 0.37.dev0
               vtk : 9.1.0
             numpy : 1.23.2
           imageio : 2.21.1
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.5.3
         pyvistaqt : 0.9.0
             PyQt5 : 5.15.7
           IPython : 8.4.0
             scipy : 1.9.0
              tqdm : 4.64.0
            meshio : 4.4.6
        jupyterlab : 3.4.5
--------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by rodrigomologni**
Resolves #3309

### CODE REVIEW

**Comment by banesullivan** [comment]
Thank you for jumping on this! This is known and perhaps and I believe was a result of big internal refactor recently.

@akaszynski, would you please review?

I'd also like to write some sort of test that captures this (which likely means enabling interactive plotting)

cc @adeak  (since we all talked about this on Slack)

**Review by banesullivan — APPROVED** [review]
This seems to fix the issue and this is bad enough that I'm merging it now. Can follow up if needed

**Comment by banesullivan** [comment]
Thank you @rodrigomologni!

**Comment by akaszynski** [comment]
> @akaszynski, would you please review?

Sorry, been out at a hackathon for my company Ansys. Good news is they're using pyvista.

**Pull request merged**
