### PR TITLE
Add support for vtkHDFReader

### PR DESCRIPTION
**Pull request by alexfikl**
### Overview

A new VTKHDF format for unstructured meshes was added in VTK (see [this PR](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7552)) and to Paraview ([readers_iohdf.xml](https://gitlab.kitware.com/paraview/paraview/-/blob/master/Remoting/Application/Resources/readers_iohdf.xml))

### Details

Tested with Paraview 5.10 and VTK 9.1 on Arch Linux.

### CODE REVIEW

**Comment by RichardScottOZ** [comment]
geoh5py to pyvista?

**Comment by alexfikl** [comment]
> geoh5py to pyvista?

Haven't heard of geoh5py before, but they seem unrelated. This is a new format that's part of VTK itself.

**Review by banesullivan — COMMENTED** [review]
This generally looks good to me, but do you have some test data in this format so that we can verify everything is working?

**Comment by alexfikl** [comment]
> This generally looks good to me, but do you have some test data in this format so that we can verify everything is working?

There are some files in the `ParaviewTestingDataFiles` at [paraview.org](https://www.paraview.org/download/) (also attached below)

[paraview-can.zip](https://github.com/pyvista/pyvista/files/8288364/paraview-can.zip)

I also have some custom files that were written with the the writer from [meshmode](https://github.com/inducer/meshmode/pull/294) that Paraview seems to be able to read nicely that I can share. For the `pyvista` tests, I just used this to conver the VTKHDF files to STL, so no idea about the more advanced functionality.

**Comment by banesullivan** [comment]
Note: I added that test data to vtk-data: https://github.com/pyvista/vtk-data/tree/master/Data/hdf if we would like for this to be tested

**Review by akaszynski — APPROVED** [review]
Thanks for adding this. I've also added in a method to `downloads.py` to support downloading the can example data @banesullivan uploaded, and a test for coverage.

**Comment by alexfikl** [comment]
> Thanks for adding this. I've also added in a method to `downloads.py` to support downloading the can example data @banesullivan uploaded, and a test for coverage.

My pleasure! Thank you for adding the tests.

**Comment by alexfikl** [comment]
Looks like this requires VTK 9.1. Should I add an `if version < 9.1: pytest.skip()`? What would be the best way to handle this?

**Comment by akaszynski** [comment]
> @akaszynski Looks like this requires VTK 9.1. Should I add an `if version < 9.1: pytest.skip()`? What would be the best way to handle this?

@ alexfikl, I’ve implemented your suggestion.

**Pull request merged**
