### PR TITLE
Allow plotting on azure pipelines

### PR DESCRIPTION
**Pull request by banesullivan**
No plotting tests were running on Azure 🤦‍♂ 

Now they all run (except Qt tests which is from https://github.com/pyvista/pyvista/pull/88)

### CODE REVIEW

**Comment by banesullivan** [comment]
@GuillaumeFavelier - could you help me with this? I'm not sure why one of the builds failed.

You helped set up PyVista plotting on Azure for `mne-python`, right?

**Comment by GuillaumeFavelier** [comment]
Yes indeed. If I recall correctly, we [upgraded](https://github.com/mne-tools/mne-python/commit/4796b32a9197c592304544f5f3b1499bdf33e331) the `CONDA_VERSION` to fix the issues we had at the time.

**Comment by banesullivan** [comment]
Hm, that's strange - any idea why that might have fixed your issues?

We're currently not using Anaconda on Azure - I wonder if there's a way we can get away without using it as Anaconda typically slows down CI builds dramatically (having to install and set up the environment)

**Comment by GuillaumeFavelier** [comment]
It's probbly not related, we had a `LinkError` problem with `ipykernel 5.1.1` during the environment setup.

**Comment by GuillaumeFavelier** [comment]
At least I think we have a clue about the issue on the `Windows Python37-64bit` and `Windows Python36-64bit` configurations. It seems to be related to the rendering window of the `BackgroundPlotter`, `ren_win` probably not available during testing.

**Comment by GuillaumeFavelier** [comment]
Coming back to your first message, I think we should just skip the tests in `tests/test_ipy_tools.py` relying on Qt. I added the same `NO_PLOTTING` variable already present in `tests/test_qt_plotting.py` and that seems to do the trick. I'll relaunch the tests on Azure again to confirm.

**Comment by banesullivan** [comment]
> I think we should just skip the tests in tests/test_ipy_tools.py relying on Qt. I added the same NO_PLOTTING variable already present in tests/test_qt_plotting.py and that seems to do the trick.

FYI, we do this:

https://github.com/pyvista/pyvista/blob/64e4435b5705cae223ed925ec6855e68507445f3/azure-pipelines.yml#L46

Is that still needed?

**Comment by GuillaumeFavelier** [comment]
As long as #340 is not fixed I think we should keep it. Actually, I think I was just lucky to find Azure green since the tests were `PASSED` instead of `SKIPPED`.

**Comment by banesullivan** [comment]
LGM - should I merge?

**Comment by GuillaumeFavelier** [comment]
+1 for merge

**Pull request merged**
