### PR TITLE
Partially add type hints to /core/

### PR DESCRIPTION
**Pull request by JevinJ**
Add type hints to common.py, composite.py, datasetattributes.py, pointset.py

Add VectorArray, Number, Color type aliases

Add mypy/typing extensions to requirements_docs.txt

### CODE REVIEW

**Comment by JevinJ** [comment]
@akaszynski How would I cleanly drop/revert a whole file from this PR? I want to exclude filters.py as that is becoming a beast of it's own to get mypy working at the moment.

**Comment by akaszynski** [comment]
> @akaszynski How would I cleanly revert a whole file from this PR? I want to exclude filters.py as that is becoming a beast of it's own to get mypy working at the moment.

Sorry, just saw this.

When I want to revert a file, I usually follow this procedure:
https://opensource.com/life/16/7/how-restore-older-file-versions-git

**Comment by JevinJ** [comment]
@akaszynski This is ready to review.

**Comment by akaszynski** [comment]
> @akaszynski This is ready to review.

I'll try to get to it later today, or at the latest on Monday.

**Review by akaszynski — APPROVED** [review]
Ran `mypy` locally and was pleasantly surprised to find no issues.  Seems that the CI runs well, though I did have to enable it for the entire `core/` directory rather than just `common.py`.

Nice work!

**Comment by akaszynski** [comment]
I'll let you merge this, as tempting as that big green button is.

**Pull request merged**
