### PR TITLE
📝 Add My PyVista artwork to external gallery

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

@stla Thank you for a [great example](https://laustep.github.io/stlahblog/posts/MyPyVistaArtworks.html) of PyVista use. We really glad that PyVista mania is increasing.

 

Duoprism_3-30

### Details

- https://github.com/pyvista/pyvista/discussions/1727

### CODE REVIEW

**Comment by akaszynski** [comment]
Nice!
Builds failing due to `ipython=8.0.0`. This is good to go.

**Comment by banesullivan** [comment]
These are super cool!!!

**Comment by adeak** [comment]
Shouldn't we call this "Stéphane Laurent's PyVista artwork"? The "My" looks confusing

**Comment by banesullivan** [comment]
Agreed. Stéphane Laurent should get full acknowledgment

**Pull request merged**
