### PR TITLE
Release/0.35.3

### PR DESCRIPTION
**Pull request by akaszynski**
Release 0.35.3 to address issues in the mne docbuild. Pinging @larsoner for visibility.

Includes:
- #3089
- #3088
- #3071
- #3075
- #3049
- #3048
- #3053
- #3028

### CODE REVIEW

**Comment by larsoner** [comment]
Doc build is red

**Comment by MatthewFlamm** [comment]
> Doc build is red

Also getting this same error in #3031.  But not all PRs seem affected.  It might be flaky code/execution in the docs.  Would be good to fix for this release so the docs don't get messed up.

**Comment by adeak** [comment]
>  It might be flaky code/execution in the docs.

I'll check what a local clean build looks like.

> Would be good to fix for this release so the docs don't get messed up.

I thought we only bumped docs.pyvista.org for minor versions (and dev.pyvista.org every n hours).

**Comment by MatthewFlamm** [comment]
> I thought we only bumped docs.pyvista.org for minor versions

If so, we may want to reconsider as this PR includes a feature addition (parameter added to add_mesh) that fixes a bug.

Or require any feature addition to be in a minor release.

**Comment by adeak** [comment]
I'm seeing the same FFT error so far in a local build. I bet this needs something like https://github.com/pyvista/pyvista/pull/2941/files#diff-c32dcf1233c1d39782559141c852a0d0372cb9482b9d1ac3a48a0fc70e2513dcR750-R758 (don't think @akaszynski I didn't notice you sneaking that in there :P)

**Comment by akaszynski** [comment]
Main builds just fine locally, and given that we're adding a feature, how about we abandon this patch release and go with a minor (`0.36`) release instead.

> (don't think @akaszynski I didn't notice you sneaking that in there :P)

Yea, gotta peel that out.

**Comment by adeak** [comment]
For the record in the local build that was the only error, with a warning fixed in https://github.com/pyvista/pyvista/pull/3023/files#diff-355952f3009b3d15d0d85ebb510556c3db59722b98c0d5c7d57abdb2b6ea5363R3192-R3193

**Pull request closed without merging**
