### PR TITLE
TST: Reproduce timeouts on Azure

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PRs follows https://github.com/pyvista/pyvista/pull/648#issuecomment-601274640 and tries to reproduce the timeouts on windows.

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Test 1) is all green

**Comment by akaszynski** [comment]
My recent commits were running just fine as well...

**Comment by akaszynski** [comment]
This seems hit or miss on windows:
```python
    # a full scene may take a while to setup, especially on macOS
    show_timeout = 500 if empty_scene else 10000

    # ensure that the widgets are showed
    with qtbot.wait_exposed(window, timeout=show_timeout):
        window.show()
    with qtbot.wait_exposed(interactor, timeout=show_timeout):
        interactor.show()
```

**Comment by banesullivan** [comment]
Closing - if still relevant, please open a new PR from a `junk/` branch

**Pull request closed without merging**
