### PR TITLE
Pin Vale version to version 2.29.5

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

This confirms Vale's version upgrade with dependabot's version-up PR. Currently, the latest version of Vale is always used. It is annoying to get Vale's warning outputs unrelated to the respective PRs because of it.

### Details

- None

### CODE REVIEW

**Comment by tkoyama010** [comment]
LGTM

**Comment by MatthewFlamm** [comment]
vale isn't a pypi package as far as I can tell.  I don't think this will work for auto updating.  We might as well just hard code the version in the action unless there is a way to get it to auto update from whatever package system vale uses.

**Comment by tkoyama010** [comment]
> vale isn't a pypi package as far as I can tell. I don't think this will work for auto updating. We might as well just hard code the version in the action unless there is a way to get it to auto update from whatever package system vale uses.

@MatthewFlamm 
Thanks for your comment. I found the following side.
https://pypi.org/project/vale/
The site seems actively updated. So dependabot autoupdate requirements_docs.tx in my mind.

**Comment by tkoyama010** [comment]
It seems that what I have presented is for providing a Python package independent of the vale project. And I found a helpful GitHubActions called [check-vale-update.yml](https://github.com/daniperez/vale-python-package/blob/main/.github/workflows/check-vale-update.yml) in the [vale-python-package](https://github.com/daniperez/vale-python-package). Isn't it a good idea to add this to our project?

**Comment by MatthewFlamm** [comment]
This could work, but it could become out of sync.  For example, if this third party provided python package publishes a version that is subsequently yanked from the official repository.  Not sure what the risk is here, but pinning it in some form is important to avoid all the noise in PRs.  I don't have a great suggestion here, so maybe we can pin it directly in the action until we find a good path forward?

**Review by MatthewFlamm — APPROVED** [review]
LGTM.  Thanks!

**Pull request merged**
