### PR TITLE
Add drilldown as external example of PyVista

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

Add the [drilldown](https://github.com/cardinalgeo/drilldown) by @cardinalgeo as an external example of PyVista.
image

### Details

- None

### CODE REVIEW

**Comment by tkoyama010** [comment]
github-actions preview

**Comment by tkoyama010** [comment]
github-actions preview

**Comment by tkoyama010** [comment]
@pyvista-bot LGTM

**Comment by cardinalgeo** [comment]
Sweet, thanks for adding `DrillDown` as an example, @tkoyama010!

**Pull request merged**
