### PR TITLE
💚 Add isort in CI

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

Let's add [isort](https://github.com/timothycrosley/isort) in CI !
image

 
https://github.com/pyvista/pyvistaqt/pull/43

#288

### Details

- None

### CODE REVIEW

**Comment by tkoyama010** [comment]
This error relate to https://github.com/PyCQA/isort/issues/457 .

**Comment by GuillaumeFavelier** [comment]
Locally, I get slightly more infos:

```
AttributeError: partially initialized module 'pyvista' has no attribute 'plot' (most likely due to a circular import)
```

@tkoyama010 may I suggest the following diff to resolve the circular import?

```diff
diff --git a/Makefile b/Makefile
index 89780a4a..f53ee9f5 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 # Simple makefile to simplify repetitive build env management tasks under posix
 
-ISORT_DIRS ?= ./pyvista/
+ISORT_DIRS ?= ./pyvista/*.py
 CODESPELL_DIRS ?= ./
 CODESPELL_SKIP ?= "*.pyc,*.txt,*.gif,*.png,*.jpg,*.ply,*.vtk,*.vti,*.js,*.html,*.doctree,*.ttf,*.woff,*.woff2,*.eot,*.mp4,*.inv,*.pickle,*.ipynb,flycheck*,./.git/*,./.hypothesis/*,*.yml,./docs/_build/*,./docs/images/*,./dist/*,*~,.hypothesis*,./docs/examples/*"
 CODESPELL_IGNORE ?= "ignore_words.txt"
diff --git a/pyvista/core/common.py b/pyvista/core/common.py
index c302647d..762b7dd1 100644
--- a/pyvista/core/common.py
+++ b/pyvista/core/common.py
@@ -273,7 +273,8 @@ class Common(DataSetFilters, DataObject):
     """Methods in common to spatially referenced objects."""
 
     # Simply bind pyvista.plotting.plot to the object
-    plot = pyvista.plot
+    from pyvista.plotting import plot as plot_func
+    plot = plot_func
 
     def __init__(self, *args, **kwargs):
         """Initialize the common object."""
diff --git a/pyvista/core/composite.py b/pyvista/core/composite.py
index aeb862f9..5377564a 100644
--- a/pyvista/core/composite.py
+++ b/pyvista/core/composite.py
@@ -61,7 +61,8 @@ class MultiBlock(vtkMultiBlockDataSet, CompositeFilters, DataObject):
     """
 
     # Bind pyvista.plotting.plot to the object
-    plot = pyvista.plot
+    from pyvista.plotting import plot as plot_func
+    plot = plot_func
     _READERS = dict.fromkeys(['.vtm', '.vtmb'], vtk.vtkXMLMultiBlockDataReader)
     _WRITERS = dict.fromkeys(['.vtm', '.vtmb'], vtk.vtkXMLMultiBlockDataWriter)
 ```

**Comment by tkoyama010** [comment]
Thanks @GuillaumeFavelier for your help. It was hard to solve this problem for me.

**Comment by tkoyama010** [comment]
It is ready for review :rocket:

**Review by akaszynski — COMMENTED** [review]
I'm fine with this, though refactoring is always worrisome for me as it obscures the blame and might potentially introduce errors.  When refactoring, we should always ask ourselves if we're adding features or making the code more readable.  If not, we're spinning our wheels and potentially making our CI workflow more complex.

I'd like to hear other opinions as well.

**Comment by akaszynski** [comment]
Going to recommend we abandon this based on the aforementioned reasoning.

**Pull request closed without merging**
