### PR TITLE
Update `validation.check`: refactor code, add type annotations, improve docstrings

### PR DESCRIPTION
**Pull request by user27182**
### Overview

Follow up from https://github.com/pyvista/pyvista/pull/5571 generally, and https://github.com/pyvista/pyvista/pull/6214 specifically (this PR is part of item 2 defined there).

### Details
This PR contains mostly under-the-hood changes. There are some API changes though, e.g.
- `check_number` got a bit of an overhaul to support different definitions of "Number"
- `check_contains` has its arguments renamed and reversed in order

This PR depends on #6216 and #6217, those should be merged first.

### CODE REVIEW

**Comment by tkoyama010** [comment]
@pyvista-bot preview

**Comment by tkoyama010** [comment]
@pyvista-bot preview

**Comment by user27182** [comment]
I could probably break this up even further and make a separate PR for each function... @tkoyama010 would that be preferable ?

**Comment by tkoyama010** [comment]
> I could probably break this up even further and make a separate PR for each function... @tkoyama010 would that be preferable ?

Yes, I think it would speed up the review process more. Thank you kindly.

**Pull request closed without merging**
