### PR TITLE
Set default scalars for filters

### PR DESCRIPTION
**Pull request by MatthewFlamm**
### Overview

 

Followup to #2433, this time for scalars.

### Details

Adding data to DataSets automatically makes them active, but it is still possible that there are no active scalars, e.g. if there is no data at all

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
I will keep this as draft until it is used in all the filters I can find.

**Comment by adeak** [comment]
Since you're already working in this ballpark, I got this warning locally on `main`:
```
tests/test_demos.py::test_plot_glyphs
tests/plotting/test_plotting.py::test_plot_compare_four
  /home/adeak/pyvista/pyvista/core/filters/data_set.py:1999: UserWarning: No vector-like data to use for orient. orient will be set to False.
    warnings.warn("No vector-like data to use for orient. orient will be set to False.")
```

Probably just a matter of a manual `False` flag, but I haven't been able to investigate yet.

**Comment by akaszynski** [comment]
> tests/test_demos.py::test_plot_glyphs
> tests/plotting/test_plotting.py::test_plot_compare_four
>   /home/adeak/pyvista/pyvista/core/filters/data_set.py:1999: UserWarning: No vector-like data to use for orient. orient will be set to False.
>     warnings.warn("No vector-like data to use for orient. orient will be set to False.")

Should be fixed in #2460. I'm tempted to merge that so we avoid duplication.

**Comment by MatthewFlamm** [comment]
It is weird to fix in #2460, I agree we don't need two semi related PRs that fix this.

**Comment by akaszynski** [comment]
> It is weird to fix in #2460, I agree we don't need two semi related PRs that fix this.

Agreed. It was bothering me, but I should have split it up.

**Comment by adeak** [comment]
OK, so I think what @akaszynski fixed in #2460 was a _doc build_ warning coming from https://github.com/pyvista/pyvista/pull/2460/files#diff-355952f3009b3d15d0d85ebb510556c3db59722b98c0d5c7d57abdb2b6ea5363L454 .

What I said was a _test_ run, somewhere in `tests/`. So there's still something to fix here.

**Comment by MatthewFlamm** [comment]
This is ready for review.

When adding all the filters I could find, I noticed that some filters use `SetInputArrayToProcess` and some filters leave it to the vtk algorithm to use the active scalars by default.  It would be good to eventually align on a preferred usage.  But, this is out of scope for this PR.

**Review by akaszynski — APPROVED** [review]
I added one final test, but otherwise this is good to go.

**Pull request merged**
