### PR TITLE
Add `--disallow-any-generics` to `mypy` config

### PR DESCRIPTION
**Pull request by user27182**
## Overview

Add [`--disallow-any-generics`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-disallow-any-generics) option.

In addition, this PR fixes roughly 130 `mypy` errors that were initially generated by using this option.

## Details

This option is a follow-up from #5285. Without this option, using array-like annotations such as `Vector` without specifying a typevar will result in a default assumption of `Vector[Any]` by `mypy`. This is generally not safe since it implies sequences or numpy arrays of strings, complex numbers, or even object types are allowed, when typically only real numbers are expected.

This option forces developers to be explicit and do something like `Vector[float]` instead of `Vector`. In cases where `Vector[Any]` is the correct annotation, this must be made explicit (or use `# type: ignore` ).

### CODE REVIEW

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Review by tkoyama010 — APPROVED** [review]
LGTM. This is a change of annotation, but there are source changes, so we will only wait a day for other reviewers' reactions before merging.

**Review by tkoyama010 — DISMISSED** [review]

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Review by tkoyama010 — APPROVED** [review]

**Review by tkoyama010 — DISMISSED** [review]

**Comment by tkoyama010** [comment]
Please help us correct the error again.

**Comment by user27182** [comment]
@tkoyama010 should be fixed now 👍

**Review by tkoyama010 — APPROVED** [review]

**Pull request merged**
