### PR TITLE
Fix Parametric objects direction error

### LINKED ISSUE #4850: Confusing behaviour of ParametricEllipsoid
### Describe the bug, what's wrong, and what you expected.

When creating a ParametricEllispoid using a direction of [0, 1, 0], the ellipsoid is rotated along the y axis.  
For example if setting the direction to [1e-5, 1, 0], which corresponds to approximately similar direction, the ellipsoid displays then the correct behaviour.

### Steps to reproduce the bug.

```python
import pyvista as pv

ellipsoid = pv.ParametricEllipsoid(300, 100, 10, direction=[0, 1, 0])
```

### System Information

```shell
Date: Wed Sep 06 14:07:38 2023 CEST

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 31.2 GiB
       Environment : Jupyter
       File system : ext4
        GPU Vendor : Intel
      GPU Renderer : Mesa Intel(R) UHD Graphics (CML GT2)
       GPU Version : 4.6 (Core Profile) Mesa 22.0.1
  MathText Support : False

  Python 3.8.13 (default, Apr 19 2022, 02:32:06)  [GCC 11.2.0]

           pyvista : 0.41.1
               vtk : 9.2.6
             numpy : 1.24.4
        matplotlib : 3.3.4
            scooby : 0.7.2
             pooch : v1.7.0
           imageio : 2.31.1
           IPython : 8.12.2
        ipywidgets : 8.0.7
             scipy : 1.10.1
              tqdm : 4.65.0
        jupyterlab : 3.6.5
             trame : 2.5.2
      trame_client : 2.10.0
      trame_server : 2.11.7
         trame_vtk : 2.5.8
      nest_asyncio : 1.5.6
```

### Screenshots

Here is the given ellipsoid
confusing_ellipsoid
Here is what is expected
expected_ellipsoid

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

resolves #4850

### Details

- None

### CODE REVIEW

**Review by adeak — APPROVED** [review]
Definitely a bug and fix looks good to me, thanks @tkoyama010.

On a broader note, there might still be some instability present, because if I pass `pv.ParametricBour(direction=np.array([1, 1000000, 1]))` there's a noticeable slant in the result, even though the normal vector should for all intents and purposes point along `[0, 1, 0]`. I think this might have to do with numerical instability when the `normz` vector is not _exactly_ a zero array, but close. But this would need a better looking at, to ensure that some `allclose` fix doesn't introduce new bugs.

**Comment by tkoyama010** [comment]
Thanks for the nice suggestion. I will organize it as an issue later.

**Comment by tkoyama010** [comment]
@user27182 Great idea. Could you suggest adding tests of it? We don't mind if we change this PR or you create a new one.

**Comment by user27182** [comment]
Found related bugs. 

(1) Looks like `all_close` is needed for `geometric_objects.translate()` as @adeak suggested. With the current `main` PyVista branch (after this PR was merged):
``` python
import pyvista as pv

default = pv.ParametricEllipsoid(300, 100, 10)
exact = pv.ParametricEllipsoid(300, 100, 10, direction=[0, 1, 0])
delta_x = pv.ParametricEllipsoid(300, 100, 10, direction=[1e-8, 1, 0])
delta_z = pv.ParametricEllipsoid(300, 100, 10, direction=[0, 1, 1e-8])

plot = pv.Plotter()
plot.add_mesh(default, style='wireframe')
plot.add_mesh(exact, color='red')
plot.add_mesh(delta_x, color='green')
plot.add_mesh(delta_z, color='blue')
plot.show()
```
Will produce the following image:
image

The darker blue ellipse still has the incorrect orientation. Using `all_close` resolves this.

(2) There is still a bug for  `direction=[0,-1,0]`. The prior use of `np.roll()` in `geometric_objects.translate()` (introduced in #4674 and removed with this PR) was intended to handle multiple cases where a zero cross product result was generated. Specifically, the cross product is zero when the input direction is collinear with the y-axis, i.e. when `direction=[0,1,0]` and  `direction=[0,-1,0]`. However, the negative case for ``direction=[0,-1,0]`` is currently unaccounted for.
e.g. 
```python
import pyvista as pv
from math import pi

default = pv.ParametricEllipsoid(300, 100, 10, max_u=pi / 2)
exact = pv.ParametricEllipsoid(300, 100, 10, max_u=pi / 2, direction=[0, -1, 0])
close = pv.ParametricEllipsoid(300, 100, 10, max_u=pi / 2, direction=[1e-4, -1, 0])

plot = pv.Plotter()
plot.add_mesh(default)

plot.add_mesh(exact, color='red')
plot.add_mesh(close, color='blue')
plot.show_axes()
plot.show()
```
Will produce:
image
The red mesh should be oriented like the dark blue.

I will make a new PR with changes to address these issues.

**Pull request merged**
