### PR TITLE
Clean up after Light PR merge

### PR DESCRIPTION
**Pull request by adeak**
There were a few things left needing cleanup after https://github.com/pyvista/pyvista/pull/1040/:

* typo fixes
* removal of lighting.png cached image (obsolete)
* removal of lighting_disable_3_lights.png cached image (obsolete)
* addition of a mesh to `test_lighting_init_none`
* some rearranging and constraining of Plotter tests

### CODE REVIEW

**Comment by akaszynski** [comment]
Please merge with master and verify.

**Comment by adeak** [comment]
Looks good to me. If I remove the mesh addition from the `test_lighting_init_none` case again the image regression error appears. Although now I'm dropped into pdb with a failing test:
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/user/pyvista/tests/plotting/test_plotting.py(117)verify_cache_image()
-> raise RuntimeError('Exceeded image regression error of '
```

Is this expected?

**Comment by adeak** [comment]
@akaszynski I think I've found it https://github.com/pyvista/pyvista/blob/master/tests/plotting/test_plotting.py#L116

**Comment by akaszynski** [comment]
Thanks for fixing that.  That breakpoint was for debugging and I forgot to remove it.

**Review by akaszynski — APPROVED** [review]

**Pull request merged**
