### PR TITLE
Replaced pyvista.wrap(alg.GetOutput()) with _get_output(alg).

### PR DESCRIPTION
**Pull request by harshi1122**
Replaced pyvista.wrap(alg.GetOutput()) with _get_output(alg).
Can close https://github.com/pyvista/pyvista/issues/2226

### CODE REVIEW

**Comment by tkoyama010** [comment]
Thank you for the contribution, it seems that Circular import is happening in CI. If you don't know how to solve it, please mention pyvista/developers.

**Comment by harshi1122** [comment]
@tkoyama010 
I don't know how to solve the CI issue 
How do I mention the developers?

**Comment by harshi1122** [comment]
@adeak 
Thanks a lot for your guidance and for answering my question.
I was having trouble pushing some commits to the other PR, and I messed up, so I decided to open a new one. 
I have just recently started exploring Open Source so learning the ropes.
Thanks once again :)

**Comment by adeak** [comment]
What probably happened is that akaszynski pushed some commits to your branch, in which case you first have to pull the changes from your remote github repo and continue working there.

If you need technical help with git (or anything related to contributing to PyVista) you can also find us [in slack](http://slack.pyvista.org/), you're welcome to join :)

**Review by akaszynski — APPROVED** [review]
LGTM

**Pull request merged**
