### PR TITLE
MAINT: Underscore numpy types

### PR DESCRIPTION
**Pull request by adeak**
### Overview

Numpy has `np.bool`, `np.int` and `np.float` and `np.complex` as aliases for the native python types `bool`, `int`, `float` and `complex`, respectively. The numpy-native types are available as `np.bool_`, `np.int_`, `np.float_` and `np.complex_`. This PR replaces the former with the latter.

### Details

The two scenarios in which these types appear in pyvista are like

  1. `array.astype(np.bool)` and
  2. `array.dtype == np.bool`

In both cases it doesn't actually make a difference whether one uses native types or numpy types:
```python
>>> np.bool_ == np.dtype(bool) is np.dtype(np.bool_) == bool
True
# even though
>>> np.bool_ == bool
False
```
So these are not bugs, but the semantics are a bit cleaner with the proper (underscored) numpy types.

### CODE REVIEW

**Comment by akaszynski** [comment]
@banesullivan, I've been on a PR rampage.  Would you mind checking this?

**Comment by banesullivan** [comment]
What is the motivation behind this?

> So these are not bugs, but the semantics are a bit cleaner with the proper (underscored) numpy types.

I'm not sure if I can approve this PR if it is purely about semantics thing there may be unintended side effects with:

1. how we pass many of these data to VTK over its Python bindings. Note that VTK's `numpy_support` module does not use these types but the "built-in" (?) types: See https://github.com/Kitware/VTK/blob/fbec110e24045adcc23b130eee06fa51a9ee3c44/Wrapping/Python/vtkmodules/util/numpy_support.py#L75-L89
2. interoperability with other Python libraries that also use/expect these built-in types rather than the numpy types.

@JevinJ, do you have any thoughts on this?

**Comment by banesullivan** [comment]
Either way, I want to do some manual testing of this with downstream projects as reassurance

**Comment by adeak** [comment]
Sorry for not explaining it well enough.

> I'm not sure if I can approve this PR if it is purely about semantics as there may be unintended side effects with:
> 
>   1. how we pass many of these data to VTK over its Python bindings. Note that VTK's numpy_support module does not use these types but the "built-in" (?) types: See https://github.com/Kitware/VTK/blob/fbec110e24045adcc23b130eee06fa51a9ee3c44/Wrapping/Python/vtkmodules/util/numpy_support.py#L75-L89
>   2. interoperability with other Python libraries that also use/expect these built-in types rather than the numpy types.

There can be no unindented side effects, since the arrays being created are exactly the same.

The issue is that the type `np.bool` does not really exist. It's literally just `bool`:
```python
>>> np.bool is bool
True
```
When you create a bool array the type of its elements will actually be the numpy native `np.bool_` type which is a different type:
```python
>>> type((np.arange(3) == 0)[0])
<class 'numpy.bool_'>
```
But when you work with `dtype`s it makes no difference whether you specify "give me a bool" as "give me a `bool`" or "give me an `np.bool_`":
```python
>>> type(np.array([0], dtype=bool)[0])
<class 'numpy.bool_'>
>>> type(np.array([0], dtype=np.bool_)[0])
<class 'numpy.bool_'>
```

So for all intents and purposes `np.bool`, `np.int` and `np.float` don't exist. Every numpy object has a specific type (either `np.bool_` or one of the fixed-size int/float types, among which `np.int_` and `np.float_` are a potentially system-specific alias). But the `dtype` objects accept boader terms and makes a default choice for the user instead.

This is why I'm saying that there's no behavioural difference: passing both `dtype=int` and `dtype=np.int_` will give you the exact same array type. And dtype comparisons are carefully forgiving:
```python
>>> np.dtype(bool) is np.dtype(np.bool_)
True
>>> np.dtype(bool) == bool
True  # even though the dtype corresponds to np.bool_
```
Which covers the 2. scenario in my PR comment.

So the only problem with `np.bool` and friends is that they are misleading. I believe Kitware did the same mistake :) These types should either be `bool` or `np.bool_` etc. I can go with either, and using built-in types is shorter. I didn't consider using the native python versions [because @akaszynski suggested the numpy ones in a comment](https://github.com/pyvista/pyvista/pull/755#issuecomment-634958769). This is not to put the blame on them, just an explanation :)

If my explanation of the above are not reassuring enough, I can change all the underscore types to proper builtin types. This would guarantee the exact same behaviour as previously, since `np.bool is bool` etc.

**Comment by adeak** [comment]
For reference, [these docs](https://numpy.org/doc/stable/reference/arrays.dtypes.html) under "Built-in python types" guarantee that `int` corresponds to `np.int_` etc. And one of many hints to the aliasing: https://github.com/numpy/numpy/issues/3998#issuecomment-27600043

**Comment by banesullivan** [comment]
Ahhhhh okay! Thank you for clarifying everything. I’ll give this a review when I get a chance

**Comment by akaszynski** [comment]
Great explaination @adeak.

**Comment by banesullivan** [comment]
I want to reiterate @akaszynski's appreciation for fixing this! This was news to me and I totally agree with the merge (even though I was very skeptical at first) given NumPy is moving to deprecate this

**Comment by adeak** [comment]
Glad I could help :) Thank you for the merge!

**Pull request merged**
