### PR TITLE
Fix slider widget coordinate parameters

### PR DESCRIPTION
**Pull request by GuillaumeFavelier**
This PR fixes a bug with the input coordinates of the slider widget.

To reproduce:

```py
import pyvista as pv


def foo(v):
    pass


rng = [0, 1]
left = [[0.1, -0.3],
        [0.1, 1.3]]
right = [[0.9, -0.3],
         [0.9, 1.3]]
p = pv.Plotter()
p.add_slider_widget(foo, rng=rng, title='left', pointa=left[0], pointb=left[1])
p.add_slider_widget(foo, rng=rng, title='right', pointa=right[0], pointb=right[1])
p.show()
```

master | PR
---------|------
2019-12-19_1920x1080 | 2019-12-19_1920x1080

### CODE REVIEW

**Comment by GuillaumeFavelier** [comment]
Also I expected the normalized coordinate system to be between 0 and 1 but for some reason, the y-axis doesn't respect this rule.

**Comment by banesullivan** [comment]
Thanks for fixing this!

**Comment by GuillaumeFavelier** [comment]
Also a render to describe the different components of the slider:

2019-12-19_1920x1080

**Comment by banesullivan** [comment]
@GuillaumeFavelier, squash and merge this whenever you're ready

**Comment by GuillaumeFavelier** [comment]
I'm not authorized to merge this pull request, I let you take care of it.

**Comment by banesullivan** [comment]
Oh weird... I thought you were

**Pull request merged**
