### PR TITLE
Change antialiasing default to ssaa

### LINKED ISSUE #4524: test_plot_cell has a very high variance
```
FAILED tests/plotting/test_plotting.py::test_plot_cell - RuntimeError: test_plot_cell Exceeded image regression error of 500.0 with an image error equal to: 2964.9764705882176
```

This test fails on my system (its the only image regression test that fails) due to point size and line size differences with my EGL build of VTK. I tried setting this as a `high_variance_test`, which increases the tolerance to `1000`, but the difference is nearly 3000. Should we increase the tolerance for this test or perhaps skip it on some builds of VTK?

| Saved in image cache | What's produced on my system |
|---|---|
| plot_cell |  plot_cell |

### PR DESCRIPTION
**Pull request by banesullivan**
I use a custom build of VTK for performant off screen rendering with my GPU - an "EGL" build. A handful of PyVista's defaults and tests have been incompatible with this build. These changes rectify that by changing the default anti-aliasing to `ssaa` instead of `fxaa` -- @akaszynski, I'd appreciate your thoughts on this change and if its okay?

Resolves #4524

### CODE REVIEW

**Comment by banesullivan** [comment]
> I really feel that having plots look awesome out of the box should be the default. We can then have a theme that's more suited for low power GPUs

Completely agree here -- let's go for this

**Comment by banesullivan** [comment]
NOTE: to validate this is not breaking the docs, we should trigger a "workflow dispatch" job for the documentation build disabling the cache.

**Comment by banesullivan** [comment]
So maybe enabling antialiasing breaks things like picking... might need to rethink enabling it by default

**Comment by banesullivan** [comment]
Ah this has been tracked in https://github.com/pyvista/pyvista/issues/2520

**Comment by akaszynski** [comment]
> Ah this has been tracked in #2520

Sorta. There are indeed issues when enabling SSAA, but it's not in #2520. One I've noticed off-hand is pressing "f" no longer focuses on the mesh. However, enabling picking (for example `enable_mesh_picking`) causes pressing "f" to both focus on the picked point and to trigger picking it. There's a bit to debug there, and I'd like to have this resolved in a separate PR.

**Comment by banesullivan** [comment]
Looks like tests are now passing after #4254

**Comment by akaszynski** [comment]
Interesting... After #4254, pressing "f" no longer focuses on the point under the cursor (regardless of the settings of anti-aliasing).

**Comment by akaszynski** [comment]
> Interesting... After #4254, pressing "f" no longer focuses on the point under the cursor (regardless of the settings of anti-aliasing).

Got it! Simply setting the default picker to the interactor fixes this regression:

```py
import pyvista as pv
from pyvista.plotting.opts import PickerType

sphere = pv.Sphere(center=(1, 0, 0))

pl = pv.Plotter()
pl.add_mesh(sphere, color='lightblue', show_edges=True)
# pl.enable_anti_aliasing('ssaa')  # works with and without anti-aliasing
pl.iren.picker = PickerType.POINT
pl.show()
```

**Pull request merged**
