### PR TITLE
🎉 HAPPY NEW YEAR 2022 🎉

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

🎉 HAPPY NEW YEAR 2022 🎉

 
relate to https://github.com/pyvista/pyvista/pull/1076

### Details

- Updated the year of LICENSE to 2022.

### CODE REVIEW

**Review by banesullivan — APPROVED** [review]
🎆

**Comment by adeak** [comment]
Do we also have/want to bump https://github.com/pyvista/pyvista/blob/9cd33929dc286adb8c1d6d4c6afa317d96a2833c/tests/tinypages/conf.py#L11? And https://github.com/pyvista/pyvista/blob/9cd33929dc286adb8c1d6d4c6afa317d96a2833c/pyvista/ext/coverage.py#L8 when sphinx bumps it? No idea how any of this works.

**Comment by banesullivan** [comment]
Anything in the docs conf should be updated to get the current year during the build. Parts of the conf already do this

**Comment by akaszynski** [comment]
Approving and merging. Let’s check the conf.py to see if there’s anything we can automate.

**Pull request merged**
